### ISSUE TITLE
Line 6 Guitar Port not working

### ISSUE THREAD

**Issue by samsixtysix** [mdias/rs_asio#104]
I have spent a few hours playing with this and I can get the hardware working fine with ASIO4ALL it does not want to work with the native Line 6 driver. 

When RS starts up it give the message 'Error Sound Initialization - No audio output device is detected ...'

If you can see what the problem is or have any ideas I could try please let me know:

The rs-asio log is 

0.000 [INFO]   - Wrapper DLL loaded (v0.5.2)
0.000 [INFO]  PatchOriginalCode
0.555 [INFO]  Patching CoCreateInstance
0.555 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.555 [INFO]  Patching call at 01C5AA85
0.555 [INFO]  Patching call at 01F03B6E
0.555 [INFO]  Patching call at 01F5C681
0.555 [INFO]  Patching call at 01FAEF75
0.555 [INFO]  Patching call at 01FAF40D
0.555 [INFO]  Patching PortAudio MarshalStreamComPointers
0.555 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.555 [INFO]  Patching call at 01F03059
0.555 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.555 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.555 [INFO]  Patching call at 01F0310E
0.557 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.558 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.558 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.558 [INFO]  AsioHelpers::FindDrivers
0.558 [INFO]    ASIO GuitarPort
0.558 [INFO]    ASIO4ALL v2
0.558 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO GuitarPort
0.558 [INFO]  Creating AsioSharedHost - dll: c:\Windows\SysWOW64\L6GPAsio.dll
0.564 [ERROR]  ASIO Error: ASIO Driver open Failure!
0.564 [INFO]  Destroying AsioSharedHost - dll: c:\Windows\SysWOW64\L6GPAsio.dll
0.564 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.564 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO GuitarPort
0.564 [INFO]  Creating AsioSharedHost - dll: c:\Windows\SysWOW64\L6GPAsio.dll
0.569 [ERROR]  ASIO Error: ASIO Driver open Failure!
0.569 [INFO]  Destroying AsioSharedHost - dll: c:\Windows\SysWOW64\L6GPAsio.dll
0.569 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.569 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.569 [INFO]    hr: 80070490
0.569 [INFO]    *ppEndpoint: 00000000
0.569 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.569 [INFO]    hr: 80070490
0.570 [INFO]    *ppEndpoint: 00000000
0.570 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.570 [INFO]    hr: S_OK
0.570 [INFO]    *ppDevices: 1615B168
12.253 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
12.253 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
12.253 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
12.253 [INFO]  AsioHelpers::FindDrivers
12.253 [INFO]    ASIO GuitarPort
12.253 [INFO]    ASIO4ALL v2
12.253 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO GuitarPort
12.253 [INFO]  Creating AsioSharedHost - dll: c:\Windows\SysWOW64\L6GPAsio.dll
12.259 [ERROR]  ASIO Error: ASIO Driver open Failure!
12.259 [INFO]  Destroying AsioSharedHost - dll: c:\Windows\SysWOW64\L6GPAsio.dll
12.259 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
12.259 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO GuitarPort
12.260 [INFO]  Creating AsioSharedHost - dll: c:\Windows\SysWOW64\L6GPAsio.dll
12.265 [ERROR]  ASIO Error: ASIO Driver open Failure!
12.265 [INFO]  Destroying AsioSharedHost - dll: c:\Windows\SysWOW64\L6GPAsio.dll
12.265 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
12.265 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
12.265 [INFO]    hr: 80070490
12.265 [INFO]    *ppEndpoint: 00000000
12.265 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
12.265 [INFO]    hr: 80070490
12.265 [INFO]    *ppEndpoint: 00000000
12.265 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
12.265 [INFO]    hr: S_OK
12.265 [INFO]    *ppDevices: 1198D4C8
12.271 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback

**Comment by mdias** [comment]
Looking at the log, your ASIO drivers appear to have some issue:

> ASIO Error: ASIO Driver open Failure!

Make sure you can use ASIO with other apps first; if you can than this might be an issue with the 32-bit ASIO driver of your interface (since that's what RS ASIO uses).

**Comment by samsixtysix** [comment]
Thanks for the quick response.

ASIO is working fine in Reaper and POD Farm 2, but presumably they are using the 64 bit driver.  

At least I can use ASIO4ALL for now.

**Comment by samsixtysix** [comment]
Now working Ok - you can add it to the list.

The main problem seems to have been that the interface needs power cycling between exiting RS and restarting RS.

I had to increase the input gain in rs-asio config to 200 in order to get it loud enough to calibrate in RS

I also updated from rs-asio 0.5.2 to 0.5.3

**Comment by mdias** [comment]
Thank you for the update.

The power cycling issue should be a combination of 2 issues:
- RS ASIO might not be uninitializing your interface properly
- Your drivers don't handle a situation where the application exits without cleanly uninitializing ASIO.

I would expect that if any of the above are true, then after using RS no other ASIO software will work either until a power cycle.

There seems to be an overall issue regarding un-initialization which happen here and there, and if I manage to fix that, it might fix this issue too. But since this is not a big problem, I'm treating it as low priority to solve.

**Comment by Leroki** [comment]
This is serous problem on esi maya22 usb.
If i try a power cycle my system crash in BSOD.

**Comment by mdias** [comment]
Sorry, but a BSOD is never a user-land software issue; this is an issue with your interface's drivers and you should report it to ESI.
This doesn't mean that RS ASIO isn't doing something wrong, and if a solution is found it will be applied, however any issue at most could crash the software, not your operating system :)

**Comment by ElectronicWar** [comment]
The problem with older Line 6 gear is their very low quality ASIO driver. I helped debugging the POD Studio GX for use with OBS ASIO and it's driver is similar to the Guitar Port. It's very crash-happy if not initialized properly and only the 32bit driver is working somewhat stable (luck here that RS-ASIO is loading the 32bit driver).

The driver will also stop working if not closed properly, this is a correct assumption by mdias.
I do not know which black magic the REAPER devs are using, but their ASIO implementation somehow works extremely well with the Line6 drivers. So if your GX or GP ASIO is "stuck", just open and close it with REAPER, then you can use RS-ASIO again.

mdias: beside those somewhat clunky drivers, the Line 6 POD Studio GX works well with RS-ASIO once the game is running. It even works with lowest possible buffer settings for me (128 samples) and you can run POD Farm (amp simulation) alongside it if you want to superimpose your own bass tone over Rocksmith for yourself.
