### ISSUE TITLE
Mini-dump with crash when RME UFX is plugged in

### ISSUE THREAD

**Issue by korypostma** [mdias/rs_asio#106]
Attaching the logs/ini and the minidump received.

I have an RME UFX audio interface.

[Rocksmith2014.zip](https://github.com/mdias/rs_asio/files/5052601/Rocksmith2014.zip)

[rocksmith2014_369567_crash_2020_8_10T18_17_0C0.zip](https://github.com/mdias/rs_asio/files/5052592/rocksmith2014_369567_crash_2020_8_10T18_17_0C0.zip)

I have visual studio pro 2019 and can help debug but not sure where to begin with this one.
Thanks,
Kory

**Comment by mdias** [comment]
Does this happen only with this interface?
I see you have other ASIO drivers (such as the focusrite) and it would be helpful to know if those work.

From the crashdump I can see that the crash is happening within the rocksmith executable and not in rs asio code, but it could be that we're feeding bad information on this specific interface. If this happens only on this interface I will need to investigate deeper.

**Comment by korypostma** [comment]
The Focusrite Scarlett 2i4 works as expected, but I use the Focusrite Scarlett 2i4 interface on a different machine and the RME UFX Fireface is the one I use on this machine with Rocksmith 2014.  So it is specific to the RME UFX interface.

Is there a good way to hook up the debugger to get a full dump instead of a minidump, if that is what you need?
Thanks,
Kory

**Comment by mdias** [comment]
There's no good way to do that, no. The game has some protections in place and it quits if you try to attach a debugger while it's running.
I will need to dig deeper into this, which can take some time... I will reply to this topic again when I have some news, or some kind of "special" build of RS ASIO that adds more information to the log that could be helpful; I don't know yet how I'll be approaching this.

**Comment by korypostma** [comment]
Was this finally fixed, which version should it be working now?
Thanks!

**Comment by mdias** [comment]
I don't have the UFX to test, but I own a RME HDSPe AIO card and it works great. However this one should be very different from the UFX since this one is a PCI-e card.
If you own this inerface please test it with latest drivers and latest RS ASIO and report back.
