### ISSUE TITLE
Alesis Core 1 Confirmation

### ISSUE THREAD

**Issue by MuThing** [mdias/rs_asio#115]
Product page: https://www.alesis.com/products/view/core-1

I can confirm that rs_asio works well with this interface using the ASIO4ALL intermediary driver. I had some issues with rs_asio picking up my internal Realtek DAC but that was no-ones fault but my own. I had to reinstall ASIO4ALL with the standalone settings program enabled and use that to prevent such a thing from happening.

With a latency buffer of 4 and ASIO buffer size of 128 the only place the game stuttered and crackled was during the company logos/loading screen; once I was logged in and at the menus the game worked flawlessly. I think I need to do some more tweaking but for now its working just fine.

I've included a zip of my Rocksmith.ini, RS_ASIO.ini and RS_ASIO-log.txt. The log in particular is slightly concerning as once the code has been patched in the rest of the log seems to be a recurring loop of AsioSharedHost::AsioCalback_bufferSwitch - buffer [1,2,3] before it detects an underrun and starts over. This goes on for the entire 25 minute test that I performed.

[rs_asio_inis_+_log.zip](https://github.com/mdias/rs_asio/files/5125230/rs_asio_inis_%2B_log.zip)

**Comment by mdias** [comment]
Thank you for the report, I'll add it to the list as soon as I can.
That means you're probably way too close to what your computer can handle in terms of buffer size.

**Comment by mdias** [comment]
Added, thank you 👍

**Comment by kubus765** [comment]
This also works great with Alesis io2
