### ISSUE TITLE
Native Audio Komplete Audio 1

### ISSUE THREAD

**Issue by Domoproja** [mdias/rs_asio#118]
Hi,

I have checked and it works without problem with the native ASIO drivers. (48khz and 128 samples) Guitar is in channel 1 (I believe it's the same as in Focusrite Scarlet solo).

**Comment by mdias** [comment]
Thank you, added to the readme.

**Comment by TimWrightImmediate** [comment]
Just another confirmation - this works fine with the new (v5.0) Native Instruments driver released Feb 2021. Reliable at 48 samples but breaks up at 32 (although even at 64 samples the latency is imperceptible to me). The guitar is indeed on channel 1, 0 corresponds to the balanced XLR connector for the microphone.

It's a real pleasure playing RS2014 with no latency - many, many thanks for taking the time to make this and release it!

**Comment by egklt** [comment]
> Just another confirmation - this works fine with the new (v5.0) Native Instruments driver released Feb 2021. Reliable at 48 samples but breaks up at 32 (although even at 64 samples the latency is imperceptible to me). The guitar is indeed on channel 1, 0 corresponds to the balanced XLR connector for the microphone.
> 
> It's a real pleasure playing RS2014 with no latency - many, many thanks for taking the time to make this and release it!

Can you share config?

**Comment by TimWrightImmediate** [comment]
No problem, here's the config I'm using: 

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=64

[Asio.Output]
Driver= Komplete Audio ASIO Driver
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver= Komplete Audio ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by MrOrnithorynque** [comment]
> No problem, here's the config I'm using:
> 
> [Config] EnableWasapiOutputs=0 EnableWasapiInputs=0 EnableAsio=1
> 
> [Asio] ; available buffer size modes: ; driver - respect buffer size setting set in the driver ; host - use a buffer size as close as possible as that requested by the host application ; custom - use the buffer size specified in CustomBufferSize field BufferSizeMode=custom CustomBufferSize=64
> 
> [Asio.Output] Driver= Komplete Audio ASIO Driver BaseChannel=0 AltBaseChannel= EnableSoftwareEndpointVolumeControl=1 EnableSoftwareMasterVolumeControl=1 SoftwareMasterVolumePercent=100
> 
> [Asio.Input.0] Driver= Komplete Audio ASIO Driver Channel=1 EnableSoftwareEndpointVolumeControl=1 EnableSoftwareMasterVolumeControl=1 SoftwareMasterVolumePercent=100
> 
> [Asio.Input.1] Driver= Channel=1 EnableSoftwareEndpointVolumeControl=1 EnableSoftwareMasterVolumeControl=1 SoftwareMasterVolumePercent=100
> 
> [Asio.Input.Mic] Driver= Channel=1 EnableSoftwareEndpointVolumeControl=1 EnableSoftwareMasterVolumeControl=1 SoftwareMasterVolumePercent=100

I use the komplete audio 1 too but I get the "ERROR SOUND INITIALIZATION" error. My sound format is set to 24 bits 48000Hz but I cannot change it to 16 bits. How did you do ?

**Comment by TimWrightImmediate** [comment]
> I use the komplete audio 1 too but I get the "ERROR SOUND INITIALIZATION" error. My sound format is set to 24 bits 48000Hz but I cannot change it to 16 bits. How did you do ?

Oddly... I would have assumed I was on 48kHz / 16 bit, but when I checked the sound control panel, I'm actually using 48kHz / 24 bit as well. So Rocksmith / rs_asio evidently works fine using that setting, and you may have a different issue? 

I can switch to 16 bit, though - Open the Sound settings page, then open the "Sound Control Panel", select the Komplete Audio playback device, then the "Properties" button, switch to the "Advanced" tab and you can change the default settings. I also have both of the "Exclusive Mode" options checked, if that helps.

**Comment by mdias** [comment]
@MrOrnithorynque I suppose that you get that error in the RS ASIO log file?
If so, does any other ASIO-enabled application work with that driver?

**Comment by JNX1** [comment]
@MrOrnithorynque Did you ever fix your issue? I have just bought the Komplete Audio 1 and I can't get it to work on Rocksmith, it always crahes on startup, so my fix has been to disconnect the interface and connect it as soon as Rocksmith has done its initial loading, but I also get the same error as you. Any fixes? 
My interface is set to 48KHz 24bit

**Comment by FuriousTurtle** [comment]
I had this ERROR SOUND INITIALIZATION message telling me that my output device was not found.
After fiddling around and checking my drivers (using reaper DAW) I was able to find that my Komplete audio 1 was not installed properly by Windows 11, and that the ASIO driver was missing even if the device was OK in the devices panel.

The fix is to retrieve the Komplete audio 1 drivers from Native Instrument website and install it, then reboot, and check again in a DAW like Reaper to see if your device is in the ASIO devices list.
Note that this driver is only available for Windows 10 but seem to work on my side for Windows 11
I also had to install the driver twice for some reason, and the second time, I didnt need to reboot. It's like it's installing in two steps, but manually, lol.

You need to pick "Realtone cable" option when calibrating if you're using an external sound card.
And the final trap for me was that I had to lower my screen refresh rate from 240 Hz to 60 Hz so that the cursor would move in the calibration. At 240 Hz it would stay stuck at 0 even if I could hear my guitar correctly in the game (this is not a joke)
