### ISSUE TITLE
Native Instruments Komplete Audio 2

### ISSUE THREAD

**Issue by virusapex** [mdias/rs_asio#120]
Man, you're a legend! I remember searching for ASIO support in Rocksmith some time ago, but haven't found anything of sorts. Just checked today and found your repo. Checked on my Komplete Audio 2 (which you can add to the list) and can confirm that it works, although i had to disable input 2 or otherwise it'll show up as two connected cables. BTW, is there any way to reroute the audio, so that it is available in Steam broadcast or Discord for example, or they just can't capture ASIO at all? Thank you again for amazing work!

**Comment by mdias** [comment]
Hey! Nice to hear it's working fine for you!

For routing there is a way, but it's a bit complicated because indeed normal apps cannot capture from ASIO at all.

The way around this is to install [voicemeeter](https://vb-audio.com/Voicemeeter/index.htm) which is like a virtual audio interface that has some routing and mixing capabilities, and it can passthrough ASIO into a virtual ASIO device (which you would configure RS_ASIO to listen to, instead of directly your actual interface) and then also send that audio into a "normal" virtual device that other apps (such as discord) can listen to.
It can be complicated to set this up, but it is possible, and there is virtually no cost in terms of latency for you.

**Comment by virusapex** [comment]
Oh, I've heard of it, thought, that it might actually add some latency, so it wouldn't sync up with the video. The other problem being that you can't really change the audio source for Discord, since the audio is taken right from the application, unless you stream the whole screen and pass it as output. Or just use the microphone pass-through, which will work if there is no delay. Anyway, thank you again for assistance.

**Comment by mdias** [comment]
Ahh yes, I didn't remember discord doesn't allow you to select the input :/
In that case I don't know how to help you with discord, sorry.

**Comment by virusapex** [comment]
Don't worry about it, we'll just have to wait, when ASIO is being handled more intuitively by applications, hopefully, this era will come eventually.

**Comment by foxx1337** [comment]
@virusapex - you can use OBS to fix this setup. I basically have a virtual camera and a virtual microphone right now in Windows. The camera publishes my current OBS scene, while the microphone publishes sound coming from Reaper. Local monitoring is latency free, while the virtual microphone signal might be delayed some milliseconds. I'm using Voicemeeter as input for the virtual microphone, that's where the delay comes from.

![image](https://user-images.githubusercontent.com/2565912/95528660-0caab780-09d9-11eb-95ab-45eea2ea4d81.png)


If you're interested, I can produce a small writeup about the setup, which I'm currently using, together with my guitar instructor, in our skype / discord / zoom / ms teams sessions.

**Comment by virusapex** [comment]
> 
> 
> @virusapex - you can use OBS to fix this setup. I basically have a virtual camera and a virtual microphone right now in Windows. The camera publishes my current OBS scene, while the microphone publishes sound coming from Reaper. Local monitoring is latency free, while the virtual microphone signal might be delayed some milliseconds. I'm using Voicemeeter as input for the virtual microphone, that's where the delay comes from.
> 
> ![image](https://user-images.githubusercontent.com/2565912/95528660-0caab780-09d9-11eb-95ab-45eea2ea4d81.png)
> 
> If you're interested, I can produce a small writeup about the setup, which I'm currently using, together with my guitar instructor, in our skype / discord / zoom / ms teams sessions.

Cool stuff, man. Still ridiculous that you have to do this in order to monitor and send it through Discord =) I tested Voicemeeter and it works great.

**Comment by TheTarikAyyildiz** [comment]
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

[Asio.Output]
Driver=ASIO4ALL v2
;Driver=ASIO4ALL v2
BaseChannel=1
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Komplete Audio ASIO Driver
;Driver=Komplete Audio ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

; [Asio.Input.1]
; Driver=
; Channel=1
; EnableSoftwareEndpointVolumeControl=1
; EnableSoftwareMasterVolumeControl=1
; SoftwareMasterVolumePercent=100

; [Asio.Input.Mic]
; Driver=
; Channel=1
; EnableSoftwareEndpointVolumeControl=1
; EnableSoftwareMasterVolumeControl=1
; SoftwareMasterVolumePercent=100

**Comment by TheTarikAyyildiz** [comment]
To head audio from laptop speakers open asio4all and configure the output.

**Comment by mdias** [comment]
You can - and probably should - just use wasapi output to output through your normal speakers, while leaving the `Driver=` empty on the ASIO output config.
