### ISSUE TITLE
Steinberg UR22C works perfectly

### ISSUE THREAD

**Issue by Chaigidel** [mdias/rs_asio#124]
This is just awesome, you brought joy back into playing RS for me and my friends!
So, been playing whole day, noticed no problems, no lag, signal is clean, multiplayer works perfectly. Don't have XLR cables, so used simple jacks. In the config just type in driver name (bet it's the same for whole UR family): `Driver=Yamaha Steinberg USB ASIO`

**Comment by mdias** [comment]
Nice to hear it works so well for you :)
Also, thank you for the report; added it to the list 👍
