### ISSUE TITLE
No Input or Output detected by game

### ISSUE THREAD

**Issue by CaffinatedPancake** [mdias/rs_asio#127]
I have a Scarlett Solo Gen 3 and I'm using rs_asio with the settings in the attached .txt (note its an actual .ini in the dir) but when the game boots it detects no output or even input. I have the thing set to 16 bit 48000hz , with 2 channel 16 bit 48000hz in windows settings.
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/5462830/RS_ASIO.txt)

**Comment by mdias** [comment]
Can you post your `RS_ASIO-log.txt`?
Also, I doubt you're going to get any good result with a custom buffer size of 16. Did you read the [known issues on the main page](https://github.com/mdias/rs_asio#known-issues)?
There's also a link to a [guide](https://github.com/mdias/rs_asio/blob/master/docs/focusrite_solo/README.md) on the main page for your interface.

**Comment by CaffinatedPancake** [comment]
Sorry for not getting back but I managed to fix it myself
