### ISSUE TITLE
AsioSharedHost::ClampBufferSizeToLimits() does not respect actual hardware limits if granularity is -1

### ISSUE THREAD

**Issue by fdinel** [mdias/rs_asio#128]
Hi there,
I'm using a Behringer Q502USB to play the game with the BEHRINGER USB AUDIO ASIO driver. At first, this mod simply failed to start, complaining about being unable to create buffers (in RSAsioAudioClient::Initialize()). After a bit of debugging and hacking, I actually found out that the AsioSharedHost::ClampBufferSizeToLimits() methods does not respect the hardware limits if the granularity obtained using getBufferSize() is -1. In my case with my device, although the getBufferSize() call returns a min size of 48, a max size of 48 and a preferred size of 48 (and a granularity of -1), the clamped buffer will still be 64.

I patched the AsioSharedHost::ClampBufferSizeToLimits() method so that if the min, max and preferred size are all equal, then the clamped buffer size is set to the preferred size, ignoring the granularity. From my tests, it actually works and allow me to play the game...

By the way, thanks for this great code, it finally allows me to play the game hearing my own guitar sound!! :)

**Comment by mdias** [comment]
Hello!

Thank you for the nicely detailed bug report! It's indeed a bug that when granularity is -1 we're apparently not fully respecting hardware limits.
Your patch makes sense, but it would still leave the bug open for cases where min and max are not equal, and they're not power-of-2 numbers, so I will make a proper fix for this soon, maybe even today :)

**Comment by fdinel** [comment]
Hi Micael,
You are totally right, a proper fix would be much better than my "test" patch. My pleasure for the report :)
Cheers

**Comment by mdias** [comment]
I have just made a [new release](https://github.com/mdias/rs_asio/releases/tag/v0.5.4) that should fix this.

I'm closing this issue as it should now be solved, but feel free to re-open it if the issue persists.

Thank you again for the report 👍
