### ISSUE TITLE
Native Instruments Audio Kontrol 1

### ISSUE THREAD

**Issue by jiridurdis** [mdias/rs_asio#131]
Hi,

Just a quick note that Native Instruments Audio Kontrol 1 (little bit older piece of hardware) works out of the box.

Line input is Channel 1 (like many other similar devices with Mic and Line inputs). Output channels appears to match real numbering of output plugs too.

Thanks for your work.

**Comment by mdias** [comment]
Hello,

Thank you for the report, I've added the interface to the list 👍
