### ISSUE TITLE
Behringer Q502USB working!

### ISSUE THREAD

**Issue by fdinel** [mdias/rs_asio#132]
Hi, Behringer Q502 USB working great starting with version 0.5.4! Here's my config:

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=BEHRINGER USB AUDIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=BEHRINGER USB AUDIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
Awesome! Thank you for the report again, sorry I forgot to add the interface to the list before, this time it's added 👍

**Comment by kadefitzpatrick** [comment]
I cannot get my Xenyx Q502 to work at all. I tried your setup but still doesn't work. I use Asio4All and it gives me no input and no input options when i go to settings within rocksmith. Ive sat here for 4 hours pulling my hair out trying everything over and over again.

**Comment by fdinel** [comment]
Hi, it's been a while but I think I used the Behringer USB Audio driver, which is not the same as the ASIO4ALL driver. Strangely, it cannot be found on the Behringer downloads page under the Q502USB, but it is there if you search for the 1204FX device. The driver is called "64-Bit USB Audio Driver", version is 2.8.40 and the file name is behringer_2902_x64_2.8.40.zip.

As a side note, in my experience when playing with other guitar amps software I also got lower latency with this driver than with the ASIO4ALL driver. YMMV.

**Comment by kadefitzpatrick** [comment]
installing that exact one strangely does not give me any new options for ASIO in rsmods

**Comment by fdinel** [comment]
Are you able to use the device in any other ASIO application? I do not want to advertise or endorse another tool or anything but I used Guitar Rig Player (free). Maybe you could try and make sure it works with that driver in another app?

Also maybe have a look at [this post](https://github.com/mdias/rs_asio/issues/7#issuecomment-565829531) (and the whole thread in fact). They seem to have used the same driver for another Behringer device and made it work.

Hope it helps.

**Comment by Elmosquitooo** [comment]
Hi 
I use my xenyx q502 with the audio driver of  1204FX but when i play i just have horrible ultrasound.
I use the version 0.5.4 and the same conf file than fdinel and i have nothing on my computer using ASIO. 
An idea?

**Comment by fdinel** [comment]
Hi,

maybe play with the settings in the Behringer ASIO configuration panel? It is a compromise between latency and noise level.

Also one thing I did not mention in my setup is that I use a passive direct box (DI box or PDB). It really helps with the electric signal level required to input guitar signal into a microphone input like the one present on the Q502USB mixer. My exact model is a Pyle PDC21... Without the DI box I really needed to increase the volume, up to a very noisy level. Maybe that's what is happening to you? So to be clear I connect my guitar in the DI box, the DI box in the mixer and the mixer in the computer by USB.

Hope that helps!
