### ISSUE TITLE
M-Audio Fast Track Ultra 8R working

### ISSUE THREAD

**Issue by sickhippie** [mdias/rs_asio#135]
By default, RS_ASIO.ini generated with all of the 8R active inputs.  I had to manually remove a few so RS would only see a single input channel - `Asio.Input.0`.  After that, RS works just fine.

**Comment by mdias** [comment]
Altough RS_ASIO sees all inputs, it will only use the ones you specify in `Asio.Input.0` and `Asio.Input.1` so it's fine keep them all enabled (if this is what you mean).

Thank you for the report, I've added the interface to the list 👍 
I'll close the issue now, but if you don't mind please still add a comment here with your RS_ASIO.ini contents to help whoever comes next with the same interface :)

**Comment by sickhippie** [comment]
Current RS_ASIO.ini contents (when I get around to configuring for mic too I'll update with a follow-on comment):

```[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=WineASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=WineASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```
