### ISSUE TITLE
Onboard Line In / Mic In

### ISSUE THREAD

**Issue by SrMouraSilva** [mdias/rs_asio#136]
Hello. Do you consider supporting on-board cards?

This is the log on my computer.

Congratulations on the project!

```
0.000 [INFO]   - Wrapper DLL loaded (v0.5.4)
0.000 [INFO]  PatchOriginalCode
0.351 [INFO]  Patching CoCreateInstance
0.351 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.351 [INFO]  Patching call at 01C5AA85
0.351 [INFO]  Patching call at 01F03B6E
0.351 [INFO]  Patching call at 01F5C681
0.351 [INFO]  Patching call at 01FAEF75
0.351 [INFO]  Patching call at 01FAF40D
0.351 [INFO]  Patching PortAudio MarshalStreamComPointers
0.351 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.351 [INFO]  Patching call at 01F03059
0.351 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.351 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.351 [INFO]  Patching call at 01F0310E
0.353 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.353 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.353 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.353 [INFO]  AsioHelpers::FindDrivers
0.353 [INFO]    ASIO4ALL v2
0.354 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.354 [INFO]    hr: 80070490
0.354 [INFO]    *ppEndpoint: 00000000
0.354 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.354 [INFO]    hr: 80070490
0.354 [INFO]    *ppEndpoint: 00000000
0.354 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.354 [INFO]    hr: S_OK
0.354 [INFO]    *ppDevices: 16E426C0
2.248 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
2.248 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
2.248 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
2.248 [INFO]  AsioHelpers::FindDrivers
2.248 [INFO]    ASIO4ALL v2
2.248 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
2.248 [INFO]    hr: 80070490
2.248 [INFO]    *ppEndpoint: 00000000
2.248 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
2.248 [INFO]    hr: 80070490
2.248 [INFO]    *ppEndpoint: 00000000
2.248 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
2.248 [INFO]    hr: S_OK
2.248 [INFO]    *ppDevices: 16E42060
2.253 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
4.695 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
5.668 [INFO]   - Wrapper DLL unloaded
```

**Comment by mdias** [comment]
Hello

The aim of the project is to support ASIO enabled devices. However, there is already support for "any" output device by setting `EnableWasapiOutputs=1` in the config file.
For input devices though, setting `EnableWasapiInputs=1` will only work for the RealToneCable, unless you enable Rocksmith's [Direct Connect mode](https://theriffrepeater.com/rsmods-but-what-is-direct-connect-mode-mods-pc-mac-steam-custom-tuning-setlist-cables-interfaces/).

Depending on what you're trying to achieve, you might not need RS_ASIO at all.

**Comment by SrMouraSilva** [comment]
Hi, I'm trying to connect my instrument directly to the mic in on the laptop's onboard sound card.

Using Direct Connect mode allows to use the instrument, but in my case, the sound quality is poor.
After installing ASIO4ALL, I saw on the "offline panel" that it lists the onboard sound card. I thought then that RS_ASIO could identify it and possibly offer better sound quality.

**Comment by mdias** [comment]
Sorry for the late reply.

RS ASIO will very likely not increase sound quality. Specially not with ASIO4ALL.

The reason your sound quality is poor is likely because your input port is not made for connecting a guitar.

**Comment by SrMouraSilva** [comment]
Hello, @mdias! I configured rs_asio with the onboard audio. I have a Inspiron Serie 7000 (i15-7580-A40S).
The sound has latency, but the detection of the notes does not.

It is not possible to play songs with fast notes sequences properly with the Guitar tone option, as latency gets in the way. Moderate notes sequences, with concentration, is possible to play well.

Another thing I noticed was that, after I managed to configure it, the sound quality with rs_asio was better than with direct connect mode.

Soon, I will share my configuration.

**Comment by SrMouraSilva** [comment]
### RS_AUDIO

```
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=6
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=ASIO4ALL v2
Channel=6
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

### Rocksmith
```
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1680
ScreenHeight=1050
Fullscreen=0
VisualQuality=2
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=0
EnablePerPixelLighting=1
MsaaSamples=1
DisableBrowser=1
[Net]
UseProxy=1
```

**Comment by mdias** [comment]
You have both:

```
[Config]
EnableWasapiOutputs=1
```

and

```
[Asio.Output]
Driver=ASIO4ALL v2
```

Which without the log makes it impossible to know whether you're using WASAPI or ASIO4ALL for the output. Also, ASIO4ALL is not achieving the same as you'd achieve with a proper ASIO driver made for your audio card.
I can't think of a reason why using WASAPI in exclusive mode would end up with lower audio quality than using ASIO4ALL other than very broken WASAPI drivers.

In any case, RS ASIO doesn't care (it doesn't even know) if your audio card is internal, external or onboard. All it does it output audio to an ASIO driver, or if configured for WASAPI "mode" it will simply redirect calls to the system WASAPI driver that the game would already use if RS ASIO wasn't there.

As you've seen, ASIO4ALL can work, but it's often problematic when trying to achieve optimal latency without glitches. You can try to decrease the buffer size used by ASIO4ALL in it's panel (and then rebooting the game) or use `BufferSizeMode=custom` along with the manually specified size. Whether it will work fine for you or not is something you'll have to test.

**Comment by SrMouraSilva** [comment]
@mdias, I opened this issue for thinking that rs_asio didn't work for the onboard audio interface. Then I found out that it was an error in my configuration. So I told you what impressions I had and shared my configuration. So I think this issue can be closed.

It may be that someone else only has the onboard audio interface and ASIO4ALL at hand, so this issue can be useful for this audience.

If you want, I can test anything you request.

> As you've seen, ASIO4ALL can work, but it's often problematic when trying to achieve optimal latency without glitches. You can try to decrease the buffer size used by ASIO4ALL in it's panel (and then rebooting the game) or use BufferSizeMode=custom along with the manually specified size. Whether it will work fine for you or not is something you'll have to test.

I tried. Unfortunately, on my computer the result in the best configuration found was not satisfactory.

I ended up buying the real tone cable. I still feel a delay, but it is (apparently) not significant.

I can try to test the use of the real tone cable with rs_asio, however, it would be with ASIO4ALL.

**Comment by mdias** [comment]
It's understandable, and given the hardware you seem to have at hands, I think you made the right decision to just buy the RTC as that should be the most problem-free approach.

RS ASIO is meant for those that have an audio interface with a dedicated ASIO driver so that they don't have to be switching cables all the time and also use their expensive hardware which in some cases is problematic to use even as a simple output device with Rocksmith.

In any case you should now be well equipped to enjoy the game, and that's what matters 👍
