### ISSUE TITLE
Rocksmith 2014

### ISSUE THREAD

**Issue by black00019** [mdias/rs_asio#141]
Hi i have a Rocksmith 2014 (not remastered)
but rs_asio not work and not recognize my focusrite

**Comment by ffio1** [comment]
The project only supports the remastered version. Please make sure you purchase the game on Steam instead of pirating it.

[https://store.steampowered.com/app/221680/](https://store.steampowered.com/app/221680/)

**Comment by mdias** [comment]
As stated on the front page, this project targets the Remastered edition.
