### ISSUE TITLE
Audient EVO 4, game crash after start 

### ISSUE THREAD

**Issue by SAARussian** [mdias/rs_asio#144]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/5750973/RS_ASIO-log.txt)

**Comment by SAARussian** [comment]
(

**Comment by SAARussian** [comment]
![image](https://user-images.githubusercontent.com/57723354/103294380-d2aee780-4a02-11eb-895b-b9b34fc31639.png)

**Comment by SAARussian** [comment]
So... Its just now working with Rocksmith, I set motherboard as default and reinstall the game. Than I run game and it crash, but when I unplug EVO, the game starts normal.

**Comment by SAARussian** [comment]
https://drive.google.com/drive/folders/1UaqmasOlHUmRu4_L2hA65aD6qJS3DMEJ?usp=sharing

**Comment by SAARussian** [comment]
OK. I just del some driver and software (Odeus ASIO Link Pro, Voicemeeter, VB Cables). And the game doesn't crash anymore. Which is strange, because all these extra devices were turned off and only EVO 4 was used. There was no such problem on the Behringer U-Phoria UM2. Windows heh...

**Comment by mdias** [comment]
This is very strange indeed since it looks like you didn't have WASAPI enabled and only used the Audient ASIO driver, so it shouldn't be affected by the other stuff as far as I can see...
But oh well, at least it's working fine now :)
