### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by SAARussian** [mdias/rs_asio#145]
It can use route like DAWs? If I just need to realize this sweet loopback (like in Reaper screen down below) to my friends in Discord without duplicating their voices.
![image](https://user-images.githubusercontent.com/57723354/103316425-99de3500-4a39-11eb-9020-2a405f0cc08b.png)

**Comment by mdias** [comment]
What do you mean by route?

You can set the channels it outputs the audio to with the `BaseChannel` setting in the output setting.

**Comment by SAARussian** [comment]
> What do you mean by route?
> 
> You can set the channels it outputs the audio to with the `BaseChannel` setting in the output setting.

So I can bring the Rocksmith via rs_ASIO, to the main output for myself and at the same time to the loopback output for the mixer loopback for discord input?

**Comment by mdias** [comment]
If you have RS ASIO outputting normally through your interface, I think the signal will already be recorded by the loopback.

You can test this by using any audio editing tool to record your loopback signal while you play normally.

**Comment by SAARussian** [comment]
No its work like this, what I wanna loop, that will going to the loopback mixer (input device). So, if I listening rocksmith through main output 1|2 (like discord too), its cause to friends hearing rocksmith and themselves 
![image](https://user-images.githubusercontent.com/57723354/103437940-530d5c80-4c3e-11eb-949b-85b55bcffe7e.png)

**Comment by mdias** [comment]
Ahh, I see, you have specific outputs that go to the mixer.

I'm assuming your interface exposes 4 output ports then, where 0+1 are "Main output", and 2+3 is the "Loop-back". Try setting `BaseChannel=2` on `[Asio.Output]` section; it should send the signal to the loop-back channels.

**Comment by ElectronicWar** [comment]
I use RS ASIO without issues with ReaRoute (ASIO router shipped with REAPER DAW). I use Reaper to do the mixing and routing and then grab what I need from the ReaRoute channels in RS ASIO and OBS.

**Comment by SAARussian** [comment]
> Ahh, I see, you have specific outputs that go to the mixer.
> 
> I'm assuming your interface exposes 4 output ports then, where 0+1 are "Main output", and 2+3 is the "Loop-back". Try setting `BaseChannel=2` on `[Asio.Output]` section; it should send the signal to the loop-back channels. But then I'm not sure if you hear it on your speakers. Please try.
> 
> If it doesn't work, please post your RS ASIO log so that I can see the in/out layout.
Like this?
![image](https://user-images.githubusercontent.com/57723354/103639375-52870580-4f5f-11eb-8679-bb345138b757.png)

**Comment by SAARussian** [comment]
Its working only on loopback output, I can get sound from main output
![image](https://user-images.githubusercontent.com/57723354/103639619-a7c31700-4f5f-11eb-8dd6-ad025d442525.png)

**Comment by SAARussian** [comment]
[Uploading RS_ASIO-log.txt…]()

**Comment by mdias** [comment]
Alright, so if I understand correctly you would need additional outputs.

Currently RS ASIO only outputs to 2 channels, starting on BaseChannel. For now the only solution would be to use something like Voicemeeter Potato through ASIO and output Rocksmith's signal to both outputs. I will need to see how easy it would be to implement something that would allow you to route the signal like you want.

**Comment by SAARussian** [comment]
> Alright, so if I understand correctly you would need additional outputs.
> 
> Currently RS ASIO only outputs to 2 channels, starting on BaseChannel. For now the only solution would be to use something like Voicemeeter Potato through ASIO and output Rocksmith's signal to both outputs. I will need to see how easy it would be to implement something that would allow you to route the signal like you want.

With these moves, you'll soon turn Rocksmith into a real DAW)))

**Comment by mdias** [comment]
Hello, please check [v0.5.6](https://github.com/mdias/rs_asio/releases/tag/v0.5.6). It adds the possibility to output the audio signal to an additional output pair with the `AltBaseChannel` option. This way you can output to your speakers and also to your loopback.

**Comment by SAARussian** [comment]
So... Yeah... It works! 
![image](https://user-images.githubusercontent.com/57723354/104827865-d13f4500-5873-11eb-8d93-0be03fd327a9.png)

**Comment by SAARussian** [comment]
Amazing man! May I ask a personal question? Why are you doing this? Do you like this game or do you just like to improve your skills in your free time?

**Comment by mdias** [comment]
Awesome! Thanks for reporting back 👍 

I started RS ASIO to scratch my own itch; I had output issues and checked if this was possible, and it was. After that, well... It's nice to improve the thing I did here and there while helping out others; you can think of it as a hobby. :)
