### ISSUE TITLE
Focusrite Clarett 2Pre Thunderbolt works

### ISSUE THREAD

**Issue by xuyn2003** [mdias/rs_asio#146]
Just report Focusrite Clarett 2Pre Thunderbolt works as well, 
thank you very much!

> 
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite Thunderbolt ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite Thunderbolt ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
>

**Comment by mdias** [comment]
Thank you for the report. Added to the list 👍
