### ISSUE TITLE
Unable to find BOSS KATANA MkII.

### ISSUE THREAD

**Issue by Steamvoker** [mdias/rs_asio#150]
When I try to launch the game it can't find my Katana MkII. Here's the log:

> 0.000 [INFO]   - Wrapper DLL loaded (v0.5.5)
0.000 [INFO]  PatchOriginalCode
0.369 [INFO]  Patching CoCreateInstance
0.369 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.369 [INFO]  Patching call at 01C5AA85
0.369 [INFO]  Patching call at 01F03B6E
0.369 [INFO]  Patching call at 01F5C681
0.369 [INFO]  Patching call at 01FAEF75
0.369 [INFO]  Patching call at 01FAF40D
0.369 [INFO]  Patching PortAudio MarshalStreamComPointers
0.369 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.369 [INFO]  Patching call at 01F03059
0.369 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.369 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.369 [INFO]  Patching call at 01F0310E
0.371 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.372 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.372 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.372 [INFO]  AsioHelpers::FindDrivers
0.373 [INFO]    ASIO4ALL v2
0.373 [INFO]    KATANA
0.373 [INFO]    Solid State Logic ASIO Driver
0.373 [INFO]    Voicemeeter AUX Virtual ASIO
0.373 [INFO]    Voicemeeter Insert Virtual ASIO
0.374 [INFO]    Voicemeeter Potato Insert Virtual ASIO
0.374 [INFO]    Voicemeeter VAIO3 Virtual ASIO
0.374 [INFO]    Voicemeeter Virtual ASIO
0.374 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: KATANA
0.374 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
0.376 [ERROR]  ASIO Error: Can not found a device. Please connect the device.
0.376 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
0.376 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.376 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: KATANA
0.376 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
0.378 [ERROR]  ASIO Error: Can not found a device. Please connect the device.
0.378 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
0.378 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.378 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.378 [INFO]    hr: 80070490
0.378 [INFO]    *ppEndpoint: 00000000
0.378 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.378 [INFO]    hr: 80070490
0.378 [INFO]    *ppEndpoint: 00000000
0.378 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.378 [INFO]    hr: S_OK
0.378 [INFO]    *ppDevices: 0DC13D28
0.391 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback

It works fine with my SSL2+ but I can't get it to work with my Katana. I've tried the config from the readme but that didn't help either.

**Comment by mdias** [comment]
This error is being reported by the ASIO driver itself, not RS ASIO.

I'm guessing you have your interface disconnected or powered off. Is it working with any other ASIO application?

**Comment by Steamvoker** [comment]
Ableton says "Failed to open audio device", but It is connected and I can change the sample rate and buffer size through driver. I've already tried reinstalling device drivers.

**Comment by mdias** [comment]
Yeah, sounds like something is broken, but it's hard to tell what it is.
If you have another computer, try it there. If it still doesn't work it could be an hardware issue with your interface. Though if you're able to change sample rate and buffer size it's likely a driver issue.

**Comment by Steamvoker** [comment]
Just tried on different pc without any other asio drivers or devices to avoid conflicts and it's basically the same thing: 

> 0.000 [INFO]   - Wrapper DLL loaded (v0.5.5)
0.000 [INFO]  PatchOriginalCode
3.236 [INFO]  Patching CoCreateInstance
3.236 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
3.261 [INFO]  Patching call at 01C5AA85
3.261 [INFO]  Patching call at 01F03B6E
3.262 [INFO]  Patching call at 01F5C681
3.262 [INFO]  Patching call at 01FAEF75
3.262 [INFO]  Patching call at 01FAF40D
3.262 [INFO]  Patching PortAudio MarshalStreamComPointers
3.262 [INFO]  Patch_CallRelativeAddress - num locations: 1
3.262 [INFO]  Patching call at 01F03059
3.262 [INFO]  Patching PortAudio UnmarshalStreamComPointers
3.262 [INFO]  Patch_CallRelativeAddress - num locations: 1
3.262 [INFO]  Patching call at 01F0310E
3.276 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
3.288 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
3.288 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
3.288 [INFO]  AsioHelpers::FindDrivers
3.309 [INFO]    KATANA
3.309 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: KATANA
3.309 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
3.328 [ERROR]  ASIO Error: Can not found a device. Please connect the device.
3.328 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
3.330 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
3.330 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: KATANA
3.331 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
3.346 [ERROR]  ASIO Error: Can not found a device. Please connect the device.
3.347 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
3.349 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
3.349 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
3.349 [INFO]    hr: 80070490
3.349 [INFO]    *ppEndpoint: 00000000
3.349 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.349 [INFO]    hr: 80070490
3.349 [INFO]    *ppEndpoint: 00000000
3.349 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.350 [INFO]    hr: S_OK
3.350 [INFO]    *ppDevices: 14847650

**Comment by mdias** [comment]
Seems like a problem with the interface itself... Perhaps you should contact your hardware vendor since no ASIO application is working.

**Comment by Steamvoker** [comment]
It worked somehow, but not for a long time. I get 

> This device cannot start. (Code 10)
>
>Insufficient system resources exist to complete the API.

So I guess it's a connection/driver issue. I'll close this issue by the end of the day.

**Comment by cloph** [comment]
FYI: there's a bug in either rs_asio or the Katana's asio driver that doesn't release the driver properly on exit of Rocksmith that confuses both steam and/or Rocksmith and requires a reboot to fix. Steam will either complain that Rocksmith is still running and won't relaunch it, or Rocksmith can launch but then cannot access the Katana. 
So if in doubt, try again after a windows reboot.

**Comment by Steamvoker** [comment]
Thanks. It seems like that's the case. I guess I'll just use my SSL2+ when I want to play the game.
