### ISSUE TITLE
Report: MOTU M2 works perfectly fine

### ISSUE THREAD

**Issue by vol-pi** [mdias/rs_asio#151]
While it might be obvious that the m2 works, since the m4 has been reported as working fine, it might still be helpful for someone. I had absolutely no issues with the MOTU M2 and it works without any problems.

This is the device: https://motu.com/en-us/products/m-series/m2/

Thank you for your great work!

**Comment by mdias** [comment]
Thank you for the report!
Indeed it's better to have full confirmation before assuming it will work :)
Added it!
