### ISSUE TITLE
Can't get ReaRoute working

### ISSUE THREAD

**Issue by Ariloum** [mdias/rs_asio#152]
Hello, I'm trying to setup Rocksmith input routing with using the Reaper DAW and rearoute, but somewhy I don't hear the guitar in Rocksmith, also Rocksmith loading with some lags in menus and rs_asio's log file is very huge (like i'm getting 1gb within 1 min RS launched).

Here is some cut of it from the top:
0.000 [INFO]   - Wrapper DLL loaded (v0.5.5)
0.000 [INFO]  PatchOriginalCode
0.412 [INFO]  Patching CoCreateInstance
0.412 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.412 [INFO]  Patching call at 01C5AA85
0.412 [INFO]  Patching call at 01F03B6E
0.412 [INFO]  Patching call at 01F5C681
0.412 [INFO]  Patching call at 01FAEF75
0.412 [INFO]  Patching call at 01FAF40D
0.412 [INFO]  Patching PortAudio MarshalStreamComPointers
0.412 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.412 [INFO]  Patching call at 01F03059
0.412 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.412 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.412 [INFO]  Patching call at 01F0310E
0.415 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.415 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.415 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.415 [INFO]  AsioHelpers::FindDrivers
0.415 [INFO]    ASIO4ALL v2
0.415 [INFO]    FL Studio ASIO
0.416 [INFO]    Focusrite Thunderbolt ASIO
0.416 [INFO]    Focusrite USB ASIO
0.416 [INFO]    KATANA
0.416 [INFO]    Novation USB ASIO Driver
0.416 [INFO]    ReaRoute ASIO
0.417 [INFO]    Traktor Audio 10
0.417 [INFO]    Traktor Audio 2 MK2
0.417 [INFO]    Traktor Audio 6
0.417 [INFO]    Traktor Kontrol S2 MK2
0.417 [INFO]    Traktor Kontrol S4 MK2
0.417 [INFO]    Traktor Kontrol S5
0.418 [INFO]    Traktor Kontrol S8
0.418 [INFO]    Traktor Kontrol Z1
0.418 [INFO]    Traktor Kontrol Z2
0.418 [INFO]    Virus USB ASIO driver
0.418 [INFO]    Voicemeeter Virtual ASIO
0.418 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.418 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusriteusb\focusriteusbasio32.dll
0.429 [INFO]    ASIO input channels info:
0.429 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
0.429 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
0.429 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 3
0.429 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 4
0.429 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Loop 1
0.429 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Loop 2
0.429 [INFO]    ASIO output channels info:
0.429 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
0.429 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
0.429 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 3
0.429 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 4
0.429 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.429 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ReaRoute ASIO
0.429 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\REAPER\rearoute.dll
0.432 [INFO]    ASIO input channels info:
0.432 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 1
0.432 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 2
0.432 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 3
0.432 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 4
0.432 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 5
0.432 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 6
0.432 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 7
0.432 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 8
0.432 [INFO]      8 - active: 0, channel: 8, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 9
0.432 [INFO]      9 - active: 0, channel: 9, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 10
0.432 [INFO]      10 - active: 0, channel: 10, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 11
0.432 [INFO]      11 - active: 0, channel: 11, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 12
0.432 [INFO]      12 - active: 0, channel: 12, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 13
0.432 [INFO]      13 - active: 0, channel: 13, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 14
0.432 [INFO]      14 - active: 0, channel: 14, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 15
0.432 [INFO]      15 - active: 0, channel: 15, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: ReaRoute REAPER=>CLIENT 16
0.432 [INFO]    ASIO output channels info:
0.432 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 1
0.432 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 2
0.432 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 3
0.432 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 4
0.432 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 5
0.432 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 6
0.432 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 7
0.432 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 8
0.432 [INFO]      8 - active: 0, channel: 8, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 9
0.432 [INFO]      9 - active: 0, channel: 9, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 10
0.432 [INFO]      10 - active: 0, channel: 10, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 11
0.432 [INFO]      11 - active: 0, channel: 11, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 12
0.432 [INFO]      12 - active: 0, channel: 12, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 13
0.432 [INFO]      13 - active: 0, channel: 13, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 14
0.432 [INFO]      14 - active: 0, channel: 14, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 15
0.432 [INFO]      15 - active: 0, channel: 15, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: ReaRoute Client=>REAPER 16
0.432 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.432 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.432 [INFO]    hr: S_OK
0.432 [INFO]    *ppEndpoint: 14EEDC00
0.432 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.432 [INFO]    hr: S_OK
0.432 [INFO]    *ppEndpoint: 14EED9C0
0.432 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.432 [INFO]    hr: S_OK
0.432 [INFO]    *ppDevices: 14EBEA38
0.432 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.432 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.432 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.432 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.432 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.432 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.432 [INFO]    *pDataFlow: eRender
0.432 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.432 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.432 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.432 [INFO]    *pDataFlow: eCapture
0.432 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.432 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.454 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.454 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.454 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.454 [ERROR]    failed to initialize asio driver with requested format
0.454 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.454 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.454 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.454 [ERROR]    failed to initialize asio driver with requested format
0.454 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.454 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.454 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.454 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
0.454 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
0.454 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 1ms (48 frames)
0.454 [INFO]  AsioSharedHost::Setup - startCount: 0
0.454 [INFO]    post output ready: 1
0.454 [INFO]    ASIOBufferSize - min: 48 max: 48 preferred: 48 granularity: 16
0.454 [INFO]    Creating ASIO buffers (4 out, 6 in)...
0.454 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
0.454 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 2 value: 0 | returning: 1
0.455 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 3 | returning: 0
0.455 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 5 | returning: 0
0.455 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 4 | returning: 0
0.455 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 6 | returning: 0
0.455 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 15 | returning: 0
0.455 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.455 [INFO]    *pNumBufferFrames: 48
0.455 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.455 [INFO]    latency: 2ms
0.455 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.455 [INFO]    returning render client
0.455 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.457 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.457 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.457 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.457 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 48
0.457 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 48
0.457 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.457 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.457 [INFO]  AsioSharedHost::Start - startCount: 0
0.457 [INFO]    Starting ASIO stream...
0.460 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.460 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 48
0.460 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 48
0.460 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.461 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.461 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 48
0.461 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 48
0.461 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.462 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
26.697 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.697 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.697 [ERROR]    failed to initialize asio driver with requested format
26.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.697 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.697 [ERROR]    failed to initialize asio driver with requested format
26.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.697 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.697 [ERROR]    failed to initialize asio driver with requested format
26.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
26.697 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
26.697 [INFO]  {ASIO IN 0} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
26.697 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - actual buffer duration: 1ms (48 frames)
26.697 [INFO]  AsioSharedHost::Setup - startCount: 0
26.697 [INFO]    post output ready: 0
26.697 [INFO]    ASIOBufferSize - min: 48 max: 48 preferred: 48 granularity: 0
26.697 [INFO]    Creating ASIO buffers (16 out, 16 in)...
26.697 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
26.697 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioEndpointVolume dwClsCtx: 1
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
26.697 [INFO]    *pNumBufferFrames: 48
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
26.697 [INFO]    latency: 1ms
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioCaptureClient
26.697 [INFO]    returning capture client
26.697 [INFO]  Patched_PortAudio_MarshalStreamComPointers
26.697 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
26.697 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Start
26.697 [INFO]  AsioSharedHost::Start - startCount: 0
26.697 [INFO]    Starting ASIO stream...
26.698 [INFO]  ReaRoute ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
26.698 [INFO]  ReaRoute ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
26.698 [INFO]  26.698 [INFO]  {ASIO IN 0} RSAsioAudioClient::OnAsioBufferSwitch - buffer underrun detected

**Comment by Ariloum** [comment]
RS_ASIO.ini

[Config]
EnableWasapi=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ReaRoute ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by Ariloum** [comment]
Rocksmith.ini

[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=2560
ScreenHeight=1440
Fullscreen=0
VisualQuality=2
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=1
[Net]
UseProxy=1

**Comment by mdias** [comment]
Hello
If your log file is getting huge it's bad news; I'm guessing you have a ton of buffer underrun errors. Start by increasing your buffer size to something like 256 to ensure you're within sane values.
Other than that I personally never used ReaRoute so I won't be of much help there, the reason I added the links in the README is because other people have reported success with them in the past.

**Comment by Ariloum** [comment]
I've tried to run it again today and everything is working good now, have no idea why did it bugged on first approach.
