### ISSUE TITLE
Extremely Bugged Audio

### ISSUE THREAD

**Issue by Jwo8** [mdias/rs_asio#153]
I think I've sort of run into an odd conjunction that doesn't really lead anywhere good. With ExclusiveMode=1 and Win32UltraLowLatencyMode=1 (as RS_ASIO requires), I have very slow, choppy, and bugged audio. Without those on, RS_ASIO doesn't work. Everything else _should_ work right if I can get that figured out. 
### Rocksmith.ini
```[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=8
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1280
ScreenHeight=720
Fullscreen=2
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
```

### RS_ASIO.ini
```
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=96

[Asio.Output]
Driver=Focusrite Thunderbolt ASIO
BaseChannel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite Thunderbolt ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

### RS_ASIO-log.txt
```
0.000 [INFO]   - Wrapper DLL loaded (v0.5.5)
0.000 [INFO]  PatchOriginalCode
0.587 [INFO]  Patching CoCreateInstance
0.587 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.587 [INFO]  Patching call at 01C5AA85
0.587 [INFO]  Patching call at 01F03B6E
0.587 [INFO]  Patching call at 01F5C681
0.587 [INFO]  Patching call at 01FAEF75
0.587 [INFO]  Patching call at 01FAF40D
0.587 [INFO]  Patching PortAudio MarshalStreamComPointers
0.587 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.587 [INFO]  Patching call at 01F03059
0.587 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.587 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.587 [INFO]  Patching call at 01F0310E
0.594 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.594 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.594 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.594 [INFO]  AsioHelpers::FindDrivers
0.595 [INFO]    ASIO DirectX Full Duplex
0.595 [INFO]    ASIO4ALL v2
0.596 [INFO]    FL Studio ASIO
0.596 [INFO]    Focusrite Thunderbolt ASIO
0.596 [INFO]    Focusrite USB ASIO
0.597 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite Thunderbolt ASIO
0.597 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusritepcie\focusritepcieasio32.dll
0.604 [ERROR]  ASIO Error: Cannot open Focusrite Thunderbolt ASIO. (Error code: 0x54f)

0.604 [INFO]  Destroying AsioSharedHost - dll: c:\program files\focusritepcie\focusritepcieasio32.dll
0.604 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.604 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite Thunderbolt ASIO
0.604 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusritepcie\focusritepcieasio32.dll
0.611 [ERROR]  ASIO Error: Cannot open Focusrite Thunderbolt ASIO. (Error code: 0x54f)

0.611 [INFO]  Destroying AsioSharedHost - dll: c:\program files\focusritepcie\focusritepcieasio32.dll
0.611 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.635 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 15 render devices, 0 capture devices
0.635 [INFO]    hr: S_OK
0.635 [INFO]    *ppEndpoint: 09DC0530
0.635 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.635 [INFO]    hr: 80070490
0.635 [INFO]    *ppEndpoint: 00000000
0.635 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.636 [INFO]    hr: S_OK
0.636 [INFO]    *ppDevices: 11567280
```

**Comment by zagatozee** [comment]
Are your speakers or headphones connected to your interface, or your motherboard?

> EnableWasapiOutputs=1

Suggests you're missing out on half of the benefit of using RS_ASIO - or almost all of the benefits when it comes to using Focusrite gear, since their WASAPI drivers are infamous for being not great.

**Comment by Jwo8** [comment]
> Are your speakers or headphones connected to your interface, or your motherboard?
> 
> > EnableWasapiOutputs=1
> 
> Suggests you're missing out on half of the benefit of using RS_ASIO - or almost all of the benefits when it comes to using Focusrite gear, since their WASAPI drivers are infamous for being not great.

Yeah, I have all sound routed through the Scarlette Solo 3G. I'm not entirely knowledgable when it comes to this kind of stuff, admittedly. If there's something better, what do you suggest?

**Comment by Jwo8** [comment]
> > Are your speakers or headphones connected to your interface, or your motherboard?
> > > EnableWasapiOutputs=1
> > 
> > 
> > Suggests you're missing out on half of the benefit of using RS_ASIO - or almost all of the benefits when it comes to using Focusrite gear, since their WASAPI drivers are infamous for being not great.
> 
> Yeah, I have all sound routed through the Scarlette Solo 3G. I'm not entirely knowledgable when it comes to this kind of stuff, admittedly. Should I set `EnableWasapiOutputs=1` to 0?

I've set the value to 0 but now it's not detecting any RT Cable. Where'd I go wrong there?

**Comment by mdias** [comment]
Can you show what your config looks like now?
I find it strange you're using `BaseChannel=1` on the output...

**Comment by Jwo8** [comment]
I ended up using this:

`[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100`

`[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=8
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=1
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1280
ScreenHeight=720
Fullscreen=2
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1`

Works just fine now. Thank you!
