### ISSUE TITLE
No Output SOUND

### ISSUE THREAD

**Issue by Arutosio** [mdias/rs_asio#154]
hi, i have a problem when i run the game the game start very well but with out output sound,
there is not output, what can i do? is this a bug?
i have a Scarlett Focusrite 4i4 3gen
this is my config file 
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/5813627/RS_ASIO.txt)
[Rocksmith.ini.txt](https://github.com/mdias/rs_asio/files/5813629/Rocksmith.ini.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/5813601/RS_ASIO-log.txt)

**Comment by mdias** [comment]
You're using 16 as the buffer size.

As described in the readme file:

> Some Focusrite devices have been reported to only output sound properly when using ASIO buffer sizes of 48, 96 or 192. You can use the custom buffer size setting on RS_ASIO.ini for this.

So you either need to change that in your focusrite panel, or change this in your config:
```
[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=96
```

**Comment by Arutosio** [comment]
it did not resolve the issue
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/5818928/RS_ASIO-log.txt)

**Comment by mdias** [comment]
You also have `Win32UltraLowLatencyMode=0` which, as you can read in the readme:

> Make sure Rocksmith.ini is set to run with `ExclusiveMode=1` and `Win32UltraLowLatencyMode=1`. If in doubt, use default settings.

**Comment by Arutosio** [comment]
ok now it works but the audio is buzzing

**Comment by Arutosio** [comment]
> ok now it works but the audio is buzzing
> [Rocksmith.ini.txt](https://github.com/mdias/rs_asio/files/5821904/Rocksmith.ini.txt)
> [RS_ASIO.ini.txt](https://github.com/mdias/rs_asio/files/5821905/RS_ASIO.ini.txt)
> [RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/5821907/RS_ASIO-log.txt)

i solved the problem by setting
LatencyBuffer=2 inside Rocksmith.ini
