### ISSUE TITLE
One more device to add to the working interface list: Focusrite Clarett 8Pre USB

### ISSUE THREAD

**Issue by LarsColman** [mdias/rs_asio#158]
Wanted to add for completeness sake, set this up with my focusrite Clarett **8**Pre USB, which also works perfectly.  
I used a buffer of 48 in the driver and latency 1, as suggested by #42 .

Much MUCH better than the RT cable, thank you!

**Comment by mdias** [comment]
Awesome! Thank you for the report, added it to the list 👍
