### ISSUE TITLE
Compatibility with Cracked Version of Rocksmith?

### ISSUE THREAD

**Issue by OmarAbzd** [mdias/rs_asio#159]
Hey, I tried using the files and when I check the RS_ASIO-log it says no valid locations for patching were found. I'm assuming this is because my version of the game is cracked. Is this true? Am I missing something?

**Comment by zagatozee** [comment]
Yes, that is correct. Good news however - $9 can fix that, will also mean you can use all of the other mods and customisations for the game - as well as all the updates UbiSoft included.

https://www.reddit.com/r/rocksmith/comments/h9lok9/rocksmith_2014_is_70_off_via_humble/

**Comment by mdias** [comment]
@zagatozee thank you for your quick reply.
