### ISSUE TITLE
Output is fine; input not working [Focusrite Saffire Pro 40]

### ISSUE THREAD

**Issue by GrowlHowell** [mdias/rs_asio#16]
It doesn't seem to make a difference what settings I use for buffer and such. Any ideas?

I'm using a Focusrite Saffire Pro 40.

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4043302/RS_ASIO-log.txt)

**Comment by mdias** [comment]
There was a bug I just fixed in [this release](https://github.com/mdias/rs_asio/releases/tag/V0.3.7).
Please try that and report back :)

**Comment by GrowlHowell** [comment]
That was crazy fast, and it's working perfectly now. Thanks!

**Comment by mdias** [comment]
No problem :)
