### ISSUE TITLE
IK Multimedia iRig Confirmation

### ISSUE THREAD

**Issue by PaletaGalleta** [mdias/rs_asio#164]
Hello,
I just configured an iRig (First Version) with ASIO4ALL V2 and it works perfectly. RS recognizes the setup like the audio cable that comes with the game.

Thank you!

**Comment by mdias** [comment]
Hello, I'm glad it's working fine for you, but beware that ASIO4ALL may not get you the best experience. Best experience is achieved with a true ASIO driver; I'm not sure it's relevant to your interface but check [this](https://www.ikmultimedia.com/faq/?id=1340).

Thank you for the report though, I've added the interface to the list 👍

**Comment by mazni25** [comment]
> Hello, I just configured an iRig (First Version) with ASIO4ALL V2 and it works perfectly. RS recognizes the setup like the audio cable that comes with the game.
> 
> Thank you!

Hello, can I know what iRig are u using? is it Amplitube iRig(cylinder version)?

**Comment by PaletaGalleta** [comment]
> Hello, can I know what iRig are u using? is it Amplitube iRig(cylinder version)?

Hello, it's [this one](https://d3ugyf2ht6aenh.cloudfront.net/stores/002/030/466/products/hf80afbc8260841a0a552c0bf08df915841-c00a2d03a3510e7edb16452244525359-640-0.jpeg)

**Comment by mazni25** [comment]
> > Hello, can I know what iRig are u using? is it Amplitube iRig(cylinder version)?
> 
> Hello, it's [this one](https://d3ugyf2ht6aenh.cloudfront.net/stores/002/030/466/products/hf80afbc8260841a0a552c0bf08df915841-c00a2d03a3510e7edb16452244525359-640-0.jpeg)

Hello PaletaGalleta, can u teach me how to install the driver step by step correctly , because I already install the driver but not working(no sound detected) 

Also I wanna ask, is it are you using headphone jack like this?
![Laptop-Headphone-jack](https://github.com/mdias/rs_asio/assets/137206950/b4814f0b-32ab-4044-a8da-108d7f13abdb)
