### ISSUE TITLE
Solid State Logic SSL2+ Confirmed Working

### ISSUE THREAD

**Issue by Aensland** [mdias/rs_asio#167]
I recently purchased a [Solid State Logic SSL2+](https://www.solidstatelogic.com/products/ssl2-plus) audio interface. I can confirm it works great with Rocksmith using RS_ASIO.

These are the config settings I use:

```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Solid State Logic ASIO Driver
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Solid State Logic ASIO Driver
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```
![SSL2_01](https://user-images.githubusercontent.com/37945705/109434708-8c670c00-79e4-11eb-9370-6dd07b726f5d.PNG)

![SSL2_02](https://user-images.githubusercontent.com/37945705/109434714-96890a80-79e4-11eb-962e-777812bc2baf.PNG)

![SSL2_03](https://user-images.githubusercontent.com/37945705/109434717-9be65500-79e4-11eb-97c1-ddf5caff43bb.PNG)

![SSL2_04](https://user-images.githubusercontent.com/37945705/109434726-a1dc3600-79e4-11eb-8e5e-3716636b63d7.PNG)

I'm sure the SSL2 (non plus) works perfectly fine as well, but I haven't tested that. I hope this helps!

**Comment by mdias** [comment]
Thank you for the report.
I will be adding it to the list soon.

**Comment by mdias** [comment]
List is updated. Thank you again 👍

**Comment by tick3r-dev** [comment]
It also work on [Solid State Logic SSL12](https://www.solidstatelogic.com/products/ssl-12) audio interface.

**Comment by chybanieczaje** [comment]
SSL 2+ MK II user here, setup above didn't work for me. After some figuring out, this is what made it work:


[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=SSL ASIO Driver 1
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=SSL ASIO Driver 1
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=SSL ASIO Driver 1
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by chybanieczaje** [comment]
In ASIO settings, there are 4 options -SSL ASIO1 - 4. I am using SSL ASIO 1, hence why that is in my config file.

**Comment by mdias** [comment]
@chybanieczaje thank you. I've added an entry in the docs for the SSL 2+ MKII variant linking directly to your comment.

**Comment by x-ticker** [comment]
@mdias I can confirm the new format is the same for others SSL interfaces. This is because of new driver version.

<img width="437" height="313" alt="Image" src="https://github.com/user-attachments/assets/393e0140-9ab8-44b3-a657-0a4f5dfc7a15" />

<img width="439" height="314" alt="Image" src="https://github.com/user-attachments/assets/873b2f6e-0d7d-4102-8b4f-c7726374f927" />

**Comment by mdias** [comment]
@x-ticker can you provide a list of which ones you specifically tested?
I'd rather have on the list only ones that people specifically tested and not try to assume other will work fine.

**Comment by x-ticker** [comment]
@mdias I tested only SSL 12 but they all share the same driver.

[SSL 2/2+ - MK I / MK II and 12 driver page](https://support.solidstatelogic.com/hc/en-gb/articles/5349706035229-SSL-USB-Audio-ASIO-WDM-Windows-Driver-Downloads)

**Comment by mdias** [comment]
@x-ticker I agree with that it's extremely likely that those interfaces will also work.

However, the driver being the same does not mean it will behave in exactly the same way for all models.
With that in mind I'd prefer to not say "it's been reported to work" in the docs without someone having tested the specific models, as we might get unlucky and encounter an incompatibility issue with a specific model after someone already spending money to buy one.
