### ISSUE TITLE
No input/ASIO Helper

### ISSUE THREAD

**Issue by pineapple223** [mdias/rs_asio#17]
I'm attempting to use this with my Scarlett 2i2 2nd gen, but my log file isn't showing the AsioHelper line nor does setting my driver to "Focusrite USB ASIO" work. 

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4050117/RS_ASIO-log.txt)

> 0.000 [INFO]   - Wrapper DLL loaded
0.000 [INFO]  PatchOriginalCode
0.000 [INFO]  Patching CoCreateInstance
0.039 [INFO]  Patch_CallAbsoluteAddress - num locations: 0
0.039 [INFO]  Patching PortAudio MarshalStreamComPointers
0.076 [INFO]  Patch_CallRelativeAddress - num locations: 0
0.077 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.114 [INFO]  Patch_CallRelativeAddress - num locations: 0
12.578 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
What version of Rocksmith are you running?

**Comment by pineapple223** [comment]
So my original issue was just me using a different no cable patch at the same time by accident. I've gotten it to load up properly now however it's still not picking up any input from my guitar. 
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4050198/RS_ASIO-log.txt)

**Comment by pineapple223** [comment]
No clue what the issue was but it's working now after restarting my computer.

**Comment by mdias** [comment]
I think I found the issue. Please try the [latest release](https://github.com/mdias/rs_asio/releases/latest) and report back.

**Comment by pineapple223** [comment]
Seems to be working fine now!

**Comment by mdias** [comment]
Awesome! Thanks for letting me know :)
