### ISSUE TITLE
Does it work with ZOOM G Series ASIO?

### ISSUE THREAD

**Issue by RengarBR** [mdias/rs_asio#170]
Hello there

I will buy the game when it get some discount, I have a Zoom G2.1NU multieffects guitar pedal which uses a ZOOM G Series ASIO driver, will it work with your program? Should I buy a Behringer interface? Which would behringer reccomend?

Thanks

**Comment by mdias** [comment]
Hello

Unfortunately there is no way for me to tell you for sure since I don't own that interface. However if that interface works well with other ASIO enabled applications and it doesn't use ASIO4ALL there's a very high chance it will work fine.

As for recomendation I wouldn't be the best person to ask in regards to specs and whatnot, but I can tell you that I own the Behringer UMC204HD and it works perfectly fine.

If in the meantime you buy the game and can confirm that it works fine with RS ASIO let me know and I'll add it to the list :)

**Comment by RengarBR** [comment]
Thanks for the fast answer, I will share my future experience.

Btw, thanks for the recomendation and the tip to avoid the ASIO4ALL (I just found out Arcano Interfaces, but sadly they use that 4ALL)

**Comment by RengarBR** [comment]
Hello, the game has disccount today and I bought to try with my guitar pedal, the log shows as:
9.435 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
9.435 [INFO]  AsioHelpers::FindDrivers
9.436 [INFO]    ZOOM G Series ASIO
9.436 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
9.436 [INFO]    hr: 80070490
9.436 [INFO]    *ppEndpoint: 00000000
9.436 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
9.436 [INFO]    hr: 80070490
9.436 [INFO]    *ppEndpoint: 00000000
9.436 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
9.436 [INFO]    hr: S_OK
9.436 [INFO]    *ppDevices: 08307250
9.446 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
125.777 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
126.015 [INFO]   - Wrapper DLL unloaded

and edited on .ini all the [Asio] boxes as:
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[ZOOM G Series ASIO]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[ZOOM G Series ASIO.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[ZOOM G Series ASIO.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[ZOOM G Series ASIO.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[ZOOM G Series ASIO.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

I have run the game but it appeared a message saying to connect the cable and that I didnt have a mic, what am I doing wrong?

**Comment by mdias** [comment]
You have added the interface driver name to the wrong places in the ini file. Try this:

```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
; driver - respect buffer size setting set in the driver
; host - use a buffer size as close as possible as that requested by the host application
; custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ZOOM G Series ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ZOOM G Series ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by RengarBR** [comment]
I've corrected the driver name on the correct places, it detected as a realtone cable, but it doesn't make any sound when the game goes to the tuner part

**Comment by mdias** [comment]
Have you tried to change `Channel=0` to something else? It's possible that your guitar is not on the 1st input. Try maybe `Channel=1` or so.

**Comment by RengarBR** [comment]
I just tried changing the 0 to 1 but it didnt detect the sound of my guitar, even the game doesnt make any sound, should I unistall the ZOOM G Series ASIO and try ASIO4all?

**Comment by mdias** [comment]
Oh, since you only mentioned no sound on the tuner part, I thought the rest of the game had sound.
Is there any error regarding sound when booting the game up? If not, RS ASIO is probably working fine, so maybe you don't have any speakers connected to your interface?

If you don't want to connect your speakers to the interface you'll have to enable Wasapi outputs, and disable the ASIO output by leaving it's driver empty.

**Comment by RengarBR** [comment]
The interface/multi-efx has a output jack connected to my amp (its a 30W small one) which I can also connect a P2 input coming from PC. The interface input+P2 headphones or with interface output work fine when I use a amp simulator,

Now with wasapi the game has sound but the game doesn't get any sound from my interface, there is no error message but when I try to tune it says +999E, when I try to calibrate the game is like this:
![R2](https://user-images.githubusercontent.com/60355840/111795022-e0745a80-88d7-11eb-8652-361d7f386706.PNG)
![R1](https://user-images.githubusercontent.com/60355840/111795042-e407e180-88d7-11eb-894f-3854b13f03e6.PNG)

**Comment by mdias** [comment]
Is there anything helpful on the log?

If ASIO is streaming audio and you don't have sound it should be because you don't have the right input channel selected. 

> The interface input+P2 headphones or with interface output work fine when I use a amp simulator,

If this amp simulator uses ASIO you should be able to check which channel you're using there. Keep in mind that RS_ASIO counts channels from zero, not one. So the first channel is channel zero.

**Comment by RengarBR** [comment]
I just tried changing from [Asio.Input.0] to [Asio.Input.1] but the game still didnt detect any sound comming from the interface, Im quite confused, I guess that my interface has input0 into channel 1 and input1 into channel 2, I think that one channel is audio from input jack and the other is from USB audio

2.892 [INFO]  AsioHelpers::FindDrivers
2.892 [INFO]    ZOOM G Series ASIO
2.892 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: ZOOM G Series ASIO
2.892 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\ZOOM\G Series Driver\zmghpaso.dll
2.905 [INFO]    ASIO input channels info:
2.905 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt16LSB, name: ZOOM G Series Audio In 01
2.905 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt16LSB, name: ZOOM G Series Audio In 02
2.905 [INFO]    ASIO output channels info:
2.905 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt16LSB, name: ZOOM G Series Audio Out 01
2.905 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt16LSB, name: ZOOM G Series Audio Out 02
2.906 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
2.910 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 15 render devices, 1 capture devices
2.910 [INFO]    hr: S_OK
2.910 [INFO]    *ppEndpoint: 18E352F8
2.910 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
2.910 [INFO]    hr: S_OK
2.910 [INFO]    *ppEndpoint: 18E35148
2.910 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
2.910 [INFO]    hr: S_OK


reading the log I found a interesting thing (I have deleted some master volume lines to make it shorter):

`29.237 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
29.237 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
29.237 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt16LSB
29.237 [ERROR]    failed to initialize asio driver with requested format
29.237 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
29.237 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
29.237 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt16LSB
29.237 [ERROR]    failed to initialize asio driver with requested format
29.237 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
29.237 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
29.237 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt16LSB
29.237 [ERROR]    failed to initialize asio driver with requested format
29.237 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
29.237 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
29.237 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
29.237 [INFO]  {ASIO IN 1} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
29.237 [INFO]  {ASIO IN 1} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
29.237 [INFO]  {ASIO IN 1} RSAsioAudioClient::Initialize - actual buffer duration: 1ms (48 frames)
29.237 [INFO]  AsioSharedHost::Setup - startCount: 0
29.237 [INFO]    post output ready: 1
29.237 [INFO]    ASIOBufferSize - min: 48 max: 960 preferred: 48 granularity: 24
29.237 [INFO]    Creating ASIO buffers (2 out, 2 in)...
29.237 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
29.271 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioEndpointVolume dwClsCtx: 1
29.271 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
29.271 [INFO]    *pNumBufferFrames: 48
29.271 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
29.271 [INFO]    latency: 1ms
29.271 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioCaptureClient
29.271 [INFO]    returning capture client
29.271 [INFO]  Patched_PortAudio_MarshalStreamComPointers
29.272 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
29.272 [INFO]  {ASIO IN 1} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
29.272 [INFO]  {ASIO IN 1} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
29.272 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
29.272 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
29.272 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Start
29.272 [INFO]  AsioSharedHost::Start - startCount: 0
29.272 [INFO]    Starting ASIO stream...
29.276 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.17
29.278 [INFO]  ZOOM G Series ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
29.278 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
29.278 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 48
29.278 [INFO]  {ASIO IN 1} RSAsioAudioClient::SwapBuffers
29.281 [INFO]  ZOOM G Series ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
29.281 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
29.281 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 48
29.281 [INFO]  {ASIO IN 1} RSAsioAudioClient::SwapBuffers
29.284 [INFO]  ZOOM G Series ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
29.284 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
29.284 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 48
62.195 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::GetMasterVolumeLevelScalar
62.210 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::GetMasterVolumeLevelScalar
62.227 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::GetMasterVolumeLevelScalar
64.195 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.4
64.729 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.41
64.746 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.42
64.763 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.43
64.779 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.44
64.796 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.45
64.813 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.46
64.829 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.47
64.846 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.48
64.863 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.49
64.879 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.5
68.817 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.968977
68.833 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.97617
68.850 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.983392
68.867 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.990629
68.883 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.99789
68.900 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 1
68.917 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 1
76.411 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Stop
76.411 [INFO]  AsioSharedHost::Stop - startCount: 1
76.411 [INFO]  AsioSharedHost::Stop  stopping ASIO stream
76.413 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
76.414 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
76.414 [INFO]  {0.0.0.00000000}.{a7742cf0-9cc5-46e3-a84f-93e8838e48f4} DebugWrapperAudioClient<struct IAudioClient3>::Stop
76.624 [INFO]   - Wrapper DLL unloaded
`

**Comment by mdias** [comment]
> I just tried changing from [Asio.Input.0] to [Asio.Input.1] 
Can you clarify what you did here?

You only need to change the `Channel=` part of one of the inputs. Otherwise you might be incorrectly editing the file.
The log looks fine and audio is streaming, and according to it your interface only has 2 inputs so there's not much to be wrong about. I don't remember if we ever had an interface that only supports 16-bit samples before though, so there's a small chance it could be that.
I would also recommend you use a bigger buffer size while testing this out, 48 samples could be a bit short.

This is how your config should look for input 0:
```
[Asio.Input.0]
Driver=ZOOM G Series ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

And this is how it should look for input 1:
```
[Asio.Input.0]
Driver=ZOOM G Series ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

Meaning that you don't have to touch `[Asio.Input.1]` at all to change the channel to use. This is just there to support 2 players.

**Comment by RengarBR** [comment]
my bad, I thought that I had to change the place of the driver name XD
what I did was this:

> [Asio.Input.0]
> Driver=
> Channel=0
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> 
> [Asio.Input.1]
> Driver=ZOOM G Series ASIO
> Channel=1
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
to this:

> > [Asio.Input.0]
> Driver=ZOOM G Series ASIO
> Channel=0
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> 
> [Asio.Input.1]
> Driver=
> Channel=1
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100

My interface is quite old, I bought it on 2012, it doesnt support anything bigger than 16bit sadly, I had a hope to play the game when you said that 48kHz was the minimum in the "how to use"
![R3](https://user-images.githubusercontent.com/60355840/111804856-88425600-88e1-11eb-930c-c4b475d24797.PNG)

**Comment by mdias** [comment]
> you said that 48kHz was the minimum in the "how to use"

This is correct, and if 16-bit is not working it's a bug that needs to be fixed :)
I just don't remember if any other interface was 16-bit.

**Comment by RengarBR** [comment]
Should I change something? Those are the only options on Control Panel:
![R5](https://user-images.githubusercontent.com/60355840/111808158-c7be7180-88e4-11eb-94bc-2734094af48c.PNG)
![R4](https://user-images.githubusercontent.com/60355840/111808367-ff2d1e00-88e4-11eb-9baa-7026bfca9722.PNG)

Maybe if I try to unistall that Driver, restart my PC then install a Asio4ALL maybe we could workaround the problem

**Comment by mdias** [comment]
I would set the latency to 3ms for now while testing (that should be equivalent to 144 samples).
And check if you have input signal on either channel 0 or 1.

**Comment by RengarBR** [comment]
I have set the latency to 3.0ms and tried both channel 0 and 1, the difference now is that on tunner it doesnt show as +999 anymore
![R6](https://user-images.githubusercontent.com/60355840/111818399-2dfcc180-88f0-11eb-9465-fb19c2335bb9.PNG)

On log I got this:

> 31.686 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
> 31.686 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt16LSB
> 31.686 [ERROR]    failed to initialize asio driver with requested format
> 31.686 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
> 31.686 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt16LSB
> 31.686 [ERROR]    failed to initialize asio driver with requested format
> 31.686 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
> 31.686 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt16LSB
> 31.686 [ERROR]    failed to initialize asio driver with requested format
> 31.686 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
> 31.686 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
> 31.686 [INFO]  {ASIO IN 0} WAVEFORMATEX
>   wFormatTag: fffe
>   nChannels: 2
>   nSamplesPerSec: 48000
>   nAvgBytesPerSec: 384000
>   nBlockAlign: 8
>   wBitsPerSample: 32
>   cbSize: 22
>   ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
>   ext.Samples: 24
>   ext.dwChannelMask: 3
> 31.686 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - actual buffer duration: 1ms (48 frames)
> 31.686 [INFO]  AsioSharedHost::Setup - startCount: 0
> 31.686 [INFO]    post output ready: 1
> 31.686 [INFO]    ASIOBufferSize - min: 48 max: 960 preferred: 144 granularity: 24
> 31.686 [INFO]    Creating ASIO buffers (2 out, 2 in)...
> 31.686 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 3 value: 0 | returning: 0
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioEndpointVolume dwClsCtx: 1
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
> 31.686 [INFO]    *pNumBufferFrames: 48
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
> 31.686 [INFO]    latency: 3ms
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioCaptureClient
> 31.686 [INFO]    returning capture client
> 31.686 [INFO]  Patched_PortAudio_MarshalStreamComPointers
> 31.686 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
> 31.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Start
> 31.686 [INFO]  AsioSharedHost::Start - startCount: 0
> 31.686 [INFO]    Starting ASIO stream...
> 31.687 [ERROR]    Failed to start ASIO stream
> 31.687 [ERROR]  ASIO Error: 
> 31.687 [INFO]    hr: E_FAIL
> 31.687 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Stop

**Comment by mdias** [comment]
I don't understand, you are able to do the calibration but not the tuning?

Your log is showing a failure to start ASIO streaming now, as you can see:
```
31.686 [INFO] Starting ASIO stream...
31.687 [ERROR] Failed to start ASIO stream
31.687 [ERROR] ASIO Error:
31.687 [INFO] hr: E_FAIL
```

> Should I set CustomBufferSize=48 to 16 to make it the same as 16 bit?

No. The buffer size has nothing to do with bit depth.

**Comment by RengarBR** [comment]
no, I can't do neither calibration and tuning, I tested with the no-cable mod, it worked but sound is really bad, the guitar is ripping all the sound, when I barely touch the pick the sound just flare my ears, after having some fun I muted my guitar on the mixer.

Its works, but not like I would want, I won't buy the realtone cable because we are on recession (Brazil) and it costs 10x the price payed the game on steam sale :(

Many thanks for @mdias for chatting with me and suporting this project and helping other people, if you want to close the issue Im fine with that

**Comment by mdias** [comment]
Does the interface work with any other ASIO-enabled application?

No cable mod is incompatible with RS_ASIO, you either use one or the other. You should make sure your Rocksmith installation is as vanilla as possible for RS_ASIO to work fine.

**Comment by RengarBR** [comment]
I deleted the 3 files from the root of the game to test no cable, well I didn't try anything other than Amped simulator, Audacity and editing custom patches of my guitar multieffects, those programs recognized the zoom driver as both input and output, I dont know what you mean as ASIO-enabled application

I didn't use it as much as Im using now, I was without a eletric guitar for 6 years (it was an awful cort model), I was training more on accoustic and bass

**Comment by mdias** [comment]
ASIO is an alternative way apps use to talk to your audio device, instead of going through the typical route windows provides (called WASAPI) which tends to result in more latency.
Audacity uses WASAPI, so it's not a good indicator that ASIO is working fine on your interface.

However since you don't seem to be familiar with ASIO at all and your interface seems to work fine with WASAPI, perhaps you'd be have less issues [using Direct Connect mode](https://www.youtube.com/watch?v=H6nAB5ogfeU).
If using that gives you really loud and distorted sound use the game volume calibration tool to see if it fixes it, or adjust the volume of your guitar in the interface or the guitar itself.

Sorry I can't be of more help using ASIO, but it's really strange you only get silence with it. It is possible this is a bug with RS ASIO that I would like to fix, but without access to the hardware it's mission impossible :/

If you try this please let me know if it helped.
