### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by SolimanGit** [mdias/rs_asio#173]
Problem. Is it normal that as soon as i put the files into the game directory I don't have sound anymore in my headset ? Nothing. Without the files the sound come back.
Thx in advance.

**Comment by mdias** [comment]
Yes, it's normal. You have to configure it first.

Read the instructions on the [README](https://github.com/mdias/rs_asio/blob/master/README.md) file.

**Comment by SolimanGit** [comment]
Thanks for your replay but i already did that.
I spent 3h to try different things. For the RSAsio.ini i used the one for the Focusrite Solo 3rd gene.

**Comment by mdias** [comment]
Please post the output log `RS_ASIO-log.txt` and your `RS_ASIO.ini`, as well as your interface name and where you have your headset connected.

**Comment by SolimanGit** [comment]
Ok thx I can't right now but later ok . All I can say now is that my headset is connected in the jack of my motherboard. And the Rs_ASIO.ini is a copy paste from the .ini in the "interface audio that works well" of Focusrite Solo 3rd gen.

**Comment by mdias** [comment]
> my headset is connected in the jack of my motherboard

You most likely have configured your RS_ASIO.ini to output through the interface.
To have the output go through your motherboard you need to set `EnableWasapiOutputs=1` and leave the `Driver=` empty on the [Asio.Output] section.

**Comment by SolimanGit** [comment]
Wow ok I didn't know for the wasapi output. Sorry and thanks a lot, it works.
