### ISSUE TITLE
Cant make it work with UMC202HD

### ISSUE THREAD

**Issue by angelo259** [mdias/rs_asio#174]
Can anyone help me with this? I don't understand what I'm doing wrong but I can't hear anything, it's like the output isn't set, I tryed different configurations but nothing happened.

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=UMC ASIO Driver
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=UMC ASIO Driver
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
This config looks good if you're outputting your audio through the interface. Where do you have your speakers/headphones connected?

**Comment by cloph** [comment]
Did you actually install the driver for the UMC202HD? it is not installed automatically, so without downloading the driver it won't work at all (sorry if that's obvious, but you can never be sure, esp. since you didn't write anything about it working in a DAW or similar). If you have the driver installed, you'll have a UMC driver control panel where you can configure the sample rate (needs to be set to 48000Hz) and the buffer size (128 should work without issues), leave safe mode enabled.

**Comment by gregorychristian** [comment]
I'm currently having the same issue:

RS_ASIO.ini file:
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=128

[Asio.Input.0]
Driver=UMC ASIO Driver
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

Error message from RS_ASIO-log.txt:
26.915 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.915 [ERROR]    failed to initialize asio driver with requested format
26.915 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.915 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.915 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.915 [ERROR]    failed to initialize asio driver with requested format
26.915 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.915 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.915 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.915 [ERROR]    failed to initialize asio driver with requested format

**Comment by mdias** [comment]
@gregorychristian please post the entirety of the log, those are not fatal errors.

Also, you seem to be using wasapi outputs instead of ASIO ones, so if you can't hear anything it's probably not ASIO related. Unless it's the case that you're also trying to output to the UMC202HD with WASAPI while using it's input through ASIO.

**Comment by gregorychristian** [comment]
> @gregorychristian please post the entirety of the log, those are not fatal errors.
> 
> Also, you seem to be using wasapi outputs instead of ASIO ones, so if you can't hear anything it's probably not ASIO related. Unless it's the case that you're also trying to output to the UMC202HD with WASAPI while using it's input through ASIO.

I was able to resolve the issue with some simple in-game settings. With regards to the WASAPI, I enabled this to prevent audio glitches (crackling, slowed tempo). Otherwise this solution works well. Thanks.
