### ISSUE TITLE
Output not working - Focusrite Scarlet 18i20

### ISSUE THREAD

**Issue by BonesJD** [mdias/rs_asio#177]
I have the latest driver installed from Focusrite
Focusrite Control 3.6.0.1882
Focusrite USB 4.65.5.658
Windows build 10.0.19042

The configuration with WASAPI output enabled works so the input from the interface is working but when I disable WASAPI out and try to use ASIO out, it does not work. I have attached the log where you can see the errors when it gets to {ASIO OUT} there is a lot of "hr: AUDCLNT_E_UNSUPPORTED_FORMAT" errors

I have also attached the RS_ASIO.ini and Rocksmith.ini as .txt files

I searched through a lot of forums and saw a lot of people having the same issue with Focusrite interfaces but could not find any solutions

[Rocksmith.txt](https://github.com/mdias/rs_asio/files/6215945/Rocksmith.txt)
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/6215946/RS_ASIO.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/6215947/RS_ASIO-log.txt)

**Comment by ffio1** [comment]
If I had to guess, it might be because your have "ExclusiveMode" in your Rocksmith.ini set to 0 when RS_ASIO requires it be set to 1 for it to work.

**Comment by RMDragonheart** [comment]
I also have a problem with output, but mine is related to that I have separate Audio Card - Realtek, to which I connect my Headset.
LOG:
RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Realtek High Definition ASIO
0.295 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.295 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO

RS_ASIO.ini:
[Asio.Output]
Driver=Realtek High Definition ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

Guitar works perfectly connected to Focusrite USB ASIO, but I don't hear anything

**Comment by mdias** [comment]
@RMDragonheart for your case, leave the `Driver=` empty on the `[Asio.Output]` section, and enable wasapi outputs at the top of the config. It should then use the default output device just as it would without RS ASIO, but still use RS ASIO for input.

**Comment by RMDragonheart** [comment]
@mdias It works! Awesome! Thanks :D

**Comment by BonesJD** [comment]
> If I had to guess, it might be because you have "ExclusiveMode" in your Rocksmith.ini set to 0 when RS_ASIO requires it be set to 1 for it to work.

that worked thanks for that!

I made the mistake because I was following this [video](https://youtu.be/gIp6IyPjGOY?t=115) where he explicitly states to uncheck exclusive mode. I guess this was because he was using WASAPI out or maybe because exclusive mode prevents you from recording the audio in OBS?

**Comment by mdias** [comment]
@BonesJD He actually re-enables exclusive mode later, see at [12:38](https://youtu.be/gIp6IyPjGOY?t=758).
I suspect the reason he disabled it at first was just to test if the input was working before continuing further.
