### ISSUE TITLE
Using two identical audio interfaces

### ISSUE THREAD

**Issue by pk044** [mdias/rs_asio#178]
This is more of a question than an issue - I'm planning to connect two Focusrite Scarlett Solos and play with someone else.

Is it possible with rs_asio?

Thanks!

**Comment by mdias** [comment]
I would assume it will be problematic unless the Focusrite driver detects both interfaces and somehow merges the available channels. It's **highly** unlikely it does that though.

**Comment by pk044** [comment]
Checked it and the other interface just gets stuck - looks like only one Scarlett interface at a time can be connected to the PC.

thanks for the input by the way!
