### ISSUE TITLE
iRig HD 2 doesn't seem to be detected 

### ISSUE THREAD

**Issue by choladodude32** [mdias/rs_asio#180]
I was following the steps from the youtube video; [https://www.youtube.com/watch?v=gIp6IyPjGOY](https://www.youtube.com/watch?v=gIp6IyPjGOY) but seem to get stuck when I go into RS_ASIO-log and look for my driver. 
here is my paste: [https://pastebin.com/kR9t44ZB](https://pastebin.com/kR9t44ZB)

**Comment by mdias** [comment]
Your log shows that you have no 32-bit ASIO drivers installed.

**Comment by choladodude32** [comment]
okay, how would I instal it?

**Comment by mdias** [comment]
Look for either `ASIO` or `driver` in your [product page](https://www.ikmultimedia.com/products/irighd2/).

**Comment by choladodude32** [comment]
thanks, it works fine!
