### ISSUE TITLE
Setting up with lexicon omega ASIO4ALL

### ISSUE THREAD

**Issue by martinmunozf** [mdias/rs_asio#189]
yo, I know this isn't an error or problem with your work, but I tried to get this to work with ASIO4ALL v2 driver using the lexicon omega but had no success, probably due to how many inputs/outputs the device has. If you know any information on this or something please let me know, I really appreciate your work!

**Comment by mdias** [comment]
Hello

I will need to see your ini configs as well as the RS_ASIO-log to have an idea of what's going on.

Also, when you say "no success" what does it mean? Is there an error message? No output sound? Input? etc

**Comment by martinmunozf** [comment]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/6446293/RS_ASIO-log.txt)

![image](https://user-images.githubusercontent.com/66289819/117548593-cca9c280-b003-11eb-958f-efc9fc8f80f9.png)
![image](https://user-images.githubusercontent.com/66289819/117548601-d9c6b180-b003-11eb-90f4-aa40dbc54501.png)

The interface itself has like 5 line inputs, where one of them is linked to Line 3 as a instrument channel. I managed to get it working once, but I couldnt get it to output anywhere (wanted it to output to my usb dac). 
Now it's always the constant "no output device detected"

**Comment by martinmunozf** [comment]
Changed to ExclusiveMode=1 and Win32UltraLowLatencyMode=1, the pop-up is gone but there is still no audio when game starts or during the game (testing output directly from interface). 
ASIO4ALL offline control panel (also tested forcing 16bit)
![image](https://user-images.githubusercontent.com/66289819/117555461-6043b900-b02d-11eb-87e8-9c02b8bb1a6d.png)
Also made sure that every one of the dectected sound outputs is on 16bit at 48khz
![image](https://user-images.githubusercontent.com/66289819/117555561-3dfe6b00-b02e-11eb-86da-d45347ecc686.png)

**Comment by martinmunozf** [comment]
Managed to get output working. currently outputing to the first usb audio device listed as output and disabled the other 2 (Lexicon mac usb OUT). The sound input from the guitar is detected by windows in the sound panel from the same input channel I guess (lexicon mac usb IN), but although ive tried changing channels in RS_audio.ini from 0 to 1 and vice versa, I cant seem to get the input working in game. Attachments included. 
![image](https://user-images.githubusercontent.com/66289819/117891501-fe7d8c00-b284-11eb-8830-da1eb26de145.png)
![image](https://user-images.githubusercontent.com/66289819/117891538-0fc69880-b285-11eb-98f1-cc7272902133.png)
![image](https://user-images.githubusercontent.com/66289819/117891632-3e447380-b285-11eb-87b0-d4acffe8cbd7.png)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/6462282/RS_ASIO-log.txt)
![image](https://user-images.githubusercontent.com/66289819/117891679-561bf780-b285-11eb-9c2b-fc9e09f8e63a.png)
![image](https://user-images.githubusercontent.com/66289819/117891786-8a8fb380-b285-11eb-9784-e98e6eadc592.png)

**Comment by mdias** [comment]
According to the ASIO4ALL screenshot, your interface has 4 inputs, so you'll have to try which one is the right one.

On the `[Asio.Input.0]` ini section, change `Channel=0` to `Channel=1`, if that doesn't work try `Channel=2` and then try `Channel=3` too.
If the interface you have selected in ASIO4ALL is indeed the right one, one of those should work.

I also notice that you're using an ASIO Buffer size of 512; this is too high and I would NOT recommend anything above 256. Using 512 may result in either too much latency, bad sound, or no sound at all.
