### ISSUE TITLE
Focusrite Solo Buggy Audio

### ISSUE THREAD

**Issue by DaGhost6** [mdias/rs_asio#193]
Just came across this when I wanted to use my new focusrite Scarlett Solo with Rocksmith. Got everything downloaded and the game recognizes it but the audio coming through is very glitchy and distorted. I use the same input for recording so I know it's not my connection. I don't know a lot about this stuff so I figured I'd ask since it would be really nice to play without latency. I put the solo at 48kHZ since I saw that in one of the issues posted. Also should note that I've tried a bunch of different values for the custom buffer and the latencybuffer (1-8). I also play the audio through my pc speakers because the headset I use is wireless so I cant plug it into my interface. Can someone get me some tips?

- Rocksmith.ini

[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=7
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1920
ScreenHeight=1080
Fullscreen=0
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1

- RS_ASIO.ini

[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=192

[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
Change `BufferSizeMode=driver` to `BufferSizeMode=custom`

If it still doesn't work, please post the `RS_ASIO-log.txt` file so we can have a look at what's going on.

**Comment by DaGhost6** [comment]
That actually totally fixed my problems, thanks! My setup is that I really only plug straight into the scarlet. I don't have studio speakers/headphones so I just plug the output into a bass amp when I want to hear. My main pc audio is done on a wireless corsair headset but it's usb so I can't use it with the scarlett itself. Although I'm sure there something you could do with like a raspberry pi but I'm not a huge programmer so I wouldn't where to start.

**Comment by mdias** [comment]
Awesome! Glad I could help :)

> My setup is that I really only plug straight into the scarlet.

If this is the case, you could also use ASIO for output (by filling the `Driver=` line in `[Asio.Output]` and disabling `EnableWasapiOutputs=1`) as that should result in a better experience.

You can also probably reduce `CustomBufferSize=192` to `CustomBufferSize=96` or even `CustomBufferSize=48` if it doesn't crackle, as well as your `LatencyBuffer=` number to reduce your latency.

Just back up your current configs in case you run into issues :)

I'm closing this issue now, but feel free to comment on it and reopen if you have more questions.
