### ISSUE TITLE
Just Checking

### ISSUE THREAD

**Issue by SAARussian** [mdias/rs_asio#195]
Is everything okay here?  In principle, everything is fine, I can hear the game and she told me, but there are a lot of movements in the log ...
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/6619704/RS_ASIO-log.txt)

**Comment by mdias** [comment]
It looks like you're just on the edge of buffer underruns with your buffer size. Increasing it a bit might help.

Either that or the driver/device has an issue similar to the focusrites where the timing of the asio callbacks jitter a bit, but it's more likely that it's just the buffer size and for some reason your system/asio-driver is not not keeping up.

**Comment by SAARussian** [comment]
So I set latencybuffer in game from 1 to 4, and asio buffer from 64 to 512 and it still send me errors
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/6626447/RS_ASIO-log.txt)

**Comment by mdias** [comment]
Do not use a buffer size higher than 256, in my experience that causes issues with the game.

In any case, the buffer underrun messages are gone.

**Comment by SAARussian** [comment]
Before I use 64 samples, and everythink be fine

**Comment by mdias** [comment]
Yes, 64 is also what I usually use without problems.

If this is problem started to happen to you suddenly, check that you don't have any background processes consuming computer resources. Or maybe you changed an installed driver?

**Comment by SAARussian** [comment]
Maybe Windows updates, as usual, spoil everything.

**Comment by SAARussian** [comment]
![image](https://user-images.githubusercontent.com/57723354/121783321-950bd880-cbb6-11eb-8774-a63f8c56211f.png)
maybe I set something wrong here?

**Comment by mdias** [comment]
The config looks fine, altough I personally use `LatencyBuffer=2` just to have some leeway.

**Comment by LukeUkk** [comment]
So im just checking does this mod still work on windows 11 not had much luck

**Comment by mdias** [comment]
@LukeUkk I've seen reports of it working fine. I myself am not using Windows 11 yet.
If it's not working for you, feel free to create an issue for that. But I would start with making sure you install the latest available drivers for your interface, as those may have been erased or misconfigured in case you did an update from Windows 10 to 11.
