### ISSUE TITLE
Zoom H6 works

### ISSUE THREAD

**Issue by kriz2** [mdias/rs_asio#198]
Hi.

I've tested this with my Zoom H6 in multi-channel interface mode and it works well. The only slightly weird thing is that the input numbers on the device doesn't match the ASIO channel numbers. Left is 0 and Right is 1 for attachments, then Input 1 is channel 2, which is the first jack input on the device.

Here is my RS_ASIO.ini file for use with Input 1:
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ZOOM H6 ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ZOOM H6 ASIO
Channel=2
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100


```

Thanks for your work. This patch made Rocksmith much more enjoyable.

**Comment by mdias** [comment]
Thanks for the report, I've added it to the list.

> The only slightly weird thing is that the input numbers on the device doesn't match the ASIO channel numbers. Left is 0 and Right is 1 for attachments, then Input 1 is channel 2, which is the first jack input on the device.

This is actually normal. Usually the interface's software start counting channels at 1, while RS ASIO starts counting them at 0.
So the first channel is zero for RS ASIO, and usually the first channel is the left speaker.
