### ISSUE TITLE
No output device detected with Scarlet solo 3rd gen

### ISSUE THREAD

**Issue by EdJBartholomew** [mdias/rs_asio#199]
[RS_ASIO.zip](https://github.com/mdias/rs_asio/files/6751480/RS_ASIO.zip)

Log and ini attached.

No output device is detected when I try to use asio output drivers. If I enable wasapi, I get no error + audio comes through the interface but there is extreme lag.

**Comment by mdias** [comment]
You are not using Exclusive mode in your Rocksmith.ini file.
Please check the "How to use" section of the [readme file](https://github.com/mdias/rs_asio/blob/master/README.md).
