### ISSUE TITLE
rocksmith hangs when closing with ASIO4ALL and iRig HD2

### ISSUE THREAD

**Issue by giordyb** [mdias/rs_asio#20]
Hi,

I just wanted to report that RS ASIO 0.3.10 works great with ASIO4ALL and an iRig HD2 audio interface, there is only a small issue where Rocksmith.exe hangs when closing (needs to be killed via task manager).

Here is the log and rs_asio.ini just in case...
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4080236/RS_ASIO-log.txt)
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/4080238/RS_ASIO.txt)

**Comment by mdias** [comment]
I found a few issues that could result in not-so-grateful shutdown of the audio system, and I'll investigate those when I have some time, but I can't promise it will make the freeze go away :/

In the meantime I would recommend you play in windowed mode to make it easier to close the game when it hangs on quit.

**Comment by kravask** [comment]
Can confirm the same issue with Yamaha THR II 30.
After quitting the game, getting a white blank screen that cannot be closed be alt+F4 or task manager, the only reboot helps. That's why I'm still using 0.2 ver - works fine for me.

**Comment by ciandial** [comment]
Hangs when using Zoom UAC-2, can't be closed with taskkill, goes away only when manually shutting down audio interface

**Comment by mdias** [comment]
Please check latest release. Hang should be fixed.

**Comment by kravask** [comment]
> Please check latest release. Hang should be fixed.

Checked, still hangs up on exit.

**Comment by mdias** [comment]
Please try [this new preview release](https://github.com/mdias/rs_asio/releases/tag/v0.4.0).

**Comment by ciandial** [comment]
Wow! I'ts a keeper! Works for me and game properly closes.
