### ISSUE TITLE
Katana amp failed to connect

### ISSUE THREAD

**Issue by Hastte** [mdias/rs_asio#202]
Hi !
I'm using a Katana amp and that doesn't work
`[Asio.Input.0]
Driver=KATANA
Channel=2
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100`
and the log:
`AsioHelpers::FindDrivers
5.494 [INFO]    ASIO4ALL v2
5.494 [INFO]    FL Studio ASIO
5.495 [INFO]    KATANA
5.495 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: KATANA
5.495 [INFO]  Creating AsioSharedHost - dll: C:\Windows\SysWOW64\RDAW1179.DLL
5.498 [ERROR]  ASIO Error: Can not found a device. Please connect the device.`

**Comment by Hastte** [comment]
My bad, missclick

**Comment by mdias** [comment]
Your driver is reporting:
`ASIO Error: Can not found a device. Please connect the device.`

Is the interface working in any other ASIO-enabled application?
