### ISSUE TITLE
ASIO4ALL device not connected issue with blackstar amplifier

### ISSUE THREAD

**Issue by SithLord24** [mdias/rs_asio#204]
Although, as I have read from other issues that ASIO4ALL causes issues but I believe that mine issue is somewhat different, I using Blackstar amps USB interface and asio4all to try to connect to the game.
![image](https://user-images.githubusercontent.com/76932371/127838411-e06b7e04-94be-4957-9e3e-caa3a6ee77d5.png)
 This is a screenshot of cakewalk DAW where I can record and monitor sound using the asio4all driver and it works fine.
 
![image](https://user-images.githubusercontent.com/76932371/127838911-30203031-6f3c-462e-b2e6-a25d5388317e.png)
This is what I see in asio4all panel. As you can see my device is named as ID:Core Amplifier and I want to use this device for rocksmith. I followed all steps and copied asio4all v2 in rs_asio.ini file, as follows-

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

So after pasting the asio4all v2 in rs_asio I started the game and in the game I could see realtonecable option active in path menu, but I couldn't hear any sound neither any input sound and I closed the game and went to rs_asio log file and this the content.

0.000 [INFO]   - Wrapper DLL loaded (v0.5.5)
0.000 [INFO]  PatchOriginalCode
0.219 [INFO]  Patching CoCreateInstance
0.219 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.219 [INFO]  Patching call at 01C5AA85
0.219 [INFO]  Patching call at 01F03B6E
0.219 [INFO]  Patching call at 01F5C681
0.219 [INFO]  Patching call at 01FAEF75
0.219 [INFO]  Patching call at 01FAF40D
0.219 [INFO]  Patching PortAudio MarshalStreamComPointers
0.219 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.219 [INFO]  Patching call at 01F03059
0.219 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.219 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.219 [INFO]  Patching call at 01F0310E
0.221 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.221 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.221 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.221 [INFO]  AsioHelpers::FindDrivers
0.222 [INFO]    ASIO4ALL v2
0.222 [INFO]    Realtek ASIO
0.222 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO4ALL v2
0.222 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\ASIO4ALL v2\asio4all.dll
3.791 [INFO]    info: asio4all detected
3.791 [INFO]    ASIO input channels info:
3.791 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Not Connected 1
3.791 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Not Connected 2
3.791 [INFO]    ASIO output channels info:
3.791 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 1
3.791 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 2
3.791 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
3.791 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO4ALL v2
3.791 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
3.791 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
3.791 [INFO]    hr: S_OK
3.791 [INFO]    *ppEndpoint: 1B138E70
3.791 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.791 [INFO]    hr: S_OK
3.791 [INFO]    *ppEndpoint: 1B138EA0
3.791 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.791 [INFO]    hr: S_OK
3.791 [INFO]    *ppDevices: 116D4618
3.791 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.791 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
3.791 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
3.791 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
3.791 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.791 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
3.791 [INFO]    *pDataFlow: eRender
3.791 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
3.791 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.791 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
3.791 [INFO]    *pDataFlow: eCapture
3.791 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
3.791 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
3.798 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
3.798 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.798 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
3.798 [ERROR]    failed to initialize asio driver with requested format
3.798 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
3.798 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.798 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
3.798 [ERROR]    failed to initialize asio driver with requested format
3.798 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
3.798 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.798 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
3.798 [INFO]    Switching sample rate from 44100 to 48000...
3.798 [INFO]   Waiting 5 seconds to give driver time to refresh
8.799 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
8.800 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
8.800 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 5ms (256 frames)
8.800 [INFO]  AsioSharedHost::Setup - startCount: 0
8.800 [INFO]    post output ready: 0
8.800 [INFO]    ASIOBufferSize - min: 64 max: 2048 preferred: 256 granularity: 8
8.800 [INFO]    Creating ASIO buffers (2 out, 2 in)...
8.800 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
8.800 [INFO]    *pNumBufferFrames: 256
8.800 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
8.800 [INFO]    latency: 5ms
8.800 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
8.800 [INFO]    returning render client
8.801 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
8.804 [INFO]  Patched_PortAudio_MarshalStreamComPointers
8.805 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
8.805 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
8.805 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
8.805 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
8.805 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
8.805 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
8.805 [INFO]  AsioSharedHost::Start - startCount: 0
8.805 [INFO]    Starting ASIO stream...
8.810 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
8.810 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
8.811 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
8.811 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
8.817 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
8.817 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
8.817 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
8.817 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
8.822 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
35.060 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
35.060 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
35.060 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
35.060 [ERROR]    no valid channels
35.060 [ERROR]    failed to initialize asio driver with requested format
35.060 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
35.060 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
35.061 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
35.061 [ERROR]    no valid channels
35.061 [ERROR]    failed to initialize asio driver with requested format
35.061 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
35.061 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
35.061 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
35.061 [ERROR]    no valid channels
35.061 [ERROR]    failed to initialize asio driver with requested format
35.061 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
35.061 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
35.061 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
35.061 [ERROR]    no valid channels
35.061 [ERROR]    failed to initialize asio driver with requested format
35.061 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
35.061 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
35.061 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
35.061 [ERROR]    no valid channels
35.061 [ERROR]    failed to initialize asio driver with requested format
35.061 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
35.061 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
35.061 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
35.061 [ERROR]    no valid channels
35.061 [ERROR]    failed to initialize asio driver with requested format
35.061 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
35.061 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
35.061 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
35.061 [ERROR]    no valid channels
35.061 [ERROR]    failed to initialize asio driver with requested format
35.061 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
35.061 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
35.061 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
35.061 [ERROR]    no valid channels
35.061 [ERROR]    failed to initialize asio driver with requested format
35.061 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
102.680 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
102.682 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
102.682 [INFO]  AsioSharedHost::Stop - startCount: 1
102.682 [INFO]  AsioSharedHost::Stop  stopping ASIO stream
102.682 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\ASIO4ALL v2\asio4all.dll
102.682 [INFO]  Restoring previously set sample rate
102.882 [INFO]   - Wrapper DLL unloaded

what I think error is device name is written as not connected 1 and not connected 2 also I may not understand any error messages coming up in the log file. I tried disabling the realtek audio as well but no luck. Changed input channels from 0 to 3 still no input. Though I can record in my DAW with same asio settings without problem and windows sounds and other sounds play on my amp without any problem as well. I am also attaching rocksmith.ini file as well if there is a some issue I am missing.

[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=1
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1280
ScreenHeight=720
Fullscreen=2
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1

I know my setup is not part of supported list you have created but any help will be appreciated.
Thanks : )

**Comment by mdias** [comment]
Your log shows some errors that don't make sense with the config you posted:

> [INFO] WARNING: max requested channel 4 is beyond the max asio channels available 2

I'm guessing this is because of the several things you were trying.

If I remember correctly ASIO4ALL saves it's setting per application, so when you run rocksmith (in windowed mode) you should be able to see ASIO4ALL's icon in your taskbar tray icon bar near the clock. Double click it and make sure the proper input and outs are selected. After that restart the game.

**Comment by SithLord24** [comment]
Yeah, I was thinking of ASIO4ALL global setting of some sort but completely missed it, now after this when I reinstalled asio4all I made sure I checked some 'Off-line Settings' which in application installer said is useless (lol idkw) and when I did it I was finally relieved when rocksmith's intro guitar sound played through my amp and input was also there from my guitar. Now I have few questions-
1. I had latency issues which online suggested that I lower down audio engine value in-game which on lowering causes weird sounds of game and some buzzing so I am skeptical if I should lower the buffer size. What is ideal value? (currently it is 256)
2. Only way to hear sound of game is through the amplifier and I have to attach my headphone to amplifier itself to hear as changing output from asio4all to realtek asio (my pc sound hardware) causes the game to give error of no attached audio device. Though this is not a major problem but it would be nice to use my laptop's headphone jack for that. 

BTW, 
Thank you so much for the help, and I am really thankful that you created RS_ASIO in the first place I am really grateful for that.
Thanks.

**Comment by mdias** [comment]
Some answers to your questions:

1) 256 is fairly low, altough probably still playable. The game asks for 144 by default, but be aware that buffer size doesn't really tell the whole story.
As you've probably read by now, ASIO4ALL is not considered to be a "proper" ASIO driver, and is instead a kind of emulator, which is why it usually doesn't do as good of a job as an actual ASIO driver would; this is probably why you might be unable to reach much lower than that.
Personally I play with 64 buffer size on my MOTU interface, but depending on several things it might be possible to go even lower.

2) You can use your normal output device by leaving the `Driver=` blank on the `[Asio.Output]` section, and setting `EnableWasapiOutputs=1`. This will output to your default audio output on windows, just like it would without RS ASIO while still using ASIO for the input. It should also allow you to get 144 buffer size **\*on the output\*** as that's what the game usually asks for.

3) `SoftwareMasterVolumePercent` on the ini file will allow you to control this, but you can't change it while in game. Altough if you opt to use `EnableWasapiOutputs=1` this problem should go away and you should be able to control your volume with windows volume control normally again.

It is possible that for your case you might be better off using [Direct Connect](https://www.youtube.com/watch?v=H6nAB5ogfeU). I've never used this myself though so I won't be able to help you with it, but I've seen people reporting success with it on [reddit.com/r/rocksmith](url).

**Comment by SithLord24** [comment]
Well, after reading your second answer I was thinking if I were to set Enablewasapiinputs=1 would I be able to use my audio interface without asio4all driver but that didn't work also when when using windows audio there is always some lag which won't go even when buffer size cranked way down to 128 so maybe I'll keep using my amp as audio output and control volume through games own mixer which is not bad though. So I think the problem is resolved and you may close this issue.
**Maybe that adds 'Blackstar ID:Core' to supported device list on the RS_ASIO page : )**

Thanks for your time and help that I am finally able to play game without mic and stuff.
Thanks Again for creating this tool.

**Comment by mdias** [comment]
> Well, after reading your second answer I was thinking if I were to set Enablewasapiinputs=1 would I be able to use my audio interface without asio4all driver but that didn't work

`EnableWasapiInputs` won't allow you to do that. It's there so you can use the RealTone Cable for input while using ASIO for output.

> Maybe that adds 'Blackstar ID:Core' to supported device list on the RS_ASIO page : )

Unfortunately since it's using ASIO4ALL and it seems to be a little bit fidgity I would rather not do that to avoid inducing wrong ideas. In fact I am thinking of removing all ASIO4ALL devices from the list, or maybe list them separately due to how problematic they usually are.
