### ISSUE TITLE
Tascam US2x2 issue

### ISSUE THREAD

**Issue by Padman163** [mdias/rs_asio#205]
Hello,

I want  to play with my Tascam US2x2 Rocksmith 2014. It's not possible :(

Could you please help me to play with Tascam US2x2?

Best regards

Patrick

**Comment by mdias** [comment]
Have you followed the instruction in the [readme file](https://github.com/mdias/rs_asio/blob/master/README.md)? If so, post the contents of your `RS_ASIO-log.txt` file.

**Comment by Padman163** [comment]
Hi

thanks for the reply.

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=256

[Asio.Output]
Driver=US-2x2 & US-4x4 Mixing Driver
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=US-2x2 & US-4x4 Mixing Driver
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100


[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1600
ScreenHeight=1024
Fullscreen=0
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1



![Tascam](https://user-images.githubusercontent.com/88320995/128746839-6f76faf5-8f79-408a-9a3c-0c0ee08e61cb.PNG)
![Settings](https://user-images.githubusercontent.com/88320995/128746846-18202200-0eb1-4bf7-9d39-f347184f8b07.PNG)

**Comment by mdias** [comment]
RS ASIO config looks good, but you should be using RealTone Cable setting inside Rocksmith instead of Microphone.

If that still doesn't work, please post your `RS_ASIO-log.txt` file
