### ISSUE TITLE
Focusrite Scarlett 2i2 3nd gen settings

### ISSUE THREAD

**Issue by amomorning** [mdias/rs_asio#208]
My working settings (guitar in left input):

Rocksmith.ini:
``` ini
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1920
ScreenHeight=1080
Fullscreen=0
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=0
```
RS_ASIO.ini
``` ini
[Config]
EnableWasapi=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

[Asio.Output]
Driver=Focusrite USB ASIO
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
;  if you are using right input
;  Driver=Focusrite USB ASIO
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by mdias** [comment]
Thank you for the report. Linked this issue to the entry I had on the list. 👍

**Comment by throughbeingjulian** [comment]
This worked for my Scarlett 8i6 3rd gen. Thanks!!

**Comment by Wrxmigel** [comment]
I just got a Focusrite 2i2 3rd gen and applied the exact information you gave and I get “No audio output device is detected. Please connect And enable an audio output then restart rocksmith” if I continue with the game, I get no audio from the game at all. But my Focusrite is outputting my guitar sound and any other computer sound, like Spotify, with the game closed. What am I doing wrong ?

**Comment by mdias** [comment]
@Wrxmigel you need to post your settings (Rocksmith.ini and RS_ASIO.ini) and log (RS_ASIO-log.txt) for us to be able to see what's going on.

If it's the same issue as shown in the other issue you posted, you might've forgotten to enable ExclusiveMode.

**Comment by Wrxmigel** [comment]
I deleted the game with all its files and tried it again. it worked. idk what I differently since I did the exact same thing yesterday. 
Thanks!

**Comment by gonzax10** [comment]
Thanks Mate!!! You solved it for me 👍

**Comment by redcx** [comment]
Hey, I have a problem “No audio output device is detected. Please connect And enable an audio output then restart rocksmith”
Rocksmith.ini and RS_ASIO.ini are exactly like the above. 
RS_ASIO-log.txt:

0.000 [INFO]   - Wrapper DLL loaded (v0.7.0)
0.000 [INFO]  PatchOriginalCode
0.038 [INFO]  image crc32: 0xd1b38fcb
0.378 [INFO]  Patching CoCreateInstance
0.378 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.378 [INFO]  Patching call at 00C02DBD
0.378 [INFO]  Patching call at 00E75278
0.378 [INFO]  Patching PortAudio MarshalStreamComPointers
0.378 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.378 [INFO]  Patching call at 00E7483F
0.378 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.378 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.378 [INFO]  Patching call at 00E748F4
0.378 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.378 [INFO]  Patching bytes at 007C0C5F
0.380 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.380 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.380 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.381 [INFO]  GetWineAsioInfo - Looking for wineasio.dll... 
0.382 [INFO]    Failed to load wineasio.dll or file not found
0.382 [INFO]  AsioHelpers::FindDrivers
0.383 [INFO]    Realtek ASIO
0.383 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.383 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.383 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
0.383 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.383 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.383 [INFO]    hr: 80070490
0.383 [INFO]    *ppEndpoint: 00000000
0.383 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.383 [INFO]    hr: 80070490
0.383 [INFO]    *ppEndpoint: 00000000
0.383 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.383 [INFO]    hr: S_OK
0.383 [INFO]    *ppDevices: 1426DC28
1.475 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
1.475 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
1.475 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
1.475 [INFO]  AsioHelpers::FindDrivers
1.475 [INFO]    Realtek ASIO
1.475 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
1.475 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
1.475 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
1.475 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
1.475 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
1.475 [INFO]    hr: 80070490
1.475 [INFO]    *ppEndpoint: 00000000
1.475 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
1.475 [INFO]    hr: 80070490
1.475 [INFO]    *ppEndpoint: 00000000
1.475 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
1.475 [INFO]    hr: S_OK
1.475 [INFO]    *ppDevices: 1426D7A8
1.486 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
3.371 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
3.500 [INFO]   - Wrapper DLL unloaded

I have disabled Realtek (built in sound on motherboard) and still getting the error. 
Any ideas/help?

**Comment by redcx** [comment]
Got it working! Re-Installed the drivers form: https://downloads.focusrite.com/focusrite/scarlett-3rd-gen/scarlett-2i2-3rd-gen
And works like a charm!

**Comment by JS-E** [comment]
> My working settings (guitar in left input):
> 
> Rocksmith.ini:
> 
> ```ini
> [Audio]
> EnableMicrophone=0
> ExclusiveMode=1
> LatencyBuffer=4
> ForceDefaultPlaybackDevice=
> ForceWDM=0
> ForceDirectXSink=0
> DumpAudioLog=0
> MaxOutputBufferSize=0
> RealToneCableOnly=0
> Win32UltraLowLatencyMode=1
> [Renderer.Win32]
> ShowGamepadUI=0
> ScreenWidth=1920
> ScreenHeight=1080
> Fullscreen=0
> VisualQuality=1
> RenderingWidth=0
> RenderingHeight=0
> EnablePostEffects=1
> EnableShadows=1
> EnableHighResScope=1
> EnableDepthOfField=1
> EnablePerPixelLighting=1
> MsaaSamples=4
> DisableBrowser=0
> [Net]
> UseProxy=0
> ```
> 
> RS_ASIO.ini
> 
> ```ini
> [Config]
> EnableWasapi=0
> EnableAsio=1
> 
> [Asio]
> ; available buffer size modes:
> ;    driver - respect buffer size setting set in the driver
> ;    host   - use a buffer size as close as possible as that requested by the host application
> ;    custom - use the buffer size specified in CustomBufferSize field
> BufferSizeMode=custom
> CustomBufferSize=192
> 
> [Asio.Output]
> Driver=Focusrite USB ASIO
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> 
> [Asio.Input.0]
> Driver=Focusrite USB ASIO
> Channel=0
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> 
> [Asio.Input.1]
> ;  if you are using right input
> ;  Driver=Focusrite USB ASIO
> Driver=
> Channel=1
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> ```

Can confirm this works beautifully for my new Scarlett, thanks for sharing - Was a tad worried Rocksmith wouldn't work anymore

**Comment by Vid0kas** [comment]
is it possible to use it with RTC?
because for 3 hours I tried to play it with RTC without realising that I MUST connect guitar to audio interface... lol

**Comment by mdias** [comment]
Yes, it's possible. Use `EnableWasapiInputs=1` in `[Config]`.

**Comment by snakecase** [comment]
In case someone encounters an issue of RS ASIO not working with the latest Focsurite driver: https://github.com/mdias/rs_asio/issues/425#issuecomment-2561318145

**Comment by sebastiano1299** [comment]
@mdias

**Comment by mdias** [comment]
@sebastiano1299 without any log I can only guess that your guitar isn't connected to the channel you specify int he config.
Also, did you try if any other software can listen to the guitar signal?

**Comment by sebastiano1299** [comment]
how can i get the log for you? and no i haven’t but ill try it on fl studio

**Comment by sebastiano1299** [comment]
@mdias

**Comment by mdias** [comment]
Please stop replying with just my username, that just creates spam.

As the readme instructions state, there's a `RS_ASIO-log.txt` file that is generated inside the game folder, next to the config file.

**Comment by sebastiano1299** [comment]
heres the log

0.000 [INFO]   - Wrapper DLL loaded (v0.7.4)
0.000 [INFO]  PatchOriginalCode
0.029 [INFO]  image crc32: 0xd1b38fcb
0.312 [INFO]  Patching CoCreateInstance
0.312 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.312 [INFO]  Patching call at 00C02DBD
0.312 [INFO]  Patching call at 00E75278
0.312 [INFO]  Patching PortAudio MarshalStreamComPointers
0.312 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.312 [INFO]  Patching call at 00E7483F
0.312 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.312 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.312 [INFO]  Patching call at 00E748F4
0.312 [INFO]  Patching Two Guitar Tones Connected Message Box (starting menu) (num locations: 1)
0.312 [INFO]  Patching bytes at 007C0C66
0.312 [INFO]  Patching Two Guitar Tones Connected Message Box (main menu) (num locations: 1)
0.312 [INFO]  Patching bytes at 007C0CDA
0.312 [INFO]  Patching unknown crash when certain audio devices are found (num locations: 1)
0.312 [INFO]  Patching bytes at 00E7CF70
0.314 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.318 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.318 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.318 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.
0.320 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.
0.321 [INFO]  AsioHelpers::FindDrivers
0.321 [INFO]    ASIO4ALL v2
0.321 [INFO]    FL Studio ASIO
0.321 [INFO]    Focusrite Thunderbolt ASIO
0.321 [INFO]    Focusrite USB ASIO
0.321 [INFO]    KATANA
0.321 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.321 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusrite\drivers\focusriteusbasio32.dll
0.326 [INFO]    ASIO input channels info:
0.326 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
0.326 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
0.326 [INFO]    ASIO output channels info:
0.326 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
0.326 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
0.326 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.326 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
0.326 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.326 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.326 [INFO]    hr: S_OK
0.326 [INFO]    *ppEndpoint: 149375B8
0.326 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.326 [INFO]    hr: S_OK
0.326 [INFO]    *ppEndpoint: 14937D38
0.326 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.326 [INFO]    hr: S_OK
0.326 [INFO]    *ppDevices: 1465E570
0.326 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.326 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.326 [INFO]    *cProps: 2
0.326 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.326 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.326 [INFO]    *pDataFlow: eRender
0.326 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.326 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.326 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.326 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.326 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.326 [INFO]    *cProps: 5
0.326 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.326 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.326 [INFO]    *pDataFlow: eCapture
0.326 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.326 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.326 [INFO]  {ASIO IN 0} RSAsioAudioClient::~RSAsioAudioClient
0.339 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.339 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.339 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.339 [INFO]    requested format is not supported
0.339 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.339 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.339 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.339 [INFO]    requested format is not supported
0.339 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.339 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.339 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.339 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
0.339 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
0.339 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 4ms (192 frames)
0.339 [INFO]  AsioSharedHost::Setup - startCount: 0
0.339 [INFO]    post output ready: 0
0.339 [INFO]    ASIOBufferSize - min: 16 max: 1024 preferred: 192 granularity: 16
0.339 [INFO]    Creating ASIO buffers (2 out, 2 in)...
0.339 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
0.339 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 2 value: 0 | returning: 1
0.339 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 3 | returning: 0
0.339 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 5 | returning: 0
0.339 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 4 | returning: 0
0.339 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 6 | returning: 0
0.339 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 15 | returning: 0
0.339 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.339 [INFO]    *pNumBufferFrames: 192
0.339 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.339 [INFO]    latency: 10ms
0.339 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.339 [INFO]    returning render client
0.340 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.341 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.341 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.341 [INFO]  {ASIO Out} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.341 [INFO]  {ASIO Out} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.341 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.341 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.341 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.341 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.341 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.341 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.341 [INFO]  AsioSharedHost::Start - enter startCount: 0
0.341 [INFO]    Starting ASIO stream...
0.394 [INFO]  AsioSharedHost::Start - leave startCount: 1
0.400 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.400 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.400 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.400 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.404 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.404 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.404 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.404 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.408 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
26.526 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.526 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.526 [INFO]    requested format is not supported
26.526 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.526 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.526 [INFO]    requested format is not supported
26.526 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.526 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.526 [INFO]    requested format is not supported
26.526 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
26.526 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
26.526 [INFO]  {ASIO IN 0} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
26.526 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - actual buffer duration: 4ms (192 frames)
26.526 [INFO]  AsioSharedHost::Setup - startCount: 1
26.526 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioEndpointVolume dwClsCtx: 1
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
26.526 [INFO]    *pNumBufferFrames: 192
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
26.526 [INFO]    latency: 8ms
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioCaptureClient
26.526 [INFO]    returning capture client
26.526 [INFO]  Patched_PortAudio_MarshalStreamComPointers
26.526 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
26.526 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Start
26.526 [INFO]  AsioSharedHost::Start - enter startCount: 1
26.526 [INFO]  AsioSharedHost::Start - leave startCount: 2
26.527 [INFO]  {ASIO IN 0} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.17
26.528 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.528 [INFO]  {ASIO IN 0} RSAsioAudioClient::SwapBuffers
26.528 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 192
26.532 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.532 [INFO]  {ASIO IN 0} RSAsioAudioClient::SwapBuffers
26.532 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 192
26.536 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.536 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 192
98.907 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
98.907 [INFO]  AsioSharedHost::Stop - enter startCount: 2
98.907 [INFO]  AsioSharedHost::Stop - leave startCount: 1
98.907 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
101.925 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Stop
101.925 [INFO]  AsioSharedHost::Stop - enter startCount: 1
101.925 [INFO]  AsioSharedHost::Stop - stopping ASIO stream
101.925 [INFO]  AsioSharedHost::Stop - leave startCount: 0
101.925 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
102.083 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
Log looks fine and shows audio is streaming on the input device.
Is the input mode in your game options set to use the RTC?

**Comment by mdias** [comment]
@Colbcuh your ASIO drivers are not streaming audio either for input or output.
Not sure what you mean about everything picking up the guitar except rocksmith, could it be that you have other applications using the interface at the same time you're playing the game?

**Comment by greatgansby** [comment]
I am also getting the “No audio output device is detected. Please connect And enable an audio output then restart rocksmith”

0.000 [INFO]   - Wrapper DLL loaded (v0.7.4)
0.000 [INFO]  PatchOriginalCode
0.037 [INFO]  image crc32: 0xd1b38fcb
0.397 [INFO]  Patching CoCreateInstance
0.397 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.397 [INFO]  Patching call at 00C02DBD
0.397 [INFO]  Patching call at 00E75278
0.397 [INFO]  Patching PortAudio MarshalStreamComPointers
0.397 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.397 [INFO]  Patching call at 00E7483F
0.397 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.397 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.397 [INFO]  Patching call at 00E748F4
0.397 [INFO]  Patching Two Guitar Tones Connected Message Box (starting menu) (num locations: 1)
0.397 [INFO]  Patching bytes at 007C0C66
0.397 [INFO]  Patching Two Guitar Tones Connected Message Box (main menu) (num locations: 1)
0.397 [INFO]  Patching bytes at 007C0CDA
0.397 [INFO]  Patching unknown crash when certain audio devices are found (num locations: 1)
0.397 [INFO]  Patching bytes at 00E7CF70
0.398 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.398 [INFO]  failed to open config file
0.398 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.398 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.398 [INFO]    hr: 80070490
0.399 [INFO]    *ppEndpoint: 00000000
0.399 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.399 [INFO]    hr: 80070490
0.399 [INFO]    *ppEndpoint: 00000000
0.399 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.399 [INFO]    hr: S_OK
0.399 [INFO]    *ppDevices: 13A93378
3.978 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
3.978 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
3.978 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
3.978 [INFO]    hr: 80070490
3.978 [INFO]    *ppEndpoint: 00000000
3.978 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.978 [INFO]    hr: 80070490
3.978 [INFO]    *ppEndpoint: 00000000
3.978 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.978 [INFO]    hr: S_OK
3.978 [INFO]    *ppDevices: 13A934B8
3.984 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
5.726 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
5.846 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
@greatgansby You don't seem to have RS ASIO properly installed.

```
0.398 [INFO] failed to open config file
```

Are you missing the `RS_ASIO.ini`?

**Comment by greatgansby** [comment]
I believe I have the RS_ASIO file in the Rocksmith 2014 folder from the latest release. 

Here are the steps I performed:

1. Click on latest release
2. Copy three files from Zip into the Rocksmith 2014 folder
    a. I see a config file in the Zip contents but it does not have the .ini extension naming convention, instead it is named RS_ASIO
3. Copy and paste the Rocksmith.ini config details mentioned above into Rocksmith 2014 config file
4. Copy and paste the RS_ASIO config details mentioned above into the RS.ASIO config file

**Comment by mdias** [comment]
Your explorer settings might just be hiding the extension, but it should be an ini file.
However, please check file permissions, or even if you have some uncommon antivirus denying access to the config file. RS_ASIO needs to be able to read the config file to proceed as normal.
