### ISSUE TITLE
44.1kHz sample rate support

### ISSUE THREAD

**Issue by deadcombo** [mdias/rs_asio#21]
Hello, I'm the guy with the Fender Mustang from the [reddit thread](https://old.reddit.com/r/rocksmith/comments/czs4gr/rocksmith_working_through_asio/ezvtiz0/) that couldn't get the game going. I tried out the latest 0.3.10 release, and by some miracle, it's launching fine!

Anyway, the reason for this issue is that, although your program is working excellently, my little Mustang only outputs ASIO at 44.1k 16bit. The logs accurately represent this:
```
27.290 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
27.290 [ERROR]    unsupported sample rate: 48000
27.290 [ERROR]    failed to initialize asio driver with requested format
27.290 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
```

Which is breaking my heart. Do you think it's possible to overcome this, or is it back to Voicemeeter for me?

**Comment by mdias** [comment]
Hello, unfortunately I can't support anything other than 48kHz as that would require resampling support for all the audio output formats supported, and not only would that be a huge amount of work, it could also affect the latency and audio quality which would defeat the purpose.

If you do use voicemeeter however, make sure you use it's ASIO virtual driver, as that should allow you to achieve low latency and it allows you to select the sample rate you wish to use on the virtual ASIO implementation it supports, effectively doing the resampling you're asking for. Then it's just a matter of configuring RS-ASIO to use that ASIO implementation instead.

**Comment by deadcombo** [comment]
Yeah, I figured resampling was a long shot.

Driving Voicemeeter ASIO into your patch though, that's genius. I've been trying to set it up, but I've had no luck. If I understood the manual correctly, then Voicemeeter doesn't actually convert ASIO samplerate:

> Note: Output A1 device configuration gives the main audio configuration of Voicemeeter and the configuration of Voicemeeter virtual ASIO driver (Sample rate and buffer size). It also means that all audio processing done in Voicemeeter will be based on this sample rate  (if  some  audio  points  work  in  another  sample  rate,  conversion  will  be  done  automatically to this main sample rate.).
> 
> Preferred Main Sample Rate can be used as a wish to make Voicemeeter run output device A1 in the wanted sample rate (44.1, 48, 88.2, 96, 176.4 kHz or 192 kHz). But it also depends on the audio device current configuration (that could stay in its own sample rate anyway).

I'm really wishing I'm retarded and not getting something here, but it really seems like Voicemeeter doesn't do sample rate conversion. At best it tries to "ask" the ASIO driver for the set Preferred Sample Rate, but if actually force it, I get no ASIO input and the A1 bus goes flashing red.

Sucks. Ditching the no-cable launcher for your solution would be a lot neater.

**Comment by mdias** [comment]
Indeed you seem to be right.
I just tested it to make sure, by switching my interface to 44.1 and trying to go through voicemeeter, but it errors out when RS-ASIO asks it for 48kHz :/

**Comment by deadcombo** [comment]
Meh, I'm content. Thanks to this experiment I've tweaked my setup so that I _surprisingly_ don't notice any latency. Thank you for all your efforts, mdias. Great stuff you have here.

If any other Mustang owner stumbles over here, what you want is to grab the Fender Universal ASIO from Fender's website, Voicemeeter, and the no-cable patch. Set the Fender ASIO as input A1 in Voicemeeter, patch ASIO input to strips 1 & 2 in Voicemeeter system settings, and direct Hardware Input 1 (the ASIO input you just patched) to bus B, which is Voicemeeter VAIO output.

In the Windows Sound control panel, under recording devices, set the Voicemeeter VAIO output  to 1 channel, 16-bit 48kHz.

Point the no-cable to Voicemeeter VAIO output, adjust gamesettings to taste, and voilá. It works.

I have to disable UltraLowLatencyMode in my INI file for it to sound right (if I don't the signal sounds pitch shifted an octave up), but I'm not sure it's due to this workaround. Keep that in mind.

mdias, if you have nothing else to add, feel free to close this issue. Thank you.

**Comment by mdias** [comment]
It's indeed surprising that you managed to make it work fine with UltraLowLatencyMode disabled, but hey, what matters is that you have a working setup!

I'm closing the issue as I **currently** don't have plans to support resampling, but it's something I'll keep in mind.
