### ISSUE TITLE
Yamaha THR10II Confirmed Working!

### ISSUE THREAD

**Issue by Bananovnik** [mdias/rs_asio#210]
I recently get Yamaha THR10II and can confrim it works like a charm with rs_asio. I got to work with latencyBuffer set to 2, but 3 or 4 works as well. I guess other Yamaha THR models like THR10IIW and THR30IIW will work without problems, because they are basically the same. Only [Yamaha Asio driver](https://uk.yamaha.com/en/products/musical_instruments/guitars_basses/amps_accessories/thr-ii/downloads.html#product-tabs) from their website is needed.

Rocksmith.ini:

```
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=0
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
```

RS_ASIO.ini:

```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO THRII
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO THRII
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by mdias** [comment]
For some reason it seems I missed this post, sorry about that.

And thank you for the report, added to the list! 👍

**Comment by ise73** [comment]
I've THR30IIW and it works without problems.

**Comment by mdias** [comment]
Also added 👍

**Comment by rvighne** [comment]
Some notes on tuning:

The Yamaha ASIO driver appears as a stereo device and puts the "wet" signal (with the amp simulator and all the physical knobs on the amp applied) as channel 0 (left) and the "dry" signal (the direct signal digitized from the guitar) as channel 1 (right). Since Rocksmith is itself an amp simulator you probably want to configure only the `[Asio.Input.1]` section i.e. the one with `Channel=1`.

The dry signal is a lot quieter, so Rocksmith may complain that your guitar is too quiet and not let you calibrate properly. Easy to fix, just set `SoftwareMasterVolumePercent=200` which adds some gain.

I found that
```
[Asio]
BufferSizeMode=custom
CustomBufferSize=128
```
allowed me to set `LatencyBuffer=1` thus achieving the lowest possible latency (not quite as snappy as playing directly from the amp though). `CustomBufferSize=96` brought the crackling back, so that's too low.

**Comment by LEC544** [comment]
hello,i have bought YAMAHA THR30WL and installed driver .But it didn't work.I guess that's because the driver isn't 32bit.I don't know how to find this driver in the official website

**Comment by zhaohm14** [comment]
> hello,i have bought YAMAHA THR30WL and installed driver .But it didn't work.I guess that's because the driver isn't 32bit.I don't know how to find this driver in the official website

https://github.com/mdias/rs_asio/issues/484#issue-2761700558

Hi! I am facing with the same issue. Sadly I can't also find an old version of this driver. Does anyone have a backup of its 32bit version?

**Comment by zhaohm14** [comment]
Hi! I located the 32-bit Yamaha ASIO driver here:
<https://usa.yamaha.com/files/download/software/7/1382387/Yamaha_Driver_THRII_v1.0.0.0_Installer.exe.zip>
But 32bit driver doesn't work fine on win11 which requires to turn off memory integrity check.
The better way is to use voicemeeter with the 64bit version driver. It works fine to me now.

**Comment by Blamad** [comment]
In case anyone has issues with game crashing out and amp making vicous noises during that I found that disabling `Asio.Input.0` makes everything run smoothly. I just commented entire `Asio.Input.0` section out and had fun for couple of hours without a single crash.
