### ISSUE TITLE
Mackie Onyx Producer 2x2 confirmed working

### ISSUE THREAD

**Issue by tucznak** [mdias/rs_asio#211]
Got this interface after finding it on the list of reported to work, but it doesn't work without adjusting configuration. Obviously, [ASIO driver](https://mackie.com/products/onyx-usb-audio-interfaces) from the bottom of their web is required. Since it's the same one for both Producer 2x2 and Artist 1x2, I assume that one will work as well.

Rocksmith.ini:
```
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
```
RS_ASIO.ini:  
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=128

[Asio.Output]
Driver=Mackie ASIO Driver
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Mackie ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```
I plug into physical input 2, for input 1 (Producer only) you will need to change to `Channel=0`

**Comment by mdias** [comment]
Thanks! Added a link to the entry on the list.

> Since it's the same one for both Producer 2x2 and Artist 1x2, I assume that one will work as well.

That is very likely, but I'll only add actual hardware that people report to be working.

Thanks again,

**Comment by Martin-Kriegor** [comment]
> Thanks! Added a link to the entry on the list.
> 
> > Since it's the same one for both Producer 2x2 and Artist 1x2, I assume that one will work as well.
> 
> That is very likely, but I'll only add actual hardware that people report to be working.
> 
> Thanks again,

Just tried this same config on my artist 1x2, works like a charm.
