### ISSUE TITLE
No option to donate the perfect solution to the eternal Rocksmith problem

### ISSUE THREAD

**Issue by statyan** [mdias/rs_asio#213]
I have spent hours trying to reach adequate latency and an aproptiate sound with Rocksmith. And when the first goal was more or less achieved, there were still a bunch of sound glitches after all Rocksmith applied effects to the output sound. 
And all of that appeared so easy to achieve with your library. I'm so grateful for it, please put a link to any donation platform so people like me could express our appreciation. Thank you!

**Comment by mdias** [comment]
Thank you for the kind words :)

These "issue" reports make me happier than a donation would. But I'm adding a donation link to the readme as this is not the first request for it.

Cheers
