### ISSUE TITLE
No devices shown in RS_ASIO-log

### ISSUE THREAD

**Issue by chadlyalan** [mdias/rs_asio#215]
After following the installation instructions of the 3 files that go in the launch folder and launching Rocksmith, the RS_ASIO-log seems to show that it found 0 render devices and  0 capture devices. 
I have headphones plugged in that allow me to hear Rocksmith when launching without those 3 files, but I hear nothing now obviously.
The USB Audio device shows up in my device manager, and recording devices. It's the only enabled recording device at the moment. Here is the log:

0.000 [INFO]   - Wrapper DLL loaded (v0.5.5)
0.000 [INFO]  PatchOriginalCode
0.514 [INFO]  Patching CoCreateInstance
0.515 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.515 [INFO]  Patching call at 01C5AA85
0.515 [INFO]  Patching call at 01F03B6E
0.515 [INFO]  Patching call at 01F5C681
0.515 [INFO]  Patching call at 01FAEF75
0.515 [INFO]  Patching call at 01FAF40D
0.515 [INFO]  Patching PortAudio MarshalStreamComPointers
0.515 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.515 [INFO]  Patching call at 01F03059
0.515 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.515 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.515 [INFO]  Patching call at 01F0310E
0.517 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.517 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.517 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.517 [INFO]  AsioHelpers::FindDrivers
0.517 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.517 [INFO]    hr: 80070490
0.517 [INFO]    *ppEndpoint: 00000000
0.517 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.517 [INFO]    hr: 80070490
0.517 [INFO]    *ppEndpoint: 00000000
0.517 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.517 [INFO]    hr: S_OK
0.517 [INFO]    *ppDevices: 16853340
4.142 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
4.142 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
4.142 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
4.142 [INFO]  AsioHelpers::FindDrivers
4.142 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
4.142 [INFO]    hr: 80070490
4.142 [INFO]    *ppEndpoint: 00000000
4.142 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
4.142 [INFO]    hr: 80070490
4.142 [INFO]    *ppEndpoint: 00000000
4.142 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
4.142 [INFO]    hr: S_OK
4.142 [INFO]    *ppDevices: 0DF3F9F8
4.150 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback

I've had this game for a while now and still never been able to play it. 
I have a J&D usb guitar cable. Thanks!

**Comment by mdias** [comment]
Does your USB cable have ASIO drivers? You need those for this to work.

**Comment by chadlyalan** [comment]
Oh I had no idea. I'll look around to see if i can find an asio driver that works for my cable. Thanks!

**Comment by mdias** [comment]
If your interface's website does not provide one, it likely doesn't have one.
You might find workarounds such as ASIO4ALL, but that tends to have issues with RS ASIO. At that point you're better served by [Direct Connect](https://www.youtube.com/watch?v=H6nAB5ogfeU) mode.

**Comment by chadlyalan** [comment]
I actually got asio4all to work for the guitar input into the game but now i have to figure out how to continue to get output to the right device since asio4all acts as a singular i/o.
