### ISSUE TITLE
PositiveGrid Spark 40 Works!

### ISSUE THREAD

**Issue by atagmester** [mdias/rs_asio#218]
It works without any issues with "PositiveGrid UsbAudio Driver" and ASIO4ALL as well. 

Rocksmith.ini:
```
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=0
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
```

RS_ASIO.ini:
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Positive Grid USB Audio Device
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Positive Grid USB Audio Device
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by kitsun8** [comment]
Can confirm, Another Spark 40 user here.

**Comment by mdias** [comment]
Thank you for the report! Added to the list 👍

**Comment by DreadKnight** [comment]
Would be interesting to find out if Spark Mini or GO work as well. I have a Mini, will give it a try soon, but I'm also considering purchasing a GO in the near future, so if someone can test that out as well, it would be really neat :3

**Comment by notdeadpool456** [comment]
Question, my amp seems to only allow 44.1kHz is this a problem? I can't seem to find a way to get it to 48kHz which is what I've heard is needed.

**Comment by mdias** [comment]
@notdeadpool456 yes, that is a problem.
The game requests 48kHz and RS ASIO does not convert sample rates.

**Comment by notdeadpool456** [comment]
Alright I think it might be good to add a note because positiveGrid seems to have made a "worse" batch of spark 40s for 2023, maybe 2024 since I recently bought mine in may, these seem to only support 44.1kHz.

**Comment by mdias** [comment]
Thank you for bringing this up to my attention. I've added a note to this interface entry.

However, I encourage you to try to find out if there is an archive with older driver versions as it's far more likely that this is a new driver issue/limitation rather than a new hardware revision with limited sample rate support (although that's not impossible).

Perhaps emailing PositiveGrid support could be a good idea after you ensure that the same issue is present in other ASIO-enabled applications.

**Comment by Papaco10** [comment]
> Question, my amp seems to only allow 44.1kHz is this a problem? I can't seem to find a way to get it to 48kHz which is what I've heard is needed.

RS Tools can do the trick, or almost.
It allows the game use 44.1kHz.
Unfortunately you can use only as output(last time I checked was 2 months ago).
But it still WIP.
