### ISSUE TITLE
AG06 just messing me abt

### ISSUE THREAD

**Issue by Tehlicn** [mdias/rs_asio#222]
i don't have the best pc,, but this just isn't working for me at all.

I disabled the main audio driver output through the playback menu and rocksmith kept using it so I've disabled the dame driver through the Device Menu and idek what's going on with it all.

I did just upgrade from an oldddd tascam US122 which worked perfectly despite its age, so im hoping this should be possible on me pc.

also how do ppl post the ini files properly here

> [Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=1
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=1
MaxOutputBufferSize=512
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1360
ScreenHeight=768
Fullscreen=2
VisualQuality=3
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=1
[Net]
UseProxy=0

> [Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1
[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=512
[Asio.Output]
Driver=Yamaha Steinberg USB ASIO
BaseChannel=0
AltBaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
[Asio.Input.1]
Driver=Yamaha Steinberg USB ASIO
Channel=2
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
[Asio.Input.Mic]
Driver=Yamaha Steinberg USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

>0.000 [INFO]   - Wrapper DLL loaded (v0.5.5)
0.000 [INFO]  PatchOriginalCode
0.714 [INFO]  Patching CoCreateInstance
0.714 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.714 [INFO]  Patching call at 01C5AA85
0.714 [INFO]  Patching call at 01F03B6E
0.714 [INFO]  Patching call at 01F5C681
0.714 [INFO]  Patching call at 01FAEF75
0.714 [INFO]  Patching call at 01FAF40D
0.714 [INFO]  Patching PortAudio MarshalStreamComPointers
0.715 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.715 [INFO]  Patching call at 01F03059
0.715 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.715 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.715 [INFO]  Patching call at 01F0310E
0.720 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.721 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.721 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.721 [INFO]  AsioHelpers::FindDrivers
0.722 [INFO]    Asio US-122 (16)
0.723 [INFO]    Asio US-122 (24)
0.723 [INFO]    ASIO4ALL v2
0.723 [INFO]    Voicemeeter AUX Virtual ASIO
0.724 [INFO]    Voicemeeter Insert Virtual ASIO
0.724 [INFO]    Voicemeeter Virtual ASIO
0.724 [INFO]    Yamaha Steinberg USB ASIO
0.724 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Yamaha Steinberg USB ASIO
0.724 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.744 [ERROR]  ASIO Error: Device could not be opened.
0.744 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.744 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.744 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Yamaha Steinberg USB ASIO
0.745 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.764 [ERROR]  ASIO Error: Device could not be opened.
0.764 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.765 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.765 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[2] requesting ASIO driver: Yamaha Steinberg USB ASIO
0.765 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.784 [ERROR]  ASIO Error: Device could not be opened.
0.784 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.784 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.796 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 15 render devices, 0 capture devices
0.796 [INFO]    hr: S_OK
0.796 [INFO]    *ppEndpoint: 05239F48
0.796 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.796 [INFO]    hr: 80070490
0.796 [INFO]    *ppEndpoint: 00000000
0.796 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.797 [INFO]    hr: S_OK
0.797 [INFO]    *ppDevices: 05238DE8
0.797 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.801 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevicePropertyStore::GetCount
0.802 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.802 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.803 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.803 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.803 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
0.804 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.804 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperEndpoint::GetDataFlow
0.804 [INFO]    *pDataFlow: eRender
0.804 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.807 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.826 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.827 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.830 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.831 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.831 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.831 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.831 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.831 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.832 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.832 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.833 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.833 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Shared Flags: 0 bufferDuration: 10ms periodicity: 0ms
0.874 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.874 [INFO]    *pNumBufferFrames: 1056
0.874 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.874 [INFO]    latency: 0ms
0.874 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.875 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.878 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.879 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.879 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 128
0.879 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 128
0.879 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.882 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 128
0.882 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 128
0.883 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 128
0.883 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 128
31.016 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
31.018 [INFO]  {0.0.0.00000000}.{4bf94643-2cde-4d44-a35b-ad7226dbb434} DebugWrapperAudioClient<struct IAudioClient3>::Stop
31.362 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
There's an important error on the log:

> 0.784 [ERROR] ASIO Error: Device could not be opened.

Also `CustomBufferSize=512` is going to be too high, altough this is not the problem right now.

Have you tried this `Yamaha Steinberg USB ASIO` with other software that uses ASIO?
