### ISSUE TITLE
Trying to use M-audio Fast Track Pro

### ISSUE THREAD

**Issue by Th3BiSh0p** [mdias/rs_asio#225]
Hello,

thank you for your patch.
I'm trying to use my M-audio Fast Track Pro, I can hear the game, no problem, but I can't figure out what to do to configure my input. My device seems to send constant signal to the game.

rocksmith.ini
https://pastebin.com/J0rD1yek

RS_AUDIO.ini
https://pastebin.com/EMqsf6MT

RS_AUDIO-log.txt
https://pastebin.com/dPYvNTHP

**Comment by theSG** [comment]
Remove driver name from

[Asio.Input.Mic]
Driver=

in RS_ASIO.ini

Or change Channel to1 if you actually trying to also use a microphone

**Comment by Th3BiSh0p** [comment]
Alright, it's working almost fine. But the tempo of the songs is slower and the sound is one tone lower from the usual...
I think it's related to my specific device and/or driver, so we can probably assume that it's working fine with M-Audio Fast Track Pro

**Comment by mdias** [comment]
Are you running at 48000?
Please post the contents of `RS_ASIO-log.txt` from after a run where you experienced that issue.

**Comment by Th3BiSh0p** [comment]
I guess so, yes.

https://pastebin.com/6UBXR2Cs

It seems to happen randomly... But as I said I don't think it has anything to do with RS ASIO since I had a similar issue in my DAW too

**Comment by mdias** [comment]
The log looks fine, but unfortunately I haven't added anything in RS ASIO to monitor sample rate consistency so it's hard to tell if that's the problem.

But according to your description of the issue it does indeed seem like your interface's clock is fluctuating enough that you can hear it. That can either be a hardware malfunction or driver issue like you said.

Just curious, when  you say it happens randomly, do you mean that it tempo can change while you're just playing the game? or does it sometimes start shifted and remains like that through the play session?

I'll add the device to the list with a note.

Thank you for the report

**Comment by Th3BiSh0p** [comment]
No, usually, I start the game once, the tempo and the tone is lower, I quit the game and launch it again, and it's working fine, for the whole game session.

**Comment by mdias** [comment]
Very strange. The only thing I can suggest is to try a buffer size bigger than 64; maybe 96 or 128, but I'm not sure that will help with anything.
At least you can achieve a good rate by just restarting the game :)

**Comment by Th3BiSh0p** [comment]
The default buffer size was 512, so I started to play like this. Now it's 64 and I can't say I see any noticeable difference.
For the record, when I first switched to W10, I couldn't install the device driver, so I've put it away for some time. Later I tried again, I could install properly the driver, but I had this strange tone issue (I never noticed anything like this on W7).

Yes, now I know the only thing I have to do is to start again my game/DAW, it's no big deal, really.

Thanks for your help.

**Comment by Th3BiSh0p** [comment]
update : this morning, my game never stopped playing the "lowered tone", no matter how many times I start and stop the game. So I guess my device is just at the end of its lifespan or something.
I will switch to M-Audio M-Track Solo

Thank you for your time

**Comment by mdias** [comment]
Ah, that sucks!
Hope you enjoy the new interface and get a good experience out of it :)

**Comment by MarkusOliver** [comment]
Hello Good Afternoon everyone
I'm trying to configure my Fast Track Pro Asio
As another person described above, I can hear the game's sound but I cannot configure the audio input or enable the microphone. I've tried all the possibilities here and nothing.

Has anyone found a way to make it work?

**Comment by MarkusOliver** [comment]
0.000 [INFO]   - Wrapper DLL loaded (v0.7.0)
0.000 [INFO]  PatchOriginalCode
0.030 [INFO]  image crc32: 0xd1b38fcb
0.181 [INFO]  Patching CoCreateInstance
0.181 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.181 [INFO]  Patching call at 00C02DBD
0.181 [INFO]  Patching call at 00E75278
0.181 [INFO]  Patching PortAudio MarshalStreamComPointers
0.181 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.181 [INFO]  Patching call at 00E7483F
0.181 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.181 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.181 [INFO]  Patching call at 00E748F4
0.181 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.181 [INFO]  Patching bytes at 007C0C5F
0.197 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.197 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.197 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.197 [INFO]  GetWineAsioInfo - Looking for wineasio.dll... 
0.197 [INFO]    Failed to load wineasio.dll or file not found
0.197 [INFO]  AsioHelpers::FindDrivers
0.198 [INFO]    Ableton Push
0.198 [INFO]    Fast Track Pro ASIO
0.198 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Fast Track Pro ASIO
0.198 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\M-Audio\Fast Track Pro\MAudioFastTrackPro_Asio.dll
0.345 [INFO]    ASIO input channels info:
0.345 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: In 1
0.345 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: In 2
0.345 [INFO]    ASIO output channels info:
0.345 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Out 1
0.345 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Out 2
0.345 [INFO]      2 - active: 0, channel: 2, group: 1, isInput: 0, type: ASIOSTInt32LSB, name: S/PDIF Out Left
0.345 [INFO]      3 - active: 0, channel: 3, group: 1, isInput: 0, type: ASIOSTInt32LSB, name: S/PDIF Out Right
0.345 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.345 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Fast Track Pro ASIO
0.345 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.345 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.345 [INFO]    hr: S_OK
0.345 [INFO]    *ppEndpoint: 17EE79F8
0.345 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.345 [INFO]    hr: S_OK
0.345 [INFO]    *ppEndpoint: 17EE7AE8
0.345 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.345 [INFO]    hr: S_OK
0.345 [INFO]    *ppDevices: 105E6480
0.345 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.345 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.345 [INFO]    *cProps: 2
0.345 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.345 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.345 [INFO]    *pDataFlow: eRender
0.345 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.345 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.345 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.345 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.345 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.345 [INFO]    *cProps: 5
0.345 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.345 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.345 [INFO]    *pDataFlow: eCapture
0.345 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.345 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.345 [INFO]  {ASIO IN 0} RSAsioAudioClient::~RSAsioAudioClient
0.354 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.354 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.354 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.354 [INFO]    requested format is not supported
0.354 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.354 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.354 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.354 [INFO]    requested format is not supported
0.354 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.354 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.354 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.354 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
0.354 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
0.354 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 3ms (160 frames)
0.354 [INFO]  AsioSharedHost::Setup - startCount: 0
0.354 [INFO]    post output ready: 1
0.354 [INFO]    ASIOBufferSize - min: 64 max: 4096 preferred: 128 granularity: 32
0.354 [INFO]    Creating ASIO buffers (4 out, 2 in)...
0.354 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
0.354 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.354 [INFO]    *pNumBufferFrames: 160
0.354 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.354 [INFO]    latency: 5ms
0.354 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.354 [INFO]    returning render client
0.355 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.355 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.355 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.355 [INFO]  {ASIO Out} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.355 [INFO]  {ASIO Out} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.355 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.355 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.355 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 160
0.355 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 160
0.355 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.355 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.355 [INFO]  AsioSharedHost::Start - enter startCount: 0
0.355 [INFO]    Starting ASIO stream...
0.356 [INFO]  AsioSharedHost::Start - leave startCount: 1
0.404 [INFO]  Fast Track Pro ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.404 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 160
0.405 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 160
0.405 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.407 [INFO]  Fast Track Pro ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.407 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 160
0.407 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 160
0.407 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.411 [INFO]  Fast Track Pro ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
73.153 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
73.154 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
73.154 [INFO]  AsioSharedHost::Stop - enter startCount: 1
73.154 [INFO]  AsioSharedHost::Stop - stopping ASIO stream
73.163 [INFO]  AsioSharedHost::Stop - leave startCount: 0
73.163 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
73.163 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\M-Audio\Fast Track Pro\MAudioFastTrackPro_Asio.dll

**Comment by mdias** [comment]
@MarkusOliver you need to share your RS_ASIO.ini
