### ISSUE TITLE
iRig HD2 Loading Issue

### ISSUE THREAD

**Issue by WarCat217** [mdias/rs_asio#229]
I'm having issues trying to get the game to load songs. 
Game itself will load up fine all the way until after I go past the tuner. It then crashes or freezes but audio is still working perfectly fine along with the sound animation from the speaker cabinets. 
[Log and Settings.zip](https://github.com/mdias/rs_asio/files/7524759/Log.and.Settings.zip)

**Comment by mdias** [comment]
Are you by any chance using CDLC?
And does it stop crashing if you don't use RS_ASIO?

**Comment by WarCat217** [comment]
Yes, I'm using CDLC. Still crashes even if I don't use CDLC and try to play a standard song already loaded in the game with RS_ASIO. 
Doesn't crash when using neither a real tone cable or RS_ASIO (loads up fretboard and can see notes but no movement other than from speaker cabinets). 
I never had it crash when using a real tone cable with or without CDLC (before installing RS_ASIO), real tone cable stopped working recently so I am unable to test if it crashes with it

**Comment by mdias** [comment]
I don't understand how you even have audio working at all; the log shows that you don't have audio exclusivity enabled, and is failing to even initialize the ASIO output.
I would advise you to move all your CDLC into a backup folder and do clean install the game, and try to get RS ASIO working before you add the CDLC.

**Comment by WarCat217** [comment]
Removed the CDLC, and re-installed the game. Doesn't crash unless I add CDLC to the DLC folder but can't seem to get any audio thru any output device.
[Log and Settings.zip](https://github.com/mdias/rs_asio/files/7532914/Log.and.Settings.zip)

**Comment by mdias** [comment]
If you want the audio to go out through your default audio output instead of the audio interface you'd have to do enable wasapi outputs and disable asio output like so:
```
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

...

[Asio.Output]
Driver=
```

As for your CDLC, you'll have to find out which one is causing the issues. RS_ASIO should have no problems running with CDLC, but some CDLC introduces stability issues with the game in general.

**Comment by WarCat217** [comment]
Thanks for the help. All seems to be working fine. I'll have to add each CDLC song individually until I find which one or ones are causing the issue.
