### ISSUE TITLE
No sound input/output in RS2014, using the ASIO application with the Yamaha Steinberg USB ASIO

### ISSUE THREAD

**Issue by DERedway** [mdias/rs_asio#234]
I have an issue recieving sound from Rocksmith 2014 when using the ASIO application (without it, I recieve sound) and the game doesn't see my mixer (where I have connected my guitar on channel 2) so I can't do any sound in-game.
I have tried many ways it could work in the RS_ASIO.ini but nothing works, neither recieving sound, nor from mixer to RS2014.
I also tried the newest (0.5.6) and an older (0.5.3) version of RS_ASIO...

At this time it looks like this:
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=48

[Asio.Output]
Driver=Yamaha Steinberg USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Yamaha Steinberg USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

I tried to change the input and output to 24000HZ and 16bit in the advanced tab of my mixer, but I can't change it how it is configured (2 channel, 24bit, 48000HZ for input and output) and I don't know if this could be the issue.
Also when I start the game with the RS_ASIO and more in the game files, the game tells me that it couldn't find any output channels.

I would like to play the game and would be very grateful if anyone of you might know any way to make it work.

**Comment by mdias** [comment]
Please post the contents of RS_ASIO-log.txt.

**Comment by DERedway** [comment]
0.000 [INFO]   - Wrapper DLL loaded (v0.5.3)
0.000 [INFO]  PatchOriginalCode
0.510 [INFO]  Patching CoCreateInstance
0.510 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.510 [INFO]  Patching call at 01C5AA85
0.510 [INFO]  Patching call at 01F03B6E
0.510 [INFO]  Patching call at 01F5C681
0.510 [INFO]  Patching call at 01FAEF75
0.510 [INFO]  Patching call at 01FAF40D
0.510 [INFO]  Patching PortAudio MarshalStreamComPointers
0.510 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.510 [INFO]  Patching call at 01F03059
0.510 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.510 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.510 [INFO]  Patching call at 01F0310E
0.512 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.513 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.513 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.513 [INFO]  AsioHelpers::FindDrivers
0.513 [INFO]    ASIO4ALL v2
0.513 [INFO]    FL Studio ASIO
0.514 [INFO]    Realtek ASIO
0.514 [INFO]    Yamaha Steinberg USB ASIO
0.514 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Yamaha Steinberg USB ASIO
0.514 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.525 [INFO]    ASIO input channels info:
0.525 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: AG06/AG03
0.525 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: AG06/AG03
0.525 [INFO]    ASIO output channels info:
0.525 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: AG06/AG03
0.525 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: AG06/AG03
0.525 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.525 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Yamaha Steinberg USB ASIO
0.525 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.525 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.525 [INFO]    hr: S_OK
0.525 [INFO]    *ppEndpoint: 1A612620
0.525 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.525 [INFO]    hr: S_OK
0.525 [INFO]    *ppEndpoint: 1A612A30
0.525 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.525 [INFO]    hr: S_OK
0.525 [INFO]    *ppDevices: 090FCB28
0.525 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.525 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.525 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.525 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.525 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.525 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.525 [INFO]    *pDataFlow: eRender
0.525 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.525 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.525 [INFO]  {ASIO IN 1} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.525 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetCount
0.525 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.525 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.525 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.525 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.525 [INFO]  {ASIO IN 1} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.525 [INFO]  {ASIO IN 1} DebugWrapperEndpoint::GetDataFlow
0.525 [INFO]    *pDataFlow: eCapture
0.525 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.525 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.535 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.551 [ERROR]    shared mode is not supported
0.551 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.552 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
4.346 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
4.346 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
4.346 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
4.346 [INFO]  AsioHelpers::FindDrivers
4.346 [INFO]    ASIO4ALL v2
4.346 [INFO]    FL Studio ASIO
4.346 [INFO]    Realtek ASIO
4.347 [INFO]    Yamaha Steinberg USB ASIO
4.347 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Yamaha Steinberg USB ASIO
4.347 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
4.357 [INFO]    ASIO input channels info:
4.358 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: AG06/AG03
4.358 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: AG06/AG03
4.358 [INFO]    ASIO output channels info:
4.358 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: AG06/AG03
4.358 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: AG06/AG03
4.358 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
4.358 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Yamaha Steinberg USB ASIO
4.358 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
4.358 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
4.358 [INFO]    hr: S_OK
4.358 [INFO]    *ppEndpoint: 0F6A8050
4.358 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
4.358 [INFO]    hr: S_OK
4.358 [INFO]    *ppEndpoint: 0F6A7F10
4.358 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
4.358 [INFO]    hr: S_OK
4.358 [INFO]    *ppDevices: 09102268
4.358 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
4.358 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
4.358 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
4.358 [INFO]    *pDataFlow: eRender
4.358 [INFO]  {ASIO IN 1} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
4.358 [INFO]  {ASIO IN 1} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
4.358 [INFO]  {ASIO IN 1} DebugWrapperEndpoint::GetDataFlow
4.358 [INFO]    *pDataFlow: eCapture
4.369 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
19.426 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
19.426 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
19.752 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
Please read the [instructions](https://github.com/mdias/rs_asio/blob/master/README.md) a bit more closely. As stated there:

> Make sure Rocksmith.ini is set to run with `ExclusiveMode=1` and `Win32UltraLowLatencyMode=1`.

**Comment by DERedway** [comment]
Tank you very much! It now works after changing ExclusiveMode=1 and Win32UltraLowLatencyMode=1 and RealToneCableOnly=1. Thanks for your help and time!

**Comment by mdias** [comment]
Glad I could help!
