### ISSUE TITLE
Custom channel mapping

### ISSUE THREAD

**Issue by theSG** [mdias/rs_asio#242]
Hi.
Sometimes I like to play guitar with music on left channel and guitar completely separately on the right. I want to make a setting in ini to map left rocksmith channel on left asio output and use a plugin for guitar sound on the right channel.
I took a quick look at the RSAsioAudioClient because it mentions channel mapping,
so `m_ChannelMap[(asioChannel=0)] = (rocksmithChannel=0)` will do what I want?
Just wanted to ask if this should be as easy to do as I think it is before spending way too much time figuring out why it doesn't work.

**Comment by theSG** [comment]
It works like I wanted it to.

**Comment by mdias** [comment]
Sorry I couldn't reply sooner. But yes, it's easy to do in code but not exposed in the config.

Since this is a rare use case I'm not sure it's worth it to do it either, and you could also achieve this with Voicemeeter or an equivalent that would allow you to reroute the signals easily.
