### ISSUE TITLE
No audio output device is detected. Please connect and enable an audio output then restart Rocksmith 2014 

### ISSUE THREAD

**Issue by shellbeach01** [mdias/rs_asio#243]

**Comment by shellbeach01** [comment]
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by shellbeach01** [comment]
[Audio]
EnableMicrophone=1
ExclusiveMode=0
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=0
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1

**Comment by shellbeach01** [comment]
0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
0.304 [INFO]  Patching CoCreateInstance
0.304 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.304 [INFO]  Patching call at 01C5AA85
0.304 [INFO]  Patching call at 01F03B6E
0.304 [INFO]  Patching call at 01F5C681
0.304 [INFO]  Patching call at 01FAEF75
0.304 [INFO]  Patching call at 01FAF40D
0.304 [INFO]  Patching PortAudio MarshalStreamComPointers
0.304 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.304 [INFO]  Patching call at 01F03059
0.304 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.304 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.304 [INFO]  Patching call at 01F0310E
0.491 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
0.618 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.186 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
1.186 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
1.187 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
1.187 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
1.187 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
1.187 [INFO]  AsioHelpers::FindDrivers
1.187 [INFO]    ASIO UX2
1.187 [INFO]    Focusrite Thunderbolt ASIO
1.187 [INFO]    Focusrite USB ASIO
1.187 [INFO]    Realtek ASIO
1.187 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
1.187 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusriteusb\focusriteusbasio32.dll
1.192 [INFO]    ASIO input channels info:
1.193 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
1.193 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
1.193 [INFO]    ASIO output channels info:
1.193 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
1.193 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
1.193 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
1.193 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
1.193 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
1.193 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
1.193 [INFO]    hr: S_OK
1.193 [INFO]    *ppEndpoint: 12052988
1.193 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
1.193 [INFO]    hr: S_OK
1.193 [INFO]    *ppEndpoint: 120527A8
1.193 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
1.193 [INFO]    hr: S_OK
1.193 [INFO]    *ppDevices: 1274B010
1.193 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.193 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
1.193 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
1.193 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
1.193 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.193 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
1.193 [INFO]    *pDataFlow: eRender
1.193 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
1.193 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.193 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
1.193 [INFO]    *pDataFlow: eCapture
1.193 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
1.193 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
1.575 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.575 [ERROR]    shared mode is not supported
1.575 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.575 [INFO]  Destroying AsioSharedHost - dll: c:\program files\focusriteusb\focusriteusbasio32.dll
3.563 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
3.563 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
3.563 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
3.563 [INFO]  AsioHelpers::FindDrivers
3.564 [INFO]    ASIO UX2
3.564 [INFO]    Focusrite Thunderbolt ASIO
3.564 [INFO]    Focusrite USB ASIO
3.564 [INFO]    Realtek ASIO
3.564 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
3.564 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusriteusb\focusriteusbasio32.dll
3.569 [INFO]    ASIO input channels info:
3.569 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
3.569 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
3.569 [INFO]    ASIO output channels info:
3.569 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
3.569 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
3.569 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
3.569 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
3.569 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
3.569 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
3.569 [INFO]    hr: S_OK
3.569 [INFO]    *ppEndpoint: 120528C8
3.569 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.569 [INFO]    hr: S_OK
3.569 [INFO]    *ppEndpoint: 120523E8
3.569 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.569 [INFO]    hr: S_OK
3.569 [INFO]    *ppDevices: 128C1970
3.569 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.569 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.569 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
3.569 [INFO]    *pDataFlow: eRender
3.569 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.569 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.569 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
3.569 [INFO]    *pDataFlow: eCapture
3.576 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
10.463 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
10.463 [INFO]  Destroying AsioSharedHost - dll: c:\program files\focusriteusb\focusriteusbasio32.dll
10.464 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
10.656 [INFO]   - Wrapper DLL unloaded

**Comment by Wrxmigel** [comment]
Was this fixed ? I’m having the same issue

**Comment by mdias** [comment]
I assume @shellbeach01 figured out the issue since they closed it.
In this case the problem was that Rocksmith.ini was not set to use Exclusive mode. As stated in the README, ExclusiveMode must be on.

**Comment by mlevett** [comment]
Really annoying as I have the exact same issue!

**Comment by mdias** [comment]
@mlevett do you have ExclusiveMode on as stated in the README?
If you do, feel free to post your log file.
