### ISSUE TITLE
asio will not detect my interface at all 

### ISSUE THREAD

**Issue by ChloricWolf7** [mdias/rs_asio#244]
hello, 
i got a bundle deal with a blucoil audio interface havent played rocksmith in years because i broke the realtone cable and havent been able to replace it. 
anyway i hooked it up and it works in my DAW but ASIO will not detect the drivers at all. pretty sure the driver is a generic usb driver but i dont see any other driver software from the  manufacturer. 
blucoil audio interface 
BLCL_INTERFACE
heres my logs 
 0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
0.436 [INFO]  Patching CoCreateInstance
0.436 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.436 [INFO]  Patching call at 01C5AA85
0.436 [INFO]  Patching call at 01F03B6E
0.436 [INFO]  Patching call at 01F5C681
0.436 [INFO]  Patching call at 01FAEF75
0.436 [INFO]  Patching call at 01FAF40D
0.436 [INFO]  Patching PortAudio MarshalStreamComPointers
0.436 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.436 [INFO]  Patching call at 01F03059
0.436 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.436 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.436 [INFO]  Patching call at 01F0310E
0.438 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.438 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.438 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.438 [INFO]  AsioHelpers::FindDrivers
0.438 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.438 [INFO]    hr: 80070490
0.438 [INFO]    *ppEndpoint: 00000000
0.438 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.438 [INFO]    hr: 80070490
0.438 [INFO]    *ppEndpoint: 00000000
0.438 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.438 [INFO]    hr: S_OK
0.438 [INFO]    *ppDevices: 16EA7ED0
4.098 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
4.098 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
4.098 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
4.098 [INFO]  AsioHelpers::FindDrivers
4.098 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
4.098 [INFO]    hr: 80070490
4.098 [INFO]    *ppEndpoint: 00000000
4.098 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
4.098 [INFO]    hr: 80070490
4.098 [INFO]    *ppEndpoint: 00000000
4.098 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
4.098 [INFO]    hr: S_OK
4.098 [INFO]    *ppDevices: 16DDBE08
4.105 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
125.353 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
125.506 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
Hello,

There are 2 reasons that could explain RS ASIO not finding the ASIO drivers:

1. You don't actually have any ASIO drivers installed (which means your DAW is not using ASIO)
2. You only have 64-bit drivers, but since Rocksmith is a 32 bit process, it requires 32-bit ASIO drivers

If your interface is detected as a generic audio interface like you say, it's very likely that it's the case that you don't have any ASIO drivers at all, and instead your DAW is just using some other audio backend (not ASIO).
