### ISSUE TITLE
Rocksmith reminds me that I don't have audio hardware

### ISSUE THREAD

**Issue by kachofugetsu1998** [mdias/rs_asio#245]
hello Micael Dias Thank you for making this program. After I deployed the program according to the tutorial, it didn't work. My sound card is hotone ampro II stomp, with 24-bit 44.1KHz 8i8. The following is my log. Please help me troubleshoot. Thank you

0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
0.435 [INFO]  Patching CoCreateInstance
0.435 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.435 [INFO]  Patching call at 01C5AA85
0.435 [INFO]  Patching call at 01F03B6E
0.435 [INFO]  Patching call at 01F5C681
0.435 [INFO]  Patching call at 01FAEF75
0.435 [INFO]  Patching call at 01FAF40D
0.435 [INFO]  Patching PortAudio MarshalStreamComPointers
0.435 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.435 [INFO]  Patching call at 01F03059
0.435 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.435 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.435 [INFO]  Patching call at 01F0310E
0.444 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.444 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.444 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.444 [INFO]  AsioHelpers::FindDrivers
0.445 [INFO]    ASIO4ALL v2
0.445 [INFO]    FL Studio ASIO
0.446 [INFO]    HOTONE AUDIO USB Audio Device
0.446 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: HOTONE AUDIO USB Audio Device
0.446 [INFO]  Creating AsioSharedHost - dll: e:\program files\hotone audio\usb audio device driver\w10_x64\hotoneusbaudioasio.dll
0.476 [INFO]    ASIO input channels info:
0.476 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 1
0.476 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 2
0.476 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 3
0.476 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 4
0.476 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 5
0.476 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 6
0.476 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 7
0.476 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 8
0.476 [INFO]    ASIO output channels info:
0.476 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 1
0.477 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 2
0.477 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 3
0.477 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 4
0.477 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 5
0.477 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 6
0.477 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 7
0.477 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 8
0.477 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.477 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: HOTONE AUDIO USB Audio Device
0.477 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.477 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.477 [INFO]    hr: S_OK
0.477 [INFO]    *ppEndpoint: 1199FE18
0.477 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.477 [INFO]    hr: S_OK
0.477 [INFO]    *ppEndpoint: 119A0458
0.477 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.477 [INFO]    hr: S_OK
0.477 [INFO]    *ppDevices: 0925DC30
0.477 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.477 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.477 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.477 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.477 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.477 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.477 [INFO]    *pDataFlow: eRender
0.477 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.477 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.477 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.477 [INFO]    *pDataFlow: eCapture
0.477 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.477 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.493 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.493 [ERROR]    unsupported sample rate: 48000
0.493 [ERROR]    failed to initialize asio driver with requested format
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.493 [ERROR]    unsupported sample rate: 48000
0.493 [ERROR]    failed to initialize asio driver with requested format
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.493 [ERROR]    unsupported sample rate: 48000
0.493 [ERROR]    failed to initialize asio driver with requested format
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.493 [ERROR]    unsupported sample rate: 48000
0.493 [ERROR]    failed to initialize asio driver with requested format
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.493 [ERROR]    shared mode is not supported
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.493 [ERROR]    shared mode is not supported
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.493 [ERROR]    shared mode is not supported
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.493 [ERROR]    shared mode is not supported
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.493 [ERROR]    shared mode is not supported
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.493 [ERROR]    shared mode is not supported
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.493 [ERROR]    shared mode is not supported
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.493 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.493 [ERROR]    shared mode is not supported
0.493 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.494 [INFO]  Destroying AsioSharedHost - dll: e:\program files\hotone audio\usb audio device driver\w10_x64\hotoneusbaudioasio.dll
11.747 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
11.747 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
11.747 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
11.747 [INFO]  AsioHelpers::FindDrivers
11.747 [INFO]    ASIO4ALL v2
11.747 [INFO]    FL Studio ASIO
11.748 [INFO]    HOTONE AUDIO USB Audio Device
11.748 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: HOTONE AUDIO USB Audio Device
11.748 [INFO]  Creating AsioSharedHost - dll: e:\program files\hotone audio\usb audio device driver\w10_x64\hotoneusbaudioasio.dll
11.781 [INFO]    ASIO input channels info:
11.781 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 1
11.781 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 2
11.781 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 3
11.781 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 4
11.781 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 5
11.781 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 6
11.781 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 7
11.781 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Analogue 8
11.781 [INFO]    ASIO output channels info:
11.781 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 1
11.781 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 2
11.781 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 3
11.781 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 4
11.781 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 5
11.781 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 6
11.781 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 7
11.781 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Analogue 8
11.781 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
11.781 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: HOTONE AUDIO USB Audio Device
11.781 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
11.781 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
11.781 [INFO]    hr: S_OK
11.781 [INFO]    *ppEndpoint: 1B9DAB80
11.781 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
11.781 [INFO]    hr: S_OK
11.782 [INFO]    *ppEndpoint: 1B9DBB70
11.782 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
11.782 [INFO]    hr: S_OK
11.782 [INFO]    *ppDevices: 0934EB00
11.782 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
11.782 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
11.782 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
11.782 [INFO]    *pDataFlow: eRender
11.782 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
11.782 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
11.782 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
11.782 [INFO]    *pDataFlow: eCapture
11.797 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
38.324 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
38.324 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
38.324 [ERROR]    unsupported sample rate: 48000
38.324 [ERROR]    failed to initialize asio driver with requested format
38.324 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
38.324 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
38.324 [ERROR]    unsupported sample rate: 48000
38.324 [ERROR]    failed to initialize asio driver with requested format
38.324 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
38.324 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
38.324 [ERROR]    unsupported sample rate: 48000
38.324 [ERROR]    failed to initialize asio driver with requested format
38.324 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
38.324 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
38.324 [ERROR]    unsupported sample rate: 48000
38.324 [ERROR]    failed to initialize asio driver with requested format
38.324 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
38.324 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
38.324 [ERROR]    unsupported sample rate: 48000
38.324 [ERROR]    failed to initialize asio driver with requested format
38.324 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
38.324 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
38.324 [ERROR]    unsupported sample rate: 48000
38.324 [ERROR]    failed to initialize asio driver with requested format
38.324 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
38.324 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
38.324 [ERROR]    unsupported sample rate: 48000
38.324 [ERROR]    failed to initialize asio driver with requested format
38.324 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
38.324 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
38.324 [ERROR]    unsupported sample rate: 48000
38.324 [ERROR]    failed to initialize asio driver with requested format
38.324 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
42.081 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
42.082 [INFO]  Destroying AsioSharedHost - dll: e:\program files\hotone audio\usb audio device driver\w10_x64\hotoneusbaudioasio.dll
42.380 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
Hello,

Unfortunately, as stated in the [readme](https://github.com/mdias/rs_asio/blob/master/README.md), if your interface doesn't support 48kHz sample rate, you're out of luck.

**Comment by kachofugetsu1998** [comment]
I've seen that the drive setting has only two modes: 16 bit 44.1KHz or 24 bit 44.1KHz. If so, can it not run?

**Comment by mdias** [comment]
No. That is only changing the sample format, the sample rate is still 44.1kHz on both of those, sorry.

**Comment by kachofugetsu1998** [comment]
Thank you, micael DIAS. Thank you for your answer. It seems that this method won't work. I'd better use my original wire
