### ISSUE TITLE
Line6 Helix

### ISSUE THREAD

**Issue by Eraseri** [mdias/rs_asio#248]
Hi, I'm trying to get this to work with Line6 Helix. I have setup my Helix like in [here](https://line6.com/support/topic/55461-i-got-helix-to-work-as-an-audio-interface-in-linux/). I started up Rocksmith after setting this up and I'm quite confused about information in the log-file. What am I suppost to use as driver?

Previously I have gotten Rocksmith to work succesfully with Helix in Linux by using some other methods. It seems to be always a fight to get it working...

0.141 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.141 [INFO]  AsioHelpers::FindDrivers
0.141 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.141 [INFO]    hr: 80070490
0.141 [INFO]    *ppEndpoint: 00000000
0.141 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.141 [INFO]    hr: 80070490
0.141 [INFO]    *ppEndpoint: 00000000
0.141 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.141 [INFO]    hr: S_OK
0.141 [INFO]    *ppDevices: 07C08830
1.726 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
1.726 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
1.726 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
1.726 [INFO]  AsioHelpers::FindDrivers
1.726 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
1.726 [INFO]    hr: 80070490
1.726 [INFO]    *ppEndpoint: 00000000
1.726 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
1.726 [INFO]    hr: 80070490
1.726 [INFO]    *ppEndpoint: 00000000
1.726 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
1.726 [INFO]    hr: S_OK
1.726 [INFO]    *ppDevices: 07C117A8
1.726 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
56.150 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
56.410 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
You don't seem to have any ASIO drivers installed.

Usually people on linux would be using wineasio, but I personally never tried it. Check out [this issue](https://github.com/mdias/rs_asio/issues/99).
