### ISSUE TITLE
Sound is distorted sometimes

### ISSUE THREAD

**Issue by DarkyKira** [mdias/rs_asio#249]
Hello, I have an external sound card, Komplete audio 1, and sometimes during the game the sound is distorted, not only the guitar is distorted, but also the music in the game itself
My sound card has a switch between line and inst, I tried to switch them, but the problem is there and there

**Comment by mdias** [comment]
Can you post your RS_ASIO.ini and also the RS_ASIO-log.txt after experiencing this issue?

**Comment by DarkyKira** [comment]
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Komplete Audio ASIO Driver
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Komplete Audio ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by DarkyKira** [comment]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/7840019/RS_ASIO-log.txt)

**Comment by mdias** [comment]
You're having buffer underruns. Try increasing the buffer size in use by your driver (you're currently using 64). You can also change that through:

```
BufferSizeMode=custom
CustomBufferSize=128
```

If the issue persists, open Rocksmith.ini and also increase the `LatencyBuffer` number.

**Comment by DarkyKira** [comment]
Thank you, when there is an opportunity to check, I will write about it here and close the problem

**Comment by DarkyKira** [comment]
I checked on 4 songs, I didn’t hear any distortion, thank you
