### ISSUE TITLE
Multiplayer not working

### ISSUE THREAD

**Issue by kwoulf** [mdias/rs_asio#25]
Hello, great job with this workaround! I love it in single player mode but I can't get it to work in multiplayer. I keep messing around with the settings but I can't get two guitars to work at the same time. Below is my current ASIO .ini file settings. I'm using a Focusrite 2i2 3rd gen interface.

Any advice?

Thanks!

 

[Config]
EnableWasapi=0
EnableAsio=1
 
[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48
 
[Asio.Output]
Driver=Focusrite USB ASIO
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
 
; [Asio.Input.0]
; Driver=Focusrite USB ASIO
; Channel=0
; EnableSoftwareEndpointVolumeControl=1
; EnableSoftwareMasterVolumeControl=1
; SoftwareMasterVolumePercent=100
 
[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4145332/RS_ASIO-log.txt)

**Comment by mdias** [comment]
You only have 1 input configured.

You have to uncomment the lines on Asio.Input.0 to also enable the first instrument input.

That said, your log is also showing a lot of buffer underruns, so I would also advise you to use `CustomBufferSize=96` instead of 48.

So your config should look like this:

```
[Config]
EnableWasapi=0
EnableAsio=1

[Asio]
; available buffer size modes:
; driver - respect buffer size setting set in the driver
; host - use a buffer size as close as possible as that requested by the host application
; custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=96

[Asio.Output]
Driver=Focusrite USB ASIO
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by kwoulf** [comment]
Hi, I figured it out. For whatever reason, I can only get game sound to work with a CustomBufferSize=48 setting in the ASIO.ini file. What ended up making Multiplayer work was doubling my MaxOutputBufferSize in the Rocksmith.ini file to 96. I just need to add or delete the semicolons in front of the Input 1 lines to play multiplayer now. If I don't add the semicolons the game keeps telling me I have two Realtone cables plugged in which doesn't work for Singleplayer.

P.S. could you take a look at this ASIO log file to see if anything else looks quirky?

Thanks again! This makes the game soooo much better

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4150194/RS_ASIO-log.txt)

**Comment by mdias** [comment]
`MaxOutputBufferSize` is usually left at zero, but if setting that to a value helps you get good results then I guess it's fine too :)

There's nothing wrong with your log file except some underruns that appear to be happining during game load, so I guess that's not a big deal if it doesn't happen while ingame.
However it suggests you might be at the very limit of what your machine can achieve in terms of latency, so I would recommend you spend a bit more time trying out things to be able to increase your buffer size to 96 (maybe try setting that in the control panel too and updating your interface drivers) to avoid possible underruns while playing.

That said, you're not the first one that says they can only make it work with a very specific buffer size and I noticed Focusrite drivers tend to have some issues so.. as long as it works, right? :)
