### ISSUE TITLE
ESI UGM96 works (almost perfectly)

### ISSUE THREAD

**Issue by zotyo86** [mdias/rs_asio#250]
I managed to set up my ESI UGM96 interface to work with Rocksmith 2014 Remastered (Steam). I plug my guitar or bass into the left input on the front panel (with a guitar symbol). Preamp gain switch is at 0 dB, guitar/microphone switch is at 'guitar'.
I have only one issue: if I close RS and restart it, RS detects no output device anymore. I have to unplug the interface USB cable from my computer and reconnect it before I can launch RS again. This issue seems to be similar to #134 reported by a MAYA44 eX user.

Configuration

RS_ASIO.ini
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=host
CustomBufferSize=

[Asio.Output]
Driver=ASIO 2.0 - ESI UGM96
BaseChannel=0
AltBaseChannel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO 2.0 - ESI UGM96
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=ASIO 2.0 - ESI UGM96
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

Rocksmith.ini
```
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=0
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
```

P.s.: This is my first-ever github issue made, therefore sorry for any violation of basic reporting guidelines.

**Comment by mdias** [comment]
Yes, as you've seen it seems that ESI drivers get stuck and this is a known issue. Unfortuntely there isn't much I can do.

Don't worry about the issue, I haven't defined any specific reporting guidelines and this is a very good report :)

Thank you for reporting. I've added the interface to the documentation, along with info about this driver issue 👍
