### ISSUE TITLE
Line6 HX Stomp works perfectly

### ISSUE THREAD

**Issue by zotyo86** [mdias/rs_asio#251]
I managed to make my freshly bought Line6 HX Stomp work with Rocksmith 2014 Remastered (Steam). The best thing is that I can use my own tone presets for any RS song, and I don't have to hassle with the poor RS amps and effects anymore. Sound quality of my guitar/bass and the songs is simply much better with HX Stomp, while the note detection in RS is still stable.

Remark 1:
I initially forced RS use my HX Stomp in ASIO mode both for input and output, but I found I could not adjust the RS palyback volume from windows to balance the song playback with my guitar output. Although it is possible to adjust USB playback gain on the Stomp itself (USB1/2) in the global settings, I simply found it more convenient to force playback via WASAPI so that I can use the special VOL+/- keys on my keyboard to adjust RS playback volume. I use the Volume pot on Stomp for adjusting the volume of the entire mix (RS + guitar signal) going to my monitors/headphones while playing.

Remark 2:
The dry DI instrument signal going from Stomp to RS via channel USB5 is at unity gain, as it is intended for reamping purposes according to Line6. The gain must be increased for RS so that calibration works correctly. I found 600% in the configuration is good enough for my Strat with passive single coils, RS ends up at +5..+6 dB input gain after calibration.

Finally here comes the configuration:

RS_ASIO.ini
```
[Config]
; using ASIO for input but Wasapi for output. This way the song volume alone can be adjusted from Windows conveniently.
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
; No ASIO driver is defined for output, because WASAPI mode is preferred for playback.
Driver=
BaseChannel=0
AltBaseChannel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=80

[Asio.Input.0]
Driver=ASIO HX Stomp
Channel=4
; 0 means feeding RS with wet signal from HX Stomp Path A for note detection (USB1)
; 4 means feeding RS with dry DI signal from HX Stomp for note detection (USB5)
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=600
; HX Stomp sends USB signal with unity gain, which is too low for RS to calibrate properly.
; 600% gain is defined to compensate for this.

[Asio.Input.1]
;shall be kept empty, otherwise RS will detect two conflicting Rocksmith cables.
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
; microphone is not used.
Driver=
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

Rocksmith.ini
```
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=1
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
```

Thank you @mdias for developing this great project.

**Comment by mdias** [comment]
Thank you for another report. Added to the docs 👍
