### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by AlexeyGulis** [mdias/rs_asio#252]
Need a hint what the problem is?
Game crashes before Enter command

0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
0.307 [INFO]  Patching CoCreateInstance
0.307 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.307 [INFO]  Patching call at 01C5AA85
0.307 [INFO]  Patching call at 01F03B6E
0.307 [INFO]  Patching call at 01F5C681
0.307 [INFO]  Patching call at 01FAEF75
0.307 [INFO]  Patching call at 01FAF40D
0.307 [INFO]  Patching PortAudio MarshalStreamComPointers
0.307 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.307 [INFO]  Patching call at 01F03059
0.307 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.307 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.307 [INFO]  Patching call at 01F0310E
0.308 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.308 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.308 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.308 [INFO]  AsioHelpers::FindDrivers
0.308 [INFO]    Realtek ASIO
0.308 [INFO]    UMC ASIO Driver
0.308 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: UMC ASIO Driver
0.308 [INFO]  Creating AsioSharedHost - dll: c:\program files\behringer\umc_audio_driver\w10_x64\umc_audioasio.dll
0.312 [INFO]    ASIO input channels info:
0.312 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: In 1
0.312 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: In 2
0.312 [INFO]    ASIO output channels info:
0.312 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Out 1
0.312 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Out 2
0.312 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.312 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: UMC ASIO Driver
0.312 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.312 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: UMC ASIO Driver
0.312 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.312 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 2 capture devices
0.312 [INFO]    hr: S_OK
0.312 [INFO]    *ppEndpoint: 18F41678
0.312 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.312 [INFO]    hr: S_OK
0.312 [INFO]    *ppEndpoint: 18F41DF8
0.312 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.312 [INFO]    hr: S_OK
0.312 [INFO]    *ppDevices: 1C897FC0
0.312 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.312 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.312 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.312 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.312 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.312 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.312 [INFO]    *pDataFlow: eRender
0.312 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.312 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.312 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.312 [INFO]    *pDataFlow: eCapture
0.312 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.312 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.312 [INFO]  {ASIO IN 1} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.313 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetCount
0.313 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.313 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.313 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.313 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.313 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
0.313 [INFO]  {ASIO IN 1} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.313 [INFO]  {ASIO IN 1} DebugWrapperEndpoint::GetDataFlow
0.313 [INFO]    *pDataFlow: eCapture
0.313 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.313 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.315 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback

**Comment by mdias** [comment]
Does it work without RS ASIO?

**Comment by AlexeyGulis** [comment]
reinstall rocksmith fix problem. 
Thank u for this amazing patch

**Comment by mdias** [comment]
Awesome! Thanks for letting me know 👍
