### ISSUE TITLE
No sound unless I do a fresh install. Says microphone not detecting while using audio interface. 

### ISSUE THREAD

**Issue by kadefitzpatrick** [mdias/rs_asio#255]
Im using a Xenyx Q502 audio interface to route my guitar, and I can get sound with a fresh installation set to microphone, but as soon as I install RS_Asio it either gives me No audio output restart, or it gives me no input and no sound...

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

edit: got it working with lots of unwanted distortion and minor input lag, restarted the game changing nothing, and im back to square one. No output...............

**Comment by mdias** [comment]
Unfortunately ASIO4ALL is known to not work too well with RS_ASIO.
However, please post the contents of RS_ASIO-log.txt so I can have a look at why it says there's no output.

**Comment by kadefitzpatrick** [comment]
0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
0.511 [INFO]  Patching CoCreateInstance
0.511 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.511 [INFO]  Patching call at 01C5AA85
0.511 [INFO]  Patching call at 01F03B6E
0.511 [INFO]  Patching call at 01F5C681
0.511 [INFO]  Patching call at 01FAEF75
0.511 [INFO]  Patching call at 01FAF40D
0.511 [INFO]  Patching PortAudio MarshalStreamComPointers
0.511 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.511 [INFO]  Patching call at 01F03059
0.511 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.511 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.511 [INFO]  Patching call at 01F0310E
0.721 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
0.950 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.180 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.396 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.617 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.831 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.055 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.802 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
2.802 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
2.803 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
2.803 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
2.803 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
2.803 [INFO]  AsioHelpers::FindDrivers
2.803 [INFO]    ASIO4ALL v2
2.804 [INFO]    FL Studio ASIO
2.804 [INFO]    Voicemeeter Virtual ASIO
2.804 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO4ALL v2
2.804 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\ASIO4ALL v2\asio4all.dll
3.481 [INFO]    info: asio4all detected
3.481 [INFO]    ASIO input channels info:
3.481 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: USB Audio CODEC  1
3.481 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: USB Audio CODEC  2
3.481 [INFO]    ASIO output channels info:
3.481 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: USB Audio CODEC  1
3.481 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: USB Audio CODEC  2
3.481 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
3.481 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO4ALL v2
3.481 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
3.481 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
3.481 [INFO]    hr: S_OK
3.481 [INFO]    *ppEndpoint: 0DF28C30
3.481 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.481 [INFO]    hr: S_OK
3.481 [INFO]    *ppEndpoint: 0DF28A20
3.481 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.481 [INFO]    hr: S_OK
3.481 [INFO]    *ppDevices: 159CD298
3.481 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.481 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
3.481 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
3.481 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
3.481 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.481 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
3.481 [INFO]    *pDataFlow: eRender
3.481 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
3.481 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
3.481 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.481 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
3.482 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
3.482 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
3.482 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
3.482 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
3.482 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
3.482 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.482 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
3.482 [INFO]    *pDataFlow: eCapture
3.482 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
3.482 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
3.488 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
3.488 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.488 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
3.488 [ERROR]    failed to initialize asio driver with requested format
3.488 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
3.488 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.488 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
3.488 [ERROR]    failed to initialize asio driver with requested format
3.488 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
3.488 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.488 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
3.488 [INFO]    Switching sample rate from 44100 to 48000...
3.489 [INFO]   Waiting 5 seconds to give driver time to refresh
8.492 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
8.492 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
8.492 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 3ms (144 frames)
8.492 [INFO]  AsioSharedHost::Setup - startCount: 0
8.492 [INFO]    post output ready: 0
8.492 [INFO]    ASIOBufferSize - min: 64 max: 2048 preferred: 96 granularity: 8
8.492 [INFO]    Creating ASIO buffers (2 out, 2 in)...
8.492 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
8.492 [INFO]    *pNumBufferFrames: 144
8.492 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
8.492 [INFO]    latency: 8ms
8.492 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
8.492 [INFO]    returning render client
8.492 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
8.494 [INFO]  Patched_PortAudio_MarshalStreamComPointers
8.495 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
8.495 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
8.495 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
8.495 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
8.495 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
8.495 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
8.495 [INFO]  AsioSharedHost::Start - startCount: 0
8.495 [INFO]    Starting ASIO stream...
9.192 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
9.192 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
9.192 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
9.192 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
9.196 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
9.196 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
9.196 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
9.196 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
9.200 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
16.636 [INFO]  {ASIO Out} RSAsioAudioClient::OnAsioBufferSwitch - buffer underrun detected
16.636 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
16.640 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
16.640 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
16.644 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
16.648 [INFO]  ASIO4ALL v2 - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
30.331 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
30.332 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
30.332 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
30.332 [INFO]  AsioSharedHost::Stop - startCount: 1
30.332 [INFO]  AsioSharedHost::Stop  stopping ASIO stream
30.776 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\ASIO4ALL v2\asio4all.dll
30.776 [INFO]  Restoring previously set sample rate
30.993 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
ASIO4ALL is not swapping buffers at a regular enough interval.
The first thing I see is that it's starting with 44100hz, and you must be using 48000hz for Rocksmith. Maybe changing that will be enough.

**Comment by kadefitzpatrick** [comment]
I tried that, I tried every option under the sun. I am out of solutions.

**Comment by mdias** [comment]
I'm afraid ASIO4ALL won't be working correctly for you.
The only thing I can suggest is trying to go with the [legacy driver](https://www.reddit.com/r/rocksmith/comments/odhlcx/guide_behringer_uphoria_um2_and_other_behringer/).

**Comment by kadefitzpatrick** [comment]
I dont want to use microphone mode but its the only way ive been able to get it to work in the slightest. I want it to just work on input. Im trying the whole legacy driver thing now, even though I installed it last night and it didnt give me any other ASIO options.

**Comment by mdias** [comment]
Glad you got it working! Enjoy! :)
