### ISSUE TITLE
Doesnt work. Focusrite solo 3rd gen

### ISSUE THREAD

**Issue by ZzZakko** [mdias/rs_asio#26]
Hi. Thanks for great job with this thing :) Sounds amazing, but it doesn't work for me somehow :(

I have "focusrite solo 3rd gen" set to 48kHz and 48 buffer.
Also in rocksmith.ini I have Win32UltraLowLatencyMode=1
Also I found some issues with this soundcard and tried to set driver to "Focusrite USB ASIO". Anyway, with or without there is nothing happens, even not matching drivers in log file. I have attached the log file. 
I even tried to unblock dll/ini files from release zip (win 10 is blocking files from internet). 
I saw in Reaper DAW that driver called Focusrite USB ASIO, same as other man in issue. 
I have steam version, do I need some "no cable" crack or what?

What am I doing wrong?

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4149167/RS_ASIO-log.txt)
sure its in .ini, not in .txt
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/4149171/RS_ASIO.txt)

Thanks in advice.

**Comment by mdias** [comment]
There's a "G" in the very beginning of your RS_ASIO.ini.
This is likely the issue :)

**Comment by ZzZakko** [comment]
Okay, I'm soooooooooooooooooo sorry :)
It was mute button in discord X_X
