### ISSUE TITLE
No audio with Irig HD2 (rocksmith 2014)

### ISSUE THREAD

**Issue by Farrel70** [mdias/rs_asio#260]
I'm having trouble getting my Irig Hd 2 working with Rocksmith. I can't seem to get the game to detect the device. 

**This is my RS_ASIO.ini**

>[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

>[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

>[Asio.Output]
Driver=iRig Device
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

>[Asio.Input.0]
Driver=iRig Device
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

>[Asio.Input.1]
Driver=iRig Device
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

>[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**This is my Log output:**

>0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
0.166 [INFO]  Patching CoCreateInstance
0.166 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.166 [INFO]  Patching call at 01C5AA85
0.166 [INFO]  Patching call at 01F03B6E
0.166 [INFO]  Patching call at 01F5C681
0.166 [INFO]  Patching call at 01FAEF75
0.166 [INFO]  Patching call at 01FAF40D
0.166 [INFO]  Patching PortAudio MarshalStreamComPointers
0.166 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.166 [INFO]  Patching call at 01F03059
0.166 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.166 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.166 [INFO]  Patching call at 01F0310E
0.167 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.167 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.167 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.167 [INFO]  AsioHelpers::FindDrivers
0.168 [INFO]    FL Studio ASIO
0.168 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Realtek ASIO
0.168 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.168 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: iRig Device
0.179 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.179 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.179 [INFO]    hr: 80070490
0.179 [INFO]    *ppEndpoint: 00000000
0.179 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.179 [INFO]    hr: 80070490
0.179 [INFO]    *ppEndpoint: 00000000
0.179 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.179 [INFO]    hr: S_OK
0.179 [INFO]    *ppDevices: 1764FBE0
2.882 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
2.882 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
2.882 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
2.882 [INFO]  AsioHelpers::FindDrivers
2.882 [INFO]    FL Studio ASIO
2.882 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Realtek ASIO
2.882 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
2.882 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: iRig Device
2.882 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
2.882 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
2.882 [INFO]    hr: 80070490
2.882 [INFO]    *ppEndpoint: 00000000
2.882 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
2.882 [INFO]    hr: 80070490
2.882 [INFO]    *ppEndpoint: 00000000
2.882 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
2.882 [INFO]    hr: S_OK
2.882 [INFO]    *ppDevices: 0EC4D4B8
2.887 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
278.553 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
278.690 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
There are two issues I can see

1. Your log isn't the result of running with the config you posted; log shows you trying to use `Realtek ASIO` for output, but your config says it should be using `iRig Device`.
2. You don't have any 32-bit `iRig Device` (or `Realtek ASIO` for that matter) ASIO drivers installed.

Please re-install your iRig device drivers and try again. You can see the drivers that RS_ASIO detects in the log here:
```
0.167 [INFO] AsioHelpers::FindDrivers
0.168 [INFO] FL Studio ASIO
```
