### ISSUE TITLE
help with configuring the ini (M-Audio m-track 2x2/ G PRO X Wireless headphones)

### ISSUE THREAD

**Issue by 3ShottyShane** [mdias/rs_asio#261]
I want to set my input as my 2nd input of my audio interface (m-audio track 2x2)

and my output as Logitech G pro x wireless headset

my log https://pastebin.com/pah8RfBx

my settings https://pastebin.com/YF6hgkEq

what am i doing wrong?

**Comment by mdias** [comment]
The first channel is channel 0, and the 2nd channel is channel 1.
You're trying to use the 3rd channel (`Channel=2`) which is a channel that does not exist in your interface, as stated in the log:

> WARNING: max requested channel 3 is beyond the max asio channels available 2

**Comment by mdias** [comment]
Closing as crossposted in [reddit](https://www.reddit.com/r/rocksmith/comments/smqtx0/i_need_help_configuring_rs_asio/).
