### ISSUE TITLE
Issues with Scarlett solo 3rd gen

### ISSUE THREAD

**Issue by Aarn70** [mdias/rs_asio#262]
Followed all the .ini guides for my Scarlett solo 3rd gen and I’m currently getting a “No audio output detected….please connect and restart rocksmith.”

My solo is my only audio output available along with copying the settings identically, would really appreciate some trouble shooting tips 

Thanks

**Comment by mdias** [comment]
Please post your RS_ASIO.ini and RS_ASIO-log.txt files.

**Comment by Aarn70** [comment]
RS ASIO

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

Rocksmith ini

[Audio]
EnableMicrophone=1
ExclusiveMode=0
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1280
ScreenHeight=720
Fullscreen=0
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=0
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1



Thanks for getting back so quickly appriciate the help

**Comment by Shadowfaith** [comment]
Hello,

I'm having the very same problem described above using the same audio interface (Scarlet Solo Gen3).

I found a reddit post previously describing how to fix the error (didn't work for me), however it was compatible for Windows 10 Pro 64-bit - I'm already using Win 11 64bit

Reddit link - my Ini file represents the changes described below, (I tried previously without these changes):
https://www.reddit.com/r/rocksmith/comments/evi0o2/rocksmith_and_scarlett_solo_gen_3_easy_thanks_to/

Ini file:

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

; [Asio.Input.0]
; Driver=Focusrite USB ASIO
; Channel=1
; EnableSoftwareEndpointVolumeControl=1
; EnableSoftwareMasterVolumeControl=1
; SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

Log

0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
0.330 [INFO]  Patching CoCreateInstance
0.330 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.330 [INFO]  Patching call at 01C5AA85
0.330 [INFO]  Patching call at 01F03B6E
0.330 [INFO]  Patching call at 01F5C681
0.330 [INFO]  Patching call at 01FAEF75
0.330 [INFO]  Patching call at 01FAF40D
0.330 [INFO]  Patching PortAudio MarshalStreamComPointers
0.330 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.330 [INFO]  Patching call at 01F03059
0.330 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.330 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.330 [INFO]  Patching call at 01F0310E
0.332 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.332 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.332 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.332 [INFO]  AsioHelpers::FindDrivers
0.332 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.332 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.332 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Focusrite USB ASIO
0.332 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.332 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.332 [INFO]    hr: 80070490
0.332 [INFO]    *ppEndpoint: 00000000
0.332 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.332 [INFO]    hr: 80070490
0.332 [INFO]    *ppEndpoint: 00000000
0.332 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.332 [INFO]    hr: S_OK
0.332 [INFO]    *ppDevices: 1649D570
4.779 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
4.779 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
4.779 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
4.779 [INFO]  AsioHelpers::FindDrivers
4.779 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
4.779 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
4.779 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Focusrite USB ASIO
4.779 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
4.779 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
4.779 [INFO]    hr: 80070490
4.779 [INFO]    *ppEndpoint: 00000000
4.779 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
4.779 [INFO]    hr: 80070490
4.779 [INFO]    *ppEndpoint: 00000000
4.779 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
4.779 [INFO]    hr: S_OK
4.779 [INFO]    *ppDevices: 1649A0D0
4.787 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
14.204 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
14.373 [INFO]   - Wrapper DLL unloaded

Please let me know

Thanks

**Comment by Shadowfaith** [comment]
PS:

I tried the following solutions as well without success:

https://github.com/mdias/rs_asio/issues/208

https://old.reddit.com/r/rocksmith/comments/egimx0/there_is_asio_support/?st=k4rervg3&sh=5f84bf21
