### ISSUE TITLE
Nux Mg-300 HELP

### ISSUE THREAD

**Issue by xRoMeRx** [mdias/rs_asio#264]
This effects pedal serves as an audio interface I've been trying to connect through this interface for several days but I can't. I have also tried to connect it with a normal cable but it does not work either. any help is good, thanks.

**Comment by mdias** [comment]
Follow a tutorial such as [this one](https://www.youtube.com/watch?v=R0yIGDYzJPI).

If it doesn't work, post your `RS_ASIO.ini` and `RS_ASIO-log.txt` file contents so we can check what's wrong.
