### ISSUE TITLE
ASIO input resampling

### ISSUE THREAD

**Issue by JakubPetriska** [mdias/rs_asio#267]
Hi to all,

first of all thanks for this amazing code and for all the support that's given here.

I have [Boss ME-25](https://www.boss.info/us/products/me-25/) guitar pedal which has a USB port but unfortunately runs at 44.1 kHz sampling frequency. I'd like to connect my guitar to PC and Rocksmith using this pedal but it's proven very difficult due to the mismatch in sampling rate. 

So I'm asking you for advice. Do you know about any software setup that would help me resample my device and connect it's ASIO output to the Rocksmith using rs_asio?

I tried Voicemeeter and VB-cable and Asio bridge and Hi-fi cable (all [VB-audio](https://vb-audio.com/Cable/index.htm) products) but unfortunately I was not able to make it work.

**Comment by mdias** [comment]
As far as I'm aware [RSMods](https://github.com/Lovrom8/RSMods) allows you to set a custom sample rate for the game, so in theory that should work.
RS ASIO itself does not support resampling and the game does ask only for 48kHz by default.

**Comment by JakubPetriska** [comment]
Thank you @mdias that would probably be the best solution. However I cannot find this in the README of the project. Do you know how this can be achieved with RSMods?

**Comment by JakubPetriska** [comment]
Oh thank you very much. It's quite hidden as it's not really mentioned an anywhere in the doc and can only be found in the code. Thank you again for the suggestion. I'll try this ASAP.

**Comment by JakubPetriska** [comment]
Unfortunately I was not able to make this work. The device is still not detected. I even tried enabling the direct input mode with RSMods and that did not accept the input either.

Do you or anybody else maybe happen to know any other way or software tool that I could use to make this work? Suggestions on how to configure Voicemeeter and the likes are also welcome.

**Comment by mdias** [comment]
> Unfortunately I was not able to make this work. The device is still not detected.
That's unfortunate.

> Suggestions on how to configure Voicemeeter and the likes are also welcome.

Try maybe using direct input with a voicemeeter virtual device that is set to 48000hz (on windows sound control panel) and then within voicemeeter send your interface's input to that device.
Not sure if this is going to work though, as Voicemeeter does reconfigure the inputs to run at the same clock as the master device you select, and since Rocksmith tries to use audio exclusivity there probably isn't going to be any resampling taking place.

I'm not aware of any software that would allow you to do resampling on the fly like that, sorry.

**Comment by JakubPetriska** [comment]
I think I will resort to purchasing one of the sound cards that were confirmed to work with rs_asio. I was not able to figure this out even after getting help from the VB-audio guys on their discord.

Anyway thank you for your time and knowledge.
