### ISSUE TITLE
Yamaha-Steinberg CI1 Works

### ISSUE THREAD

**Issue by kachunkachunk** [mdias/rs_asio#268]
Hey There,

Unsure what the exact/proper process is here to report a working interface - did you prefer a pull request on a modified readme file?

Anyway, I have a Yamaha/Steinberg CI1 working flawlessly - thank you so much for your work, by the way!
Everything below is just FYI for anyone shopping around or troubleshooting, for the most part. You can just say that it works, the only obvious trappings being that it defaults to 44.1kHz, and it might have pretty conservative buffer settings.

Guitar and headphones go into the CI1, mix is set to favor the guitar juuuust a bit so I can hear and be critical of what I'm doing. Not much input gain needed at all on the interface or in-game.

A huge benefit I'm coming to also realize is that I don't have to switch primary audio devices in Windows - it remains on some other device(s), so I can flip my headphones off and hear stuff out-of-game just fine. The game itself just sticks with using the ASIO hardware. It's overall perfect for my needs.

Just had to configure RS_ASIO to use the CI1 for input and output, then go. No appreciable latency. Using the following configs:
Rocksmith.ini:
```
LatencyBuffer=1
MaxOutputBufferSize=0 (default, also meaning automatic).
```

RS_ASIO.ini:
```
[Asio.Output]
Driver=Yamaha Steinberg USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Yamaha Steinberg USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

And commenting a bit more at length in case someone wants this info for a working config -
- In the Yamaha Steinberg USB Driver settings, the Sample Rate must be set to 48kHz (defaults at 44.1kHz, which will not work, as documented).
- In the driver, ASIO settings are happy/working fine in Low Latency mode, and 64 samples. You could probably go even lower, but at this point it's already at 4.4ms input latency, and 7.1ms output latency. It's good enough for me.
- System may not matter much here, but it's a Gigabyte Z97X-Gaming GT with an Intel 4790K (Haswell gen). Pretty dated, but no issues.
- These things need to be set obviously with the game open. You may need to unplug/replug the device if you can't hear anything too.

Other note:
I actually have a Realtone cable as well, but I never really figured out how to get it working as an input device with RS_ASIO in the mix. My initial issues were with output latency. Anyway, now I can do everything without the Realtone cable, and without much latency - no complaints!

**Comment by mdias** [comment]
Glad to hear it's working fine for you :)

> Unsure what the exact/proper process is here to report a working interface - did you prefer a pull request on a modified readme file?

Opening an issue like this is totally fine!

> I actually have a Realtone cable as well, but I never really figured out how to get it working as an input device with RS_ASIO in the mix.

You would set `EnableWasapiInputs=1` and then leave the Input sections with an empty driver name.
This allows Rocksmith to see your normal (wasapi) input devices as before you installed RS_ASIO, and disable the ASIO inputs, so if you have your RTC cable connected it will work (without hotplugging; must boot the game with it connected already)

Thank you for report! I've added the interface to the list 👍
