### ISSUE TITLE
GT-1 multi effects processor

### ISSUE THREAD

**Issue by DovahTheGod** [mdias/rs_asio#269]
when I use wasapi the ASIO isn't recognized as a realtone cable. i looked it up and yes the gt-1 doubles an audio interface

[RS_ASIO-log - Copy.txt](https://github.com/mdias/rs_asio/files/8356353/RS_ASIO-log.-.Copy.txt)

[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=GT-1
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
According to the log, it seems your interface doesn't support 48khz.

**Comment by DovahTheGod** [comment]
okay i see that now thank you i just ended up using my amp
