### ISSUE TITLE
Game freezes on quitting (Windowed Mode, ASIO4All V2, realtek on-board audio using Line-in)

### ISSUE THREAD

**Issue by sabzingeur** [mdias/rs_asio#27]
- RS ASIO latest version (0.3.1.1)
- Windowed Mode
- ASIO4All V2
- realtek on-board audio using Line-in

Please let me know if there's anything else I should provide to help fix this problem. (Currently I using Task Manager to close the game).

**Comment by mdias** [comment]
Please try [this new preview release](https://github.com/mdias/rs_asio/releases/tag/v0.4.0).

**Comment by Warneck** [comment]
Idk where to write it, but RS Asio works with my ZOOM U-44 just perfect. And guys you need to do some kind of "HOW TO" in more detailed way, cause its not obvious how to find your device name, channel name etc
