### ISSUE TITLE
No Sound when avrt.dll in folder

### ISSUE THREAD

**Issue by rakantarifky** [mdias/rs_asio#270]
Hello, I've try using latest RS_Asio. 
It used to be work on my Laptop ASUS A43L , but when I move on PC using ryzen 3 it won't work anymore. The game running normal, but have no sound. If I deleted the avrtl.dll file , It will going normal but I can't using my guitar. Is that any way to solve that?
Thanks

**Comment by rakantarifky** [comment]
Or maybe there is specifically runtime library from windows that I should install or update?

**Comment by rakantarifky** [comment]
nvm , already solve by run compability using windows 7

**Comment by Mortalcabra** [comment]
I seem to still have this problem but running the program in windows compatibility 7 doesn't work for me

**Comment by mdias** [comment]
That's strange. It shouldn't require it, but well.. if it works it works :)
