### ISSUE TITLE
No microphone sound detected with Steinberg UR22mkii

### ISSUE THREAD

**Issue by Steinad** [mdias/rs_asio#271]
RS not receiving guitar audio from Steinberg URmkii
 
I am using RS2014 launched from Steam.
Selected Yamaha Steinberg USB Driver with 48kHz Sample rate
Standard Mode and 128 Samples 

Windows 10 Sound Config:
Playback:
2channel 24Bit 48000Hz Studio Quality Greyed out
Allowing applications to take exclusive control of this device
Giving exclusive mode applications priority
Recording:
2channel 24Bit 48000Hz Studio Quality Greyed out
Allowing applications to take exclusive control of this device
Giving exclusive mode applications priority

RS_ASIO.ini

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Yamaha Steinberg USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
;Driver=Yamaha Steinberg USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Yamaha Steinberg USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

Rocksmith.ini

[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1280
ScreenHeight=720
Fullscreen=2
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1

RS_ASIO-log
0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
0.151 [INFO]  Patching CoCreateInstance
0.151 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.151 [INFO]  Patching call at 01C5AA85
0.151 [INFO]  Patching call at 01F03B6E
0.151 [INFO]  Patching call at 01F5C681
0.151 [INFO]  Patching call at 01FAEF75
0.151 [INFO]  Patching call at 01FAF40D
0.151 [INFO]  Patching PortAudio MarshalStreamComPointers
0.151 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.151 [INFO]  Patching call at 01F03059
0.151 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.151 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.151 [INFO]  Patching call at 01F0310E
0.152 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.152 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.152 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.152 [INFO]  AsioHelpers::FindDrivers
0.152 [INFO]    Yamaha Steinberg USB ASIO
0.152 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Yamaha Steinberg USB ASIO
0.152 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.557 [INFO]    ASIO input channels info:
0.557 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: UR22mkII Input 1
0.557 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: UR22mkII Input 2
0.557 [INFO]    ASIO output channels info:
0.557 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: UR22mkII Output 1/L
0.557 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: UR22mkII Output 2/R
0.557 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.557 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Yamaha Steinberg USB ASIO
0.557 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.557 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.557 [INFO]    hr: S_OK
0.557 [INFO]    *ppEndpoint: 1617E4C8
0.557 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.557 [INFO]    hr: S_OK
0.557 [INFO]    *ppEndpoint: 1617E678
0.557 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.557 [INFO]    hr: S_OK
0.557 [INFO]    *ppDevices: 0D797A30
0.557 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.557 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.557 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.557 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.557 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.557 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.557 [INFO]    *pDataFlow: eRender
0.557 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.557 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetCount
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.557 [INFO]  {ASIO IN 1} DebugWrapperEndpoint::GetDataFlow
0.557 [INFO]    *pDataFlow: eCapture
0.557 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.557 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.561 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.561 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.561 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.561 [ERROR]    failed to initialize asio driver with requested format
0.561 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.561 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.561 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.561 [ERROR]    failed to initialize asio driver with requested format
0.561 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.561 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.561 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.561 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
0.561 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
0.561 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 2ms (128 frames)
0.561 [INFO]  AsioSharedHost::Setup - startCount: 0
0.561 [INFO]    post output ready: 1
0.561 [INFO]    ASIOBufferSize - min: 128 max: 128 preferred: 128 granularity: 0
0.561 [INFO]    Creating ASIO buffers (2 out, 2 in)...
0.761 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
0.761 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.761 [INFO]    *pNumBufferFrames: 128
0.761 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.761 [INFO]    latency: 7ms
0.761 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.761 [INFO]    returning render client
0.762 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.763 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.763 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.763 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.763 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 128
0.763 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 128
0.763 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.763 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.763 [INFO]  AsioSharedHost::Start - startCount: 0
0.763 [INFO]    Starting ASIO stream...
0.763 [INFO]  Yamaha Steinberg USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.763 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 128
0.763 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 128
0.763 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.766 [INFO]  Yamaha Steinberg USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.766 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 128
0.766 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 128
0.766 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.810 [INFO]  Yamaha Steinberg USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
26.973 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
26.973 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.973 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.973 [ERROR]    failed to initialize asio driver with requested format
26.973 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.973 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.973 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.973 [ERROR]    failed to initialize asio driver with requested format
26.973 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.973 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.973 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.973 [ERROR]    failed to initialize asio driver with requested format
26.973 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.973 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.973 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
26.973 [INFO]  {ASIO IN 1} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
26.973 [INFO]  {ASIO IN 1} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
26.973 [INFO]  {ASIO IN 1} RSAsioAudioClient::Initialize - actual buffer duration: 2ms (128 frames)
26.973 [INFO]  AsioSharedHost::Setup - startCount: 1
26.973 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioEndpointVolume dwClsCtx: 1
26.973 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
26.973 [INFO]    *pNumBufferFrames: 128
26.973 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
26.973 [INFO]    latency: 6ms
26.973 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioCaptureClient
26.973 [INFO]    returning capture client
26.973 [INFO]  Patched_PortAudio_MarshalStreamComPointers
26.974 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
26.974 [INFO]  {ASIO IN 1} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.974 [INFO]  {ASIO IN 1} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.974 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.974 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
26.974 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Start
26.974 [INFO]  AsioSharedHost::Start - startCount: 1
26.974 [INFO]  {ASIO IN 1} RSAsioAudioClient::OnAsioBufferSwitch - buffer underrun detected; still processing last buffer...
26.974 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.17
26.976 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
26.976 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 128
26.976 [INFO]  {ASIO IN 1} RSAsioAudioClient::SwapBuffers
26.979 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
26.979 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 128
26.979 [INFO]  {ASIO IN 1} RSAsioAudioClient::SwapBuffers
26.982 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
26.982 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 128
68.278 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Stop
68.278 [INFO]  AsioSharedHost::Stop - startCount: 2
68.278 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
68.279 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
68.279 [INFO]  AsioSharedHost::Stop - startCount: 1
68.279 [INFO]  AsioSharedHost::Stop  stopping ASIO stream
68.437 [INFO]   - Wrapper DLL unloaded

I am using the line 2 as instructed with a high level (I can see the signal peaking). Also used line 1 but the game can't get any sound from the guitar. I suppose the issue is that I am sending 24bit sound instead 16, but I am no expert. Tried to check if it could be reduced but couldn't find any way. Any help would be greatly appreciated. Many thanks,

**Comment by mdias** [comment]
Both 16 and 24 bit will work fine.
Also everything looks fine on your config and log.

If your guitar is connected to the right port it should work fine. Make sure you go through the guitar volume calibration ingame just in case.

If that still doesn't work, try any other 32-bit ASIO enabled app to ensure your ASIO drivers and device are working correctly.

Since you only mention that guitar input isn't heard, I assume the other game output sounds are working fine?

**Comment by Steinad** [comment]
> Both 16 and 24 bit will work fine. Also everything looks fine on your config and log.
> 
> If your guitar is connected to the right port it should work fine. Make sure you go through the guitar volume calibration ingame just in case.
> 
> If that still doesn't work, try any other 32-bit ASIO enabled app to ensure your ASIO drivers and device are working correctly.
> 
> Since you only mention that guitar input isn't heard, I assume the other game output sounds are working fine?

Hi, thanks for answering. I just notice what was wrong! The USB port I was using. I was using one of the blue ones, 3.0, instead the 2.0. Hope this helps to other users.

I am so happy it is working! Thanks a million for all the hard work you put into this!

**Comment by mdias** [comment]
Thank you for reporting back!
Glad to hear you have it working. Have fun! 👍

**Comment by Discobrick** [comment]
> 
> Hi, thanks for answering. I just noticed what was wrong! The USB port I was using. I was using one of the blue ones, 3.0, instead the 2.0. Hope this helps to other users.
> 
> I am so happy it is working! Thanks a million for all the hard work you put into this!
Hey there @Steinad I wanted to ask if you are using the Yamaha AG03 interface and if there's anything else that you did, right now I'm having a similar issue that I'm not getting any sound from the input. 

I tried your settings and all USB 2.0 ports but still no sound.
