### ISSUE TITLE
Multiple ASIO Devices

### ISSUE THREAD

**Issue by RREXXY** [mdias/rs_asio#276]
Using guitar with Scarlet 2i2 (2nd Gen) and it works fine when using the same interface as the output device
When I set the output device to my Creative Sound Blaster G6 it stops working all together.
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/8694711/RS_ASIO-log.txt)

INI Settings

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio.Output]
Driver=Creative Sound Blaster ASIO Device
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
Your Creative ASIO driver is reporting some huge ASIO buffer sizes:
> 0.532 [INFO]    ASIOBufferSize - min: 2400 max: 2400 preferred: 2400 granularity: 0

If your Create ASIO driver has a control panel, try using it to lower the buffer size to 128 or so if possible. If not, I suggest using the Wasapi output instead for that card as it's ASIO buffer size is too big to make sense using it anyway.
