### ISSUE TITLE
 focusrite scarlett solo 3rd gen real tune cable not found

### ISSUE THREAD

**Issue by scarled** [mdias/rs_asio#277]
Hi guys, i have a focusrite scarlett solo 3rd gen and i try to connect it to Rocksmth (mac os M1).
This is the RS_ASIO.init conf
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100


[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
;Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```
When i open the game it says that "It sounds like your cable is unplugged. Connect a Rocksmith Real Tone Cable".
I dont have a  real tone cable, but i try to add RealToneCableOnly=1 in Rocksmith.init and to create an  aggregate audio divice named "Rocksmith USB Cable Adapter" but dosent work :(.
Thx a lot :D.

**Comment by scarled** [comment]
I find a mac plugin and now i have the direct connect option, but i have no input. I think its because the guitar in in input 2, no   in the input 1

**Comment by mdias** [comment]
I'm afraid RS ASIO works on Windows only.
The files you put on your Mac computer are probably not doing anything at all.

You are most likely correct regarding the reason you hear no input. Since I'm not a Mac user I won't be able to help you directly, however I suggest you look at this [reddit post](https://www.reddit.com/r/rocksmith/comments/mgpwgq/mac_how_to_use_focusrite_solo_with_big_sur/gsuf99p/?context=3).

**Comment by scarled** [comment]
Hi mdias, thx for you hel, i readed the reddit post and i found the solution, in Rocksmith.init file, there was an MonoToStereoChannel=0 instead of MonoToStereoChannel=1 and it works. The only problem is that the sound is not from the interface or headphones, is from laptop
