### ISSUE TITLE
RTC how to make it work after installing asio

### ISSUE THREAD

**Issue by krisring** [mdias/rs_asio#278]
I know this is counterintuitive - but I need a way to turn off asio use in the game or somehow configure the RTC to work with asio.

After getting the game to work on a rather troublesome PC the user of said PC wants to use the RTC but can't as the asio being installed makes the game not see the cable despite the system seeing it just fine. 

If I'm missing some setting that I can do to make this happen it would be very much appreciated if someone can point that out, thank you!

**Comment by mdias** [comment]
If you just want to have the RTC visible to Rocksmith while using ASIO too, you can do so by setting `EnableWasapiInputs=1`, however you have to have the RTC cable already connected when you boot the game.

RS ASIO doesn't really have a config to be disabled, however if you rename the `avrt.dll` file to something else like `_avrt.dll` it will be enough to completely disable RS ASIO.

**Comment by krisring** [comment]
Wonderful I very much appreciate this information!
