### ISSUE TITLE
Rs_Asio do not detect ReRoute driver

### ISSUE THREAD

**Issue by Charliesaya** [mdias/rs_asio#279]
Can you help me please ? i have been trying to catch rocksmith game sound and use it on reaper to stream but i can't get ReaRoute Driver, i used to do this easily but i erased my pc.

0.702 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.705 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.705 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.705 [INFO]  AsioHelpers::FindDrivers
0.706 [INFO]    M-Audio M-Track Solo and Duo ASIO
0.706 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ReaRoute ASIO
0.706 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.706 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: M-Audio M-Track Solo and Duo ASIO

**Comment by mdias** [comment]
RS ASIO is not detecting any ASIO driver with the name `ReaRoute ASIO`.

If I remember correctly ReaRoute is part of the Reaper DAW, so I'm guessing you haven't installed it.

**Comment by Charliesaya** [comment]
yes i did, and thanks for replaying, i solved it already i just needed to install also the 32 bit version of Reaper now everything works fine !.
