### ISSUE TITLE
Cannot calibrate (make noise) using ASIO Juli@ driver

### ISSUE THREAD

**Issue by Andric** [mdias/rs_asio#28]
It works but the volume never gets high enough to finish setup. 48000 256 buffer - as I use in BIAS Fx

rs-asio.ini
[Config]
EnableWasapi=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO 2.0 - ESI Juli@
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO 2.0 - ESI Juli@
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

rocksmith.ini
[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=2
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1

digital interface link: https://www.esi-audio.com/products/juliaxte/

**Comment by mdias** [comment]
Increase the `SoftwareMasterVolumePercent` of your `Asio.Input.0` to something like 200 or even 400.
This is software gain, so it can be prone to clipping if set too high, however the ingame calibrator should detect it and internally fix the ingame gain for it.

**Comment by Andric** [comment]
this worked thanks - opening a new issue for no output.
