### ISSUE TITLE
Not an issue but rather how I got it to work flawlessly with a Presonus studio 24C no delay

### ISSUE THREAD

**Issue by jacqueshenning** [mdias/rs_asio#280]
For the Presonus Studio 24c

First install "PreSonus_UniversalControl", downloaded directly from the Presonus website.

Optional:
To add MIC support add the driver info to i.e.:
[Asio.Input.Mic]
Driver=Studio USB ASIO Driver
And on the first input make it:
Channel=0

Then below is the RS_ASIO.ini config using the second input for electric guitar.

_To note: I made no other changes only installed the driver and setup the below config changes..._

###################
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=host
CustomBufferSize=

[Asio.Output]
Driver=Studio USB ASIO Driver
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.2]
Driver=Studio USB ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
###################

Hope this helps someone!

Cheers...

**Comment by mdias** [comment]
Thanks! I've linked it to the interface entry on the readme 👍

**Comment by UglyBassPlayer** [comment]
> For the Presonus Studio 24c
> First install "PreSonus_UniversalControl", downloaded directly from the Presonus website....

Yo man, I made an account just to thank you.  I was tooling around for hours trying to make it work and you saved my ass.  It works PERFECT.  

Cheers
