### ISSUE TITLE
ASIO communication cuts out intermittently

### ISSUE THREAD

**Issue by kgfeuerherm** [mdias/rs_asio#281]
I'm not sure this is a new problem, but in the past I may have had the occasional communication drop; but after a long pause in playing RS, when I tried it yesterday, sound dropped, and as far as I can see, picking up the input as well.

This happened on the opening screen or later when playing. In most cases, once it dropped, it stayed that way and the game became unplayable. Very occasionally, it would come back after a moment or two but not often.

I've attached the log file in case it helps.

I'm on Windows 11, btw and using a Steinbery UR22 MkII (which works fine otherwise). And I did replace the DLLs just in case, but they are the same version in any case.

Let me know if there's any other information I can provide.

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/8900589/RS_ASIO-log.txt)
.

**Comment by kgfeuerherm** [comment]
RIght, here's what I have so far.

1. The buffer size in Rocksmith.ini is set to 0, so I wasn't setting it to 512 myself,
2. If I set it manually, the lowest figure which works is in fact 512. Anything less (even just 32 bytes) and there's no sound at all. So I guess I'm stuck with 512. . (It would help btw to clarify that one should be looking at this file and not your configuratrion file, where I thought I had to replace the line with '=driver' with a value, which so far as I can see had no effect.)
4. As for the latency setting, it's at 4. Anything lower than that and the sound crackles, so I think that's the end of that tune too. Ini file attached for reference.
5. I was using an electronic switch since the Steinberg is used by this PC and by a Mac depending on what I'm doing; as I said, works in every other situation. But I disconnected it and plugged the Steinberg directly into a front USB on the PC and the problem seems to have disappeared. This *suggests* that it was a hardware, rather than software, problem.
6. This morning i tentatively put it back into the electronic switch, but a different port, seems to work....

So my guess right now is that this is a hardware issue with the switch. All I can do, really, is to continue to test that hypothesis if it happens again but taking it out of the circuit. BTW so far as I can tell alt-tab has no effect (which would make sense if that's the problem).

**Comment by mdias** [comment]
> The buffer size in Rocksmith.ini is set to 0, so I wasn't setting it to 512 myself,

This would be set in RS_ASIO.ini, not in Rocksmith.ini. It would look like this:
```
BufferSizeMode=custom
CustomBufferSize=128
```

> So I guess I'm stuck with 512.

It's very possible that you can only change this through some control panel that is installed along with your interface's audio driver.
When `BufferSizeMode=Driver` this means that RS ASIO will use the buffer setting that you set on that control panel. But even if you use `BufferSizeMode=Custom` it might be possible that your driver forces RS ASIO to use the Driver setting instead of the custom setting.

Your problem is indeed unlikely to come from RS ASIO, but you should still try to have your buffer size never above 256; you're really getting a lot of latency with a 512 buffer size, although it's possible that you don't notice it much (varies a lot per person).

**Comment by kgfeuerherm** [comment]
Aha. This panel you speak of is not directly documented, I found it in a thread where someone else was wondering about it.

It’s here: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\yusb_cp.exe

I set the buffer ‘samples’ to 256 with no problem, then 128, again with no problem. New log file attached. Should I be pushing it any further, like 64? (Assuming, of course, that I’m doing the right thing!!)

Thanks for all the help!

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/8923591/RS_ASIO-log.txt)

**Comment by mdias** [comment]
People usually try to go as low as possible, however don't forget it's diminishing returns.
512 is about 10ms of latency just on the buffers, but 128 is already 2.5ms.

Going lower will get you a very tiny improvement at a higher CPU cost, so you may start to hear some crackling in audio. 64 could still be doable, but 128 is definitely already quiet good.

Log looks good! It shows 128 there being used :)

**Comment by kgfeuerherm** [comment]
Great, thanks for the feedback!! I think I can leave it be now; “if it ain’t broke…” :)

I’ve appreciated this, and now there’s a log of detail if anyone else experiences this. Best wishes!

**Comment by kgfeuerherm** [comment]
Thanks, I’ll make the change; no idea why it would be weird I just changed what I thought I needed to.

Alt-tab? I can try that. The problem is pretty frequent, though. Something must not be right somewhere. I also checked the Steinberg drivers and firmware since posting, they’re up-to-date.

I’ll keep you posted. Thanks for the quick response!
