### ISSUE TITLE
Arturia Minifuse 2 works with RS_ASIO

### ISSUE THREAD

**Issue by spiriapbergeron** [mdias/rs_asio#282]
(.... and I suppose, Minifuse 1)

My Windows machine was set to 44 khz by default, so I set up my sound devices via Windows to 48 khz

- In the minifuse control center, I set buffer size 64

- In RS_ASIO.INI, I set: Driver=MiniFuse ASIO Driver    
  (for output, and input 1 & 2)

**Comment by mdias** [comment]
Thanks. Added to the list 👍

**Comment by cesarnuness** [comment]
How am I supposed to use this?
Why only Minifuse doesn't have the full code for us to just paste :(

**Comment by vers-2071** [comment]
[RS_ASIO_INI.zip](https://github.com/user-attachments/files/23915142/RS_ASIO_INI.zip)

Here is the working config:

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=128

[Asio.Output]
Driver=MiniFuse ASIO Driver
BaseChannel=
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=MiniFuse ASIO Driver
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=MiniFuse ASIO Driver
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=MiniFuse ASIO Driver
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
