### ISSUE TITLE
Selecting output on startup

### ISSUE THREAD

**Issue by spiriapbergeron** [mdias/rs_asio#284]
I have my steam computer hooked up to my TV through my home theater system.  My Non-ASIO audio goes through to the HDMI cable to the HT.

So when I want to play RS on the HT speakers, I simply set enablewasapioutput to 1 and all is good.

But when I want to play on my headphones, I have to plug them on my regular amplifier, which is extra inconvenient because the plug is far. I would much rather plug my headphones into the audio interface.

So every time I want to change this, I have to go back to the INI file, disable wasapi output, set the name of my DI ASIO driver in the output section.

It's a bit of a pain.

Yes yes, I could have a two separate INI files with various configurations in them, and then have a desktop batch file that copies the one I select over RS_ASIO.ini before starting the game, but I'd much rather have a messagebox that pops up that lets me choose this on startup after the RS_ASIO.ini file was parsed. 

Of course I realize not what all users want to be bothered with a popup on startup, so why not something like this?

in the RS_ASIO.ini file, add another possible value for enablewasapioutput:

; if this value is set to -1, then rs_asio will pop up and let the user choose
enablewasapioutput=-1

Then a simple messagebox appears and displays something like this:

"Select audio output"
"Use ASIO for audio output?  (click NO for wasapi)"
[YES]   [NO]

And then you grab the return value from ::MessageBox and set one mode or the other.

**Comment by mdias** [comment]
I liked this idea and it was fairly easy to implement. I have made a [new release](https://github.com/mdias/rs_asio/releases/tag/v0.5.8) with this feature.
Please report back if it works fine for your use case.

**Comment by spiriapbergeron** [comment]
Thank you!
________________________________

**Comment by spiriapbergeron** [comment]
Hum. I noticed that while the 0.5.8 release was issued a few hours ago, the last commit was... about 9 days ago. 

I downloaded the 0.5.8 source, and since I already had 0.5.7 I diff'd them using Araxis merge and I see no difference.

Did you forget to commit/push the changes?

**Comment by mdias** [comment]
Sorry! The release I created had the right binaries but I had forgotten to push the new source.
Should be fixed now :)

**Comment by spiriapbergeron** [comment]
Not sure I confirmed but all is good!

Sent from my iPhone

On Aug 4, 2022, at 7:18 PM, Micael Dias ***@***.***> wrote:

﻿

Closed #284<https://github.com/mdias/rs_asio/issues/284> as completed.
