### ISSUE TITLE
Focusrite Solo 2i2 Buffer size, distortion, crackling.

### ISSUE THREAD

**Issue by outdatedx** [mdias/rs_asio#286]
I have almost tried every single number for the buffer size I can get rid of the distortion, crackling.

> # RS ASIO Log #
0.000 [INFO]   - Wrapper DLL loaded (v0.5.8)
0.001 [INFO]  PatchOriginalCode
0.765 [INFO]  Patching CoCreateInstance
0.765 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.765 [INFO]  Patching call at 01C5AA85
0.766 [INFO]  Patching call at 01F03B6E
0.766 [INFO]  Patching call at 01F5C681
0.766 [INFO]  Patching call at 01FAEF75
0.766 [INFO]  Patching call at 01FAF40D
0.766 [INFO]  Patching PortAudio MarshalStreamComPointers
0.766 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.766 [INFO]  Patching call at 01F03059
0.766 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.766 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.766 [INFO]  Patching call at 01F0310E
1.341 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.986 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.483 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.920 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
3.355 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
3.807 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
4.213 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
4.598 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
4.951 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
5.298 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
5.631 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
5.975 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
7.338 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
7.338 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
7.341 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
7.341 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
7.341 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
7.341 [INFO]  AsioHelpers::FindDrivers
7.341 [INFO]    ASIO4ALL v2
7.342 [INFO]    Focusrite Thunderbolt ASIO
7.342 [INFO]    Focusrite USB ASIO
7.342 [INFO]    Realtek ASIO
7.342 [INFO]    Voicemeeter AUX Virtual ASIO
7.343 [INFO]    Voicemeeter Insert Virtual ASIO
7.343 [INFO]    Voicemeeter Virtual ASIO

># RS ASIO INI
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

[Asio.Output]
Driver=Voicemeeter AUX Virtual ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

># Rocksmith INI # 
[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=Driver=Voicemeeter AUX Virtual ASIO
ForceWDM=0
ForceDirectXSink=1
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=1
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1920
ScreenHeight=1080
Fullscreen=0
VisualQuality=0
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=0
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1

**Comment by mdias** [comment]
Does it work fine when outputting to `Focusrite USB ASIO` too?

Also, your log is massively trimmed and there's basically no useful information in there that could help track the issue down. However I would start by assuming the problem is in the way you have voicemeeter configured.-

**Comment by outdatedx** [comment]
> Does it work fine when outputting to `Focusrite USB ASIO` too?
> 
> Also, your log is massively trimmed and there's basically no useful information in there that could help track the issue down. However I would start by assuming the problem is in the way you have voicemeeter configured.

yeah the output works fine there is crackle doe.
and Ik the log is trimmed my bad for that here is the full version

https://drive.google.com/file/d/1LspCA2za2N4-3twfTqWAVC_QmwKeJm5b/view?usp=sharing

I mean im not sure about the voicemeter thing cause Im not a audiophile really

**Comment by mdias** [comment]
That log shows you're using a 128 frame buffer size.
Please check the [Known Issues section on the readme](https://github.com/mdias/rs_asio#known-issues).

**Comment by outdatedx** [comment]
> That log shows you're using a 128 frame buffer size. Please check the [Known Issues section on the readme](https://github.com/mdias/rs_asio#known-issues).

well you can see the RS asio config, can it be caused because of the ASIO4ALL?

**Comment by outdatedx** [comment]
wait i think I figured it out
![image](https://user-images.githubusercontent.com/38858226/175867377-46e0150b-f212-4722-baaa-602b2b9a3d2b.png)
I think this is it in the voicemeter system settings

**Comment by outdatedx** [comment]
Yeah I fixed it I think thanks for the help.


Solution: **Change your Voicemeter ASIO Buffer in the system settings.**
