### ISSUE TITLE
Juli@ card - output problems

### ISSUE THREAD

**Issue by Andric** [mdias/rs_asio#29]
posting the log. Seems to fail on creating output:
0.000 [INFO]   - Wrapper DLL loaded
0.000 [INFO]  PatchOriginalCode
0.000 [INFO]  Patching CoCreateInstance
0.149 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.149 [INFO]  Patching call at 01C5AA85
0.149 [INFO]  Patching call at 01F03B6E
0.149 [INFO]  Patching call at 01F5C681
0.149 [INFO]  Patching call at 01FAEF75
0.149 [INFO]  Patching call at 01FAF40D
0.149 [INFO]  Patching PortAudio MarshalStreamComPointers
0.299 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.299 [INFO]  Patching call at 01F03059
0.299 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.449 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.449 [INFO]  Patching call at 01F0310E
0.450 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.454 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.454 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.454 [INFO]  AsioHelpers::FindDrivers
0.455 [INFO]    ASIO 2.0 - ESI Juli@
0.455 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO 2.0 - ESI Juli@
0.455 [INFO]  Creating AsioSharedHost - dll: C:\Windows\system32\JulaASIO32.dll
0.475 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.475 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO 2.0 - ESI Juli@
0.475 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.475 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.475 [INFO]    hr: 0
0.475 [INFO]    *ppEndpoint: 1C8C1128
0.475 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.475 [INFO]    hr: 0
0.475 [INFO]    *ppEndpoint: 1C8BF3B8
0.475 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.475 [INFO]    hr: 0
0.475 [INFO]    *ppDevices: 196CEE20
0.475 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.475 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.475 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.475 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.475 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.475 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.475 [INFO]    *pDataFlow: eRender
0.475 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.475 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.475 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.475 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.475 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.475 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.475 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.475 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.475 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.475 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.475 [INFO]    *pDataFlow: eCapture
0.475 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.475 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.533 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.533 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.533 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.533 [ERROR]    failed to initialize asio driver with requested format
0.533 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.533 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.533 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.533 [ERROR]    failed to initialize asio driver with requested format
0.533 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.533 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.533 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.533 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
0.533 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
0.533 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 5ms (256 frames)
0.533 [INFO]  AsioSharedHost::Start - startCount: 0
0.533 [INFO]    ASIO input channels info:
0.533 [INFO]      0 - active: 1, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Juli@ 1/2:L
0.533 [INFO]      1 - active: 1, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Juli@ 1/2:R
0.533 [INFO]      2 - active: 1, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Juli@ 3/4:L
0.533 [INFO]      3 - active: 1, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Juli@ 3/4:R
0.533 [INFO]    ASIO output channels info:
0.533 [INFO]      0 - active: 1, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Juli@ 1/2:L
0.533 [INFO]      1 - active: 1, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Juli@ 1/2:R
0.533 [INFO]      2 - active: 1, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Juli@ 3/4:L
0.533 [INFO]      3 - active: 1, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Juli@ 3/4:R
0.533 [INFO]    ASIOBufferSize - min: 256 max: 256 preferred: 256 granularity: 0
0.533 [INFO]    Creating ASIO buffers (4 out, 4 in)...
0.533 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 2 value: 0 | returning: 1
0.533 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 1
0.533 [INFO]    Starting ASIO stream...
0.553 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.553 [INFO]    *pNumBufferFrames: 256
0.553 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.553 [INFO]    latency: 5ms
0.554 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.554 [INFO]    returning render client
0.554 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.555 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.555 [INFO]    marshalling output device
0.555 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.555 [INFO]    unmarshalling output device
0.555 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.555 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
0.555 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
0.555 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.555 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.558 [INFO]  Juli@ - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.558 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
0.558 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
0.558 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.564 [INFO]  Juli@ - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.564 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
0.564 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
0.564 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.569 [INFO]  Juli@ - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
26.734 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.734 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.734 [ERROR]    failed to initialize asio driver with requested format
26.734 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.734 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.734 [ERROR]    failed to initialize asio driver with requested format
26.734 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.734 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.734 [ERROR]    failed to initialize asio driver with requested format
26.734 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
26.734 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
26.734 [INFO]  {ASIO IN 0} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
26.734 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - actual buffer duration: 5ms (256 frames)
26.734 [INFO]  AsioSharedHost::Start - startCount: 1
26.734 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioEndpointVolume dwClsCtx: 1
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
26.734 [INFO]    *pNumBufferFrames: 256
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
26.734 [INFO]    latency: 5ms
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioCaptureClient
26.734 [INFO]    returning capture client
26.734 [INFO]  Patched_PortAudio_MarshalStreamComPointers
26.734 [INFO]    marshalling input device
26.734 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
26.734 [INFO]    unmarshalling input device
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
26.734 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Start
26.735 [INFO]  {ASIO IN 0} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.17
26.740 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.740 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 256
26.740 [INFO]  {ASIO IN 0} RSAsioAudioClient::SwapBuffers
26.745 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.745 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 256
26.745 [INFO]  {ASIO IN 0} RSAsioAudioClient::SwapBuffers
26.750 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.750 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 256
213.296 [INFO]  {ASIO IN 0} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 1
365.081 [INFO]  {ASIO IN 0} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.17
434.291 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Stop
434.291 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
434.292 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
434.292 [INFO]  AsioSharedHost::Stop - startCount: 2
434.475 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
Please try [this new preview release](https://github.com/mdias/rs_asio/releases/tag/v0.4.0).

**Comment by Andric** [comment]
thanks! happy to report it's to be working fine now! Will report back if any other issues arise
