### ISSUE TITLE
Behringer XR18 no audio?

### ISSUE THREAD

**Issue by Keribi** [mdias/rs_asio#292]
Cant seem to figure this out.  I get a "No audio output device" error on RS startup.  Could this be a channel numbering issue? the XR18 has 18 and I am not sure what RS Audio wants to see.  0 -17 or 1-18 for channels?  There is a couple errors in the RS audio log.  Looks like its not seeing the interface.  I am using Win 11 and the RTC works fine.  Would like to get this to work, Thanks.
![Log](https://user-images.githubusercontent.com/61951736/179560138-ea408bc8-3bb4-4c02-8ad5-a23d8f8f6d83.png)
![ini](https://user-images.githubusercontent.com/61951736/179560150-26447530-cb3e-4e33-bc39-be479a837529.png)

**Comment by mdias** [comment]
It's not about the number of inputs/outputs, I also use a 18-channel interface and it works just fine. This interface is also reported to work fine [here](https://github.com/mdias/rs_asio/issues/72).

However, looking at the log, it seems that the driver is failing to load/initialize.
Check if you have the newest drivers and if some other 32-bit application is working fine with ASIO.

**Comment by mdias** [comment]
Those format errors are normal as the game negotiates a proper format with the driver.

Unless specified differently in `Rocksmith.ini` (not RS_ASIO.ini) the game will try to use the default output device set in windows. In the case of using RS_ASIO it will only see the output you provided in RS_ASIO.ini unless you also enabled the WASAPI outputs.
