### ISSUE TITLE
Quad Cortex and Antelope Audio Zen Tour Interface Intermittent static fix!

### ISSUE THREAD

**Issue by DammitEric** [mdias/rs_asio#294]
Hello!  I first wanna say I'm super hype to get started trying this out as it makes my life infintely easier to just play through my interface or Neural DSP!  That said, I've tested for about a few hours and if for some strange reason someone uses what I use, this definitely works with some config changes.

[RS_ASIO.ini](https://pastebin.com/nM3AXfA3)

Signal chain is as follows
NeuralDSP Quad Cortex has a USB to computer
Antelope Audio Zen Tour also has a USB to computer
They're routed together with a 1/4" from the outs of the QC to the guitar ins on the Zen Tour.  Adam A7x monitors are plugged into the Zen tour through the monitor outs.  Guitar is routed directly to the QC.  If I need to use headphones I would switch to a Schiit Jotunheim 2(routed through the DAC to computer, so separate signal chain) with some Focal Celestee's but that's bonus points if I needed to change the output :).  

Also if platform matters for anyone, Windows 11 brand new build, AMD 5950x with a 6900xt card, 32gb of 4000mhz RAM and a 2tb WD SN850 nvme(that's what RS 2014 is installed on, backup drive is a 1tb SN850).  

This works if you switch to `BufferSizeMode=host` in the RS_ASIO.ini.  If you try with just the driver, no matter the latency settings, after about 30m-1hr of playtime the guitar tone will become staticy and robotic, requiring a reboot(note that JUST the guitar tone distorts, the music and announcer remain fine).  The logs don't really stand out with any issue, I checked and in the ERROR layer and didn't note anything unusual, but so far when set to host I have yet to replicate the robotic sound.  In terms of ASIO, I'm admittedly not the best at understanding which would be confirmed "working" but it sounds like both work without issue.  I'd need to check just the interface to see if it has any issues if the guitar is plugged directly into it, but likely not and likely should work without issue.  

I'll run some further tests but it looks like after about 2-3 hours of play it's fine with these settings.  I will try to adjust RS Latency as well, it's currently at "3" but I have not tested lowering it after changing the bufferSizeMode to 'host'.

**Comment by DammitEric** [comment]
Wanted to followup as I experimented today for another few hours.  2 hours later and can confirm with the latency settings at 3, zero issues when BufferSizeMode=host.  Also, I tried setting the RS latency settings to 1 but immediate robotic/static.  So, I tried 2 for another 2 hours and zero issues so far, but 3 has the most rigorous testing so far, I'll likely just continue trying to break it while set to 3, but good to know this works flawlessly for the Antelope Audio interfaces as well as the NeuralDSP Quad Cortex!

**Comment by mdias** [comment]
Thank you for the extensive testing and report.
I've added both interfaces to the list 👍

**Comment by DammitEric** [comment]
I've largely not had issues with note detection with this setup, but I'm using 2 different devices.  For sound, I'm routing to my Antelope Audio Zen Tour, for guitar, I'm using my Quad Cortex which is connected directly through USB, and my QC is also routed through my Zen Tour.   I did this so I could play guitar outside of RockSmith and get access to my monitors connected to the interface.  The only thing I had issues with was needing to set the BufferMode to host, but otherwise no issues!

**Comment by Corno1** [comment]
Ah ok I will try that, thank you for the fast response :)

**Comment by Corno1** [comment]
So I hooked it up like you said and it works way better as you said so I was curious why and think got an answer on this site from neural dsp. 
https://support.neuraldsp.com/help/hardware-daw-monitoring

I noticed that Rocksmith doesn't recognize the Pitchshifter I use in several presets for Drop G or A tunings, so I think out of the box RS is getting the DI signal and thats why the note recognition is pretty good. 
Backside of this is that I have to find a way to feed it the pitch shifted signal but I think i will just go with the easy solution and put my digitech drop infront of the QC. 
You don't have to answer, just wanted to write this down in case someone stumbles accross this too.

**Comment by VanWolf13** [comment]
i just create a github account to comment that it also works with Antelope Audio Zen Go so u can add this interface to the list as well :) 👍 even to play the multiplayer mode, this is the config i put: 

[Asio.Output]
Driver=ZenGo SC ASIO Driver
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=ZenGo SC ASIO Driver
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=ZenGo SC ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
@VanWolf13 added it to the list, thank  you for the report 👍

**Comment by MisterToolbox** [comment]
Commenting here for posterity: Using `Channel=2` or `Channel=3` for the QC Input will let you send your signal through the Quad Cortex to do transposition, etc. before it gets to Rocksmith:

```
[Asio.Input.0]
Driver=NeuralDSP USB Audio Device
Channel=2              # use 0 for Input 1 (DI signal); use 2/3 for Input 3/4 (routed through Quad Cortex signal chain)
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```
