### ISSUE TITLE
Audient ID4 Confirmation 

### ISSUE THREAD

**Issue by hibrhmk** [mdias/rs_asio#295]
Audient id4 works well with rs_asio.
Product page : [https://audient.com/products/audio-interfaces/id4/overview/](url)
Config and log files : [rs_asio_id4.zip](https://github.com/mdias/rs_asio/files/9249686/rs_asio_id4.zip)

**Comment by mdias** [comment]
Thank you for the confirmation. I've linked the entry on the list to this issue. 👍 

I did notice you're using a 512 sample buffer size for your input. Since your config is set to use the driver preference, you can use your interface's control panel to decrease this in order to achieve better latency.
You should be able to get it to at least 128 without issue, which should get you a 8ms improvement in latency.

**Comment by hibrhmk** [comment]
Thanks for information. I will look into this. 👍

**Comment by L0FKA** [comment]
My iD4 mk2 should be set to second channel input being "input channel=1"

**Comment by alexdmc93** [comment]
Thank you eveyone for your combined efforts, i got i working

`[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Audient USB Audio ASIO Driver
BaseChannel=
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=Audient USB Audio ASIO Driver
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100`

**Comment by alexdmc93** [comment]
So I am using my Audient ID4 as both Instrument input and headphone output.

I changed `EnableWasapiOutputs=` to `0 `, `-1` and `"null"` and noted no difference.

When I tried using `[Asio.Input.0]` It would not detect my guitar. `Mic` is the only way I have been able to get audio from the ID4 front instrument port

**Comment by mdias** [comment]
@alexdmc93 are you using RTC mode in the game, or microphone mode?
You should be using RTC mode.

Other than that, if you have problems with the output I'll only be able to help if you post your config and log.

**Comment by alexdelli** [comment]
why not use ASIOforALL ?

**Comment by mdias** [comment]
> why not use ASIOforALL ?

https://www.theaudioblog.org/post/should-i-use-asio4all
