### ISSUE TITLE
Driver and Rocksmith Audio Problem.

### ISSUE THREAD

**Issue by NickDeBeenAIE** [mdias/rs_asio#297]
I have no audio after switching to ASIO Driver for C-Media USB DAC.

I don't understand what this means. My game now has no audio.

**Comment by mdias** [comment]
Can you be more descriptive? Is there a log? did you change the ini file at all?

**Comment by NickDeBeenAIE** [comment]
Theres no need to give a better explanation for something that f***s with
my game dude, I had to clean the steam library, then re-install the game
from scratch.

As I get the files put into the games folder, there goes its audio....
completely.

There is no log as I have had to reinstall the game.

I didn't see no ASIO driver either when I checked it last.

I don't even know how to set this up, because theres a lot of things you'd
be required to adjust.

As on Rocksmiths .ini, I just left it be.

No modifications to it until I re-installed the game last.

**Comment by mdias** [comment]
You seem to be a little too aggravated for something you paid nothing to try.
If you'd read the documentation **that's on the front page of the project** you'd know how to do the extremely simple steps of uninstalling this mod. You'd also know how to configure and reach for the log.

That said, I'm extremely happy to see you go away from this project.
