### ISSUE TITLE
No audio output device is detected. Please connect and enable an audio output then restart Rocksmith 2014 

### ISSUE THREAD

**Issue by Sir0cks** [mdias/rs_asio#298]
Hello,
I recently downloaded RS_ASIO and placed it where it should and how it should
I proceeded to launch the game and now I'm getting "No audio output device is detected. Please connect and enable an audio output device then restart Rocksmith 2014"
My gear is - Motu M4 Audio Interface, Beyerdynamic DT 900 PRO X Open-Back Studio Headphones.
The audio used to come in through my headset before attempting to play through my audio interface.

**Comment by mdias** [comment]
Please post the contents of your `RS_ASIO.ini` and `RS_ASIO-log.txt` files.

**Comment by Sir0cks** [comment]
Thank you for the reply, I was able to solve the issue and now it works perfectly. Thank you for making audio interfaces and rocksmith compatible. Amazing job!

**Comment by mdias** [comment]
Thank you for reporting back.
Glad to hear you have it working now, enjoy 👍
