### ISSUE TITLE
RS_ASIO not working

### ISSUE THREAD

**Issue by pussyslayer624** [mdias/rs_asio#30]
Ok, so i have this issue where i cant get the driver name,
and also when i get to the calibration tutorial it says that there is no guitar conected 
the rs_asio_log file doesnt give the driver name
im attaching the log file
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4228159/RS_ASIO-log.txt)

**Comment by mdias** [comment]
What version of rocksmith are you running? Is it the latest?

**Comment by pussyslayer624** [comment]
im using the 2014 version, not remastered, i think that has to do with it

**Comment by mdias** [comment]
That is more than likely the case, yes.
