### ISSUE TITLE
Working : JackRouter

### ISSUE THREAD

**Issue by jbarrett** [mdias/rs_asio#303]
Many thanks for this project - it's fantastic!

I use a M-Audio interface, though I have a bit of a noisy setup - lots of electrical interference. I decided to try [Jack's ASIO driver](https://jackaudio.org/) (JackRouter) and qjackctl to route audio through the [Carla VST host](https://kx.studio/Applications:Carla) + an equaliser VST acting as a high-pass filter to bring down some of the noise around 50Hz.

Everything inserted between the application and audio interface is going to increase latency, but this is a highly flexible setup and changing the routing graph in QjackCtl/Carla worked in real time. This may also be an option for interfaces which do not work properly when configured directly.

While the config will differ depending on your jack setup, I have included it below for the record, alongside a screenshot of a working routing graph in jack.

Cheers!

```ini
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
;Driver=M-Audio M-Track Solo and Duo ASIO
Driver=JackRouter
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
;Driver=M-Audio M-Track Solo and Duo ASIO
Driver=JackRouter
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

![image](https://user-images.githubusercontent.com/444449/186947164-8983bd36-ca90-47bf-9570-faee86341426.png)

**Comment by mdias** [comment]
Thank you for the report and sorry it took me so long to reply.
I've added this driver to the compatibility list 👍
