### ISSUE TITLE
Freeze on Exit

### ISSUE THREAD

**Issue by Kiname** [mdias/rs_asio#304]
First of all thank you for this amazing tool.

It works perfectly, only issue is that Rocksmith freeze on exit.

Audio Interface M-Audio M-Track Solo.

RS_ASIO.ini

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=M-Audio M-Track Solo and Duo ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=M-Audio M-Track Solo and Duo ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=M-Audio M-Track Solo and Duo ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9478907/RS_ASIO-log.txt)

**Comment by Kiname** [comment]
After testing old releases found that work fine with release 0.4.2 but of course can not activate the WASAPI output...

**Comment by mdias** [comment]
Hello!

Thank you for the information. Can you confirm that v0.5.0 is the first release that doesn't work correctly for you?

**Comment by Kiname** [comment]
Hi,
Yes I Can confirm, last version that works fine is 0.4.2

**Comment by mdias** [comment]
Can you check if it works with the following version: [release-0.5.9.zip](https://github.com/mdias/rs_asio/files/9492035/release-0.5.9.zip)
And the following config:

```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
; driver - respect buffer size setting set in the driver
; host - use a buffer size as close as possible as that requested by the host application
; custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=M-Audio M-Track Solo and Duo ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=true

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=true

[Asio.Input.1]
Driver=M-Audio M-Track Solo and Duo ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=true

[Asio.Input.Mic]
Driver=M-Audio M-Track Solo and Duo ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=true
```

If not, please post the resulting RS_ASIO-log.txt.
Thanks.

**Comment by mdias** [comment]
Please use the following version instead as the one I attached on the previous post didn't fully enable the potential fix: 
[release-0.5.9.zip](https://github.com/mdias/rs_asio/files/9492206/release-0.5.9.zip)

**Comment by Kiname** [comment]
Sorry, same result, freeze on exit.

RS_ASIO.ini

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=M-Audio M-Track Solo and Duo ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=M-Audio M-Track Solo and Duo ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9494540/RS_ASIO-log.txt)

**Comment by Kiname** [comment]
YES!!! works perfectly thank you for your amazing job man, and for maintain this great tool.

**Comment by Kiname** [comment]
YES!!! works perfectly thank you for your amazing job man, and for maintain this great tool.

**Comment by mdias** [comment]
Thank you for reporting back.
I will publish this version through the normal releases page 👍
