### ISSUE TITLE
Not working since latest update

### ISSUE THREAD

**Issue by andrewhawkes** [mdias/rs_asio#305]
Rocksmith just updated today and it appears it's no longer working for me with my 4i4.
I've updated to the latest release and updated my configs to match but I'm getting this in the log:

```
0.000 [INFO]   - Wrapper DLL loaded (v0.5.9)
0.000 [INFO]  PatchOriginalCode
0.075 [ERROR]  No valid locations for patching were found. Make sure you're trying this on the right game version.
```

I think the latest patch had maybe f*** it - or it's just me

**Comment by andrewhawkes** [comment]
Okay - done some digging in the Steam forum and someone posted this which has allowed me to backtrack a version so I'll try it again:

Quick step-by-step guide:
1. Right click RS2014
2. Properties...
3. Betas...
4. Enter `JustInCaseWeNeedIt` and check code
5. Select "previous_version" beta
6. Wait for install to finish (if already updated)

**Comment by andrewhawkes** [comment]
Okay - so that worked. From what I can gather people also recommend disabling the auto updates now as Ubisoft are on a quest to ruin the game. Instructions from this post on [Reddit](https://www.reddit.com/r/rocksmith/comments/xa49mq/important_update_coming_to_rocksmith_2014/)

To disable updates for a specific game, first disable autoupdate for that game:

1. Select "LIBRARY" from the top menu.
2. Right click on the corresponding game within your Steam library.
3. Select "Properties..." from the menu that appears.
4. Select "UPDATES" from the side menu on the properties window.
5. Select the dropdown under "AUTOMATIC UPDATES" to view available options.
6. Select "Only update this game when I launch it"

Then you'll need to use the hidden skip update option. You will likely need to do this every time you want to run the software (unless you switch Steam to offline mode to start it, which no longer requires a Steam restart).

1. Make sure Steam is already running on your system
2. PressWin+R keyboard shortcut to open the run box.
3. Go to Console tab in Steam client, type `@AllowSkipGameUpdate 1`. The console should respond with the following:

`] @AllowSkipGameUpdate 1` in red text

`"@AllowSkipGameUpdate" = "1"` in white text, with quotes

Now, with this temporarily enabled (one-time use, IIRC), go to your Library and start the app, and press "Update Later".

**Comment by andrewhawkes** [comment]
I'll leave this open just in case anyone comes here with the same issue and there might be a way to get it to work with the latest version. But feel free to close.

**Comment by mdias** [comment]
Yes, please leave open while it's an issue.

I will need to find some time to update RS ASIO to work with the newer version, and I'll release a new version when done.

**Comment by golfar** [comment]
Thank you Andrewhawkes!!! That fixed it for me right away. So glad it working again. So appreciative.

**Comment by fluxcapacitor81** [comment]
Thank you!

**Comment by Gawainli** [comment]
Thank you Andrewhawkes!!!

**Comment by mdias** [comment]
Should be working with [new release](https://github.com/mdias/rs_asio/releases/latest).
