### ISSUE TITLE
Is CDLC supposed to work w RS_ASIO installed?

### ISSUE THREAD

**Issue by fluxcapacitor81** [mdias/rs_asio#306]
I don't have the update installed i did the rollback "just in case you need it".  

I can't load any CDLC...it just hangs when it should start.

IDK if this could RS_ASIO.

**Comment by mdias** [comment]
CDLC works fine with RS ASIO.
However there has been a very recent update to RS 2014 that broke compatibility with RS ASIO.

As of now I'm still not sure if it will be possible to update RS ASIO to make it work, but for now there is [another solution](https://github.com/mdias/rs_asio/issues/305).

**Comment by fluxcapacitor81** [comment]
doing the roll back though makes RS_ASIO work but not cldc.

**Comment by mdias** [comment]
Please check [this reddit post](https://www.reddit.com/r/rocksmith/comments/xblbit/people_are_claiming_that_a_new_patch_is_out_that/). The CDLC patch has been updated.

**Comment by fluxcapacitor81** [comment]
Thanks looking at that now.  Appreciated much.

**Comment by fluxcapacitor81** [comment]
> 

Do you have a link I don't see  it in there or in the linked reddit post and discord

**Comment by mdias** [comment]
I don't have a direct link for it, sorry.

**Comment by fluxcapacitor81** [comment]
NM I see the link.

I'm new to Discord though and all I see is this:

![image](https://user-images.githubusercontent.com/95678795/189551610-ccfc19c7-7ef1-4b25-a59d-eef0114c9271.png)

Did I miss something setting up my account?  Or is the link listed just bad?

**Comment by fluxcapacitor81** [comment]
Yo thank you so much for all your help.  

I don't think there's actually a fix yet though.  The news isn't spreading and that discord link does nothing it seems.

**Comment by fluxcapacitor81** [comment]
OK it must be something I'm not doing right because I'm already on the beta rollback and .0.5.9.

**Comment by fluxcapacitor81** [comment]
Yep I had the DLL in the DLC folder it goes in the root.

**Comment by mdias** [comment]
I just tested the DLL available through [CustomsForge](https://customsforge.com/index.php?/topic/901-how-to-use-custom-dlcs-in-rs2014-remastered/) along with RS ASIO on the latest patch and it seems to work as expected.
