### ISSUE TITLE
UAD Apollo Twin USB

### ISSUE THREAD

**Issue by imsartic** [mdias/rs_asio#307]
I see that the Apollo Twin USB interface is listed as confirmed to be working but I can not for the life of me figure out how to get it running :( I was wondering if I'm doing something wrong like using the wrong channels in the .ini or something? 

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9543266/RS_ASIO-log.txt)

![rocksmith settings](https://user-images.githubusercontent.com/113307431/189543310-e9d337e4-0f96-4e76-9331-e3ff27e6630a.PNG)

![asio settings](https://user-images.githubusercontent.com/113307431/189543316-09a26648-1cc0-4aae-9621-6bcf31c4fa71.PNG)

**Comment by mdias** [comment]
This is strange. The driver appears to fail to instantiate properly.

Please try any other 32-bit ASIO-enabled software, such as [this test signal generator](http://www.tropicalcoder.com/ASIOTestSigGen.htm) to see if it works there.

**Comment by imsartic** [comment]
Okay so I tried that program and when I try to run it I get an error and it crashes and then this is what the crash log says

Debug log

Date: Sunday, September/11/2022 - Time started: 17:04:07 847

ASIOSigGen version 4.33 Copyright (C) 2021 George W. Taylor
All rights reserved!
http://www.TropicalCoder.com
"C:\Users\Tyler\Desktop\asio test\ASIOSigGen.exe" 

Enumerating ASIO Drivers...

numDev: 0
Universal Audio Apollo FireWire
c:\program files (x86)\universal audio\powered plugins\drivers\audio\fw\x86\uafwaudioasio.dll

numDev: 1
Universal Audio USB
c:\program files (x86)\universal audio\powered plugins\drivers\audio\usb\x86\uausbaudioasio.dll

Total num devices found: 2
Found ASIO Configuration file!
nRequestedDrvNum: 2, Num devices: 2
nRequestedDrvNum > lnumDevs!: 2
asioOpenDriver failed for device: 0
AsioDriverList destruction.


Shutting down debug logging system...
Date: Sunday, September/11/2022 - Time: 17:04:10 991

**Comment by imsartic** [comment]
I tried uninstalling the UAD software and drivers, and then installing a past version and still the same issue happens. So I downloaded this tool https://forum.vb-audio.com/viewtopic.php?t=1204 and when I run the 64 bit version it works perfectly fine, but when I run the 32 bit version it comes up with an error. Super weird haha

**Comment by imsartic** [comment]
Okay so I think I fixed it! I went to that thread you linked of the guy saying it works and realized it was from 3 years ago. I then realized that, if UAD had broken the 32 bit drivers at some point, would anyone REALLY have noticed because no one uses 32 bit applications anymore. I downloaded the software from around 3 years ago and BOOM, the 32 bit ASIO test worked. Booted up Rocksmith and everything works flawlessly now =D Now I'll try to update the software since I do need the newer version for the plugins I use but hopefully it doesn't overwrite the drivers.

**Comment by mdias** [comment]
Ohh, that's annoying. 
Anyway, thanks for investigating; I'll add a link on the interface to this issue along with a note.

It could still be helpful to notify UAudio that the 32-bit driver they're shipping isn't working. I understand they're not supporting anymore, but I doubt they mean to still ship it if it doesn't work at all.
If you end up contacting them and they fix it, please let us know so that I update the compatibility list.

**Comment by Mimile182** [comment]
Hello guys,
I tried to tell about this issue with the Universal Audio support but this is what they answered (and it's a bummer)

![Capture](https://github.com/mdias/rs_asio/assets/146925900/3f716df8-bcd0-4358-9b5b-8c7764848231)

**Comment by mdias** [comment]
As a workaround you might be able to use Voicemeeter's 32-bit drivers that end up feeding your interface's 64-bit drivers.

**Comment by Mimile182** [comment]
I'm not sure i understand .. i can update my Apollo Twin driver to the latest version and then when i launch rocksmith i have something to do with Voicemeeter's and i'll be able to make everything work ?

**Comment by mdias** [comment]
@Mimile182 Voicemeeter creates virtual audio devices on your machine and uses a real "main audio device" as a "main driver" of the whole thing when running. This "main audio device" can be your 64 bit Apollo Twin interface with latest drivers.

Voicemeeter also provides ASIO drivers (32-bit too!) so you'd configure RS ASIO to use Voicemeeter instead of your Apollo Twin's drivers. Then you'd configure Voicemeeter to patch the virtual device's audio ports to your real device's audio ports. So basically Voicemeeter will be a man in the middle and will hand between RS_ASIO and your Apollo Twin's ASIO drivers.

So yes, in theory you can run your Apollo Twin with latest drivers if you're willing to open Voicemeeter every time you wish to play the game too.

**Comment by Mimile182** [comment]
Thank you very much, i'll try this the day i'm forced to update my Apollo Twin driver for whatever reason. Hope i'll figure this out, seems pretty easy (i hope) ! Thanks you for that very clear explanation

**Comment by Mimile182** [comment]
Hello again @mdias !
I've seen the last known issues (that according to reports, newer Focusrite driver releases no longer include 32 bit ASIO drivers...)

And here we are, i now need to have the latest firmware version of my Apollo Twin.., i was searching for the correct way to configure voicemeeter to have Rocksmith working fine.
'cause i know a lot of focusrite owner are playing rocksmith too, but didn't find any video on youtube or any screenshot showing the right configuration

Do you know if I can find it somewhere ? Maybe I haven't done my research well ... Maybe we could add this once and for all on the main page ? 

Regards

**Comment by sonnyearl** [comment]
Damn, I use to use an ampeg amp sim in the console while muting the bass in the game. I think there might a MacGyver solution to this though. Using an ABY pedal I can plug my bass in and then on the output one goes to the Twin USB so I can monitor the instrument, the other output sends a copy of my signal to the real tone cable... Will report back when I get a chance.
