### ISSUE TITLE
Focusrite Scarlett i2i and Rocksmith+ will be supported?

### ISSUE THREAD

**Issue by JoseArostegui** [mdias/rs_asio#309]
Hi,

Just playing with Rocksmith+ in PC Win 11, and the Focusrite Scarlett i2i is not detected.

Do you plan to include it in this great project?

Thanks,
Jose.

**Comment by theSG** [comment]
scarlett 2i2 is in the list of tested and supported audio interfaces
https://www.ubisoft.com/en-us/help/rocksmith-plus/gameplay/article/supported-peripherals-for-rocksmith/000103038

**Comment by JoseArostegui** [comment]
I've installed "Focusrite Control" and now everything works perfectly.
Thanks for your answer. Please close this issue.
