### ISSUE TITLE
No sound/input at all on Focusrite 18i8 2nd Gen

### ISSUE THREAD

**Issue by PolVanAcoleyen** [mdias/rs_asio#31]
I have a Focusrite 18i8, and I get no sound or input.
The RS_Asio log also seems a lot shorter than it should be.
I've included my RS_ASIO ini and log files, as wel as the Rocksmith.ini and audiodump.txt  (inis as txt)
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/4229374/RS_ASIO.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4229363/RS_ASIO-log.txt)
[audiodump.txt](https://github.com/mdias/rs_asio/files/4229364/audiodump.txt)
[Rocksmith.txt](https://github.com/mdias/rs_asio/files/4229371/Rocksmith.txt)

**Comment by mdias** [comment]
What version of rocksmith are you running? Is it the latest?

**Comment by PolVanAcoleyen** [comment]
Rocksmith 2014, update 7

**Comment by mdias** [comment]
This is only compatible with `Rocksmith 2014 Edition - Remastered` as stated in the readme.

**Comment by PolVanAcoleyen** [comment]
Sorry, hadn't noticed that!
Updated my game to Remastered, up to the latest version.

AND IT WORKS !

Thanks!!
