### ISSUE TITLE
RS-ASIO doesn't work after recent update of Rocksmith

### ISSUE THREAD

**Issue by Farmatique** [mdias/rs_asio#314]
The title pretty much described what happens. It used to work just fine before the Steam updated Rocksmith to a recent version.

Win 10, Soundcard Zoom U-22. Here's the RS_ASIO.log:

0.000 [INFO]   - Wrapper DLL loaded (v0.5.8)
0.000 [INFO]  PatchOriginalCode
0.242 [ERROR]  No valid locations for patching were found. Make sure you're trying this on the right game version.
109.338 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
You will need to update RS ASIO to a [newer release](https://github.com/mdias/rs_asio/releases/latest).

**Comment by Farmatique** [comment]
That works, thank you, @mdias! I'm closing out the ticket
