### ISSUE TITLE
Crash on lauch

### ISSUE THREAD

**Issue by Arutosio** [mdias/rs_asio#318]
hi guys, the game crash when i try to run it before the the logos in the white screen
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9692865/RS_ASIO-log.txt)
[RSMods_debug.txt](https://github.com/mdias/rs_asio/files/9692866/RSMods_debug.txt)
[Videodump.txt](https://github.com/mdias/rs_asio/files/9692868/Videodump.txt)

some one can help me?

**Comment by mdias** [comment]
Does it crash without RS ASIO?

**Comment by Arutosio** [comment]
> Does it crash without RS ASIO?

how do i try to run the game without RS Asio?
do you need the rocksmith2014_396631_crash_2022_10_3T6_15_25C0.mdmp file to investigate?

**Comment by mdias** [comment]
> how do i try to run the game without RS Asio?

Just rename `avrt.dll` to something else, like `_avrt.dll` and run the game like that. That completely disables RS ASIO.
You can just rename it back to the original filename if you want to re-enable it.

I don't need that file, no.

**Comment by Arutosio** [comment]
the problem persists, maybe I should uninstall and reinstall
what do you think?

**Comment by mdias** [comment]
That's a good idea. Ensure all files are deleted too just in case you were using some other modifications.
Then check if it works, and if it does start adding your needed mods one by one to see which one causes the problem.

**Comment by mdias** [comment]
Yes, that should be safe.

**Comment by Arutosio** [comment]
i updated RSMods now it works, maybe the problem was the old version I had

**Comment by mdias** [comment]
That is very well possible.
Thank you for reporting back :)
