### ISSUE TITLE
No audio output device is detected.

### ISSUE THREAD

**Issue by nightwayf** [mdias/rs_asio#320]
Using Digitech RP360 with ASIO4ALL driver. Done basic configuration. Here are my log and config files. 
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/9801944/RS_ASIO.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9801950/RS_ASIO-log.txt)

**Comment by nightwayf** [comment]
[Rocksmith.txt](https://github.com/mdias/rs_asio/files/9801955/Rocksmith.txt)
Also, Rocksmith ini

**Comment by mdias** [comment]
ASIO4ALL is reporting that it doesn't support 48kHz.
You likely need to change your audio devices to 48kHz in windows sound settings for ASIO4ALL to support it properly.
