### ISSUE TITLE
Rocksmith stops recognizing input

### ISSUE THREAD

**Issue by NoBrainnm** [mdias/rs_asio#321]
It happens randomly when i'm playing
here's my log
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9842972/RS_ASIO-log.txt)
When the problem happens rocksmith stops recognizing any input so there's no visual feedback either from the speakers or the high res scope. Also i'm using the generic ASIO4ALL v2 drivers in my .ini because my interface has no proprietary drivers. The issue persists even if i close then open the game again here's the log after opening the game after the issue happened for the first time 
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9842985/RS_ASIO-log.txt)

Asio v.2.15
RS Asio 0.6.3

**Comment by mdias** [comment]
ASIO4ALL is often not reliable enough for Rocksmith.
Please try increasing your buffer size as you're getting a lot of xruns, which might be causing the problem.

Alternatively you could try using the game's [Direct Connect](https://www.youtube.com/watch?v=H6nAB5ogfeU) mode.
