### ISSUE TITLE
No guitar sound in game

### ISSUE THREAD

**Issue by xkhroshkax** [mdias/rs_asio#322]
Hi all. I've been trying for 4 days to solve the problem of no guitar sound in the game, I've tried a bunch of tips, but still can't solve this problem, I'm desperate :(

About my hardware: Focusrite Scarlet 2i2 3gen. Connected via USB, identified as Analogue 1+2 (Focusrite USB Audio). Headphone output through the same audio interface.

What has already been done:
1. Connecting a guitar via an interface without using RS ASIO files. In the game, the microphone is selected in the audio input selection menu. The result is negative. There is game sound, but no guitar sound. At the same time, the guitar is defined by the game and I can tune it and play songs, but without sound.

2. RS ASIO files were added to the game folder, but in this case I get an audio output placement error when starting the game and the complete absence of any sound in the game.

3. I tried to connect the guitar to the microphone and line inputs of the computer, but then the guitar is not detected again.

Below I show my files:

Rocksmith.ini 

```
[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=1
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1920
ScreenHeight=1080
Fullscreen=0
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=0
[Global]
Version=1
```
And RS_ASIO.ini

```
# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```

I really count on your help, because I myself do not know what else can be done.

**Comment by mdias** [comment]
> In the game, the microphone is selected in the audio input selection menu

Do not do this. Use the RealTone Cable mode always.

> At the same time, the guitar is defined by the game and I can tune it and play songs, but without sound.

After having the game properly working, you should go through the guitar volume calibration ingame and it will set the appropriate volume.

> I tried to connect the guitar to the microphone and line inputs of the computer, but then the guitar is not detected again.

This is unrelated to RS ASIO. RS ASIO will only help with getting your Focusrite to work.

1. Ensure you have your interface's ASIO drivers installed
2. Ensure you have RS ASIO files in place along with the config you just posted
3. run the game

If it doesn't work you should post here the resulting `RS_ASIO-log.txt` that should be in the game's folder too so that I can see what is the error.

**Comment by xkhroshkax** [comment]
> > В игре микрофон выбирается в меню выбора аудиовхода
> 
> Не делайте этого. Всегда используйте кабельный режим RealTone.
> 
> > При этом гитара определяется игрой и я могу ее настроить и играть песни, но без звука.
> 
> После того, как игра заработает правильно, вы должны пройти калибровку громкости гитары в игре, и она установит соответствующую громкость.
> 
> > Пробовал подключать гитару к микрофонному и линейному входам компьютера, но потом гитара снова не определяется.
> 
> Это не связано с RS ASIO. RS ASIO поможет только заставить ваш Focusrite работать.
> 
> 1. Убедитесь, что у вас установлены ASIO-драйверы вашего интерфейса.
> 2. Убедитесь, что у вас есть файлы RS ASIO вместе с конфигурацией, которую вы только что опубликовали.
> 3. запустить игру
> 
> Если это не сработает, вы должны опубликовать здесь результат `RS_ASIO-log.txt`, который также должен быть в папке с игрой, чтобы я мог увидеть, в чем ошибка.



> > In the game, the microphone is selected in the audio input selection menu
> 
> Do not do this. Use the RealTone Cable mode always.
> 
> > At the same time, the guitar is defined by the game and I can tune it and play songs, but without sound.
> 
> After having the game properly working, you should go through the guitar volume calibration ingame and it will set the appropriate volume.
> 
> > I tried to connect the guitar to the microphone and line inputs of the computer, but then the guitar is not detected again.
> 
> This is unrelated to RS ASIO. RS ASIO will only help with getting your Focusrite to work.
> 
> 1. Ensure you have your interface's ASIO drivers installed
> 2. Ensure you have RS ASIO files in place along with the config you just posted
> 3. run the game
> 
> If it doesn't work you should post here the resulting `RS_ASIO-log.txt` that should be in the game's folder too so that I can see what is the error.

It turns out that it was only necessary to select the connection via the cable, without choosing the cable itself as the input source, then there will be no message with the requirement to connect the cable. The solution turned out to be so simple, but not obvious. It might be worth writing in the instructions in RS ASIO that you just need to check the cable mode in the game menu, without trying to specify the audio input there.
Thanks for your help, I'm glad the problem is finally solved!

**Comment by mdias** [comment]
No problem!
This instruction is written in the "How to use" steps of the readme:
> Make sure your game is set to use the RTC input instead of the microphone one

Glad it's solved for you. Enjoy :)
