### ISSUE TITLE
using HX Stomp XL over USB no longer works

### ISSUE THREAD

**Issue by LarsColman** [mdias/rs_asio#325]
This setup used to work flawlessly, after coming back to rocksmith after a couple weeks surrounding that last update, it no longer works. And I can't for the life of me figure out why.
I've
- removed all rocksmith files and reinstalled RS_asio -> did not work
- reinstalled the hx usb drivers -> did not work
- use the focusrite as input -> this works
- use ASIO Helix instead of ASIO HX Stomp driver -> did not work
- rebooted -> did not work
- set all kinds of different buffer sizes -> did not work
- tried settings through both rs_mods and editing the .ini file manually -> did not work

[rocksmith.ini](https://pastebin.com/Tq8ysYDL)
[RS_ASIO.ini](https://pastebin.com/4JJjPZ1e)
[RS_ASIO-log.txt](https://pastebin.com/WHcRNU2u)

I'm assuming the issue is on my end but I'm all out of ideas why rs_asio suddenly does not see the HX Stomp XL. This is probably the issue:
```
0.846 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO HX Stomp
0.846 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
```

**Comment by LarsColman** [comment]
I should probably say what the actual issue is:
![image](https://user-images.githubusercontent.com/9090551/198421287-152b38b1-87c8-4899-abd5-8dd7628fb1b0.png)
any feedback is very much appreciated!

**Comment by mdias** [comment]
The `ASIO HX Stomp` driver you provided for the input was not found on the system:

These are the drivers found by RS ASIO installed on your system:
```
0.843 [INFO]  AsioHelpers::FindDrivers
0.843 [INFO]    ASIO Helix
0.844 [INFO]    Blackmagic ASIO Driver
0.844 [INFO]    Focusrite Thunderbolt ASIO
0.844 [INFO]    Focusrite USB ASIO
0.844 [INFO]    Realtek ASIO
```

Remember that Rocksmith is a 32 bit application, and therefore you will need to have 32-bit ASIO drivers to use them with Rocksmith.
That said, perhaps the problem is you didn't install the ASIO drivers for yourr interface at all. Please try to get and install the latest drivers for it.

**Comment by LarsColman** [comment]
I wanted to continue looking into it some more over the weekend, and it just worked again without additional changes. Might have been a windows update or something... Sorry to waste your time!
