### ISSUE TITLE
RSAsio doesn't find my device

### ISSUE THREAD

**Issue by Desman109** [mdias/rs_asio#328]
Hello, I've tried installing RSAsio with my Scarlett 2i2, but it doesn't seem to detect it, and it does detect unconnected devices (such as my drum kit):

Here's the log:
 - Wrapper DLL loaded (v0.6.3)
0.000 [INFO]  PatchOriginalCode
0.029 [INFO]  image crc32: 0xd1b38fcb
0.168 [INFO]  Patching CoCreateInstance
0.168 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.168 [INFO]  Patching call at 00C02DBD
0.169 [INFO]  Patching call at 00E75278
0.169 [INFO]  Patching PortAudio MarshalStreamComPointers
0.169 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.169 [INFO]  Patching call at 00E7483F
0.169 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.169 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.169 [INFO]  Patching call at 00E748F4
0.169 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.169 [INFO]  Patching bytes at 007C0C5F
0.170 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.171 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.171 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.171 [INFO]  AsioHelpers::FindDrivers
0.171 [INFO]    ASIO4ALL v2
0.171 [INFO]    FL Studio ASIO
0.171 [INFO]    Realtek ASIO
0.171 [INFO]    TD-11

It does seem to find the Scarlett 2i2 as a microphone input

**Comment by mdias** [comment]
You need to install the drivers from the Focusrite website.
Also, if you're planning to connect a guitar, do not set it up ingame as microphone. RS ASIO will trick Rocksmith into thinking it's a normal RealTone Cable.

**Comment by Desman109** [comment]
Thanks, it finds my Focusrite now but now there's no audio output, what do I do about that? I think I followed the steps correctly, here's the code:

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
Do you have your speakers/headphones connected to the Focusrite?

**Comment by Desman109** [comment]
Yes I do, is there a way to make it emulate a RealTone Cable and also play the audio through it?

**Comment by Desman109** [comment]
Or should I just connect my headphones to my PC and make my PC's built in ASIO the output?

**Comment by mdias** [comment]
You can do either, but the reason I asked is that by default RS ASIO will output to your Focusrite and some people have the speakers connected to the PC instead.

Everything should be working fine with the settings you have. Perhaps the outputs you have your speakers/headphones connected to are not the first ones. If so, try setting `BaseChannel=2` and check if it works that way.

If it still doesn't work, please post the RS_ASIO-log.txt file here so I can have a look if there's anything suspicious there.

**Comment by mdias** [comment]
I forgot to mention. If you want to have your speakers connected to your PC instead of the focusrite, you should set `EnableWasapiOutputs=1` and leave `Driver=` empty for the output section of the config.

**Comment by Desman109** [comment]
Hey, I tried making the adjustment you suggested, it didn't work, here's the log file:

0.000 [INFO]   - Wrapper DLL loaded (v0.6.3)
0.000 [INFO]  PatchOriginalCode
0.037 [INFO]  image crc32: 0xd1b38fcb
0.222 [INFO]  Patching CoCreateInstance
0.223 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.224 [INFO]  Patching call at 00C02DBD
0.224 [INFO]  Patching call at 00E75278
0.224 [INFO]  Patching PortAudio MarshalStreamComPointers
0.224 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.224 [INFO]  Patching call at 00E7483F
0.224 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.224 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.224 [INFO]  Patching call at 00E748F4
0.224 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.224 [INFO]  Patching bytes at 007C0C5F
0.227 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.228 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.228 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.228 [INFO]  AsioHelpers::FindDrivers
0.229 [INFO]    ASIO4ALL v2
0.229 [INFO]    FL Studio ASIO
0.229 [INFO]    Focusrite Thunderbolt ASIO
0.229 [INFO]    Focusrite USB ASIO
0.229 [INFO]    Realtek ASIO
0.229 [INFO]    TD-11
0.229 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.229 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusrite\drivers\focusriteusbasio32.dll
0.264 [INFO]    ASIO input channels info:
0.264 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
0.264 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
0.264 [INFO]    ASIO output channels info:
0.264 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
0.264 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
0.264 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.264 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
0.264 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.264 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.264 [INFO]    hr: S_OK
0.264 [INFO]    *ppEndpoint: 11A6D190
0.264 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.264 [INFO]    hr: S_OK
0.264 [INFO]    *ppEndpoint: 11A6D070
0.264 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.264 [INFO]    hr: S_OK
0.264 [INFO]    *ppDevices: 0AD54820
0.264 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.264 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.264 [INFO]    *cProps: 2
0.264 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.264 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.264 [INFO]    *pDataFlow: eRender
0.264 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.264 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.264 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.264 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.264 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.264 [INFO]    *cProps: 5
0.264 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.264 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.264 [INFO]    *pDataFlow: eCapture
0.264 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.264 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.264 [INFO]  {ASIO IN 0} RSAsioAudioClient::~RSAsioAudioClient
0.429 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.429 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
0.429 [ERROR]    requested channels use multiple different sample types
0.429 [INFO]    requested format is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.429 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
0.429 [ERROR]    requested channels use multiple different sample types
0.429 [INFO]    requested format is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.429 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
0.429 [ERROR]    requested channels use multiple different sample types
0.429 [INFO]    requested format is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.429 [INFO]    WARNING: max requested channel 4 is beyond the max asio channels available 2
0.429 [ERROR]    requested channels use multiple different sample types
0.429 [INFO]    requested format is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.429 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.429 [ERROR]    shared mode is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.429 [ERROR]    shared mode is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.429 [ERROR]    shared mode is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.429 [ERROR]    shared mode is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.429 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.429 [ERROR]    shared mode is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.429 [ERROR]    shared mode is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.429 [ERROR]    shared mode is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.429 [ERROR]    shared mode is not supported
0.429 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.429 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.429 [INFO]  Destroying AsioSharedHost - dll: c:\program files\focusrite\drivers\focusriteusbasio32.dll
6.554 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
6.554 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
6.554 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
6.554 [INFO]  AsioHelpers::FindDrivers
6.555 [INFO]    ASIO4ALL v2
6.555 [INFO]    FL Studio ASIO
6.555 [INFO]    Focusrite Thunderbolt ASIO
6.555 [INFO]    Focusrite USB ASIO
6.555 [INFO]    Realtek ASIO
6.555 [INFO]    TD-11
6.555 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
6.555 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusrite\drivers\focusriteusbasio32.dll
6.560 [INFO]    ASIO input channels info:
6.560 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
6.560 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
6.560 [INFO]    ASIO output channels info:
6.560 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
6.560 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
6.560 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
6.560 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
6.560 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
6.560 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
6.560 [INFO]    hr: S_OK
6.560 [INFO]    *ppEndpoint: 11A6D430
6.560 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
6.560 [INFO]    hr: S_OK
6.560 [INFO]    *ppEndpoint: 11A6D3A0
6.560 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
6.560 [INFO]    hr: S_OK
6.560 [INFO]    *ppDevices: 0AD56360
6.560 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
6.560 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
6.560 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
6.560 [INFO]    *pDataFlow: eRender
6.560 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
6.560 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
6.560 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
6.560 [INFO]    *pDataFlow: eCapture
6.568 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
9.103 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
9.103 [INFO]  Destroying AsioSharedHost - dll: c:\program files\focusrite\drivers\focusriteusbasio32.dll
9.320 [INFO]   - Wrapper DLL unloaded

**Comment by Desman109** [comment]
Also, the .ini file:

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=2
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
There's a couple of things you can do. You can decrease the buffer size, decrease the `LatencyBuffer` in Rocksmith.ini, and you should also calibrate the latency in the ingame options.
