### ISSUE TITLE
Crackle/distortion from input

### ISSUE THREAD

**Issue by jlongwell** [mdias/rs_asio#329]
Using my Scarlett Solo and rs_asio, I get some pretty heavy crackling/distortion from my guitar in Rocksmith 2014.  Only occurs in RS2014, RS+ is fine using the native interface support.  No other audio is affected, the game intro and song previews sound fine.  I have also tried swapping cables and switching the usb port that my interface is plugged into, nothing seems to make a difference.

I have tried 48, 96 and 192 buffer sizes - 48 sounds the best but still bad.

Any ideas?  Thanks in advance!

```
[Config]
EnableWasapi=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

; [Asio.Input.0]
; Driver=Focusrite USB ASIO
; Channel=0
; EnableSoftwareEndpointVolumeControl=1
; EnableSoftwareMasterVolumeControl=1
; SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10042833/RS_ASIO-log.txt)

**Comment by mdias** [comment]
If all your sound output (game sounds and music) sound fine but your input (guitar sound) sounds bad I suspect you might have the input volume too high.

Have you tried to run the guitar volume calibration ingame?
Also, try to change the guitar gain on the interface itself to see if you can get rid of the distortion.

**Comment by jlongwell** [comment]
I'm 99.9% certain this was not a rs_asio issue and was just something about my interface that didn't want to jive with RS2014 specifically.  I stumbled on a great deal on a 2i2 today and did a straight swap, no config changes.  Everything sounds great now.
