### ISSUE TITLE
Helix HX Stomp

### ISSUE THREAD

**Issue by Fr33sp1r1t** [mdias/rs_asio#33]
I use a HX Stomp as my interface to my PC.
I was trying the new RS ASIO 0.4.0 release. I put my driver name (ASIO HX Stomp) into the ini file and started Rocksmith. The game started fine with sound through the HX Stomp, but the game thinks my cable is unplugged and gives me no input (on either channel). 

If i edit the ini file to have EnableWasapi=1 and remove the Asio.Output driver= bit, then using my laptops own speakers/headphones the game plays fine AND finds the cable input from the RS ASIO wrapper (and i mean really well in this configuration).

The reason I am mentioning this is because RS ASIO 0.3.11 (which i was using before) works fine. Both input and output work at the same time. So something seems to have changed between 3.11 and 4.0.

I actually like my work around (it means i don't have to bend under the table to move the headphones :)) so I don't actually have any problem I just thought I should report the issue.

I am not at my music laptop at the moment so do not have the log files handy but I can get them tomorrow if you wish them. 

Keep up the great work and many thanks for this wrapper.

**Comment by mdias** [comment]
Hello!

Thank you very much for reporting this even if it's not an issue for you.
As you're probably guessing this should be an unintended regression that I
would rather see fixed.

Can you please attach a log after running the game with the issue present,
slong with your rs_asio config contents?

>

**Comment by Fr33sp1r1t** [comment]
ok i will start with Release 0.3.11 ini and log. THIS WORKS in and out.
[RS_ASIO.ini.txt](https://github.com/mdias/rs_asio/files/4240064/RS_ASIO.ini.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4240066/RS_ASIO-log.txt)

**Comment by Fr33sp1r1t** [comment]
This is release 0.4.0 ASIO only. It only works to play back NO INPUT
[RS_ASIO.ini.txt](https://github.com/mdias/rs_asio/files/4240069/RS_ASIO.ini.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4240070/RS_ASIO-log.txt)

**Comment by Fr33sp1r1t** [comment]
Release 0.4.0 with Wasapi enabled (so using laptops output) and ASIO output disabled. ASIO input is ENABLED. This works config. works for me with a great low latency INPUT.
[RS_ASIO.ini.txt](https://github.com/mdias/rs_asio/files/4240082/RS_ASIO.ini.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4240083/RS_ASIO-log.txt)

**Comment by Fr33sp1r1t** [comment]
Oh and I added .txt to the ini files as it would not let me upload just the ini extension.

**Comment by mdias** [comment]
I think I know what's going on and just made a [new release](https://github.com/mdias/rs_asio/releases/tag/v0.4.1) in an attempt to fix it.
Please try it when you're able :)

**Comment by Fr33sp1r1t** [comment]
RS ASIO 0.4.1 works great. it has both INPUT and OUTPUT working fine again. You are doing a great job for the community. Thank you for you time and vision.

**Comment by mdias** [comment]
Awesome!
No problem, glad it's helping people enjoy their guitars :)
