### ISSUE TITLE
Focusrite 8i6

### ISSUE THREAD

**Issue by yianni54** [mdias/rs_asio#331]
Hello,

I have two issues, the first is when I use Rocksmith with Neural DSP standalone plugin, if I click on the plugin then rocksmith mutes itself. Is there a way to keep them running independently? Second, when I use standalone plugin I am also hearing the DI signal, anyway to have that signal turned off so I can just hear the plugin? Thanks

**Comment by mdias** [comment]
> when I use Rocksmith with Neural DSP standalone plugin, if I click on the plugin then rocksmith mutes itself. Is there a way to keep them running independently?

This is standard behavior from Rocksmith. I believe [RSMods](https://github.com/Lovrom8/RSMods) provides a mod to still play audio while the game is in the background.

> Second, when I use standalone plugin I am also hearing the DI signal, anyway to have that signal turned off so I can just hear the plugin? Thanks

I've never used Neural DSP, but it sounds like you might have your interface direct monitoring on. If that's not the case then I don't know how to help you with Neural DSP. RS ASIO does not play the DI signal by itself.

**Comment by yianni54** [comment]
Hey MicaelThank you for the reply. I think your right about direct monitoring. Do you know how I should have it setup in Focusrite so it doesn’t play the DI? ThanksOn Dec 13, 2022, at 7:30 PM, Micael Dias ***@***.***> wrote:﻿

when I use Rocksmith with Neural DSP standalone plugin, if I click on the plugin then rocksmith mutes itself. Is there a way to keep them running independently?

This is standard behavior from Rocksmith. I believe RSMods provides a mod to still play audio while the game is in the background.

Second, when I use standalone plugin I am also hearing the DI signal, anyway to have that signal turned off so I can just hear the plugin? Thanks

I've never used Neural DSP, but it sounds like you might have your interface direct monitoring on. If that's not the case then I don't know how to help you with Neural DSP. RS ASIO does not play the DI signal by itself.

**Comment by mdias** [comment]
I just looked up your interface online, and it seems to be the big knob in front of the interface that says "Monitor", just rotate it to the side where you can still hear the game but not the guitar DI.

**Comment by yianni54** [comment]
Thanks! I have found a workaround through load tracks in reaper but just figured there has to be an easier way. On Dec 13, 2022, at 9:12 PM, Micael Dias ***@***.***> wrote:﻿
It also looks like you may have some Focusrite software to route audio, so you could also have monitoring through this software, but then I don't know how to help you. Please look it up in the manual or perhaps in youtube and you should be able to find out how to do it.

**Comment by mdias** [comment]
No problem
