### ISSUE TITLE
Distorted and delayed audio

### ISSUE THREAD

**Issue by OhKayBet** [mdias/rs_asio#337]
Audio is coming in distorted/choppy and delayed. I'm using an Rme Babyface pro fs. I'm an amateur when it comes to comprehending what logs say, could I get some help. From my understanding its saying Exclusive mode isn't going through because of the sample type? I'm unsure as to what it means by sample type though. Is it similar to sample rate or bit rate?

0.213 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.214 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.214 [INFO]    requested format is not supported
0.214 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.214 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.215 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.215 [INFO]    requested format is not supported
0.215 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT

I Have buffer size set to 1024 and sample rate set to 48k

Full Log.txt file
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10300640/RS_ASIO-log.txt)

Config Output
[Asio.Output]
Driver=ASIO Fireface USB
BaseChannel=0
AltBaseChannel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

Any help attempting to solve this would be appreciated thanks!

**Comment by mdias** [comment]
Those are expected "errors" while the game negotiates a compatible format, you can ignore them.

Your problem is most likely the fact that you're using a 1024 buffer size; you need something much smaller. Try something like 128.

**Comment by OhKayBet** [comment]
ive tried messing with the buffer size, but it doesnt help. Is there anything else that could be an issue?

**Comment by mdias** [comment]
Please post the log after running it with a 128 buffer size so I can have a look what's wrong.
Also post your full `RS_ASIO.ini` file.

**Comment by OhKayBet** [comment]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10306046/RS_ASIO-log.txt)
[RS_Asio.txt](https://github.com/mdias/rs_asio/files/10306063/RS_Asio.txt)

**Comment by mdias** [comment]
I see nothing wrong in your logs and it looks like RS ASIO is streaming audio for both input and output just fine without any xruns or similar.
I would assume your distorted sound might be coming from elsewhere.
The only weird thing I see in your config is that you're using the same channel for both Input 1 and input 2, and there's no reason to do that.

Have you tried any other ASIO-enabled software to check if it sounds fine there?
You might have some settings on your interface itself or it's drivers causing the issue.

**Comment by OhKayBet** [comment]
Hi, just seeing this. The audio in my DAW sounds fine and across all of the PC there's no issue with sound.
In regards of the input thing i was just messing with that on setup to see if it would hopefully change something.
Im not too sure what it could've been but its working fine now.

**Comment by OhKayBet** [comment]
Thank you for your help

**Comment by mdias** [comment]
Looking at the logs again, it seems your drivers are still only swapping buffers with a 1024 buffer size for whatever reason. We can see this here:
````
0.203 [INFO]  hdspfire - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.225 [INFO]  hdspfire - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.246 [INFO]  hdspfire - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
````

Now, while everything else in the log points out that 128 is the size in use, we can see from the timing on the log that your driver is not behaving this way.

If we look at the timings `0.203 -> 0.225 -> 0.246` we can see that there's a delta of ~0.021 seconds per swap, but a buffer size of 128 should result in a delta of (128 / 48000) ~0.002, meaning a swap every ~2ms.
If we calculate the delta for 1024 (1024 / 48000), it's ~0.021, which matches the swaps that you're seeing.

It seems something is behaving strangely with your drivers.
Regarding other applications working with 128 buffer size, I have no explanation, but something to be aware of is that your applications are most likely using your 64-bit drivers, while RS ASIO has to use the 32-bit ones.

**Comment by mdias** [comment]
Please also post your `Rocksmith.ini` file just in case there's something wrong there.
