### ISSUE TITLE
Can't get whole thing working properly

### ISSUE THREAD

**Issue by ri4ard55** [mdias/rs_asio#338]
Hello! First of all, I need to say that I'm not using RS_ASIO for what it was developed (i guess).
I have built-in soundboard and my problem is that in game I get sound only from left channel (of my guitar audio cable) which is completely unusable, so I need to cut off left channel to be able to play Rocksmith. Only thing I found as possible solution is RS_ASIO.

So, I've spent approximately all day to figure out how to make everything work but never achieved my goals. Maximum what I've been able to do is to get Output working, but when I get working Output, there is no working Input (no sound from guitar at all).

I've been trying to use different Universal ASIO drivers but without any real success.
Besides Rocksmith, I'm using Guitar Rig. Guitar Rig works absolutely fine with any of these ASIO 'drivers', but when I'm trying to use them with RS_ASIO then.. well, I've already described what happens.

List of drivers that I've tried to use:
ASIO4ALL V2;
--- When I turn on ASIO4ALL Input and Output - there is no any sound. If I turn on WASAPI Output, then "Another application has exclusive control of your audio output device" - "No output device is detected" errors appear (still no sound, obvious)
FlexASIO;
--- When I turn on FlexASIO Input and Output, "No output device is detected" error appear. If I turn on FlexASIO Input and WASAPI Output, then there is sound and actually I can hear some sound of guitar in Rocksmith, but Rocksmith itself doesn't appear to register this sound. Also, if I play any sound on guitar, sound goes for about 1sec and then whole game sound like disappears for 1sec. So, doesn't work properly any way.
ASIO2WASAPI;
--- When I turn on ASIO2WASAPI Input and Output, "No output device is detected" error appear. If I turn on WASAPI Output, then "Another application has exclusive control of your audio output device" - "No output device is detected" errors appear (still no sound, obvious)

Log files for everything I've described:
[1ASIO4ALL Input and Output.txt](https://github.com/mdias/rs_asio/files/10316173/1ASIO4ALL.Input.and.Output.txt)
[2ASIO4ALL Input and WASAPI Output.txt](https://github.com/mdias/rs_asio/files/10316174/2ASIO4ALL.Input.and.WASAPI.Output.txt)
[3FlexASIO Input and Output.txt](https://github.com/mdias/rs_asio/files/10316175/3FlexASIO.Input.and.Output.txt)
[4FlexASIO Input and WASAPI Output.txt](https://github.com/mdias/rs_asio/files/10316176/4FlexASIO.Input.and.WASAPI.Output.txt)
[5ASIO2WASAPI Input and Output.txt](https://github.com/mdias/rs_asio/files/10316177/5ASIO2WASAPI.Input.and.Output.txt)
[6ASIO2WASAPI Input and WASAPI Output.txt](https://github.com/mdias/rs_asio/files/10316178/6ASIO2WASAPI.Input.and.WASAPI.Output.txt)

**Comment by mdias** [comment]
I didn't quiet understand what you're experiencing about the left channel. Do you mean that you only hear out of the left speaker?

Also, as stated in the readme RS ASIO requires `Win32UltraLowLatencyMode=1` in Rocksmith.ini, which you don't seem to have enabled.

**Comment by ri4ard55** [comment]
> I didn't quiet understand what you're experiencing about the left channel. Do you mean that you only hear out of the left speaker?

No. Well, I didn't mention that I'm using 3.5mm to 6.3mm adapter (6.3mm Male - 3.5mm Female) and it is kinda transformating Mono signal from guitar into Stereo, but Channel 0 (left channel) is completely empty (except that sometimes if I try to get something really loud, I can hear some silent pieces of distorted sounds) and all normal sound from guitar goes only into Channel 1. That's what I meant.

**Comment by mdias** [comment]
I see. Be aware that guitar signal is much weaker than normal speaker signal, and so if you're connecting to your Line-In port for example you likely will hear either nothing at all, or a very low volume guitar.
Ideally you connect your guitar to a proper input port made for connecting instrument-level signal.

**Comment by ri4ard55** [comment]
> 

Yeah I know. That's why I'm connecting guitar through amplifier. Now I'm getting pretty nice quality/volume sound. But sadly, couldn't play Rocksmith because it listens only to problematic (for me) left channel.

**Comment by ri4ard55** [comment]
Ok I've just turned Low Latency mode on and, well, I've got pretty much what I was afraid of.
Heavily distorted terrific input sound, but at least the game was registering it. Changing LatencyBuffer value doesn't help.

For me, Ultra Low Latency mode acted same without RS_ASIO. 
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10322025/RS_ASIO-log.txt)

**Comment by mdias** [comment]
Since you're using ASIO4ALL instead of a true ASIO driver, a 64 buffer size might just be too small.
Try 256 with ASIO4ALL, and with Ultra Low Latency.
Remember that Ultra Low Latency is required for RS ASIO to work properly; now it's a matter of having ASIO4ALL working well enough for your use case.

However keep in mind that ASIO4ALL is often problematic with RS ASIO because of the tight timing requirements etc. Ideally your audio card would have a true ASIO driver.
