### ISSUE TITLE
Default Playback Device

### ISSUE THREAD

**Issue by Airtrooper719** [mdias/rs_asio#34]
Is it possible to bypass ASIO for the output only, but have the ASIO input.

For example, I'm using Axe-FX II for my input, but as I'm using a desktop audio enhancer, using ASIO output on rocksmith bypasses the desktop EQ.

I need to be able to leave the Axe-FX II as input and set my output device to the default that windows is using. In my case it is DFX FXSound application which is pulling audio from the Axe FX II. However, in windows I'm set to DFX Audio Enhancer output.

I have checked the RSASIO log but I believe it only shows ASIO supported drivers. Hope this makes sense.

**Comment by mdias** [comment]
Yes, it's possible. You need to open the RS_ASIO.ini and set `EnableWasapi=1` and leave the driver name for the output blank.

This will expose all normal audio devices to rocksmith, not expose the ASIO version of the output and expose the ASIO version of the input (if driver name of input is filled in the ini file).

It may or may not work though as your soundcard may show as busy if being used with ASIO.

**Comment by Airtrooper719** [comment]
Thanks for the response I'll give that a try and report back when I can.

Also big thanks for your hard work on the software, we really appreciate you.

________________________________
