### ISSUE TITLE
Yamaha Steinberg UR24C USB ASIO

### ISSUE THREAD

**Issue by m3talliz3d** [mdias/rs_asio#341]
- Input is showing feedback noise.
- Output is working good
- When setting input channel to **1** or **2** there is no sound at all.

_By feedback noise I mean like screaming sound like when you have two mobiles in the same room and you open speaker on both._ 

**Below is the ASIO-log.txt**
0.449 [INFO]  AsioHelpers::FindDrivers
0.454 [INFO]    ASIO4ALL v2
0.454 [INFO]    KATANA
0.454 [INFO]    Yamaha Steinberg USB ASIO
0.454 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Yamaha Steinberg USB ASIO
0.454 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
0.941 [INFO]    ASIO input channels info:
0.941 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: UR24C Input 1
0.941 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: UR24C Input 2
0.941 [INFO]    ASIO output channels info:
0.941 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: UR24C Mix L
0.941 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: UR24C Mix R
0.941 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: UR24C Output 2 L
0.941 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: UR24C Output 2 R
0.941 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK

**RS_ASIO.ini**
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio.Output]
Driver=Yamaha Steinberg USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Yamaha Steinberg USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
Please check your interface's DSP Mix software to ensure you don't have any special loopback mode or send going into your input channels.

**Comment by m3talliz3d** [comment]
Thanks Micael, I would like to thank you for the effort you have done on this project, I was that close to delete this game for the latency Tone Cable provided.

I forgot my Loopback on "Live cast" and once I turned it off, everthing worked great and latency and sound are perfect.

**Comment by m3talliz3d** [comment]
Thanks Micael, I would like to thank you for the effort you have done on this project, I was that close to delete this game for the latency Tone Cable provided.

I forgot my Loopback on "Live cast" and once I turned it off, everything worked great and latency and sound are perfect.

**Comment by mdias** [comment]
Thank you for reporting back. I've added this interface to the list too.
Enjoy 👍
