### ISSUE TITLE
"No audio output device detected"

### ISSUE THREAD

**Issue by santanacodes** [mdias/rs_asio#342]
Not sure if being on windows 11 is an issue, but every time I try to load in I get the error "No audio output device detected". Also nothing changes in my .log file even after I open up the game. I have tried using a fresh install and even different versions that I saw people using on Youtube, but still I get the same issue. I've made sure my Focustire gen 3 solo is set to 48k hz. Has anyone ever had this problem before?

**Comment by mdias** [comment]
Please post your `RS_ASIO.ini` and `RS_ASIO-log.txt` file contents.

**Comment by santanacodes** [comment]
[RS_ASIO.ini]
# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=


[RS_ASIO-log.txt]
0.000 [INFO]   - Wrapper DLL loaded (v0.6.3)
0.000 [INFO]  PatchOriginalCode
0.026 [INFO]  image crc32: 0xd1b38fcb
0.128 [INFO]  Patching CoCreateInstance
0.128 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.128 [INFO]  Patching call at 00C02DBD
0.128 [INFO]  Patching call at 00E75278
0.128 [INFO]  Patching PortAudio MarshalStreamComPointers
0.128 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.128 [INFO]  Patching call at 00E7483F
0.128 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.128 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.128 [INFO]  Patching call at 00E748F4
0.128 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.128 [INFO]  Patching bytes at 007C0C5F
0.129 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.129 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.129 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.129 [INFO]  AsioHelpers::FindDrivers
0.129 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.129 [INFO]    hr: 80070490
0.129 [INFO]    *ppEndpoint: 00000000
0.129 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.129 [INFO]    hr: 80070490
0.129 [INFO]    *ppEndpoint: 00000000
0.129 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.129 [INFO]    hr: S_OK
0.129 [INFO]    *ppDevices: 10F253C8
3.134 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
3.134 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
3.134 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
3.134 [INFO]  AsioHelpers::FindDrivers
3.134 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
3.134 [INFO]    hr: 80070490
3.134 [INFO]    *ppEndpoint: 00000000
3.134 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.134 [INFO]    hr: 80070490
3.134 [INFO]    *ppEndpoint: 00000000
3.134 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.134 [INFO]    hr: S_OK
3.134 [INFO]    *ppDevices: 10F247C8
3.136 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
68.546 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
68.688 [INFO]   - Wrapper DLL unloaded

**Comment by santanacodes** [comment]
# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by santanacodes** [comment]
0.000 [INFO]   - Wrapper DLL loaded (v0.6.3)
0.000 [INFO]  PatchOriginalCode
0.026 [INFO]  image crc32: 0xd1b38fcb
0.128 [INFO]  Patching CoCreateInstance
0.128 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.128 [INFO]  Patching call at 00C02DBD
0.128 [INFO]  Patching call at 00E75278
0.128 [INFO]  Patching PortAudio MarshalStreamComPointers
0.128 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.128 [INFO]  Patching call at 00E7483F
0.128 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.128 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.128 [INFO]  Patching call at 00E748F4
0.128 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.128 [INFO]  Patching bytes at 007C0C5F
0.129 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.129 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.129 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.129 [INFO]  AsioHelpers::FindDrivers
0.129 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.129 [INFO]    hr: 80070490
0.129 [INFO]    *ppEndpoint: 00000000
0.129 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.129 [INFO]    hr: 80070490
0.129 [INFO]    *ppEndpoint: 00000000
0.129 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.129 [INFO]    hr: S_OK
0.129 [INFO]    *ppDevices: 10F253C8
3.134 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
3.134 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
3.134 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
3.134 [INFO]  AsioHelpers::FindDrivers
3.134 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
3.134 [INFO]    hr: 80070490
3.134 [INFO]    *ppEndpoint: 00000000
3.134 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.134 [INFO]    hr: 80070490
3.134 [INFO]    *ppEndpoint: 00000000
3.134 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.134 [INFO]    hr: S_OK
3.134 [INFO]    *ppDevices: 10F247C8
3.136 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
68.546 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
68.688 [INFO]   - Wrapper DLL unloaded

**Comment by santanacodes** [comment]
I've just noticed that when setting my interface clock, I can go (24 bit, 48k hz) not (16 bit, 48 hz). Man I've been dying to be able to try this game!

**Comment by santanacodes** [comment]
IT WORKS. Cant believe I couldn't think of installing a simple driver. Thank you my friend it means a lot!

**Comment by mdias** [comment]
No problem, glad to hear you've got it working :)
Enjoy 👍
