### ISSUE TITLE
Not showing the proper RS_ASIO-logs

### ISSUE THREAD

**Issue by MxkeCoding** [mdias/rs_asio#344]
0.000 [INFO]   - Wrapper DLL loaded (v0.6.3)
0.000 [INFO]  PatchOriginalCode
0.022 [INFO]  image crc32: 0xbb2758fd
0.022 [ERROR]  Unknown game version
80.015 [INFO]   - Wrapper DLL unloaded

^is the log

**Comment by mdias** [comment]
You seem to have an unsupported version of the game installed. Usually this happens when people used cracked versions of the game or similar. RS ASIO only supports an up-to-date version of `Rocksmith 2014 Edition - Remastered` from Steam.

**Comment by criscola** [comment]
you might have more luck with this one https://github.com/Maxx53/NoCableLauncher @MxkeCoding
