### ISSUE TITLE
RS ASIO DLL

### ISSUE THREAD

**Issue by jlopsu5145** [mdias/rs_asio#345]
Hello, 

When I attempt to extract the files from 6.3 to versions 6.0 the dll disappears when I attempt to copy into rocksmith folder. Am I doing something wrong?

**Comment by mdias** [comment]
Hi,
The only explanation I can think of is you have some antivirus or antimalware that is quarantining the files immediately when you paste them on your game's folder.

**Comment by jlopsu5145** [comment]
I figured out that issue, I need to revert back to the JustIncaseWeNeedIT Beta since the October update in 2022. But now when my game starts it immediately crashes. I am currently using the Audient EVO4 and it seems to have been well received but I am having some troubles.

**Comment by jlopsu5145** [comment]
0.000 [INFO]   - Wrapper DLL loaded (v0.5.9)
0.000 [INFO]  PatchOriginalCode
0.162 [INFO]  Patching CoCreateInstance
0.162 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.162 [INFO]  Patching call at 01C5AA85
0.162 [INFO]  Patching call at 01F03B6E
0.162 [INFO]  Patching call at 01F5C681
0.162 [INFO]  Patching call at 01FAEF75
0.162 [INFO]  Patching call at 01FAF40D
0.162 [INFO]  Patching PortAudio MarshalStreamComPointers
0.162 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.162 [INFO]  Patching call at 01F03059
0.162 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.162 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.162 [INFO]  Patching call at 01F0310E
1.041 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
1.041 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
1.042 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
1.042 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
1.042 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
1.042 [INFO]  AsioHelpers::FindDrivers
1.042 [INFO]    Audient USB Audio ASIO Driver
1.042 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Audient USB Audio ASIO Driver
1.042 [INFO]  Creating AsioSharedHost - dll: c:\program files\audient\usbaudiodriver\x64\audientusbaudioasio.dll
1.051 [INFO]    ASIO input channels info:
1.051 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Mic | Line | Instrument 1
1.051 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Mic | Line 2
1.051 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Loop-back 1 (L)
1.051 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Loop-back 2 (R)
1.051 [INFO]    ASIO output channels info:
1.051 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Main Output 1 (L)
1.051 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Main Output 2 (R)
1.051 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Loop-back 1 (L)
1.051 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Loop-back 2 (R)
1.051 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
1.051 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Audient USB Audio ASIO Driver
1.051 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
1.051 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
1.051 [INFO]    hr: S_OK
1.051 [INFO]    *ppEndpoint: 0FD7A1E8
1.051 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
1.051 [INFO]    hr: S_OK
1.051 [INFO]    *ppEndpoint: 071B9B08
1.051 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
1.051 [INFO]    hr: S_OK
1.051 [INFO]    *ppDevices: 251085E0
1.051 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.051 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
1.051 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
1.051 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
1.051 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.051 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
1.051 [INFO]    *pDataFlow: eRender
1.051 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
1.051 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
1.051 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.051 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
1.051 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
1.051 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
1.051 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
1.051 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
1.051 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
1.052 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.052 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
1.052 [INFO]    *pDataFlow: eCapture
1.052 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
1.052 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
1.092 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
1.092 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
1.092 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
1.092 [ERROR]    failed to initialize asio driver with requested format
1.092 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.092 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
1.092 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
1.092 [ERROR]    failed to initialize asio driver with requested format
1.092 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.092 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
1.092 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
1.092 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
1.092 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
1.092 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 10ms (512 frames)
1.092 [INFO]  AsioSharedHost::Setup - startCount: 0
1.092 [INFO]    post output ready: 0
1.092 [INFO]    ASIOBufferSize - min: 8 max: 2048 preferred: 512 granularity: -1
1.092 [INFO]    Creating ASIO buffers (4 out, 4 in)...
1.092 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
1.092 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 2 | returning: 0
1.092 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 3 | returning: 0
1.092 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 4 | returning: 0
1.092 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 5 | returning: 0
1.092 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 6 | returning: 0
1.092 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
1.092 [INFO]    *pNumBufferFrames: 512
1.092 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
1.093 [INFO]    latency: 14ms
1.093 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
1.093 [INFO]    returning render client
1.093 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
1.095 [INFO]  Patched_PortAudio_MarshalStreamComPointers
1.096 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
1.096 [INFO]  {ASIO Out} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
1.096 [INFO]  {ASIO Out} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
1.096 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
1.096 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
1.096 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 512
1.096 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 512
1.096 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
1.096 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
1.096 [INFO]  AsioSharedHost::Start - startCount: 0
1.096 [INFO]    Starting ASIO stream...
1.107 [INFO]  Audient USB Audio ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
1.107 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 512
1.107 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 512
1.107 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
1.118 [INFO]  Audient USB Audio ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
1.118 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 512
1.118 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 512
1.118 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
1.128 [INFO]  Audient USB Audio ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
2.742 [INFO]  {ASIO Out} RSAsioAudioClient::OnAsioBufferSwitch - buffer underrun detected
2.743 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers

**Comment by mdias** [comment]
You're not using the latest version.
You should also be using a buffer size of 256 or less. Probably something like 128 or even less.

Also you should not need to run the `JustIncaseWeNeedIT` branch, but if you choose to run that and it keeps crashing, please check if it stops crashing without RS ASIO.

**Comment by jlopsu5145** [comment]
Yeah I can't use the most up to date RS asio version due to it deleting the DLL file evrytime. I will try to turn off my antivirus and see if it stays. I set my buffer size to 128 and it still crashed.

**Comment by jlopsu5145** [comment]
Update, able to download most recent RS ASIO after uninstalling Mcafee antivirus trial.

**Comment by mdias** [comment]
Does it work correctly now?

**Comment by jlopsu5145** [comment]
As of right now it is working correctly, only issue is if I drop my sample rate too low the sound cuts out 128 and 64 seem to work fine but 32 and 16 are super fuzzy and cut out any reason?

**Comment by mdias** [comment]
This is pretty normal and will happen with any ASIO enabled software although the max value may vary depending on the software.

The reason is that the lower the buffer size, the more frequently your CPU has to submit new buffers to the audio interface and this has an inherent cost by itself, but the benefit is lower latency. However don't forget that buffer latency for Rocksmith:
- 128 buffer size = ~2.7ms
- 64 buffer size = ~1.3ms
- 32 buffer size = ~0.7ms

So there's diminishing returns at very rapidly increasing costs in resource consumption.

There are many variables affecting the minimum buffer size you can achieve. The whole stack from RS ASIO -> driver -> OS -> CPU -> USB bus hardware -> audio interface and everything involved in between will have some sort of impact on the values you can achieve, but it's safe to say that if you're able to reach 64 samples per buffer without xruns (the audio issues you hear when going below that), you're already at a very good level of performance.
