### ISSUE TITLE
Scarlett Solo Gen 3, Voicemeeter, and RS_ASIO

### ISSUE THREAD

**Issue by Herbstein** [mdias/rs_asio#348]
I cannot for the life of me get Voicemeeter, my Scarlett Solo Gen 3, and RS_ASIO to play nice.

The only time I've been able to get any type of output from Rocksmith through Voicemeeter with this interface has been with the device buffer size set to 16. A value that is much too low, and results in a completely distorted output. But it _does_ result in output. Setting the device buffer size to anything else results in Voicemeeter not receiving any audio at all. Changing the CustomBufferSize value doesn't seem to have any impact, and neither does the LatencyBuffer setting.

I am able to play Rocksmith with RS_ASIO while going through the Scarlett Solo directly, and Voicemeeter works as it should for every other Windows and ASIO source I've tried.

#### System

* Windows 11
* Ryzen 3900X
* (assuming rest of the system would be irrelevant)

#### Voicemeeter

* ASIO Buffer: Default (aka: as in the device settings)
* Virtual ASIO Type: Int32LSB
* Preferred SampleRate: 48000 Hz
* ASIO SR: 48000 Hz

#### Device Settings

* Sample Rate: 48000 Hz
* Buffer Size: 16

#### RS_ASIO

```ini
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
BufferSizeMode=custom
CustomBufferSize=96

[Asio.Output]
Driver=Voicemeeter Virtual ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```

### Things I've tried

* Changing buffer size in device settings and/or in Voicemeeter. They're synced.
* Change ASIO Type to Float32LSB
* Change BaseChannel offset on the output
* Change CustomBufferSize
* Verify that ASIO through Voicemeeter works in general through an ASIO signal generator

### Help

I'm not sure what else to try, so I'm creating this issue.

Below are two log files. One is from when the device is configured to a buffer size of 16. The other from a device buffer size of 48. That is the only configuration change. During both of these runs I can start and stop playback of other audio through Voicemeeter without problems. I'm more than happy to provide additional data, information, or anything else you'd need

[RS_ASIO-log device buffer 16.txt](https://github.com/mdias/rs_asio/files/10669591/RS_ASIO-log.device.buffer.16.txt)
[RS_ASIO-log device buffer 48.txt](https://github.com/mdias/rs_asio/files/10669592/RS_ASIO-log.device.buffer.48.txt)

**Comment by mdias** [comment]
Which A1 hardware output do you have selected in Voicemeeter? You should have the ASIO one for Focusrite.

I'm also unsure how the Focusrite ASIO driver will behave if you try to use that driver directly from RS_ASIO while using that same driver in Voicemeeter.
You should have RS ASIO configured to use Voicemeeter's ASIO driver for both input and output and then on Voicemeeter's system settings patch the ASIO input to the appropriate device's input.

To make it easier at first you should try to make it run without any inputs in RS ASIO. Once you have proper output working then you can try to have input.
