### ISSUE TITLE
Lexicon Alpha input produces audio garbage (hissing)

### ISSUE THREAD

**Issue by srdo** [mdias/rs_asio#35]
Hi,

I'm trying to get audio input on a Lexicon Alpha working. I saw the earlier issue at https://github.com/mdias/rs_asio/issues/8, but it's not clear to me whether that user's issue was solved.

I'm using release 0.4.1 on Windows 10. The input in the game doesn't appear to work, and I'm only hearing loud hissing. The regular output from Rocksmith works fine, e.g. the intro music.

The input and output devices are set to 24-bit 48000hz, and I have also tried 16-bit. The devices are set to allow exclusive mode.

My rocksmith.ini is 

> [Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1

My RS_ASIO.ini is 

> > [Config]
> EnableWasapi=0
> EnableAsio=1
> 
> [Asio]
> ; available buffer size modes:
> ;    driver - respect buffer size setting set in the driver
> ;    host   - use a buffer size as close as possible as that requested by the host application
> ;    custom - use the buffer size specified in CustomBufferSize field
> BufferSizeMode=custom
> CustomBufferSize=128
> 
> [Asio.Output]
> Driver=Alpha ASIO driver
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> 
> [Asio.Input.0]
> Driver=Alpha ASIO driver
> Channel=0
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100

I have tried both channel 0 and 1 with no difference. I've verified that ASIO input works fine in another sound recorder program.
The log file is attached. 
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4270212/RS_ASIO-log.txt)

No settings jumps out at me as obviously wrong. Any ideas?

**Comment by wisamasd** [comment]
Your card has 2 inputs, HIGH and MIC. You don't need to change the channel, but the input. Try it as is the case with Focusrite to use the section `[Asio.Input.1]`

**Comment by srdo** [comment]
Thanks for taking a look. I tried with these settings

> [Asio.Input.0]
> Driver=
> Channel=0
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> 
> [Asio.Input.1]
> Driver=Alpha ASIO driver
> Channel=1
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100

and it made no difference. I tried leaving out the `[Asio.Input.0]` section, and separately tried setting the `[Asio.Input.1]` channel to 0. I'm still just getting a loud hiss.

**Comment by mdias** [comment]
This is likely to do with the 24-bit format not being handled properly.

There is no difference between "Asio.Input.0" and "Asio.Input.1" except for providing 2 inputs to the game that can be assigned to 2 different input ports on your device.

I'll look into this.

**Comment by mdias** [comment]
Please try [this new release](https://github.com/mdias/rs_asio/releases/tag/v0.4.2) and let me know if it worked :)

**Comment by srdo** [comment]
It works really well. Thank you so much. I'm hearing the very rare audio pop, but that might be fixed by trying out a larger buffer size. I think you can go ahead and add Lexicon Alpha to the list :)
