### ISSUE TITLE
Audio device not detected when using voicemeter as asio output 

### ISSUE THREAD

**Issue by L3apr** [mdias/rs_asio#350]
I tried everything i know i could try and i can't get it to work

> 0.000 [INFO]   - Wrapper DLL loaded (v0.6.3)
0.000 [INFO]  PatchOriginalCode
0.027 [INFO]  image crc32: 0xd1b38fcb
0.120 [INFO]  Patching CoCreateInstance
0.120 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.120 [INFO]  Patching call at 00C02DBD
0.120 [INFO]  Patching call at 00E75278
0.120 [INFO]  Patching PortAudio MarshalStreamComPointers
0.120 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.120 [INFO]  Patching call at 00E7483F
0.120 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.120 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.120 [INFO]  Patching call at 00E748F4
0.120 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.120 [INFO]  Patching bytes at 007C0C5F
0.606 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.606 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.606 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.606 [INFO]  AsioHelpers::FindDrivers
0.606 [INFO]    ASIO4ALL v2
0.606 [INFO]    FL Studio ASIO
0.606 [INFO]    KATANA
0.607 [INFO]    Voicemeeter AUX Virtual ASIO
0.607 [INFO]    Voicemeeter Insert Virtual ASIO
0.607 [INFO]    Voicemeeter Potato Insert Virtual ASIO
0.607 [INFO]    Voicemeeter VAIO3 Virtual ASIO
0.607 [INFO]    Voicemeeter Virtual ASIO
0.607 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Voicemeeter AUX Virtual ASIO
0.607 [INFO]  Creating AsioSharedHost - dll: c:\program files (x86)\vb\voicemeeter\vbvmaux_asiodriver.dll
0.680 [INFO]    ASIO input channels info:
0.680 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 1
0.680 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 2
0.680 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 3
0.680 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 4
0.680 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 5
0.680 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 6
0.680 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 7
0.680 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 8
0.680 [INFO]    ASIO output channels info:
0.680 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 1
0.680 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 2
0.680 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 3
0.680 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 4
0.680 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 5
0.680 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 6
0.680 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 7
0.680 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 8
0.680 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.680 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: KATANA
0.680 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
0.685 [INFO]    ASIO input channels info:
0.685 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: PRIMARY
0.685 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: PRIMARY(R)
0.685 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: SECONDARY
0.685 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: SECONDARY(R)
0.685 [INFO]    ASIO output channels info:
0.685 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: PRIMARY
0.685 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: PRIMARY(R)
0.685 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: SECONDARY
0.685 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: SECONDARY(R)
0.685 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.685 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.685 [INFO]    hr: S_OK
0.685 [INFO]    *ppEndpoint: 14FD6BD8
0.685 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.685 [INFO]    hr: S_OK
0.685 [INFO]    *ppEndpoint: 14FD6C98
0.685 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.685 [INFO]    hr: S_OK
0.685 [INFO]    *ppDevices: 0243D7E8
0.686 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.686 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.686 [INFO]    *cProps: 2
0.686 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.686 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.686 [INFO]    *pDataFlow: eRender
0.686 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.686 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.686 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.686 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.686 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.686 [INFO]    *cProps: 5
0.686 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.686 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.686 [INFO]    *pDataFlow: eCapture
0.686 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.686 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.686 [INFO]  {ASIO IN 0} RSAsioAudioClient::~RSAsioAudioClient
0.697 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.697 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.697 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
0.697 [ERROR]    shared mode is not supported
0.697 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.697 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.697 [INFO]  Destroying AsioSharedHost - dll: c:\program files (x86)\vb\voicemeeter\vbvmaux_asiodriver.dll
0.697 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
1.917 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
1.917 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
1.917 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
1.917 [INFO]  AsioHelpers::FindDrivers
1.917 [INFO]    ASIO4ALL v2
1.917 [INFO]    FL Studio ASIO
1.917 [INFO]    KATANA
1.917 [INFO]    Voicemeeter AUX Virtual ASIO
1.917 [INFO]    Voicemeeter Insert Virtual ASIO
1.917 [INFO]    Voicemeeter Potato Insert Virtual ASIO
1.917 [INFO]    Voicemeeter VAIO3 Virtual ASIO
1.917 [INFO]    Voicemeeter Virtual ASIO
1.917 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Voicemeeter AUX Virtual ASIO
1.917 [INFO]  Creating AsioSharedHost - dll: c:\program files (x86)\vb\voicemeeter\vbvmaux_asiodriver.dll
1.990 [INFO]    ASIO input channels info:
1.990 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 1
1.990 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 2
1.990 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 3
1.990 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 4
1.990 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 5
1.990 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 6
1.990 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 7
1.990 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 1, type: ASIOSTFloat32LSB, name: VM-VAIO 8
1.990 [INFO]    ASIO output channels info:
1.990 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 1
1.990 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 2
1.990 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 3
1.990 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 4
1.990 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 5
1.990 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 6
1.990 [INFO]      6 - active: 0, channel: 6, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 7
1.990 [INFO]      7 - active: 0, channel: 7, group: 0, isInput: 0, type: ASIOSTFloat32LSB, name: VM-VAIO 8
1.990 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
1.990 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: KATANA
1.991 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
1.996 [INFO]    ASIO input channels info:
1.996 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: PRIMARY
1.996 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: PRIMARY(R)
1.996 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: SECONDARY
1.996 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: SECONDARY(R)
1.996 [INFO]    ASIO output channels info:
1.996 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: PRIMARY
1.996 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: PRIMARY(R)
1.996 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: SECONDARY
1.996 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: SECONDARY(R)
1.996 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
1.996 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
1.996 [INFO]    hr: S_OK
1.996 [INFO]    *ppEndpoint: 15217848
1.996 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
1.996 [INFO]    hr: S_OK
1.996 [INFO]    *ppEndpoint: 15217698
1.996 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
1.996 [INFO]    hr: S_OK
1.996 [INFO]    *ppDevices: 151159B8
1.996 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.996 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.996 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
1.996 [INFO]    *pDataFlow: eRender
1.996 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.996 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.996 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
1.996 [INFO]    *pDataFlow: eCapture
2.003 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
2.820 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
2.820 [INFO]  Destroying AsioSharedHost - dll: c:\program files (x86)\vb\voicemeeter\vbvmaux_asiodriver.dll
2.820 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\SysWOW64\RDAW1179.DLL
2.906 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
You are not using exclusive mode.
Please [read the instructions](https://github.com/mdias/rs_asio#how-to-use).

**Comment by L3apr** [comment]
> You are not using exclusive mode. Please [read the instructions](https://github.com/mdias/rs_asio#how-to-use).

It was disabled from troubleshooting, but it didn't work with it enabled as well. I still tried it now with exclusive mode enabled and it now somehow detected it, but the audio is distorted as in sampling issue distortion and the ga
me crashed after a few seconds.
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10714725/RS_ASIO-log.txt)

**Comment by mdias** [comment]
You seem to be running into xruns with a 48 sample buffer for input. Yous hould try to increase it.
Also, what do you have as your main (A1) output in Voicemeeter? If you're trying to use the same Katana device as the input it might not be a good idea to have RS_ASIO trying to access the audio interface at the same time as Voicemeeter. In this case you should patch your interface's input to go through Voicemeeter's input and setup RS_ASIO to also use Voicemeeter as input.

At the moment it looks very odd that your output (Voicemeeter) is trying to use a 320 sample buffer size while your input is trying to use a 48 sample buffer size.

**Comment by L3apr** [comment]
`At the moment it looks very odd that your output (Voicemeeter) is trying to use a 320 sample buffer size while your input is trying to use a 48 sample buffer size.`

Output is a pair of usb headphones, non asio, i will try to increase the asio input buffer size and see if anything changes.

**Comment by L3apr** [comment]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10717119/RS_ASIO-log.txt)

Latest log with it working so you know what is going on.

**Comment by mdias** [comment]
> Output is a pair of usb headphones, non asio

The log shows you're using `Voicemeeter AUX Virtual ASIO` for the output.

If you mean that Voicemeeter itself is using a non-ASIO output as the main A1 output, this is likely the problem.
If you're able to select your KATANA device for the A1 output, please do that and then disable ASIO output in RS_ASIO.ini and instead enable the Wasapi outputs so that sound output goes to your main output as if you didn't have RS_ASIO. This will ensure only the input is ASIO and output skips ASIO altogether.

**Comment by mdias** [comment]
In fact, now that I think about it, you don't require Voicemeeter at all for this setup, unless you're trying to do something else.

**Comment by L3apr** [comment]
> If you mean that Voicemeeter itself is using a non-ASIO output as the main A1 output, this is likely the problem.

Yes, voicemeter is using my headphones as an output, and i use voicemeter because these headphones don't have an asio driver ( and asio4all sucks), and i want to record the output and also redirect it to discord, so i need voicemeter, But thanks for the help, as i now got it working with 128 bufer on asio input and on a1 voicemeter output

**Comment by mdias** [comment]
Happy to hear it's working fine now :)
