### ISSUE TITLE
Focursite Scarlett Solo 3rd Gen No Input-Output.

### ISSUE THREAD

**Issue by tzeetzee** [mdias/rs_asio#351]
For the last 3 days I have been going through RS_ASIO trying to get it to work with my Focusrite Scarlett Solo 3rd Gen and for the love of god I can't get Rocksmith 2014 to see my damn bass guitar and detect my speakers (output). 

### **Specs**
- Win 10 22H2
- i5-6600K
- Scarlett connected through: USB

**Focusrite Control Settings**
- Sample Rate set to: 44100hz
- Buffer Size set to: 48

### **My Current RS_ASIO.ini:**
https://github.com/mdias/rs_asio/blob/master/docs/focusrite_solo/README.md
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
;Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

I'm aware that Channel 1 is likely the instrument channel for the Scarlett Solo, although changing to `Channel=0` in either `[Asio.Input]` does nothing and in all occasions never was a "Real Tone" cable detected. (https://imgur.com/a/oChfRvv)

The things I've tried are:
- Put semicolons ( ; ) through the whole `[Asio.Input.0]` as said in [this](https://www.reddit.com/r/rocksmith/comments/evi0o2/rocksmith_and_scarlett_solo_gen_3_easy_thanks_to/) reddit post (basically copy pasting his RS_ASIO.ini)
- Downgrading to earlier releases of RS_ASIO like 0.4.2 and 0.3.7 which fortunately **got only the output working**. Although with the latest version of RS_ASIO 0.6.3 it brings up ERROR SOUND INITIALIZATION on startup (https://imgur.com/a/M3LguP1) and neither the output nor the input is working
- Uninstalling ASIO4ALL and Focusrite Thunderbolt drivers (incase they interfere)

### **Am I doing something wrong here?**
I have absolutely no audio and I've tried everything my smooth low IQ brain has thought of. I genuinely don't know what to do next with this goddamn audio interface and I don't get why Ubisoft has got to make connecting another audio interface other than theirs so freaking hard!! And no way in hell do I want to play Rocksmith by mic input as my mic is very crappy.

Honestly, mdias if you'd help me it would be much much appreciated :D

**Comment by tzeetzee** [comment]
My most recent log: https://pastebin.com/3yXUZvmP

**Comment by mdias** [comment]
You are not using Exclusive Mode as [stated in the instructions](https://github.com/mdias/rs_asio#how-to-use).

**Comment by tzeetzee** [comment]
Thank you so much!! I went by the reddit guide and it never said to change that setting... I told you I have a smooth brain
