### ISSUE TITLE
Unknown game version

### ISSUE THREAD

**Issue by ProtoxViler** [mdias/rs_asio#352]
All in the title.
Just here my log :
0.000 [INFO]   - Wrapper DLL loaded (v0.6.3)
0.000 [INFO]  PatchOriginalCode
0.019 [INFO]  image crc32: 0xbb2758fd
0.019 [ERROR]  Unknown game version
167.403 [INFO]   - Wrapper DLL unloaded

Its a cracked game (sry for that) with the update 7
Its all info i have about the game

**Comment by ProtoxViler** [comment]
I forgot to say, the game is a crack :/

**Comment by mdias** [comment]
Only the official version is supported.

**Comment by ProtoxViler** [comment]
I make a mistake, the crack that I downloaded was not the remaster of the game, so normal, but now it's ok

**Comment by tlacloc** [comment]
> I make a mistake, the crack that I downloaded was not the remaster of the game, so normal, but now it's ok

where did you get the remastered version?
