### ISSUE TITLE
Rocksmith isnt detecting my audio device...

### ISSUE THREAD

**Issue by Damian-dev-ops** [mdias/rs_asio#354]
I use a Bose headset (usb into the pc) and i have a focusrite 2i2 3rd gen, and im getting the error of "no audio output...please restart"
![image](https://user-images.githubusercontent.com/59776493/221062241-8139ed8d-4952-4281-a71d-377b761b90b6.png)

My bose headset is set to default and is at 48k
My focusrite is set to 48k
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10819577/RS_ASIO-log.txt)
![image](https://user-images.githubusercontent.com/59776493/221062047-93c53e2f-25df-42a8-8409-cd305fc5bac9.png)
![image](https://user-images.githubusercontent.com/59776493/221062090-e6a13656-c723-48d9-af6f-55d70b85f695.png)

My ini configuration:
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite USB Audio
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
If you want to use your headset set `EnableWasapiOutputs=1` in RS_ASIO.ini

**Comment by Damian-dev-ops** [comment]
gotcha testing it now.

**Comment by Damian-dev-ops** [comment]
Got it to work thank you man!
