### ISSUE TITLE
Everything seems like its working...

### ISSUE THREAD

**Issue by Damian-dev-ops** [mdias/rs_asio#355]
But once I load up a song it doesnt read my playing, however I can see the speakers doing that spiky shiz and hear the guitar.

My setup is a focusrite 2i2 3rd gen, and bose QC35II.

Video showcasing it: https://youtu.be/KXRfFmDqAwM

Im rather confused and dont understand this issue.

Rocksmith ini:
[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1920
ScreenHeight=1080
Fullscreen=2
VisualQuality=2
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1

ASIO ini:
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1
[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48k
[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
Your `CustomBufferSize=48k` config should be `CustomBufferSize=48` instead.

**Comment by Damian-dev-ops** [comment]
Okay, I'll give it a shot.

**Comment by Damian-dev-ops** [comment]
It still isn't reading my notes, even after editing it.

**Comment by mdias** [comment]
Please post the contents of your RS_ASIO-log.txt file.

**Comment by Damian-dev-ops** [comment]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10832844/RS_ASIO-log.txt)

**Comment by mdias** [comment]
Please let the game reach at least the main menu as otherwise it hasn't initialized everything yet and the log is very incomplete.
After that close the game and send the log again.

**Comment by Damian-dev-ops** [comment]
I let the game it the main menu, should I wait a couple minutes before sending the log?

**Comment by Damian-dev-ops** [comment]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/10832864/RS_ASIO-log.txt)
Just closed the game.

**Comment by mdias** [comment]
There doesn't seem to be anything particularly wrong on the log apart from some xruns happening every once in a while. You should be able fix those by increasing the buffer size from 48 to 96 or so, but I suspect this may not be enough to fix the issue you're having.

Ignoring the input, does the game itself play it's sounds fine? Like, do you hear all the music etc just fine and it's only the guitar that doesn't seem to be working?

**Comment by Damian-dev-ops** [comment]
Alrighty I'll increase it to 96.

Yeah the game's audio is working just fine and I hear all the music and such, just the guitar input not working.

**Comment by mdias** [comment]
Do you have your guitar plugged in the first input? If not, try that.
Also if you're able, please check with any other ASIO enabled software to see if you can record/hear your guitar there. Something like Guitar Rig 6 demo or similar would do.

**Comment by Damian-dev-ops** [comment]
The first input on the Focusrite I have is for microphones, while the second input where my guitar is plugged in. I'm going to download guitar rig 6 to see if it will detect the guitar.

**Comment by mdias** [comment]
In this case your input config should look like this:
```
[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```

(Note that the first input has the `Driver=` setting empty)

**Comment by Damian-dev-ops** [comment]
Ahh... I see my bad I'll give it a whirl.

**Comment by Damian-dev-ops** [comment]
I can hear the audio and it reads it, however it still doesn't register the notes I'm playing.

**Comment by mdias** [comment]
If you can hear your guitar from the game sound, that means RS ASIO should be good now.
To fix note detection you should calibrate the guitar in the game, tune it and ensure it's properly intonated.
