### ISSUE TITLE
No audio output device detected, then immediately crashes

### ISSUE THREAD

**Issue by Noiroja** [mdias/rs_asio#358]
Have tried to fix this at multiple points even getting a new audio interface and still cannot fix the issue with ASIO.
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/11035470/RS_ASIO-log.txt)
I try launching the game, gives me the usual "No audio output detected" before immediately telling me RS has crashed.

**Comment by mdias** [comment]
Do you have your interface connected through thunderbolt?

**Comment by Alexbeav** [comment]
Try using WASAPI Output

**Comment by Noiroja** [comment]
> Do you have your interface connected through thunderbolt?

I switched from thunderbolt to USB to see if that changes anything, as well as switching between WASAPI Output. Previously it would give me that "No audio output detected" for a split second before crashing, now it just crashes, so I'm not sure if that changed anything in a meaningful fashion.

**Comment by mdias** [comment]
Does it also crash without RS_ASIO?
What is your CPU? There is a known issue with the game when using a CPU with more than 32 threads.

**Comment by Noiroja** [comment]
Rocksmith does still crash without RS_Asio enabled, and goes back to giving the 'not detecting audio' box before crashing. CPU is AMD Ryzen 9 5900X 12-core, 24 threads.

**Comment by mdias** [comment]
Sounds like the crash is unrelated to RS_ASIO.
Unfortunately I don't know how you'd go about fixing this. I have heard cases in the past of it ceasing to work after certain windows updates etc, and other stories of fixing the crash by re-installing windows, but I personally never had this kind of crashes with or without RS_ASIO so I'm unable to help further.
