### ISSUE TITLE
Boss Katana Air support

### ISSUE THREAD

**Issue by dronky** [mdias/rs_asio#359]
Tested. Works either with wireless adaptor or via cable input.

```
[Asio.Output]
Driver=KATANA
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=KATANA
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by mdias** [comment]
Thank you for the report. Added to the list 👍

**Comment by aNo2masss** [comment]
Hi, dronky.My Katana Air still cannot be recognized after entering the game according to your settings. Is your playback 48kHz? I cannot set it to 48 Khz.
