### ISSUE TITLE
Nothing gets patched

### ISSUE THREAD

**Issue by vedi-advatange** [mdias/rs_asio#36]
No sound of course. Is it a problem with my Rocksmith distro?

Here are my RS-ASIO-log.txt contents:

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4277297/RS_ASIO-log.txt)

**Comment by vedi-advatange** [comment]
Rocksmith v165.260519

**Comment by mdias** [comment]
Only `Rocksmith 2014 Edition - Remastered` is supported by RS ASIO at this time.
