### ISSUE TITLE
Works with NUX Mighty Air - WIRELESS ASIO Rocksmith!

### ISSUE THREAD

**Issue by DudeInMyrtleBeach** [mdias/rs_asio#364]
Set NUX ASIO control panel Preferred ASIO Buffer Size to 128. 
Set in Rocksmith.ini:
LatencyBuffer=3

Set in RS_ASIO.ini
[Asio.Input.Mic]
Driver=NUX Audio
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

That's it! Easy peasy no latenc-eesie! (Sounded better in my head...)

That's right ... a totally WIRELESS ASIO interface to Rocksmith!!

**Comment by mdias** [comment]
Thanks. Added to the list 👍
