### ISSUE TITLE
Displaying a RS_ASIO.dll error

### ISSUE THREAD

**Issue by pacmcman** [mdias/rs_asio#365]
I've tried many different methods but can't find any to fix this issue so I can use my focusrite on rocksmith 2014. I have noticed that when I drag the 3 files into the game filels, all but that file go into it. I tried extracting but this doesn't work. Any ideas would help greatly.
Thank you

**Comment by mdias** [comment]
You might have some kind of antivirus detecting it as a falso positive and immediately removing the files.

**Comment by pacmcman** [comment]
ok thank you i'll try and see if that is the issue :)
