### ISSUE TITLE
Randomly crashes at Rocksmith launch

### ISSUE THREAD

**Issue by DariuszDro** [mdias/rs_asio#367]
Hi, I wanted to report an issue which to me is not clear why it happens. 1 out of maybe 20 game launches is successful but for others the game is stuck at the white screen with rocksmith logo in the right bottom corner and then crash.

I'm not changing any settings to either game, music interface, sound settings, config files. It just happens that sometimes it runs and sometimes not. This seems to be like an rs_asio bug.

I managed to get 2 log files, one generated after successful game start and one where it crashes.
[crash_RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/11563721/crash_RS_ASIO-log.txt)
[working_RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/11563723/working_RS_ASIO-log.txt)

I'm using Focusrite Scarlett solo 3gen and the 0.6.3 version of rs_asio.
Rocksmith is patched with standard mod to work with CDLC after that last steam update broke it.

Here is my Rocksmith.ini file
[Rocksmith.ini.txt](https://github.com/mdias/rs_asio/files/11563757/Rocksmith.ini.txt)

**Comment by mdias** [comment]
Are you by any chance using mods such as the Fast Load mod?

**Comment by DariuszDro** [comment]
No, no additional mods other than the one I mentioned which is the https://ignition4.customsforge.com/tools/cdlcenabler . Does the log provide any clue on what might be going wrong in the library?

**Comment by mdias** [comment]
There is no clue in the log of anything going wrong.
Does it work fine every time without RS ASIO?

**Comment by DariuszDro** [comment]
Yes, when I remove rs_asio then it's working fine. I'll close this issue as it might be something specific to my system (I noticed for example that when I don't connect external monitor to my laptop then it pretty much always runs without problem with rs_asio). Thanks for the help anyway.
