### ISSUE TITLE
Sound Error Initialization

### ISSUE THREAD

**Issue by SLEID66** [mdias/rs_asio#368]
Hello, I just bought Rocksmith 2014 on Steam today, downloaded rs asio and i get ''Sound Error Initialization'' every time i start the game. I have an SSL2 interface and an Ibanez guitar, could you help please?

**Comment by mdias** [comment]
You need to post the contents of RS_ASIO.ini, RS_ASIO-log.txt and Rocksmith.ini

**Comment by SLEID66** [comment]
I tried without the RS Asio and now it's working fine with my guitar connected to the interface, idk if it's using the SSL Asio or something, is there a point to get the RS ASIO anyway?

**Comment by mdias** [comment]
Well, if it's working fine, it's up to you if you feel the need for ASIO.
Usually ASIO will provide a more direct signal path between the game and the interface, which may result in decreased latency etc.

It's very strange that you got it to work with your interface without any sort of mod though.

**Comment by SLEID66** [comment]
Well, the latency is fine, the only issue which i don't know if it has anything to do with it, but i don't really hear my in-game guitar, i hear a song when i'm playing, but on the menu and in general, i don't hear it. Also, i have FL Studio Asio and the Asio of my interface as well, so maybe those are enough. But i'm curious if you know anything about the guitar sound in the game, i don't use any amp.

**Comment by mdias** [comment]
You're probably using microphone mode of Rocksmith instead of RealTone Cable mode...
RS ASIO is meant to replace the RealTone Cable, not to just act as a mic.

**Comment by SLEID66** [comment]
Yes, it's microphone mode, is that why i can't hear the guitar?

**Comment by mdias** [comment]
Yes.

**Comment by SLEID66** [comment]
I have made it work, thanks for your time though.
