### ISSUE TITLE
question: using rs_asio input only

### ISSUE THREAD

**Issue by damnms** [mdias/rs_asio#370]
hi, i have a htpc that uses its graphic card to signal audio to the avr (and video of course).
i would like to use rocksmith rs asio on a focusrite scarlett 2i2 usb to input the guitar signal into the htpc, but the audio out should be my marantz (htpc->avr). is that possible? or do i have to use asio4all, create some sort of dummy device and reroute the audio signal?

**Comment by mdias** [comment]
It should be possible.
Something like this in the config:

```
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

[Asio.Output]
Driver=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

This should have the game using the default audio card/interface for the output as if RS ASIO was not in use, but still use RS ASIO for the input.
Tweak buffer size and input channel number as needed.

**Comment by damnms** [comment]
thanks @mdias that worked. but i have some cracking/stuttering when playing and a bit high latency. any clue how i should change the buffer size? whats reasonable? or should i go with driver or host in asio?
