### ISSUE TITLE
"No audio output device is detected"

### ISSUE THREAD

**Issue by Draggo1** [mdias/rs_asio#371]
https://pastebin.com/6qq08Cvu

Not sure what's going on; I followed this tutorial to a T and it's still not working. https://youtu.be/5faVrz-ZD3k

**Comment by Draggo1** [comment]
I rechecked the install guide and ticked the settings it says. It's still giving me errors though
https://pastebin.com/zvDrmnvm

**Comment by Draggo1** [comment]
I looked at some closed issues. Okay now I've gotten the prompt to go away and the game loads normally, but I have no game audio or anything. 

Rocksmith.ini
https://pastebin.com/wiFCEhR6
RS_ASIO.ini
https://pastebin.com/gPtLMh9P
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/11987262/RS_ASIO-log.txt)

**Comment by Draggo1** [comment]
I got it working now, but the audio is extremely distorted and if I set it to below 176 buffer rate I can't hear anything anymore. before I just turned low latency mode off and it solved it before I found out about this, but obviously I can't turn it off now.

**Comment by mdias** [comment]
Your RS_ASIO.ini config shows you're trying to use ASIO only for the input, and WASAPI for the output, but the log only shows the WASAPI output being initialized. Are you sure that log is from that config?

You're also using `ReaRoute ASIO` for the input, but does it work if you use directly the ASIO drivers of your audio interface? Which audio interface is it by the way?

Reading your last message it appears the whole output is distorted; but if you're using WASAPI for output, this goes around RS_ASIO and there's not much I can do there.

**Comment by Draggo1** [comment]
Sorry I went on Vacation. I just kept getting nothing when I tried routing it through ReaRoute ASIO for the output. It'd constantly say "No Audio Output Device is Detected". Enabled it quickly, and here is the logs. 
[Rocksmith.txt](https://github.com/mdias/rs_asio/files/12045589/Rocksmith.txt)
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/12045590/RS_ASIO.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/12045591/RS_ASIO-log.txt)

**Comment by Draggo1** [comment]
I'm using it through Reaper. I wanted to use a plugin that allows me to tune my strings down so I can play more things.

**Comment by mdias** [comment]
I understand, but first and foremost we need to know if it works without going through Reaper; only then we should attempt to send it through Reaper.

In any case, in your config you have:
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=0
```

Which means you're disabling every audio driver type. You'll need `EnableAsio=1` to be able to use ReaRoute ASIO.
