### ISSUE TITLE
RSAsio + WineASIO with Scarlett Solo (3rd Gen)

### ISSUE THREAD

**Issue by snypervash** [mdias/rs_asio#373]
To preface, I believe I have jack setup correctly. Whenever I launch Rocksmith, RSAsio cannot seem to find my Scarlett Solo 3rd Gen. My computer detects it just fine and I can even use it outside of rocksmith. Attaching my RSAsio Log.

0.000 [INFO]   - Wrapper DLL loaded (v0.6.3)
0.000 [INFO]  PatchOriginalCode
0.026 [INFO]  image crc32: 0xd1b38fcb
0.117 [INFO]  Patching CoCreateInstance
0.117 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.117 [INFO]  Patching call at 00C02DBD
0.117 [INFO]  Patching call at 00E75278
0.117 [INFO]  Patching PortAudio MarshalStreamComPointers
0.117 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.117 [INFO]  Patching call at 00E7483F
0.117 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.117 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.117 [INFO]  Patching call at 00E748F4
0.117 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.117 [INFO]  Patching bytes at 007C0C5F
0.117 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.117 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.117 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.117 [INFO]  AsioHelpers::FindDrivers
0.118 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 0 capture devices
0.118 [INFO]    hr: S_OK
0.118 [INFO]    *ppEndpoint: 066EE9A0
0.118 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.118 [INFO]    hr: 80070490
0.118 [INFO]    *ppEndpoint: 00000000
0.118 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.118 [INFO]    hr: S_OK
0.118 [INFO]    *ppDevices: 0851BC90
0.118 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.121 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperDevicePropertyStore::GetCount
0.121 [INFO]    *cProps: 8
0.122 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.122 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperEndpoint::GetDataFlow
0.122 [INFO]    *pDataFlow: eRender
0.122 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.122 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::GetDevicePeriod
0.123 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.123 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::IsFormatSupported - ShareMode: Shared
0.123 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::Initialize - ShareMode: Shared Flags: 0 bufferDuration: 10ms periodicity: 0ms
0.130 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::GetBufferSize
0.130 [INFO]    *pNumBufferFrames: 1440
0.130 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::GetStreamLatency
0.130 [INFO]    latency: 20ms
0.130 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::GetService - riid: IID_IAudioRenderClient
0.130 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.130 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.131 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.131 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.131 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
0.131 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
0.131 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::Start
0.133 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
0.133 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
0.135 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
0.135 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
1.883 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::Stop
11.934 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
11.934 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::IsFormatSupported - ShareMode: Shared
11.934 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::Initialize - ShareMode: Shared Flags: 0 bufferDuration: 10ms periodicity: 0ms
11.940 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::GetBufferSize
11.940 [INFO]    *pNumBufferFrames: 1440
11.940 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::GetStreamLatency
11.940 [INFO]    latency: 20ms
11.940 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::GetService - riid: IID_IAudioRenderClient
11.940 [INFO]  Patched_PortAudio_MarshalStreamComPointers
11.941 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
11.941 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
11.941 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
11.941 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
11.941 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::Start
11.943 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
11.943 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
11.945 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 256
11.945 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 256
12.859 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
12.859 [INFO]  {0.0.0.00000000}.{FD47D9CC-4218-4135-9CE2-0C195C87405B} DebugWrapperAudioClient<struct IAudioClient>::Stop
13.008 [INFO]   - Wrapper DLL unloaded

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/12044736/RS_ASIO-log.txt)

**Comment by mdias** [comment]
RS_ASIO is not finding any ASIO drivers installed in your system, otherwise they would show up next to `0.117 [INFO]  AsioHelpers::FindDrivers`

Keep in mind the game is a 32-bit application, as well as RS_ASIO so it needs 32-bit ASIO drivers properly registered in the system.

**Comment by snypervash** [comment]
The winetricks prefix I have it installed in is definitely 32 bit, I accidentally did 64 bit for the first one and realized my mistake and created a new one.

**Comment by mdias** [comment]
RS_ASIO searches for available ASIO drivers in the registry; more specifically `HKEY_LOCAL_MACHINE\SOFTWARE\ASIO` and then somewhere in `HKEY_CLASSES_ROOT` depending on the CLSID of the registered drivers.

I assume your WineASIO is not properly registered.

**Comment by snypervash** [comment]
Is there a defacto guide to follow? Its possible the one I follow was incorrect and I'd like to start from scratch

**Comment by mdias** [comment]
There is no defacto guide and I don't run linux which makes it difficult to ensure anything, but if you look at issue #99 some people there got it working; it also shows wineasio being registered with `regsvr32`.

Hope it helps.

**Comment by mdias** [comment]
FYI there's a [new release](https://github.com/mdias/rs_asio/releases/tag/v0.7.0) that is able to use WineASIO without registering it, as well as some [Ubuntu documentation](https://github.com/mdias/rs_asio/blob/master/docs/linux/ubuntu_1204_lts.md) for it.

**Comment by snypervash** [comment]
This is really awesome however I've switched back to windows already.
