### ISSUE TITLE
RealTone cable not detected

### ISSUE THREAD

**Issue by atagmester** [mdias/rs_asio#376]
This is a common issue for me, and don't know what is the solution. 
If i want to use the RealTone cable, and remove the files (rs_asio.dll and avrt.dll) the game can't detect the cable anymore, and the sound quality is very poor.
Repair the game doesn't help, remove and reinstall does, but it is not to comfy during every cable change.
Any ideas?

**Comment by mdias** [comment]
Without `avrt.dll` and/or `rs_asio.dll` there is nothing from RS ASIO changing the original game behavior.

If you get an error (I assume that's what you mean) saying that the RealTone Cable is not detected after you remove either of those files, your problem lies elsewhere.

**Comment by adrian-vogler** [comment]
I have not Real Tone Cable attached but get the error.
The message pops up when I want to tune the guitar.
![Screenshot 2023-11-03 120323](https://github.com/mdias/rs_asio/assets/95128254/7a3f2d6d-a918-47a0-a8a0-bf8b130ef651)

I get no sound from the guitar. I have different audio interfaces.

**Comment by mdias** [comment]
@adrian-vogler are you using RS ASIO?
If so, can you post your config and log files?

**Comment by mdias** [comment]
@adrian-vogler I just noticed you're the same person posting also on #393 and #388. Please refrain from posting the same problem in more than 1 place.
