### ISSUE TITLE
Can't get output via ASIO

### ISSUE THREAD

**Issue by Eyal51** [mdias/rs_asio#377]
Hi,

I'm using Zoom U-22, and when I try following the instructions and the example config, there's no output sound. I tried various channels and configurations and none worked.
If I set the output to WASAPI, delete the name of the driver (ZOOM U-22 ASIO Driver) and the latency to 2 I can get it to work.
I read here somewhere that if I'm using WASAPI I'm missing out on the experience.
How can I debug that any further?

I've attached configs and logs if that matters.

Thanks!
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/12255351/RS_ASIO-log.txt)
[audiodump.txt](https://github.com/mdias/rs_asio/files/12255352/audiodump.txt)
[Rocksmith.txt](https://github.com/mdias/rs_asio/files/12255353/Rocksmith.txt)
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/12255354/RS_ASIO.txt)

**Comment by mdias** [comment]
You have your output driver empty in RS_ASIO.ini:
```
[Asio.Output]
Driver=
```

You sent the log from a run of the game with WASAPI, so there's no error.

Do you get any error when using ASIO for the output, or do you simply not hear anything?
If you can't hear anything, could it be that your speakers/headphones are not connected to the interface itself?

**Comment by Eyal51** [comment]
You are correct. Correct files attached.
I don't spot any errors in the logs.
I simply don't hear anything, but when I change it to WASAPI output I can play normally, so there's no issue with audio connectivity.
Zoom U-22 connected to PC via USB, audio connect to PC via HDMI.
[audiodump.txt](https://github.com/mdias/rs_asio/files/12262164/audiodump.txt)
[Rocksmith.txt](https://github.com/mdias/rs_asio/files/12262166/Rocksmith.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/12262167/RS_ASIO-log.txt)
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/12262168/RS_ASIO.txt)

**Comment by mdias** [comment]
Your buffer size is too high! You should open your ASIO driver control panel and ajust it lower; it's currently on 512 but you should be able to get it to at least 128.

Also, do you have your speakers connected to your Zoom interface? Your current settings would require that.
If you don't want that you'll have to enable WASAPI for output.

**Comment by Eyal51** [comment]
Any idea for how to adjust the buffer size?

**Comment by mdias** [comment]
You do that through your ASIO driver's control panel, as I stated above.

**Comment by Eyal51** [comment]
Thank you for your support!
