### ISSUE TITLE
No Audio output from game, but it recognizes Cable

### ISSUE THREAD

**Issue by filipbarak** [mdias/rs_asio#379]
Hey, I appreciate the work you've put into this!

If you could help me, I am having some problems. I am using a Blackstar ID:Core v3 which is connected by a USB to the PC and the guitar is plugged into it. 

I don't get any output from the game, but it first said I didn't have any cable connected. Now I get to that stage where you calibrate, but there is no sound, and it seems no input as well as the strums when calibrating don't reflect anything.

I don't seem like I'm getting any errors from the logs, and I've no idea where to go from here. Here's my logs

RS_ASIO-log.txt: https://pastebin.com/KmNBWhqt
RS_ASIO.ini: 

```
# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=
Channel=2
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=ASIO4ALL v2
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```

and 

Rocksmith.ini
```

[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1440
ScreenHeight=900
Fullscreen=1
VisualQuality=3
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=0
EnableShadows=1
EnableHighResScope=0
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=1
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1
```

Thank you!!!

**Comment by filipbarak** [comment]
if it's any help, here's my ASIO4ALL config

![image](https://github.com/mdias/rs_asio/assets/19386836/7ceedaf0-69ca-4637-929e-81d94142f82e)

**Comment by mdias** [comment]
Let me start by saying that ASIO4ALL is known to cause problems, but it also sometimes works just fine.

I see that your interface channels say `4x 44.1kHz 24Bits`. It seems like your interface is expecting a 44100hz signal; this is the first thing to check and fix if possible.

Other than that, I see that you're using input index 1 (channel 2) for your guitar. Did you check that this is correct? Maybe trying different channels (including channel=0) could help.

Since you don't even hear any of the game sound at the moment it's likely your problem is with the ASIO interface to the device itself as the game is trying to switch to 48000hz mode, but I'm not sure if your device works in that state.
