### ISSUE TITLE
How to play my acoustic guitar through the microphone

### ISSUE THREAD

**Issue by GreatNewHope** [mdias/rs_asio#384]
Hi! Thank you for your amazing work. I love rs_asio!

My current configuration works flawlessly with my electric guitar on a behringer um2

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
BufferSizeMode=custom
CustomBufferSize=32

[Asio.Output]
Driver=BEHRINGER USB AUDIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=BEHRINGER USB AUDIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=BEHRINGER USB AUDIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

With this configuration I can play my guitar coming from the Channel 1 and listen to my voice/acoustic guitar on the mic in Channel 0 (I previously set Enable for singing to On, like [this](https://github.com/mdias/rs_asio/issues/79#issuecomment-650339199). This offers the experience in which you play with your guitar through Channel 1 and your voice is amplified in Channel 0, but nothing from Channel 1 is actually going in the game.

What if I wanted to play my acoustic guitar on Channel 0 with a mic and play the game just like I would do with my electric guitar? How could I approach this issue?

Thank you very much

**Comment by mdias** [comment]
Sorry for the late reply. Somehow I lost track of this issue.
I'm not sure how you'd configure the game to do this.
