### ISSUE TITLE
Confirmed as working on Mackie Big Knob Studio+

### ISSUE THREAD

**Issue by philtimm** [mdias/rs_asio#385]
Copied the settings from another Mackie interface on the list, and it worked first time.  Actually, I lied, it was horribly distorted the first time because my interface was set to 24bit, but changing to 16bit/48k worked a charm!

Thank you so much for this! <3

**Comment by mdias** [comment]
Thank you so much for the report and tip, highly appreciated.
I've added the interface to the list.

As for the 24 bit distorted sound, there's a possibility this is a RS ASIO bug as I don't have access to any true 24 bit interface to test it. I tried to blindly add support but it may not be working correctly.

**Comment by philtimm** [comment]
Correction: 24bit audio works just fine.  Not sure what the issue was the first time I tried it.
