### ISSUE TITLE
JACK protocol mismatch (8 vs 9)

### ISSUE THREAD

**Issue by RaphaelNeubert** [mdias/rs_asio#386]
I can't get Rocksmith to connect to JACK. 
I think this is a winasio problem, so i made an issue on the wineasio github page.
(https://github.com/wineasio/wineasio/issues/71)

Please let me know if you think this is rs_asio and not wineasio related.
Otherwise feel free to close it.

Cheers

**Comment by mdias** [comment]
This is not RS_ASIO related. I believe it means you have a version mismatch between the jack "client" libraries and the "server" jack libraries.

**Comment by RaphaelNeubert** [comment]
Alright so i got  the issues resolved now.

It turns out that the steam runtime overrides the system libraries. 
The jacklib provided by the steam runtime was compiled for an older jack version than the one on my system.

A possible workarround is to run Rocksmith without steam using
`WINEDLLOVERRIDES="wineasio=n,b;" WINEPREFIX=~/.steam/steam/steamapps/compatdata/221680/pfx ~/.steam/steam/steamapps/common/Proton\ 5.13/dist/bin/wine Rocksmith2014.exe`

Another way to fix this would be to replace the old jacklibs inside the steam runtime directories with the jacklib provided by the system.

On Ubuntu and other Debian based systems this has not been an issue yet because debian uses a 6 year old jack version which is compatible with the old jacklib in the steam runtime.

related: 
https://github.com/ValveSoftware/steam-runtime/issues/438
https://github.com/ValveSoftware/steam-runtime/issues/307
