### ISSUE TITLE
RS-ASIO does not work anymore

### ISSUE THREAD

**Issue by adrian-vogler** [mdias/rs_asio#393]
I have problems with RS-ASIO which worked well for years.
Ran Rocksmith 2014 again after some month so I am sure Windows Update altered my system in the meantime.
The audio interfaces are detected but I have no signal coming through.
When I switch to tuner I get an error that the Real Tone Cable is missing.

I uninstalled Rocksmith and installed it again.
I installed new versions of RS-ASIO and RSmods.
No success.

Here is a video:
https://youtu.be/KSIxmsy5ekY

Please help.

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/13249601/RS_ASIO-log.txt)

```
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=
BaseChannel=1
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=UMC ASIO Driver
Channel=2
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=AXE IO ONE
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=


```

**Comment by mdias** [comment]
Please set `DumpAudioLog=1` in `Rocksmith.ini` inside the `[Audio]` category, and run the game again.
This will create an `audiodump.txt` file in the game folder, please post it here.

**Comment by adrian-vogler** [comment]
Maybe a dumb question, but where do You start counting the channels?

Do You start counting at 0 or at 1?
My AXE IO One has only one guitar input.
So is this then channel 0 or is it channel 1?

My Behringer has four inputs.
Are they accessible as channel 0 to 3 or as channel 1 to 4?

**Comment by mdias** [comment]
Channels are zero-indexed.
So for your AXE interface you'd use channel zero.
Your Behringer has channels 0 to 3.
