### ISSUE TITLE
Repo usage after Steam store delisting

### ISSUE THREAD

**Issue by jeroenstevens** [mdias/rs_asio#395]
Thanks for updating this project for all this time! Is there a chance that (in the future) this repo will work with "non-steam" versions of the game? Since it has been delisted from sale from the Steam store. 

I'd really like to make a Scarlet Solo 3rd work with it, but unfortunately the log gives an error about not being able to find the correct version.

**Comment by mdias** [comment]
Hello.
Although I understand the frustration, supporting pirated versions of the game is not a planned feature for obvious reasons. It would also not be good for the future of this project.

**Comment by jeroenstevens** [comment]
Rather frustrating indeed, but I totally understand. Thanks for the reply, enjoy your day.
