### ISSUE TITLE
Rocksmith not detecting output when using RS_ASIO

### ISSUE THREAD

**Issue by Lightningaus** [mdias/rs_asio#397]
My rocksmith refuses to detect an audio output (my interface). I had 'solved' this previously by setting wasapi=1/asio=0 in the .ini but then when I tried to get the app to detect my interface obviously it didn't because ASIO was not being used. So I turned ASIO back on, but I don't get any output. To double check my interface wasnt the issue I booted FL studio and can hear my guitar fine without interface monitoring. The only thing that confuses me is that I can only hear FL studio when ASIO is on, youtube, spotify, ect make no sound even with ASIO4ALL off. My headphones are USB, and apparently this doesn't work with RS2014, so I have unplugged the USB adaptor and when rocksmith was working they were plugged into the 3.5mm jack, however I would like to use my interface headset output. I don't know why it won't detect an output with ASIO on, its really annoying, because the output works in FL studio. 

My setup: Behringer UMC22 connected to windows 10 pc with headphones plugged into a 3.5mm adaptor which is in the interface.

**Comment by Lightningaus** [comment]
here is the log and error: 
![Rocksmith 2014 13_11_2023 12_06_03 PM](https://github.com/mdias/rs_asio/assets/150644499/ba7fb113-dbc8-464d-9daa-fce24e6c30c2)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/13331004/RS_ASIO-log.txt)

**Comment by Lightningaus** [comment]
Ok, disregard most of the original post. I have set my interface to 48000hz and the output to my headphones is working, however when launching the game with FL studio on (+ASIO4ALL on) AND when launching it without FL studio, rocksmith still does not detect an output. Completely stumped lol

**Comment by Lightningaus** [comment]
The only way I can 'fix' it is to have asio AND wasapi enabled but that messes up the audio badly. I'm wondering if I can turn ASIO4ALL on without FL studio to try see if it will work.

**Comment by Lightningaus** [comment]
great, fixed the mentioned issues. however now working on finding the right drivers and channels for the .ini

**Comment by mdias** [comment]
Not all audio interfaces will allow you to have multiple apps using ASIO at the same time.
