### ISSUE TITLE
(IK Multimedia iRig) No sound detect when I try to strum the guitar 

### ISSUE THREAD

**Issue by mazni25** [mdias/rs_asio#398]
RS_ASIO only detect Asio4all V2 drivers and no Irig device driver is detect  
![Annotation 2023-11-19 123125](https://github.com/mdias/rs_asio/assets/137206950/81472a2c-cc35-4366-a495-de970427062b)

**Comment by mazni25** [comment]
Im sorry for not being detail, here is my full RS Log 
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/13426569/RS_ASIO-log.txt)

And here is my Rocksmith.ini
![Annotation 2023-11-21 211420](https://github.com/mdias/rs_asio/assets/137206950/12ed4f65-994b-43d5-94ed-bd9d9bad2d06)

Here is the picture I setup the irig 
![WhatsApp Image 2023-11-21 at 21 33 32_b89762fa](https://github.com/mdias/rs_asio/assets/137206950/136f8760-8e37-47ad-97a2-9830451bfcbd)

I tried other ASIO enabled software like yousician it can detect guitar strums well, but yousician can't detect sound produced by guitar strums. Here is audio setting
![Yousician](https://github.com/mdias/rs_asio/assets/137206950/7b97136c-0ab1-494d-b0bd-5ef6533e16ab)

**Comment by zagatozee** [comment]
I wouldn't bother using RS_ASIO for this, since it is using ASIO4ALL as the driver. You'd almost certainly be better off using "Direct Connect Mode" from RSMods instead. If nothing else, it'll skip a layer of setup. - https://github.com/Lovrom8/RSMods/releases

**Comment by mdias** [comment]
I agree with @zagatozee here, there's not much to gain using RS ASIO with ASIO4ALL.

In any case I don't see anything wrong with the log, however you didn't post RS-ASIO.ini so I can't check your input channel in use.

**Comment by mazni25** [comment]
Still no sound when i pick the guitar
![2023-11-22](https://github.com/mdias/rs_asio/assets/137206950/4133b9c3-e01d-41e0-824e-5c320f6960f5)

Here's my RS-ASIO.ini
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/13439004/RS_ASIO.txt)

**Comment by mazni25** [comment]
Is this correct?
![Annotation 2023-11-23 201555](https://github.com/mdias/rs_asio/assets/137206950/70a3d1d7-263d-428d-8d5e-d532e1fd2ecb)

**Comment by mazni25** [comment]
> Note that for Direct Connect you don't want RS ASIO installed.
> 
> As for your config you're using input `1` , and according to your log:
> 
> ```
> 4.179 [INFO]    ASIO input channels info:
> 4.179 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: rtmicinwave 1
> 4.179 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: rtmicinwave 2
> ```
> 
> Input `1` is `rtmicinwave 2`, which is NOT what you tested in yousician (`rtmicinwave 1`); for that you need to use Input `0`.
> 
> However, you either use RS ASIO with the game in RTC mode, or Direct Connect mode WITHOUT RS_ASIO (or with RS ASIO + enabled wasapi inputs).

I try using method (Direct Connect mode WITHOUT RS_ASIO) it show like this 
![2023-11-23](https://github.com/mdias/rs_asio/assets/137206950/b29c52ce-8359-4671-bb32-18d159aea453)

I try every method that you suggest and still doesnt work ;)

**Comment by zagatozee** [comment]
That is showing an audio ouput error - so asusming you disabled RS_ASIO proeprly, as in you removed the avrt.dll file from the rocksmith folder, you need to make sure your windows default audio ouput device is set to 48khz/16 bit DVD quality.

**Comment by mazni25** [comment]
> That is showing an audio ouput error - so asusming you disabled RS_ASIO proeprly, as in you removed the avrt.dll file from the rocksmith folder, you need to make sure your windows default audio ouput device is set to 48khz/16 bit DVD quality.

Yep, I try every method but still doesnt work ;)
