### ISSUE TITLE
Zoom G2.1Nu/G2.1DM works fine

### ISSUE THREAD

**Issue by Mcmx1337** [mdias/rs_asio#400]
Using code below, bypass mode, 48kHz. 3ms ASIO driver latency, rs.ini latency = 2. Big thanks to you!

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=128

[Asio.Output]
Driver=ZOOM G Series ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=ZOOM G Series ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
Thanks! Added to the list 👍
