### ISSUE TITLE
No audio output device detected

### ISSUE THREAD

**Issue by JessykaBass** [mdias/rs_asio#403]
I recently reformatted my computer and had to reinstall everything. Unfortunately RS_ASIO no longer works for me. With WASAPI enabled the audio works but is glitchy so I know its exclusive to RS_ASIO. I'm using a Focusrite 2i2 3rd gen, I've tried exclusive mode on and off. 48KHZ. I've tried uninstalling focusrite drivers, reinstalling and then restarting my computer. I've tried the recommended buffer sizes. 

Here are the relevant logs and settings. I'm using windows 10 and the "justincase" old version of Rocksmith 2014 for some of my custom cache.psarc mods I made a few years back. Thanks in advance for the help! 

-----------------------------------------------------------

rs-asio.ini

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=0

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=2
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

--------------------------

rs-asio.log

0.000 [INFO]   - Wrapper DLL loaded (v0.7.0)
0.000 [INFO]  PatchOriginalCode
0.286 [INFO]  image crc32: 0x21a8959a
0.664 [INFO]  Patching CoCreateInstance
0.664 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 5
0.664 [INFO]  Patching call at 01C5AA85
0.664 [INFO]  Patching call at 01F03B6E
0.664 [INFO]  Patching call at 01F5C681
0.664 [INFO]  Patching call at 01FAEF75
0.664 [INFO]  Patching call at 01FAF40D
0.664 [INFO]  Patching PortAudio MarshalStreamComPointers
0.664 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.664 [INFO]  Patching call at 01F03059
0.664 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.664 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.664 [INFO]  Patching call at 01F0310E
0.667 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.667 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.667 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.667 [INFO]  GetWineAsioInfo - Looking for wineasio.dll... 
0.669 [INFO]    Failed to load wineasio.dll or file not found
0.669 [INFO]  AsioHelpers::FindDrivers
0.670 [INFO]    Focusrite Thunderbolt ASIO
0.670 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.670 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.670 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
0.670 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.670 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Focusrite USB ASIO
0.670 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.670 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.670 [INFO]    hr: 80070490
0.670 [INFO]    *ppEndpoint: 00000000
0.670 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.670 [INFO]    hr: 80070490
0.670 [INFO]    *ppEndpoint: 00000000
0.670 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.670 [INFO]    hr: S_OK
0.670 [INFO]    *ppDevices: 12705DA0
2.250 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
2.250 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
2.250 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
2.250 [INFO]  AsioHelpers::FindDrivers
2.250 [INFO]    Focusrite Thunderbolt ASIO
2.250 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
2.250 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
2.250 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
2.250 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
2.250 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Focusrite USB ASIO
2.250 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
2.250 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
2.250 [INFO]    hr: 80070490
2.250 [INFO]    *ppEndpoint: 00000000
2.250 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
2.250 [INFO]    hr: 80070490
2.250 [INFO]    *ppEndpoint: 00000000
2.250 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
2.250 [INFO]    hr: S_OK
2.250 [INFO]    *ppDevices: 12705780
2.257 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
4.230 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
4.386 [INFO]   - Wrapper DLL unloaded

--------------------------------------
audiodump.txt

00000000:  : INIT ExclusiveMode 1
00000000:  : INIT LatencyBuffer 4
00000000:  : INIT ForceWDM 0
00000000:  : INIT ForceDirectXSink 0
00000729: !: pSinkPortAudio->Init() != AK_Success
00002271:  : ************* NSoundInputMgr_Win32::SETUP mUsePortAudio 1 mUseNWin32 0 mUseWaveIn 0 mForceDirectXSink 0 mForceWDM 0 
00002271:  : ************* NSoundInputMgr_Win32::SETUP mRealtoneCableOnly 1 
00003074:  : AK::ReleaseAudioSink WMFocusCallback

-----------------------------------------

**Comment by JessykaBass** [comment]
Updating to latest Rocksmith version has allowed RS_ASIO to work although I am dealing with considerable worse audio glitching and messing with all of my audio settings and buffer size of both my focusrite and rocksmith is not giving me any useable results. So I'd still be interested in a solution for this problem as the older beta version had a combination of settings that worked without audio glitching.

**Comment by JessykaBass** [comment]
I've uninstalled and reinstalled Focusrite control a bunch of times which also installs the appropriate drivers and tried different versions of it too. I will note that the name of the Focusrite driver is called something different prior to my reformat, which does make me suspect it could be an issue with it not being installed for some reason. I have it set to driver so I can change my buffer size easier, which I have tried all 3 suggested both in the old beta version of Rocksmith, and new version of Rocksmith. The former still has no audio output device detected, the latter is lots of audio glitching unless I set my buffer size to something crazy like 1024.

**Comment by mdias** [comment]
Can you upload a recent log coming from a gameplay session where glitches were heard?

**Comment by mdias** [comment]
I'm glad to hear you got it working.
There are many variables than can influence whether or not you can go lower without glitches.  In `Rocksmith.ini` itself you also have the `LatencyBuffer` to specify the number of queued up buffers which will affect your latency and your ability to have the buffer lower than 96.
In any case, there's not much I can do to improve this, so I'll close the issue.

**Comment by Armedorrr** [comment]
im having the same problem all im getting is Focusrite Thunderbolt ASIO to be detected but i need Focusrite USB ASIO to be detected. how can i fix this? is this a windows 11 issue?

**Comment by Armedorrr** [comment]
btw JessykaBass the new 4th gen drivers are ass i cant rocksmith to detect them but it had no problem detecting the older drivers they should work if you have a 3rd gen interface
your welcome 

Here is a link to download the old scarlett drivers
https://drive.google.com/file/d/1d39DVZKLin1n13cG48IiiOTVCZ5MtgY7/view?pli=1
