### ISSUE TITLE
Bad Echo - using FocusRite 2i2 (3rd Gen)

### ISSUE THREAD

**Issue by GhostlyClone** [mdias/rs_asio#404]
Hi there! So I've been searching through a lot of the resolved issues and all the known issues but can't seem to find the answer to my dilemma. This is for RockSmith 2014. At first I couldn't get the output to work but I fixed that. But now it comes through with a bad echo. I've tried a couple different things. Tried changing my BufferSizeMode to "custom" and changing the CustomBufferSize to match my audio interface. Mine is the FocusRite 2i2 (3rd Gen) so I know that it has that issue. However, it only seems to output sound if I have it set to 48hz. Output works fine if the BufferSizeMode=driver with the interface at 48hz. If I change the hz to literally anything else, the output is not detected. Even with the custom setting (works fine as both custom or driver as long as FocusRite is set to 48hz).

I've also tried switching between setting WasapiOutput and EnableAsio to 0 or 1 respectively. Output fails unless Wasapi is 1 and Asio is 0. However, one red flag I've noticed is my Asio-Log looks completely out of whack from when I first installed all of this. I don't see where my audio interface is. **The line for "AsioHelpers::FindDrivers" is missing.** 
I'll include my Asio-Log and other configurations below. 

I also noticed that when I first set this up that my driver's name is "Focusrite Thunderbolt ASIO" while everyone else who uses the Focusrite 2i2 3rd Gen seems to have theirs listed as "Focusrite USB ASIO", which I find odd. Any guidance would be greatly appreciated. Thank you!

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/13574643/RS_ASIO-log.txt)

**RS_ASIO:**
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=0

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Focusrite Thunderbolt ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite Thunderbolt ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=Focusrite Thunderbolt ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**RockSmith:**
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1920
ScreenHeight=1080
Fullscreen=0
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=0
[Global]
Version=1

**Comment by Armedorrr** [comment]
the new 4th gen scarlett driver suck ass and are not detected by rocksmith
down below i linked a download for the old driver from 2019 
it works the best and has no issues

Here is a link to download the old scarlett drivers
https://drive.google.com/file/d/1d39DVZKLin1n13cG48IiiOTVCZ5MtgY7/view?pli=1

**Comment by GhostlyClone** [comment]
> the new 4th gen scarlett driver suck ass and are not detected by rocksmith down below i linked a download for the old driver from 2019 it works the best and has no issues
> 
> Here is a link to download the old scarlett drivers https://drive.google.com/file/d/1d39DVZKLin1n13cG48IiiOTVCZ5MtgY7/view?pli=1

This made everything so much worse. Now my computer doesn't even recognize my Focusrite. I uninstalled yours and had to reinstall the driver directly from Focusrite since yours force deleted mine. But even now it's STILL not recognizing Focusrite. Like I will have the drivers installed but now Focusrite Control just says "No hardware detected". Meaning now I can't even ANY SOUND out of my speakers. This messes me up bad, now I don't have a way to use my DAW. Please help.

**Comment by mdias** [comment]
>  it only seems to output sound if I have it set to 48hz

This is expected. As stated in the readme: "Your interface MUST support 48kHz playback"

> Even with the custom setting (works fine as both custom or driver as long as FocusRite is set to 48hz).

The custom setting is there to ask the driver for a different buffer size than what you've set in your driver's control panel. It will not affect the sample rate. If you use "custom" with the same buffer size as what's set on your device's control panel, the end result will effectively be the same as using "driver" for `BufferSizeMode`.

> The line for "AsioHelpers::FindDrivers" is missing

Wasapi does not use ASIO; if neither outputs or inputs are trying to use ASIO, it won't try to find the available drivers on your system. Since you have `EnableAsio=0` in your config, ASIO is disabled.

> I also noticed that when I first set this up that my driver's name is "Focusrite Thunderbolt ASIO"

This is a missing driver problem. Make sure you reinstall the official drivers.
It's also possible that the latest Focusrite drivers don't provide a 32-bit ASIO driver (which RS ASIO needs), but since I don't own any Focusrite device, I can't check for that myself.
If that's the case you might still be able to workaround it by using Voicemeeter as a "translation layer" from 32-bit to 64-bit, but it's more cumbersome to have it set up like that.

> the new 4th gen scarlett driver suck ass and are not detected by rocksmith

The OP is using a 3rd Gen interface.

**Comment by GhostlyClone** [comment]
> Wasapi does not use ASIO; if neither outputs or inputs are trying to use ASIO, it won't try to find the available drivers on your system. Since you have `EnableAsio=0` in your config, ASIO is disabled.
I'll be honest, I'm not sure what Wasapi or ASIO means. Can you provide some clarity and guidance on what I should be doing?
> This is a missing driver problem. Make sure you reinstall the official drivers. It's also possible that the latest Focusrite drivers don't provide a 32-bit ASIO driver (which RS ASIO needs), but since I don't own any Focusrite device, I can't check for that myself. If that's the case you might still be able to workaround it by using Voicemeeter as a "translation layer" from 32-bit to 64-bit, but it's more cumbersome to have it set up like that.
So I uninstalled the other driver and actually had to get assistance from a Focusrite tech to reinstall everything cause it was so out of the ordinary. I have sound on my laptop again but the problem with Rocksmith still persists. Should I resend my logs now? Or is there something I else I can try that you can suggest?

**Comment by mdias** [comment]
> I'll be honest, I'm not sure what Wasapi or ASIO means.

ASIO and WASAPI are 2 different ways to communicate with audio hardware. ASIO tends to offer lower latency as it skips over some Windows layers and usually offers a more direct access to the hardware.

> Can you provide some clarity and guidance on what I should be doing?

If you want the lowest possible latency you should be using ASIO only (that means both your speakers and guitar are connected to your Focusrite.

> Should I resend my logs now? Or is there something I else I can try that you can suggest?

Yes, please resend the logs after you've installed the drivers and tried to run the game once with ASIO enabled in RS_ASIO.ini.
You should be able to just use [these settings](https://github.com/mdias/rs_asio/issues/208) if you have the proper drivers installed.

**Comment by steadybright** [comment]
I use the Scarlett Solo, and I had an echo issue when I had "Direct Monitor" engaged. It took me a couple minutes to realize that was the issue. Good luck!

**Comment by GhostlyClone** [comment]
> Yes, please resend the logs after you've installed the drivers and tried to run the game once with ASIO enabled in RS_ASIO.ini. You should be able to just use [these settings](https://github.com/mdias/rs_asio/issues/208) if you have the proper drivers installed.

Ok so I uninstalled Rocksmith entirely and deleted all the files from the original posting. I redownloaded Rocksmith 2014, redownloaded the zip files (extracted them and pasted them into the Rocksmith 2014 common folder), ran Rocksmith, and it all sounds fine now. I also enabled CDLC. I have my RS_ASIO.ini and Rocksmith.ini copied EXACTLY like it is in the settings you had referenced. However, now the guitar is not being picked up by Rocksmith at all. But when I use my DAW, my guitar signal works just fine. Even without the DAW or Rocksmith, my speakers omit the sound from my guitar. I know I have the right driver plugged in because I had to get everything redownloaded with assistance from a Focusrite rep. Here's the new RS_ASIO-log. I'm not sure what else to do. 
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/13667772/RS_ASIO-log.txt)

**Comment by mdias** [comment]
Log looks fine now.
The settings I linked assume you have the guitar connected to the first input. Is that the case for you?

**Comment by GhostlyClone** [comment]
> Log looks fine now. The settings I linked assume you have the guitar connected to the first input. Is that the case for you?
 
That was it, thank you for clarifying. Switched the input and its fine now. The only issue I have now is lag in the video, not the audio. I tried messing with the in game lag correction but it didn't seem to help. No other programs are open and I've restarted my laptop a few times. Any tips on what I should adjust within any of the .ini files to correct visual lag? Otherwise, everything else is working perfectly.

**Comment by mdias** [comment]
> The only issue I have now is lag in the video

If you're using a TV, set it to Game mode. If not using a TV then I have no idea why you'd have display lag.

**Comment by GhostlyClone** [comment]
> If you're using a TV, set it to Game mode. If not using a TV then I have no idea why you'd have display lag.

Using a laptop. But no worries, I'll see if I can figure something out. Thank you so much for the help though. Everything else seems to be working fine for now! Merry Christmas and Happy New Year!

**Comment by mdias** [comment]
Thank you. Happy New Year for you too!
