### ISSUE TITLE
HX Stomp, cant pass calibration and no note detection

### ISSUE THREAD

**Issue by amaryniuk** [mdias/rs_asio#408]
I have the default setting set on my HX stomp - Though I am unsure if the global settings Input/Output levels should be set to Inst or Line (I have them set to Inst, but I've tried both). My ini files are attached. 

My issue is RS calibration and note detection.
When SoftwareMasterVolumePercent=100 and I try to calibrate, the volume is not high enough.
The HX Stomp config in this repo suggests 600, which I tried, but RS complained volume was too high.
So at 200 and above, I can pass step 1 of the RS calibration process, but when I mute the strings, the graph bounces up and down very crazily. Even cutting the volume on my guitar has the same problem.

So in the past I could just skip calibration (I used to use the built in gain override), but the tuning and note detection would still work. Now I can't pass the tuning stage or get proper note detection as it constantly bounces up and down with no guitar input.

Ive verified game files, factory reset my hx stomp, tried multiple guitars, replaced cables, and am running out of ideas.

[Rocksmith.txt](https://github.com/mdias/rs_asio/files/13643074/Rocksmith.txt)
[RS_ASIO.txt](https://github.com/mdias/rs_asio/files/13643075/RS_ASIO.txt)

**Comment by mdias** [comment]
It sounds like you have a high noise floor or your guitar volume signal is too low.
I recommend you try some audio recording software to check if your guitar signal is coming clean and high enough.

RS ASIO seems to be working fine in this case, it merely redirects the audio it receives to the game and can amplify the full signal as you noted, but if the signal is bad there's nothing RS ASIO can do.
