### ISSUE TITLE
No Longer on Steam Store

### ISSUE THREAD

**Issue by deeseem** [mdias/rs_asio#409]
Since Rocksmith has been pulled from Steam, would it be possible to make rs-asio available as a generic plug-in minus the Steam requirement please?

**Comment by mdias** [comment]
Not possible with the way RS ASIO works.
It requires knowing about .exe specifics of the game, which will change depending on game versions and would require very time consuming reverse engineering to figure out these details for all available versions.

Not to mention that making it work with "non-steam" versions would mean supporting piracy which is not something that would be great for the future of this project as you can imagine...
