### ISSUE TITLE
RS_ASIO-log is "empty"

### ISSUE THREAD

**Issue by wizznet** [mdias/rs_asio#41]
Hey there, first of all: Thanks for your great work! you are awesome.

I installed everything as described. But my Log to find the Drivers to insert into RS_ASIO.ini is kind of empty: this is everything it gives me:
```
0.000 [INFO]   - Wrapper DLL loaded (v0.4.2)
0.000 [INFO]  PatchOriginalCode
0.000 [INFO]  Patching CoCreateInstance
0.035 [INFO]  Patch_CallAbsoluteAddress - num locations: 0
0.035 [INFO]  Patching PortAudio MarshalStreamComPointers
0.067 [INFO]  Patch_CallRelativeAddress - num locations: 0
0.068 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.100 [INFO]  Patch_CallRelativeAddress - num locations: 0
3.508 [INFO]   - Wrapper DLL unloaded

```

i've already put the Buffersize to 192 and 48k as recommended. 
Im using a focusrite scarlett 2i2(2nd gen).

Thanks

**Comment by mdias** [comment]
Hello!
This is a big indication that you're not using the correct version of Rocksmith.

Only the 2014 Remastered version from Steam is supported.

**Comment by wizznet** [comment]
oh dang it! you are 100% right. How could i be so blind. Just bought it 2 hrs ago after i've seen, that there are finally asio driver for rs. Thank you :D
