### ISSUE TITLE
No audio while streaming to Discord

### ISSUE THREAD

**Issue by LukeWilson100** [mdias/rs_asio#413]
I recently installed the rs_asio folders for my Scarlett Solo 3rd gen so I could play with my audio interface. Anytime I play I can hear all the audio and there's no issues, but when I try streaming to my friends in Discord, they can't hear any audio. I've tried removing audio exclusivity on everything and that didn't work. I'm wondering if it's a Discord issue or an issue with my Rocksmith.

**Comment by mdias** [comment]
See https://github.com/mdias/rs_asio/blob/master/docs/streaming/README.md
