### ISSUE TITLE
No input connection when setting up RS_ASIO

### ISSUE THREAD

**Issue by RoBINNN0024** [mdias/rs_asio#415]
I swapped over to using a Scarlet 2i2 3rd gen audio interface and set up RS_ASIO to utilize it while playing Rocksmith, but ran into the issue of my bass guitar not being picked up at all anymore regardless if I connect through my scarlet, or while using an RTC wire. I've had this problem for weeks but have found no solution for it.
just to note, I have had it at 48k sample rate and tried every buffering rate too, The output works just fine as I can hear Rocksmith smoothly, my only issue is the fact is that my guitar will not be picked up in the input, as it says there are no inputs available.

**Comment by mdias** [comment]
> as it says there are no inputs available.

Can you show your RS_ASIO.ini contents?

**Comment by RoBINNN0024** [comment]
> > as it says there are no inputs available.
> 
> Can you show your RS_ASIO.ini contents?

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
What is the exact messagethe game displays to you?
It shouldn't ever be telling you that you don't have a cable connected with that config.

Can you maybe post a screenshot?

**Comment by RoBINNN0024** [comment]
![DR](https://github.com/mdias/rs_asio/assets/156490409/076c9740-3631-4824-8a8f-2b490b0d63ff)
![RTC](https://github.com/mdias/rs_asio/assets/156490409/70b21e9d-bcea-4a27-ad5d-9dbb6dc0e634)
Here is the screenshot of both when i attempt to connect to both Direct Connect and RTC connection, my cable is plugged into my output 2, I've tried switching to the other output while also disconnecting my microphone.

**Comment by mdias** [comment]
You need to be playing in RTC mode.
RS ASIO presents itself as the RTC to the game.

**Comment by RoBINNN0024** [comment]
My microphone is also connected to my focusrite, usually plugged into output one while the guitar cable occupies output 2. Something that might be interesting was that when i set up my audio interface, i still used a regular RTC cable plugged into my pc.

ran through my AI perfectly fine for some time till i had that "no audio output detected" issue popped up for me, fixed that issue that caused me to install RS_ASIO, and fixed the output issue, but now causes this.

**Comment by mdias** [comment]
Ok, so in your config you have 2 "guitars" configured (using `[Asio.Input.0]` and `[Asio.Input.1]`), which is making the game believe you have 2 players conected; player one on the first input (you have `Channel=0` inside `[Asio.Input.0]`) and the other player on the second input (you have `Channel=1` inside `[Asio.Input.1]`).

If you have the mic connected to your first input, then I guess the game is now listening to your mic expecting it to be a guitar. Note that RS ASIO starts counting from zero, so the first input is zero, and the 2nd input is 1 etc.
If you want to fix this, and assuming your setup is Mic on the 1st input and Guitar on the 2nd input, you should be using:

```
[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
...

[Asio.Input.1]
Driver=
Channel=
...

[Asio.Input.Mic]
Driver=Focusrite USB ASIO
Channel=0
```
(the mic setting is only needed if you use that ingame, if not you can leave it empty)

If along with the Focusrite interface you ALSO want to use your RTC you'll need to set:
`EnableWasapiInputs=1`

**Comment by RoBINNN0024** [comment]
I updated as followed, but I still don't have audio being picked up, I'm sensing that it may be a cable issue but I'd like to rule out any other possibilities, i don't have a spare cable to test but I will be picking a new one up tomorrow.
![20240113221449_1](https://github.com/mdias/rs_asio/assets/156490409/7b0f4ff0-daa5-48b2-b6a5-a453ed2ecc06)
![20240113220155_1](https://github.com/mdias/rs_asio/assets/156490409/690dba69-42bc-4539-810d-eb433c77e397)

heres what it says when i try to connect my RTC, i dont know if this is a normal screen to see or not.

![20240113220344_1](https://github.com/mdias/rs_asio/assets/156490409/9e8138dc-a5f4-4098-b732-d12e6f0ac55f)
 
 This is what it says when i try to tune or play a song.

**Comment by mdias** [comment]
Can you post your RS_ASIO-log.txt?

RS ASIO doesn't support hot-plugging of your RTC, you have to have it connected before you launch the game. However, you should still not see that message about RTC not being plugged since according to your config the game should see at least 1 RTC at all times.

**Comment by RoBINNN0024** [comment]
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/13930328/RS_ASIO-log.txt)

Theres the text log, and my cable was always connected before I launched the game, never took it out.

**Comment by mdias** [comment]
I see 3 issues:
- Your interface doesn't seem to be configured to use 48kHz in it's control panel (not just windows sound settings).
- You're having xruns, indicating that 48 samples is probably too low for your system, you should try 96.
- The last config you posted here is missing the `[Asio]` section

Other than that it doesn't look like the game is even trying to use the input that RS ASIO is providing it. This is very strange.
Not sure I can help you any further as this seems to be just the game not requesting the initialization of the input. Perhaps try a clean install

**Comment by RoBINNN0024** [comment]
I'll reinstall Rocksmith and RS_ASIO whenever I get the chance. 
![FocusriteSS](https://github.com/mdias/rs_asio/assets/156490409/1376c1a4-79e3-4c10-9174-9512a4ff5106)

![SoundOptionsSS](https://github.com/mdias/rs_asio/assets/156490409/209ff111-5dc5-411d-9aaf-71717ef4d46d)

Here are screenshots of both what my Focusrite application settings and sound options settings are set to for the time being.

**Comment by mdias** [comment]
> So on my Focusrite app, i should set my sample rate to 96kHz? or my buffer rate on the ASIO section of RS_ASIO?

`CustomBufferSize` in RS_ASIO.
Sample rate should be 48kHz, but the number of samples (`CustomBufferSize=` in the ini file) controls the buffer size and therefore latency; the lower you go, the more it pushes your system until you start getting xruns.

All other settings you posted look fine, but the reason I talked about your sample rate is because your log had this entry:
`1.674 [INFO]    Switching sample rate from 44100 to 48000...`
which indicates the driver was previously set to 44.1 kHz.
