### ISSUE TITLE
TASCAM US-4x4HR, input #4?

### ISSUE THREAD

**Issue by mattpula** [mdias/rs_asio#416]
Hello - I got rs_asio working with my TASCAM US-4x4HR, but it only seems to work if I'm plugged into input #1. I've tried a few things, including changing the channel # for ASIO.Input.0 to 3 or 4 but it didn't seem to work. Is there anything I can do in the asio config that would lets you specify different inputs? Input #4 is the input I always have my DI box plugged into, so it'd be ideal if I didn't have to swap cables around every time I open the game.

Thanks!

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=US-HR Series ASIO Driver
BaseChannel=1
AltBaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=US-HR Series ASIO Driver
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
It should work setting the `Asio.Input.0` to `Channel=3`.
I'm not familiar with your interface, so idk if it might require some other config elsewhere in it's drivers/cointrol panel.

Can you post the `RS_ASIO-log.txt` log? It could have useful info in there.

**Comment by mattpula** [comment]
huh - I changed it to channel=3 again and this time it worked. Weird. Maybe I forgot to save the config file when I was troubleshooting earlier. Thanks dude!

**Comment by mdias** [comment]
No problem! Glad it worked :)
