### ISSUE TITLE
Can't get Rocksmith 2014 to recognise my Scarlett Solo 3rd gen

### ISSUE THREAD

**Issue by RainMakeRMusic** [mdias/rs_asio#419]
I've plugged in my 3rd gen Scarlett Solo and followed all the instructions, such as pasting the setting listing for my audio interface into RS_ASIO.ini. But Rocksmith still just tells me to connect a real tone cable and won't let me past the initial calibration. I have noticed in RS_ASIO-log there is no "Focusrite USB ASIO". What  do I need to do?

What my RS_ASIO-log says:
0.000 [INFO]   - Wrapper DLL loaded (v0.7.0)
0.000 [INFO]  PatchOriginalCode
0.376 [INFO]  image crc32: 0xbb2758fd
0.376 [ERROR]  Unknown game version
140.728 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
You need to have the latest steam version of the game.

**Comment by RainMakeRMusic** [comment]
Bugger. I would get it. But its not available to purchase anymore.

**Comment by mdias** [comment]
Sadly this is the current state of affairs with the game and you're not alone with the problem.
I can only say some people have been successful at getting a steam key from online sellers on closed-box items and such.

**Comment by Dered118** [comment]
I'm using a non steam version of rocksmith 2014 remastered and it works using my 3rd gen solo.

**Comment by qdsec** [comment]
@Dered118 Hey bud, you mean you are using a "green steam" version of the game wink, wink? If thats the case, could you help us sharing your configuration or game version :)
