### ISSUE TITLE
Just want to say that the Focusrite Clarett 4Pre USB works as well :)

### ISSUE THREAD

**Issue by loiphin** [mdias/rs_asio#42]
Hi,

I setup my Focusrite Clarett 4Pre USB, using  a buffer of 48 (configured within  Clarett 4Pre USB settings), and latency of 1 (in Rocksmith.ini). 

I finally have a working solution within Windows! Thank you :)

**Comment by mdias** [comment]
Thank you for the report.
I've added it to the list of devices known to work :)
