### ISSUE TITLE
No ASIO input sound

### ISSUE THREAD

**Issue by cryptins** [mdias/rs_asio#421]
I turn on "Use WASAPI Output" and keep "Use WASAPI Input" disabled and for some reason it allows my audio to work but the input does not. Is there a fix?

0.000 [INFO]   - Wrapper DLL loaded (v0.7.0)
0.000 [INFO]  PatchOriginalCode
0.039 [INFO]  image crc32: 0xd1b38fcb
0.295 [INFO]  Patching CoCreateInstance
0.295 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.295 [INFO]  Patching call at 00C02DBD
0.295 [INFO]  Patching call at 00E75278
0.295 [INFO]  Patching PortAudio MarshalStreamComPointers
0.295 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.295 [INFO]  Patching call at 00E7483F
0.295 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.295 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.295 [INFO]  Patching call at 00E748F4
0.295 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.295 [INFO]  Patching bytes at 007C0C5F
0.466 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
0.688 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
0.906 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.124 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.352 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.589 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
1.810 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.020 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.231 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.443 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.655 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
2.873 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
3.088 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
3.809 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
3.810 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
3.810 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
3.810 [INFO]  GetWineAsioInfo - Looking for wineasio.dll... 
3.811 [INFO]    Failed to load wineasio.dll or file not found
3.811 [INFO]  AsioHelpers::FindDrivers
3.811 [INFO]    Realtek ASIO
3.811 [INFO]    Voicemeeter Virtual ASIO
3.811 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Realtek ASIO
3.811 [INFO]  Creating AsioSharedHost - dll: c:\windows\SysWow64\rtcom\rthdasio.dll
3.827 [INFO]    ASIO input channels info:
3.827 [INFO]      0 - active: 1, channel: 0, group: 0, isInput: 1, type: ASIOSTInt24LSB, name: HD Audio input 1
3.827 [INFO]      1 - active: 1, channel: 1, group: 0, isInput: 1, type: ASIOSTInt24LSB, name: HD Audio input 2
3.827 [INFO]    ASIO output channels info:
3.827 [INFO]      0 - active: 1, channel: 0, group: 0, isInput: 0, type: ASIOSTInt24LSB, name: HD Audio output 1
3.827 [INFO]      1 - active: 1, channel: 1, group: 0, isInput: 0, type: ASIOSTInt24LSB, name: HD Audio output 2
3.827 [INFO]      2 - active: 1, channel: 2, group: 0, isInput: 0, type: ASIOSTInt24LSB, name: HD Audio output 3
3.827 [INFO]      3 - active: 1, channel: 3, group: 0, isInput: 0, type: ASIOSTInt24LSB, name: HD Audio output 4
3.827 [INFO]      4 - active: 1, channel: 4, group: 0, isInput: 0, type: ASIOSTInt24LSB, name: HD Audio output 5
3.827 [INFO]      5 - active: 1, channel: 5, group: 0, isInput: 0, type: ASIOSTInt24LSB, name: HD Audio output 6
3.827 [INFO]      6 - active: 1, channel: 6, group: 0, isInput: 0, type: ASIOSTInt24LSB, name: HD Audio output 7
3.827 [INFO]      7 - active: 1, channel: 7, group: 0, isInput: 0, type: ASIOSTInt24LSB, name: HD Audio output 8
3.827 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
3.838 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 19 render devices, 1 capture devices
3.838 [INFO]    hr: S_OK
3.838 [INFO]    *ppEndpoint: 18809B38
3.838 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.838 [INFO]    hr: S_OK
3.838 [INFO]    *ppEndpoint: 18809AA8
3.838 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.838 [INFO]    hr: S_OK
3.838 [INFO]    *ppDevices: 0258E038
3.838 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.838 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperDevicePropertyStore::GetCount
3.839 [INFO]    *cProps: 78
3.866 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.866 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperEndpoint::GetDataFlow
3.866 [INFO]    *pDataFlow: eRender
3.866 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
3.868 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
3.869 [INFO]  {0.0.0.00000000}.{ecf6098d-af5c-465d-98b3-c0862faf1215} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.869 [INFO]  {0.0.0.00000000}.{ecf6098d-af5c-465d-98b3-c0862faf1215} DebugWrapperDevicePropertyStore::GetCount
3.869 [INFO]    *cProps: 56
3.885 [INFO]  {0.0.0.00000000}.{ecf6098d-af5c-465d-98b3-c0862faf1215} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.885 [INFO]  {0.0.0.00000000}.{ecf6098d-af5c-465d-98b3-c0862faf1215} DebugWrapperEndpoint::GetDataFlow
3.885 [INFO]    *pDataFlow: eRender
3.885 [INFO]  {0.0.0.00000000}.{ecf6098d-af5c-465d-98b3-c0862faf1215} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
3.885 [INFO]  {0.0.0.00000000}.{ecf6098d-af5c-465d-98b3-c0862faf1215} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
3.886 [INFO]  {0.0.0.00000000}.{f2098d7e-0600-4204-82ae-a355005b14f3} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.886 [INFO]  {0.0.0.00000000}.{f2098d7e-0600-4204-82ae-a355005b14f3} DebugWrapperDevicePropertyStore::GetCount
3.886 [INFO]    *cProps: 86
3.918 [INFO]  {0.0.0.00000000}.{f2098d7e-0600-4204-82ae-a355005b14f3} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.918 [INFO]  {0.0.0.00000000}.{f2098d7e-0600-4204-82ae-a355005b14f3} DebugWrapperEndpoint::GetDataFlow
3.918 [INFO]    *pDataFlow: eRender
3.918 [INFO]  {0.0.0.00000000}.{f2098d7e-0600-4204-82ae-a355005b14f3} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
3.919 [INFO]  {0.0.0.00000000}.{f2098d7e-0600-4204-82ae-a355005b14f3} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
3.919 [INFO]  {ASIO IN 1} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
3.919 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetCount
3.919 [INFO]    *cProps: 5
3.919 [INFO]  {ASIO IN 1} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
3.919 [INFO]  {ASIO IN 1} DebugWrapperEndpoint::GetDataFlow
3.919 [INFO]    *pDataFlow: eCapture
3.919 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
3.919 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
3.919 [INFO]  {ASIO IN 1} RSAsioAudioClient::~RSAsioAudioClient
3.931 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
3.932 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.950 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
3.950 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.951 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
3.951 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
3.951 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
3.960 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
3.960 [INFO]    *pNumBufferFrames: 144
3.960 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
3.960 [INFO]    latency: 3ms
3.960 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
3.960 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
3.962 [INFO]  Patched_PortAudio_MarshalStreamComPointers
3.963 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
3.963 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
3.963 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
3.963 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
3.963 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
3.963 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
3.963 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
3.963 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Start
3.965 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
3.965 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
3.966 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
3.966 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
30.310 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
30.310 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
30.310 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt24LSB
30.310 [INFO]    requested format is not supported
30.310 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
30.310 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
30.310 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt24LSB
30.310 [INFO]    requested format is not supported
30.310 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
30.310 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
30.310 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt24LSB
30.310 [INFO]    requested format is not supported
30.310 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
30.310 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
30.310 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
30.310 [INFO]    Switching sample rate from 0 to 48000...
30.384 [ERROR]  ASIO Error: 
30.384 [INFO]    hr: E_FAIL
30.384 [INFO]  {ASIO IN 1} RSAsioAudioClient::~RSAsioAudioClient
59.617 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Stop
233.449 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
233.450 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
233.476 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
233.476 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
233.477 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
233.477 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
233.478 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
233.486 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
233.486 [INFO]    *pNumBufferFrames: 144
233.486 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
233.486 [INFO]    latency: 3ms
233.486 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
233.486 [INFO]  Patched_PortAudio_MarshalStreamComPointers
233.487 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
233.487 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
233.487 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
233.487 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
233.487 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
233.487 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
233.487 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
233.487 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Start
233.489 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
233.489 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
233.490 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
233.490 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
236.685 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Stop
642.816 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
642.817 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
642.843 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
642.843 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
642.844 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
642.844 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
642.844 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
642.854 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
642.854 [INFO]    *pNumBufferFrames: 144
642.854 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
642.854 [INFO]    latency: 3ms
642.854 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
642.854 [INFO]  Patched_PortAudio_MarshalStreamComPointers
642.855 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
642.855 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
642.855 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
642.855 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
642.855 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
642.855 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
642.855 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
642.855 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Start
642.858 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
642.858 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
642.859 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
642.859 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
644.560 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
644.562 [INFO]  {0.0.0.00000000}.{c9756042-faac-4231-bd47-bb7da3bb20bd} DebugWrapperAudioClient<struct IAudioClient3>::Stop
644.568 [INFO]  Destroying AsioSharedHost - dll: c:\windows\SysWow64\rtcom\rthdasio.dll
646.341 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
You need to post your RS_ASIO.ini config file, as well as let us know which audio interface you're trying to use for input, and which one for output.
