### ISSUE TITLE
Not detecting Focusrite Drivers?

### ISSUE THREAD

**Issue by Mrak408** [mdias/rs_asio#423]
Hello, I am new to all of this so excuse my lack of knowledge. I recently got a Focusrite Scarlette Solo 1st gen to use with Amplitube and Rocksmith. I have the latest drivers installed for Windows 10 (Focusrite Driver 4.119.13). These drivers work great on all my amp sim plugins using Windows sound or ASIO. However, it seems like RS_ASIO doesnt detect the USB drivers? This is odd since, as I said, they are detected by all my Amp plugins and work fine. I did find out that using the Windows 7 drivers (Focusrite USB Driver 4.65.5) does get it to work with RS_ASIO, at the cost of all Windows audio functionality and not working with my plugins... Has anyone experienced this before? 

> 0.000 [INFO]   - Wrapper DLL loaded (v0.7.0)
> 0.000 [INFO]  PatchOriginalCode
> 0.027 [INFO]  image crc32: 0xd1b38fcb
> 0.139 [INFO]  Patching CoCreateInstance
> 0.139 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
> 0.139 [INFO]  Patching call at 00C02DBD
> 0.139 [INFO]  Patching call at 00E75278
> 0.139 [INFO]  Patching PortAudio MarshalStreamComPointers
> 0.139 [INFO]  Patch_CallRelativeAddress - num locations: 1
> 0.139 [INFO]  Patching call at 00E7483F
> 0.139 [INFO]  Patching PortAudio UnmarshalStreamComPointers
> 0.139 [INFO]  Patch_CallRelativeAddress - num locations: 1
> 0.139 [INFO]  Patching call at 00E748F4
> 0.139 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
> 0.139 [INFO]  Patching bytes at 007C0C5F
> 0.155 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
> 0.258 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
> 0.403 [INFO]  Patched_CoCreateInstance called: {DC12A687-737F-11CF-884D-00AA004B2E24}
> 0.849 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
> 0.849 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
> 0.849 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
> 0.849 [INFO]  GetWineAsioInfo - Looking for wineasio.dll... 
> 0.850 [INFO]    Failed to load wineasio.dll or file not found
> 0.850 [INFO]  AsioHelpers::FindDrivers
> 0.850 [INFO]    Focusrite Thunderbolt ASIO
> 0.850 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
> 0.850 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
> 0.850 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
> 0.850 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
> 0.850 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
> 0.850 [INFO]    hr: 80070490
> 0.850 [INFO]    *ppEndpoint: 00000000
> 0.850 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
> 0.850 [INFO]    hr: 80070490
> 0.850 [INFO]    *ppEndpoint: 00000000
> 0.850 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
> 0.850 [INFO]    hr: S_OK
> 0.850 [INFO]    *ppDevices: 0C7F8788
> 2.315 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
> 2.315 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
> 2.315 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
> 2.315 [INFO]  AsioHelpers::FindDrivers
> 2.316 [INFO]    Focusrite Thunderbolt ASIO
> 2.316 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
> 2.316 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
> 2.316 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
> 2.316 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
> 2.316 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
> 2.316 [INFO]    hr: 80070490
> 2.316 [INFO]    *ppEndpoint: 00000000
> 2.316 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
> 2.316 [INFO]    hr: 80070490
> 2.316 [INFO]    *ppEndpoint: 00000000
> 2.316 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
> 2.316 [INFO]    hr: S_OK
> 2.316 [INFO]    *ppDevices: 0C7F7468
> 2.320 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
> 58.283 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
> 58.388 [INFO]   - Wrapper DLL unloaded
> 

**RS_ASIO.ini**

> [Config]
> EnableWasapiOutputs=0
> EnableWasapiInputs=0
> EnableAsio=1
> 
> [Asio]
> ; available buffer size modes:
> ;    driver - respect buffer size setting set in the driver
> ;    host   - use a buffer size as close as possible as that requested by the host application
> ;    custom - use the buffer size specified in CustomBufferSize field
> BufferSizeMode=custom
> CustomBufferSize=48
> 
> [Asio.Output]
> Driver=Focusrite USB ASIO
> BaseChannel=0
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> 
> [Asio.Input.0]
> Driver=Focusrite USB ASIO
> Channel=1
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> 
> [Asio.Input.1]
> ;Driver=Focusrite USB ASIO
> Channel=1
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
Since the game is a 32-bit process, you need to install 32-bit drivers.

**Comment by JesseWebDotCom** [comment]
> Since the game is a 32-bit process, you need to install 32-bit drivers.

Please explain

**Comment by mdias** [comment]
@JesseWebDotCom sometimes driver installers will allow you to select if you want 64 bit, 32 bit or both versions of the ASIO drivers.
For RS ASIO it is mandatory to have the 32 bit drivers installed since both the game and the mod are 32-bit.

Alternatively you'll need to fiddle around with programs like Voicemeeter (which provide a 32-bit driver) to route the audio to your 64 bit interface asio driver.

**Comment by JesseWebDotCom** [comment]
Interesting as I did have Voicemeeter installed (for another reason) on my previous Win11 install where this was working.  I will give that a try as I don't see any Focusrite Scarlett Solo 32 bit drivers.
