### ISSUE TITLE
wineasio32 and wineasio (version compatibility in Linux)

### ISSUE THREAD

**Issue by OdinVex** [mdias/rs_asio#424]
Could you also look for `wineasio32.dll`, Linux users use both `wineasio` and `wineasio32` (depending upon version of `wineasio`, and both dll are 32-bit).

**Comment by mdias** [comment]
This should be easy enough.
Can you link me some information regarding which version/distro etc uses the `wineasio32` name too?

**Comment by mdias** [comment]
I will have a look and probably have a release ready today :)

**Comment by mdias** [comment]
Please try [this release](https://github.com/mdias/rs_asio/releases/tag/v0.7.1) which should try both `wineasio32.dll` and `wineasio.dll` and report back :)

**Comment by mdias** [comment]
All good. Keep in mind you should use `wineasio-rsasio` as the driver name to use this automatically detected driver.

Everything else should just be interaction between wineasio, jack, and whatever sound server you use, so there's not much else I can help with there unfortunately.

Thank you for trying it though, I'll promote that release to a normal release and close this issue.

**Comment by pdriley** [comment]
If you are using pipewire to supply your jack backend, you might be running into trouble with the steam runtime using a jack library with an previous incompatible protocol. Game would not detect sound until copied the system (pipewire in my case) library on into steam sniper platform
