### ISSUE TITLE
Teyun Q-24

### ISSUE THREAD

**Issue by sprxngh** [mdias/rs_asio#427]
Teyun Q-24 Work with driver ASIO4ALL v2

**Comment by mdias** [comment]
Thank you for the report. Added to the list 👍

**Comment by c4rbss** [comment]
please could you provide the .ini file, i couldn't understand how to properlly configure

**Comment by sprxngh** [comment]
My RS_ASIO.ini

`# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=`











My Rocksmith.ini

`[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1920
ScreenHeight=1080
Fullscreen=1
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=0
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1
`

**Comment by renanleonel** [comment]
> My RS_ASIO.ini
> 
> ```
> for "EnableWasapiOutputs" you can use -1 to have a message prompting
> to use either WASAPI or ASIO for output every time you boot the game
> [Config]
> EnableWasapiOutputs=0
> EnableWasapiInputs=0
> EnableAsio=1
> 
> [Asio]
> ; available buffer size modes:
> ;    driver - respect buffer size setting set in the driver
> ;    host   - use a buffer size as close as possible as that requested by the host application
> ;    custom - use the buffer size specified in CustomBufferSize field
> BufferSizeMode=custom
> CustomBufferSize=192
> 
>  if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
>  when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
>  true if RS ASIO detects the usage of Asio4All.
>  the same applies for all inputs.
> [Asio.Output]
> Driver=ASIO4ALL v2
> BaseChannel=0
> AltBaseChannel=
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> EnableRefCountHack=
> 
> [Asio.Input.0]
> Driver=ASIO4ALL v2
> Channel=0
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> EnableRefCountHack=
> 
> [Asio.Input.1]
> Driver=
> Channel=1
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> EnableRefCountHack=
> 
> [Asio.Input.Mic]
> Driver=
> Channel=1
> EnableSoftwareEndpointVolumeControl=1
> EnableSoftwareMasterVolumeControl=1
> SoftwareMasterVolumePercent=100
> EnableRefCountHack=
> ```
> 
> My Rocksmith.ini
> 
> ```
> [Audio]
> EnableMicrophone=1
> ExclusiveMode=1
> LatencyBuffer=2
> ForceDefaultPlaybackDevice=
> ForceWDM=0
> ForceDirectXSink=0
> DumpAudioLog=0
> MaxOutputBufferSize=
> RealToneCableOnly=0
> MonoToStereoChannel=0
> Win32UltraLowLatencyMode=1
> [Renderer.Win32]
> ShowGamepadUI=0
> ScreenWidth=1920
> ScreenHeight=1080
> Fullscreen=1
> VisualQuality=1
> RenderingWidth=0
> RenderingHeight=0
> EnablePostEffects=0
> EnableShadows=1
> EnableHighResScope=1
> EnableDepthOfField=1
> EnablePerPixelLighting=1
> MsaaSamples=4
> DisableBrowser=0
> [Net]
> UseProxy=1
> [Global]
> Version=1
> ```

@sprxngh i just copied your configuration with my Teyun, but my guitar doesn't produce any sound in the game. when using Reaper, these are my configurations:

![image](https://github.com/user-attachments/assets/8248b0b2-6b0a-419c-9a30-13af5572e33f)

do you have any tips?

**Comment by Julio-Cesar-PC** [comment]
Can you explain the config of the interface. if hi rez is on and lopp back, mono, and channel 0 is the phone output?

**Comment by DarkGabo0112** [comment]
Hey, i just got the Teyun Q-24, did everything as above, but my rocksmith isnt outputing sound, does anyone know what might be the issue?

My RS_ASIO-log

[RS_ASIO-log.txt](https://github.com/user-attachments/files/20972897/RS_ASIO-log.txt)

**Comment by mdias** [comment]
@DarkGabo0112 You might not have your ASIO4ALL configured correctly.
Put the game in windowed mode and access the ASIO4ALL configuration panel in your tray bar. After you change your settings there, restart the game.

You should also tell us where you have your speakers/headphones connected.

**Comment by rrvgarcia** [comment]
I still cant use in rocksmith. It doesnt show anything on mic inputs

**Comment by EricJordanBastos** [comment]
Worked pretty well here ASIO4ALL V2.19 and RS ASIO V0.7.4
