### ISSUE TITLE
Recommended audio interface?

### ISSUE THREAD

**Issue by JesseWebDotCom** [mdias/rs_asio#428]
While the main page states interfaces that work well, it doesn’t list a recommended interface (ie most performant with the least issues and complexity).  I think this will help reduce reported compatibility issues.

so what do you all recommend that works great for you (maybe agreement here would get it listed on the front page)?

I’m also looking at price (ie something reasonable most rocksmith users could afford) and portability (something you can easily connect/disconnect between multiple computers, etc.

**Comment by mdias** [comment]
Of all the ones that I've had, the one that's probably the simplest to get going and works fine was a Behringer UMC204HD. It should be relatively cheap too.
