### ISSUE TITLE
Only Detects Focusrite Thunderbolt ASIO Driver, not Focusrite USB ASIO Driver, Also game audio is fuzzy

### ISSUE THREAD

**Issue by zackwaterman** [mdias/rs_asio#429]
0.000 [INFO]   - Wrapper DLL loaded (v0.7.1)
0.000 [INFO]  PatchOriginalCode
0.031 [INFO]  image crc32: 0xd1b38fcb
0.260 [INFO]  Patching CoCreateInstance
0.260 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.260 [INFO]  Patching call at 00C02DBD
0.260 [INFO]  Patching call at 00E75278
0.260 [INFO]  Patching PortAudio MarshalStreamComPointers
0.260 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.260 [INFO]  Patching call at 00E7483F
0.260 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.260 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.260 [INFO]  Patching call at 00E748F4
0.260 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.260 [INFO]  Patching bytes at 007C0C5F
0.260 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.260 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.260 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.260 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.
0.260 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.
0.261 [INFO]  AsioHelpers::FindDrivers
0.261 [INFO]    Focusrite Thunderbolt ASIO
0.261 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.261 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.261 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
0.261 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.261 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.261 [INFO]    hr: 80070490
0.261 [INFO]    *ppEndpoint: 00000000
0.261 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.261 [INFO]    hr: 80070490
0.261 [INFO]    *ppEndpoint: 00000000
0.261 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.261 [INFO]    hr: S_OK
0.261 [INFO]    *ppDevices: 0BA44118
0.268 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
28.859 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
29.035 [INFO]   - Wrapper DLL unloaded

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Audio]
EnableMicrophone=1
ExclusiveMode=1
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1920
ScreenHeight=1080
Fullscreen=1
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1

**Comment by mdias** [comment]
Please see #425
