### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by Cxlxssal** [mdias/rs_asio#432]
Everytime I try to download Asio it always gives me a virus warning and when i check windows security it says it detects a trojan

![Screenshot 2024-04-17 145132](https://github.com/mdias/rs_asio/assets/167368565/d8b7cfb7-5d3b-4488-82f3-3ad4e1f22a82)
![Screenshot 2024-04-17 145041](https://github.com/mdias/rs_asio/assets/167368565/cc61e1ed-4a22-4f86-b9e7-6920aeb39164)
![Screenshot 2024-04-17 145041](https://github.com/mdias/rs_asio/assets/167368565/7ba13629-d809-41ce-9c3b-1284968af62d)

**Comment by mdias** [comment]
This is a false positive. I just tested copying the zip file I have stored locally to the windows downloads folder and I'm also getting this warning.
However if I re-generate the zip file, it seems to go away.

I'm guessing somehow the file has been signature-marked as a potential threat, however I would encourage you to try any other malware software to check, or even just extract the files and do a windows scan; it should be clean.

I'll probably re-upload a newly generated zip file to avoid scaring people away.

**Comment by mdias** [comment]
I just uploaded a new zip file.

**Comment by Cxlxssal** [comment]
I got it to download but is said something about malicious content but idk because I've downloaded it before and I've never gotten anything like this to pop up

**Comment by mdias** [comment]
I would assume the antivirus database just got updated and now it was flagging the old zip as a false positive.
