### ISSUE TITLE
No Input Detected

### ISSUE THREAD

**Issue by nohatt** [mdias/rs_asio#433]
I'm having a few issues. I've followed the installation guide, however I cannot seem to get it to work. 
![image](https://github.com/mdias/rs_asio/assets/167656969/dace602b-4a39-4699-98c5-12003bb6f836)
![image](https://github.com/mdias/rs_asio/assets/167656969/f11a4697-bb70-4f21-91f0-e6751a4d130f)
![image](https://github.com/mdias/rs_asio/assets/167656969/130cd389-2f8d-4215-9dc3-c2787a5596ef)
RS_ASIO was previously working perfectly with my Presonus Audiobox interface. Once switching to the Steinberg UR22C, it no longer works. I uninstalled and reinstalled rocksmith and RS_ASIO, however that did not fix my problems. Once launching Rocksmith, the audio continuous cuts in and out. It also does not detect any RTC inputs. Appreciate any help!

**Comment by mdias** [comment]
What game version is this?

**Comment by nohatt** [comment]
![image](https://github.com/mdias/rs_asio/assets/167656969/6145f106-09b9-46d4-ab4a-3add0cf32033)
is that what you need?

**Comment by mdias** [comment]
Yes.
That looks like the Build ID for the MacOS build of the game. How are you even able to get RS ASIO running there?

RS ASIO will only run properly on the Windows build of the game.

**Comment by nohatt** [comment]
I am playing on windows :) I’m not sure why that looks like the Mac build, but the game runs fine other than that audio bug I mentioned.

**Comment by mdias** [comment]
RS ASIO is not recongizing your version of the game, and you gave a suspicious Build ID...
Are you running the latest version of the game on steam?

**Comment by nohatt** [comment]
It says my game is up to date. I have another computer that is a mac and I've installed rocksmith on that as well. Could it be giving the build ID from that even though im on my Windows computer?

**Comment by nohatt** [comment]
Just to be sure, I attempted to download the pc version straight from steam DB and replaced the files. It still says the build ID is the mac version even though I replaced the files.
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/15069640/RS_ASIO-log.txt)
This is the log file after first launch. I still have the audio glitch and the inputs look wrong.

**Comment by mdias** [comment]
I don't fully understand what you mean by replacing files downnloaded from steam DB, but you seem to have RS ASIO loading now.

You also seem to be trying to use 2 different ASIO drivers for output and input, which is fine, but without explanation it makes it difficult to understand what kind of setup you're trying to achieve...

Since your input drivers are set to Yamaha Steinberg, I suppose that's the interface you want to use to connect your guitar while you want to output the sound elsewhere?
If so, assuming your guitar is connected to the first input of your interface, try this config:

```
# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Yamaha Steinberg USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```

**Comment by nohatt** [comment]
Had the same audio bug happen. This prompt showed up shortly after booting the game. 
![image](https://github.com/mdias/rs_asio/assets/167656969/d8d14523-b2eb-4db2-8823-c179e1d7c2f6)
Here's an example of the audio I'm hearing. 
https://github.com/mdias/rs_asio/assets/167656969/434ee2b9-4789-4f38-99cc-2eb176159d35
And Rocksmith seems to not be seeing my interfaces inputs.

**Comment by mdias** [comment]
The config I posted is not using voice meeter or other vb-audio asio drivers, so if you got this message I'm guessing you have a virtual cable device set as your default playback device on windows?
That could help explain that audio issue...
Also, how did you record this? Usually windows won't allow you to record since the game will take exclusive access to the audio device for latency reasons.

**Comment by nohatt** [comment]
I used the voicemeeter record feature. 
![image](https://github.com/mdias/rs_asio/assets/167656969/a52cf092-12f2-45b1-9148-85db7bf98107)

**Comment by mdias** [comment]
Most interfaces/drivers will not play well with multiple applications trying to use ASIO at the same time, that and with the config I sent you, you're also trying to grab exclusive access from WASAPI.

It's getting hard to help you with new variables appearing all the time on your setup...

Have you ever tried to run the game on a minimal setup first? No ASIO, no extra programs, no virtual cables/interfaces and see if it even works fine that way?

**Comment by nohatt** [comment]
Yes I used to play the game with just the RTC and it worked fine. I then got an interface and wanted to use that so I followed this guide: https://raidntrade.com/tutorials/RS-ASIO-VoiceMeeter.html , and with my previous presonus audiobox interface everything worked great. Now, once switching to this interface these issues popped up.

**Comment by nohatt** [comment]
Still attempting to get this to work. This was my most recent log file. 
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/15154319/RS_ASIO-log.txt)
I've attempted to read it, but I have no clue what's going on with it. 

I've tried making my interface directly the input and output, but that resulted in the same audio distortion. I then gave the old method a try, same result. I'm really not sure where to go from here, especially since I can't decipher the log file.

**Comment by mdias** [comment]
I'm a bit lost right now on this issue... I can't even tell anymore what you tried and didn't try; let's start from scratch...

So, you say that without RS ASIO it used to work fine. That's a good first step.

Now you want to use RS ASIO, here's a couple of questions:

1. Where will your speakers be connected to?
2. Where will your guitar be connected to?
3. If you don't use voicemeeter and instead use your interface drivers directly can you have a working setup?

PS: Don't use BOTH `Yamaha Steinberg USB ASIO` and `Voicemeeter Virtual ASIO`. In many interface drivers that will cause issues.
There's no reason you wouldn't be able to use `Voicemeeter Virtual ASIO` for both input and output, and then you just patch the sound to your real outputs in voicemeeter.

**Comment by nohatt** [comment]
1. My speakers are connected to my interface.
2. My guitar is also connected to my interface. 
3. I've attempted to use Yamaha Steinberg USB ASIO for both input and output but it didn't change anything. I can give that another try though.

**Comment by nohatt** [comment]
I have set my interface to be the default playback and recording in my PC and have made Yamaha Steinberg USB ASIO the input and output. This has fixed the weird audio, however, I do not see my interface or any real tone cable as an input. With my previous interface, its inputs showed up both as a Real Tone Cable, which is what I assume is meant to happen. Is there any information you need?

**Comment by mdias** [comment]
> I have set my interface to be the default playback and recording in my PC and have made Yamaha Steinberg USB ASIO the input and output. This has fixed the weird audio

I can't tell if you were using WASAPI or ASIO for the output in this scenario. Usually if using ASIO the windows settings should make no difference as the whole purpose of using ASIO is to go around the windows sound system.
But if you say it fixed it, then I guess you were still using `EnableWasapiOutputs=1` with empty output drivers.

> I do not see my interface or any real tone cable as an input. With my previous interface, its inputs showed up both as a Real Tone Cable,

Not sure what you mean by this. If I remember correctly the game has no screen where it shows your inputs.
Unless you mean that the game complains about missing RTC cable?


So if both the speakers and guitar are connected to the same audio interface, your config should look like this:

```
# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=Yamaha Steinberg USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Yamaha Steinberg USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```

Can you post the log after running the game with the above config?

**Comment by nohatt** [comment]
Very sorry for taking so long, had finals this week. I tried using this configuration and I could not hear my bass. For some reason the log has not updated since 4/17, even though I've relaunched the game many times since then. 
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/15287736/RS_ASIO-log.txt)
And what I meant about the inputs was that with my last interface, my inputs would show up as two Real Tone Cables when I would click on "Available Inputs" here. However, now I only see system inputs when I click on it. 
![image](https://github.com/mdias/rs_asio/assets/167656969/b3771fca-4df2-4fcc-9dae-60cf7d0e55cd)

**Comment by mdias** [comment]
The important part of your log:
```
0.149 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Voicemeeter Virtual ASIO
0.149 [INFO]  Creating AsioSharedHost - dll: c:\program files (x86)\vb\voicemeeter\vbvm_asiodriver.dll
...
0.221 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK

0.221 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Yamaha Steinberg USB ASIO
0.221 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
2.730 [ERROR]  ASIO Error: Device could not be opened.
2.730 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
2.730 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.

2.730 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Yamaha Steinberg USB ASIO
2.730 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
5.239 [ERROR]  ASIO Error: Device could not be opened.
5.239 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\Yamaha\Yamaha Steinberg USB Driver\ysusb_asio32.dll
5.239 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
```

As you can see, the inputs cannot initialize the `Yamaha Steinberg USB ASIO` ASIO driver.
This could be for several reasons, but I suspect it's because you're already using your Yamaha device with Voicemeeter (which you're using as the output driver).

Your drivers most likely don't support more than one application using the device at the same time.

**Comment by nohatt** [comment]
That was a log from a few days ago. I'm not sure why but the RS_ASIO log file doesn't change anymore when I launch the game. I've had my input and output set to Yamaha Steinberg USB ASIO for a while now, and even with that it doesn't see the inputs. Even with voicemeeter closed and the outputs and inputs set to Yamaha Steinberg USB ASIO it's not recognizing it for some reason.

**Comment by nohatt** [comment]
I gave the game one last reinstall and it worked this time. Thank you for your help!
