### ISSUE TITLE
WineASIO-RSASIO fails to open

### ISSUE THREAD

**Issue by Skyler69420** [mdias/rs_asio#440]
Title says it all. I've followed [this](https://github.com/mdias/rs_asio/blob/master/docs/linux/ubuntu_1204_lts.md) link to try and get wineasio working with no luck. 
I also tried to use the wineasio-register file in protons wine prefix however when I executed that command I get this
```
sudo env WINEPREFIX=~ /home/skyler/.steam/steam/steamapps/compatdata/221680/pfx/ wineasio-register 
env: ‘/home/skyler/.steam/steam/steamapps/compatdata/221680/pfx/’: Permission denied
```
I am currently on Manjaro with the realtime kernel. I have jack and Cadence installed and wine asio is working with Ableton Live

I have also included my rs asio log here
[RS_ASIO-log.txt](https://github.com/user-attachments/files/15901596/RS_ASIO-log.txt)

Any help would be appreciated ;))

**Comment by mdias** [comment]
It seems that RS ASIO is actually loading the WineASIO DLL, but WineASIO DLL is erroring out. Probably because there's no jack daemon running?
It's hard to tell exactly the reason because it doesn't give us proper error messages, as you can see here:
```
0.146 [ERROR]  ASIO Error: WineASIO does not return error messages
```

**Comment by Skyler69420** [comment]
Hmm weird. Jack is configured and running as I've tested it with reaper. Jack's 32bit libraries were already installed.
Is there a way to get wine asio error messages at all?

**Comment by mdias** [comment]
I'm not sure. Perhaps there's some sort of environment variable that can output some log messages?

See the [wine faq](https://wiki.winehq.org/FAQ#get_log) or in the case of steam with proton, try the [PROTON_LOG=1 %command%](https://github.com/ValveSoftware/Proton?tab=readme-ov-file#runtime-config-options) option.

**Comment by mdias** [comment]
Thank you for the update. Glad you got it to work.

Your proton log contains this message which is likely the reason it didn't work for you:
```
JACK protocol mismatch 8
Cannot connect to the server
```

Also no worries with time spent; I only look at these issues when I have some free time :)
