### ISSUE TITLE
No guitar with Focusrite 2i2 4th GEN

### ISSUE THREAD

**Issue by Kenshikaze** [mdias/rs_asio#443]
Using the 3rd GEN .ini settings I am able to get game sound however, the game keeps telling me that my microphone is unplugged.

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
;Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
Go the the game options and change from using Microphone to using RTC.
RS ASIO makes your configured inputs be detected as RTC cables, not as microphones.

**Comment by Kenshikaze** [comment]
Oh blimey, my apologies. Thank you! Sent from my Galaxy
-------- Original message --------From: Micael Dias ***@***.***> Date: 6/26/24  11:44 PM  (GMT+00:00) To: mdias/rs_asio ***@***.***> Cc: Adam ***@***.***>, Author ***@***.***> Subject: Re: [mdias/rs_asio] No guitar with Focusrite 2i2 4th GEN (Issue #443) 
Go the the game options and change from using Microphone to using RTC.
RS ASIO makes your configured inputs be detected as RTC cables, not as microphones.
