### ISSUE TITLE
Hotone Ampero II Stage (maybe it will work on Ampero II Stomp)

### ISSUE THREAD

**Issue by SteveGrey7** [mdias/rs_asio#444]
This works successfully on my Hotone Ampero II Stage with firmware v1.0.4 and Hotone Generic USB ASIO Driver V5.57.1.
I also tested multiplayer and it worked for me.

Maybe exactly the same settings will be suitable for Ampero II Stomp users, since these two amp modelers are almost identical to each other. But I don't have Ampero Stomp to verify this.

If you use L(MONO) as input for playing singleplayer, use this. For R as input change Channel 6 to 7.
RS_ASIO.ini:
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=HOTONE AUDIO USB Audio Device
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=HOTONE AUDIO USB Audio Device
Channel=6
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```

If you want to play multiplayer, try this.
RS_ASIO.ini:
```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=HOTONE AUDIO USB Audio Device
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=HOTONE AUDIO USB Audio Device
Channel=6
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=HOTONE AUDIO USB Audio Device
Channel=7
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```
If you're having trouble with game note recognizing, try to change REC LEVEL(7/8) in Global Settings -> USB Audio.

If you want to hear only your guitar signal processed by Hotone Ampero, don't forget to mute sound of your guitar ingame.
Otherwise, if you want hear your guitar processed by game sound engine, mute output node of your Chain, or change Output mode of node.

To explain why channels 6 and 7 are used here:
0 - game will take signal from LEFT channel of Chain A output (between slot A6 and output node A)
1 - from RIGHT channel of Chain A output (between slot A6 and output node A)
2 - from LEFT channel of Chain B output (between slot B6 and output node B)
3 - from RIGHT channel of Chain B output (between slot B6 and output node B)
4 - from LEFT channel of FX Loop Return Jack _(I haven't tested FX Loop as input, but in theory it can be used instead ch 6/7)_
5 - from RIGHT channel of FX Loop Return Jack
6 - from L(MONO) input jack _(actually a dry signal of first input. It's better for game note recognition)_
7 - from R input jack _(it's dry signal of second input)

From 0 to 3 this will be a wet signal. This means that all the effects that you apply in the chain of Ampero II Stage will affect the signal read by the game, so it is not recommended to set these channels in ini file. The game needs your dry signal, that is, channels 6 and 7.

**Comment by mdias** [comment]
Thank you for the detailed explanation.
Added the interface to the list 👍

**Comment by kdby-io** [comment]
Ampero II Stomp also works! (firmware v1.0.4 and Hotone Generic USB ASIO Driver V5.57.1.)

**Comment by mdias** [comment]
@kdby-io added, thank you for the report 👍

**Comment by MrHamburger27** [comment]
> Ampero II Stomp also works! (firmware v2.0.0 and Hotone Generic USB ASIO Driver V5.57.1.)

Can I ask about your detailed settings? I'm using the same version firmware and Hotone Driver, and I copied the entire setting of the RS-Asio.ini, but RS Asio doesn't work on my PC.

**Comment by MrHamburger27** [comment]
> > Ampero II Stomp also works! (firmware v2.0.0 and Hotone Generic USB ASIO Driver V5.57.1.)
> 
> Can I ask about your detailed settings? I'm using the same version firmware and Hotone Driver, and I copied the entire setting of the RS-Asio.ini, but RS Asio doesn't work on my PC.

It worked! I update my firmware version to 2.0.1 and get 48kHz playback.

**Comment by jungsama666** [comment]
@kdby-io Please tell me if it's true, I'm interested in buying this product, and if I can get 48kHz playback, it will give me another reason to buy😊
