### ISSUE TITLE
"It sounds like your cable is unplugged, connect a Rocksmith Real Tone Cable"

### ISSUE THREAD

**Issue by agonsvec** [mdias/rs_asio#445]
Hi!

I followed every step, but still get the "It sounds like your cable is unplugged, connect a Rocksmith Real Tone Cable" error when selecting input. 

![image](https://github.com/mdias/rs_asio/assets/73953547/27499c47-5449-41c4-939d-e22eaf68aefb)

Right now im using a Presonus Studio 24c audio interface, and works perfectly with other ASIO apps, but it seems like the mod somehow has not been installed properly.

Is there any known fix to this?

**Comment by mdias** [comment]
Please post your `RS-ASIO.ini` and `RS-ASIO-log.txt` file contents so I can check what's happening.
