### ISSUE TITLE
Confirmation Report: Works with NUX Mighty Lite BT MK II

### ISSUE THREAD

**Issue by zyf722** [mdias/rs_asio#446]
Actually not an issue here - just to report and confirm that it works perfectly with NUX Mighty Lite BT MK II.

Use the same configuration as #364 and everything goes quite well:
- LatencyBuffer=3
- ASIO Buffer Size = 128 (in NUX control panel)
- Routing Mode = Dry Out (in NUX Mighty Editor)

Much appreciated for creating this fantastic patch!

**Comment by mdias** [comment]
Thank you for the report!
Added to the list 👍

**Comment by ashviinbano20-hub** [comment]
> Actually not an issue here - just to report and confirm that it works perfectly with NUX Mighty Lite BT MK II.
> 
> Use the same configuration as [#364](https://github.com/mdias/rs_asio/issues/364) and everything goes quite well:
> 
> * LatencyBuffer=3
> * ASIO Buffer Size = 128 (in NUX control panel)
> * Routing Mode = Dry Out (in NUX Mighty Editor)
> 
> Much appreciated for creating this fantastic patch!

I tried everything here and the post on #364 . But I'm still getting the no real tone cable alert. Not really tech savvy. Could anyone help me out?

**Comment by mdias** [comment]
@ashviinbano20-hub what alert is this "real tine cable alert" you mention?
There's not supposed to be any alert.

**Comment by YMS444** [comment]
If anyone struggles with setting this up: I only got my NUX Mighty Lite BT MK II running after following the instructions here, in #364, _and_ in https://github.com/mdias/rs_asio/issues/437#issuecomment-2133923754

(Alternatively, it also worked in Direct Connect mode.)
