### ISSUE TITLE
Crash when using CDLC

### ISSUE THREAD

**Issue by NicolasMuzette** [mdias/rs_asio#45]
Hi,

Thanks for this amazing program.

I use a Focusrite Scarlett 2i2 2nd Gen with following settings. the game freezes when i play the second song if i use CDLC. Same problem with Fresh IInstall. works perfectly (with latency tho) without RS_asio.

```
[Config]
EnableWasapi=1
EnableAsio=0

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

```
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=2
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=2
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
```

**Comment by mdias** [comment]
That's a strange one... Can you post the `RS_ASIO-log.txt` file on [pastebin](https://pastebin.com/)?

**Comment by NicolasMuzette** [comment]
Nevermind, i didn't do my homework properly before pyblishing issue. This is a known problem that can be solved by adding a dll file on the folder, and has nothing to do with your code. sorry for bothering you, thanks again for this amazing program. i go back to my guitar !

More informations here about the fix of my problem if you are curious : https://www.youtube.com/watch?v=I2GB16G0LD0
http://customsforge.com/topic/33138-rocksmith-remastered-cdlc-fix/
