### ISSUE TITLE
No audio in game with Presonus iTwo

### ISSUE THREAD

**Issue by FriendlyMxdder** [mdias/rs_asio#451]
Hi there, I followed the guide and it is detecting my guitar finally but I have no in game audio now. Here is my log.

0.000 [INFO]   - Wrapper DLL loaded (v0.7.1)
0.000 [INFO]  PatchOriginalCode
0.028 [INFO]  image crc32: 0xd1b38fcb
0.225 [INFO]  Patching CoCreateInstance
0.225 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.225 [INFO]  Patching call at 00C02DBD
0.225 [INFO]  Patching call at 00E75278
0.225 [INFO]  Patching PortAudio MarshalStreamComPointers
0.225 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.225 [INFO]  Patching call at 00E7483F
0.225 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.225 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.225 [INFO]  Patching call at 00E748F4
0.225 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.225 [INFO]  Patching bytes at 007C0C5F
0.227 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.227 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.227 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.227 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.
0.228 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.
0.229 [INFO]  AsioHelpers::FindDrivers
0.229 [INFO]    AudioBox ASIO Driver
0.229 [INFO]    ioStation ASIO Driver
0.230 [INFO]    Quantum ASIO driver
0.230 [INFO]    Quantum ES ASIO
0.230 [INFO]    Quantum HD ASIO
0.230 [INFO]    Revelator ASIO
0.230 [INFO]    Studio 192 ASIO
0.230 [INFO]    Studio USB ASIO Driver
0.230 [INFO]    StudioLive AR ASIO
0.230 [INFO]    StudioLive Classic USB
0.230 [INFO]    StudioLive Series III ASIO
0.230 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: AudioBox ASIO Driver
0.230 [INFO]  Creating AsioSharedHost - dll: c:\program files\presonus\universal control\drivers\audiobox\x64\paeusbaudioasio.dll
0.236 [INFO]    ASIO input channels info:
0.236 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
0.236 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
0.236 [INFO]    ASIO output channels info:
0.236 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output Left
0.236 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output Right
0.236 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.236 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: AudioBox ASIO Driver
0.236 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.237 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 26 render devices, 1 capture devices
0.237 [INFO]    hr: S_OK
0.237 [INFO]    *ppEndpoint: 14B8EF20
0.237 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.237 [INFO]    hr: S_OK
0.237 [INFO]    *ppEndpoint: 14B8EF80
0.237 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.238 [INFO]    hr: S_OK
0.238 [INFO]    *ppDevices: 14B18488
0.238 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.238 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.238 [INFO]    *cProps: 2
0.238 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.238 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.238 [INFO]    *pDataFlow: eRender
0.238 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.238 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.238 [INFO]  {0.0.0.00000000}.{9c4ad045-977a-4ad3-ae67-b637912c0f44} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.239 [INFO]  {0.0.0.00000000}.{9c4ad045-977a-4ad3-ae67-b637912c0f44} DebugWrapperDevicePropertyStore::GetCount
0.239 [INFO]    *cProps: 59
0.239 [INFO]  {0.0.0.00000000}.{9c4ad045-977a-4ad3-ae67-b637912c0f44} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.239 [INFO]  {0.0.0.00000000}.{9c4ad045-977a-4ad3-ae67-b637912c0f44} DebugWrapperEndpoint::GetDataFlow
0.239 [INFO]    *pDataFlow: eRender
0.239 [INFO]  {0.0.0.00000000}.{9c4ad045-977a-4ad3-ae67-b637912c0f44} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.240 [INFO]  {0.0.0.00000000}.{9c4ad045-977a-4ad3-ae67-b637912c0f44} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.241 [INFO]  {0.0.0.00000000}.{a54842f9-5880-4457-b251-f0760f2e9bb6} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.241 [INFO]  {0.0.0.00000000}.{a54842f9-5880-4457-b251-f0760f2e9bb6} DebugWrapperDevicePropertyStore::GetCount
0.241 [INFO]    *cProps: 60
0.241 [INFO]  {0.0.0.00000000}.{a54842f9-5880-4457-b251-f0760f2e9bb6} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.241 [INFO]  {0.0.0.00000000}.{a54842f9-5880-4457-b251-f0760f2e9bb6} DebugWrapperEndpoint::GetDataFlow
0.241 [INFO]    *pDataFlow: eRender
0.241 [INFO]  {0.0.0.00000000}.{a54842f9-5880-4457-b251-f0760f2e9bb6} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.242 [INFO]  {0.0.0.00000000}.{a54842f9-5880-4457-b251-f0760f2e9bb6} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.242 [INFO]  {0.0.0.00000000}.{b0cc3be4-a04b-4786-b0e3-fc6cf2253217} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.242 [INFO]  {0.0.0.00000000}.{b0cc3be4-a04b-4786-b0e3-fc6cf2253217} DebugWrapperDevicePropertyStore::GetCount
0.242 [INFO]    *cProps: 59
0.248 [INFO]  {0.0.0.00000000}.{b0cc3be4-a04b-4786-b0e3-fc6cf2253217} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.248 [INFO]  {0.0.0.00000000}.{b0cc3be4-a04b-4786-b0e3-fc6cf2253217} DebugWrapperEndpoint::GetDataFlow
0.248 [INFO]    *pDataFlow: eRender
0.248 [INFO]  {0.0.0.00000000}.{b0cc3be4-a04b-4786-b0e3-fc6cf2253217} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.248 [INFO]  {0.0.0.00000000}.{b0cc3be4-a04b-4786-b0e3-fc6cf2253217} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.248 [INFO]  {0.0.0.00000000}.{e100ed11-fa30-43b6-bbe8-6668a34f12ff} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.248 [INFO]  {0.0.0.00000000}.{e100ed11-fa30-43b6-bbe8-6668a34f12ff} DebugWrapperDevicePropertyStore::GetCount
0.248 [INFO]    *cProps: 64
0.249 [INFO]  {0.0.0.00000000}.{e100ed11-fa30-43b6-bbe8-6668a34f12ff} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.249 [INFO]  {0.0.0.00000000}.{e100ed11-fa30-43b6-bbe8-6668a34f12ff} DebugWrapperEndpoint::GetDataFlow
0.249 [INFO]    *pDataFlow: eRender
0.249 [INFO]  {0.0.0.00000000}.{e100ed11-fa30-43b6-bbe8-6668a34f12ff} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.249 [INFO]  {0.0.0.00000000}.{e100ed11-fa30-43b6-bbe8-6668a34f12ff} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.249 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.249 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.249 [INFO]    *cProps: 5
0.249 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.249 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.249 [INFO]    *pDataFlow: eCapture
0.249 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.249 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.249 [INFO]  {ASIO IN 0} RSAsioAudioClient::~RSAsioAudioClient
0.260 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.260 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.260 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.260 [INFO]    requested format is not supported
0.260 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.260 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.260 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.260 [INFO]    requested format is not supported
0.260 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.260 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.260 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.260 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
0.260 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
0.260 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 10ms (512 frames)
0.260 [INFO]  AsioSharedHost::Setup - startCount: 0
0.260 [INFO]    post output ready: 0
0.260 [INFO]    ASIOBufferSize - min: 16 max: 2048 preferred: 512 granularity: -1
0.260 [INFO]    Creating ASIO buffers (2 out, 2 in)...
0.319 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
0.319 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 2 | returning: 0
0.319 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 3 | returning: 0
0.319 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 4 | returning: 0
0.319 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 5 | returning: 0
0.319 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 6 | returning: 0
0.319 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.319 [INFO]    *pNumBufferFrames: 512
0.319 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.319 [INFO]    latency: 17ms
0.319 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.319 [INFO]    returning render client
0.320 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.321 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.321 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.321 [INFO]  {ASIO Out} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.321 [INFO]  {ASIO Out} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.321 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.321 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.321 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 512
0.321 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 512
0.321 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.321 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.321 [INFO]  AsioSharedHost::Start - enter startCount: 0
0.321 [INFO]    Starting ASIO stream...
0.321 [INFO]  AsioSharedHost::Start - leave startCount: 1
0.333 [INFO]  AudioBox ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.333 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 512
0.333 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 512
0.333 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.344 [INFO]  AudioBox ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.344 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 512
0.344 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 512
0.344 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.354 [INFO]  AudioBox ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
20.551 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
20.551 [INFO]  AsioSharedHost::Stop - enter startCount: 1
20.551 [INFO]  AsioSharedHost::Stop - stopping ASIO stream
20.551 [INFO]  AsioSharedHost::Stop - leave startCount: 0
20.551 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
26.550 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.550 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.550 [INFO]    requested format is not supported
26.550 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.550 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.550 [INFO]    requested format is not supported
26.550 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.550 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.550 [INFO]    requested format is not supported
26.550 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
26.550 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
26.550 [INFO]  {ASIO IN 0} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
26.550 [INFO]  {ASIO IN 0} RSAsioAudioClient::Initialize - actual buffer duration: 10ms (512 frames)
26.550 [INFO]  AsioSharedHost::Setup - startCount: 0
26.550 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioEndpointVolume dwClsCtx: 1
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
26.550 [INFO]    *pNumBufferFrames: 512
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
26.550 [INFO]    latency: 12ms
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioCaptureClient
26.550 [INFO]    returning capture client
26.550 [INFO]  Patched_PortAudio_MarshalStreamComPointers
26.550 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
26.550 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Start
26.550 [INFO]  AsioSharedHost::Start - enter startCount: 0
26.550 [INFO]    Starting ASIO stream...
26.550 [INFO]  AsioSharedHost::Start - leave startCount: 1
26.551 [INFO]  {ASIO IN 0} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.17
26.561 [INFO]  AudioBox ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
26.561 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.561 [INFO]  {ASIO IN 0} RSAsioAudioClient::SwapBuffers
26.561 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 512
26.572 [INFO]  AudioBox ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
26.572 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.572 [INFO]  {ASIO IN 0} RSAsioAudioClient::SwapBuffers
26.572 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 512
26.582 [INFO]  AudioBox ASIO Driver - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
26.582 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.582 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 512
68.138 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::Stop
68.138 [INFO]  AsioSharedHost::Stop - enter startCount: 1
68.138 [INFO]  AsioSharedHost::Stop - stopping ASIO stream
68.138 [INFO]  AsioSharedHost::Stop - leave startCount: 0
68.138 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
68.251 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
Where do you have your speakers connected?

Also, you're currently using a buffer size of 512 which will result in noticeable latency; use you interface's control panel to change this value to something lower like 128 or even less.

**Comment by FriendlyMxdder** [comment]
> Where do you have your speakers connected?
> 
> Also, you're currently using a buffer size of 512 which will result in noticeable latency; use you interface's control panel to change this value to something lower like 128 or even less.

I have my headset plugged into my PC (USB)

**Comment by FriendlyMxdder** [comment]
I lowered my buffer size to 64, and the game IS detecting my guitar inputs. But I cannot hear the game at all, I cant hear my guitar or the main menu music in game.

**Comment by mdias** [comment]
@FriendlyMxdder you're using ASIO output, not your headset.
To use your normal (windows configured) output you have to leave `Driver=` empty on the output config, and set `EnableWasapiOutputs=1`

**Comment by FriendlyMxdder** [comment]
omg its working now! Thank you so so much!
