### ISSUE TITLE
rs asio.dll not supported in windows?

### ISSUE THREAD

**Issue by rtard-jpeg** [mdias/rs_asio#454]
i copied the files from the zip file and tried to open the game, but the game gave me an error where it tells me that rs_asio.dll is not supported in windows, then it DELETES the dll file. i tried to configure my driver first before opening the game but no dice.

**Comment by mdias** [comment]
> then it DELETES the dll file
sounds like you may have an antivirus moving the file to quarantine or something... please check that.
