### ISSUE TITLE
HX Stomp - "It sounds like your cable is unplugged, connect a Rocksmith Real Tone Cable"

### ISSUE THREAD

**Issue by Rms92** [mdias/rs_asio#455]
HX Stomp is on the latest firmware 3.71. Guitar cable is connected to the Stomp's "L/MONO" Input jack, and the Stomp is connected by USB cable straight to the PC motherboard's USB port. PC automatically recognizes HX Stomp and I can set it as input/output device in sound setting. As an input device it shows up as "Digital Audio Interface (Line 6 HX Stomp)". HX Stomp is also detected by the HX Edit app. 

I also have a JDS Labs Element headphone amplifier connected to the PC. 

I copy/pasted the RS_ASIO files into the game directory and changed the .ini files as per this [config](https://github.com/mdias/rs_asio/issues/251). 

However, when I load up the game, it gives me the "your cable is unplugged" message. Below is the log txt file. No idea if something is wrong with the Stomp or the game.

[RS_ASIO-log.txt](https://github.com/user-attachments/files/16310492/RS_ASIO-log.txt)

**Comment by Rms92** [comment]
RS_ASIO-log.txt (if you don't want to download):

`0.000 [INFO]   - Wrapper DLL loaded (v0.7.1)
0.000 [INFO]  PatchOriginalCode
0.037 [INFO]  image crc32: 0xd1b38fcb
0.137 [INFO]  Patching CoCreateInstance
0.137 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.137 [INFO]  Patching call at 00C02DBD
0.137 [INFO]  Patching call at 00E75278
0.137 [INFO]  Patching PortAudio MarshalStreamComPointers
0.137 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.137 [INFO]  Patching call at 00E7483F
0.137 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.137 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.137 [INFO]  Patching call at 00E748F4
0.137 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.137 [INFO]  Patching bytes at 007C0C5F
0.139 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.139 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.139 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.139 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.
0.140 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.
0.142 [INFO]  AsioHelpers::FindDrivers
0.142 [INFO]    ASIO Helix
0.142 [INFO]    ASIO HX Stomp
0.142 [INFO]    JDS Labs USB Audio Device
0.142 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO HX Stomp
0.142 [INFO]  Creating AsioSharedHost - dll: C:\Windows\SysWow64\L6HXStompAsio_OnInterposer.dll
0.143 [INFO]  Destroying AsioSharedHost - dll: C:\Windows\SysWow64\L6HXStompAsio_OnInterposer.dll
0.143 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.154 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 49 render devices, 0 capture devices
0.154 [INFO]    hr: S_OK
0.154 [INFO]    *ppEndpoint: 1C5EE648
0.154 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.154 [INFO]    hr: 80070490
0.154 [INFO]    *ppEndpoint: 00000000
0.154 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.155 [INFO]    hr: S_OK
0.155 [INFO]    *ppDevices: 09CA4B18
0.155 [INFO]  {0.0.0.00000000}.{0353f9d0-d37b-4635-9c12-77b1bf38a6f2} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.156 [INFO]  {0.0.0.00000000}.{0353f9d0-d37b-4635-9c12-77b1bf38a6f2} DebugWrapperDevicePropertyStore::GetCount
0.156 [INFO]    *cProps: 58
0.165 [INFO]  {0.0.0.00000000}.{0353f9d0-d37b-4635-9c12-77b1bf38a6f2} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.165 [INFO]  {0.0.0.00000000}.{0353f9d0-d37b-4635-9c12-77b1bf38a6f2} DebugWrapperEndpoint::GetDataFlow
0.165 [INFO]    *pDataFlow: eRender
0.165 [INFO]  {0.0.0.00000000}.{0353f9d0-d37b-4635-9c12-77b1bf38a6f2} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.167 [INFO]  {0.0.0.00000000}.{0353f9d0-d37b-4635-9c12-77b1bf38a6f2} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.168 [INFO]  {0.0.0.00000000}.{1347a2d8-3ed4-4a68-b28c-b4ebf8019857} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.168 [INFO]  {0.0.0.00000000}.{1347a2d8-3ed4-4a68-b28c-b4ebf8019857} DebugWrapperDevicePropertyStore::GetCount
0.168 [INFO]    *cProps: 64
0.179 [INFO]  {0.0.0.00000000}.{1347a2d8-3ed4-4a68-b28c-b4ebf8019857} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.179 [INFO]  {0.0.0.00000000}.{1347a2d8-3ed4-4a68-b28c-b4ebf8019857} DebugWrapperEndpoint::GetDataFlow
0.179 [INFO]    *pDataFlow: eRender
0.179 [INFO]  {0.0.0.00000000}.{1347a2d8-3ed4-4a68-b28c-b4ebf8019857} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.179 [INFO]  {0.0.0.00000000}.{1347a2d8-3ed4-4a68-b28c-b4ebf8019857} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.180 [INFO]  {0.0.0.00000000}.{1c97a4e4-4637-447d-8407-4c7e0b92d801} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.180 [INFO]  {0.0.0.00000000}.{1c97a4e4-4637-447d-8407-4c7e0b92d801} DebugWrapperDevicePropertyStore::GetCount
0.180 [INFO]    *cProps: 65
0.191 [INFO]  {0.0.0.00000000}.{1c97a4e4-4637-447d-8407-4c7e0b92d801} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.191 [INFO]  {0.0.0.00000000}.{1c97a4e4-4637-447d-8407-4c7e0b92d801} DebugWrapperEndpoint::GetDataFlow
0.191 [INFO]    *pDataFlow: eRender
0.191 [INFO]  {0.0.0.00000000}.{1c97a4e4-4637-447d-8407-4c7e0b92d801} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.191 [INFO]  {0.0.0.00000000}.{1c97a4e4-4637-447d-8407-4c7e0b92d801} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.196 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.196 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperDevicePropertyStore::GetCount
0.197 [INFO]    *cProps: 63
0.197 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.197 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperEndpoint::GetDataFlow
0.197 [INFO]    *pDataFlow: eRender
0.197 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.198 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.205 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.205 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.205 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.206 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.206 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.206 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.206 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.219 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.219 [INFO]    *pNumBufferFrames: 144
0.219 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.219 [INFO]    latency: 3ms
0.219 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.219 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.221 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.221 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.221 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.221 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.221 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.221 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.221 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
0.221 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
0.221 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.221 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
0.222 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
0.224 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 144
0.224 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 144
64.944 [INFO]  {0.0.0.00000000}.{83021d59-8f2d-4cb2-b8e9-499d26314b3b} DebugWrapperAudioClient<struct IAudioClient3>::Stop
66.866 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
67.017 [INFO]   - Wrapper DLL unloaded
`

**Comment by mdias** [comment]
Your log contains a very strange behavior indeed.
Can you check that `C:\Windows\SysWow64\L6HXStompAsio_OnInterposer.dll` exists in your filesystem and that the 32 bit executable in the [ASIO Driver Tester](https://forum.vb-audio.com/viewtopic.php?t=1204) works for you?

**Comment by Rms92** [comment]
The L6HXStompAsio_OnInterposer.dll file does not exist. I am able to launch both the 32 bit and the 64 bit executable in the driver tester folder. In both executables, when I click on 'Devices', I see three of them: ASIO Helix, ASIO HX Stomp, and ASIO JDS Labs USB Audio Device. Clicking on the first two devices returns "Driver not found".

**Comment by mdias** [comment]
Right, so your ASIO driver doesn't appear to be registered correctly in the system.
The registry says the driver is located on `C:\Windows\SysWow64\L6HXStompAsio_OnInterposer.dll` and when RS ASIO tries to load it, it fails, just like the ASIO Driver Tester.

Try reinstalling the latest drivers for your interface to see if that fixes the problem.

**Comment by Rms92** [comment]
Ohh I see. When I tried to install the driver, the installer automatically chose Program Files (x86) as the installation directory. What if I just move or copy/paste all the files from the previous folder into SysWow64? 

I tried doing this with L6HXStompAsio_OnInterposer.dll, and the tester finally detected the driver. 
![Files](https://github.com/user-attachments/assets/61711251-6bf1-40f2-a310-631261020fc1)

**Comment by mdias** [comment]
It might work, but it's not the best idea.
In fact it would probably be better to go in the registry and change the path to the Program Files one, but that's also very annoying.

If those drivers install the files in one location, but then the registry entry points into another location, it sounds like there's a bug with the installer as I suppose no other ASIO-enabled application will work with that.
Could be worth checking if just reinstalling fixes the issue, and if not then maybe contacting Line6's support to let them know about it could help.

**Comment by Rms92** [comment]
Reinstalling does not help. Could you point me to a tutorial for regedit? Or is it a very lengthy process? Either way, I will contact Line6 support for sure and use the Stomp as I'm for now. Will update when I hear back from them.

**Comment by mdias** [comment]
`HKEY_LOCAL_MACHINE\SOFTWARE\ASIO` contains several folders with the driver names, if you open the one you want (`ASIO HX Stomp`), inside there will be a CLSID key; let's imagine that key is `{ffffffff-ffff-ffff-ffff-ffffffffffff}`.

Now, inside `HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{ffffffff-ffff-ffff-ffff-ffffffffffff}\InProcServer32` (note this would be your previously found key) the default key will point to the 32-bit DLL file. To change he 64-bit DLL path look into `HKEY_CLASSES_ROOT\CLSID\{ffffffff-ffff-ffff-ffff-ffffffffffff}\InProcServer32`.

You should be able to change these to point to the correct drivers locations. You can see the path RS ASIO tries to load from on the log it generates.

If for some reason it's not reading from the path you expect after you changed the paths, use the Find functionality in `regedit` to find more entries of your driver key `{ffffffff-ffff-ffff-ffff-ffffffffffff}` and change as appropriate.

**Comment by Rms92** [comment]
Ok, so I tried reinstalling the drivers and what I noticed was that the installer automatically sets the destination folder to be in program files (x86)\Line6.

This is the same with many of the Line6 software I downloaded. E.g., HX Edit (the preset editing software), also installs to program files (x86), and you have the option to install drivers for other devices (all of which are placed in program files).

Don't know if that is of much help but just thought it could be worth sharing. I tried changing registry as you said. The log file points to the correct path now but also ends in error. I've attached the log file as well. 

![Stomp Driver installer](https://github.com/user-attachments/assets/0822b62d-8115-469c-aff3-b100046a5755)

![HX Edit installer 1](https://github.com/user-attachments/assets/8319aee3-5be4-4db4-9e8e-5644df3891ef)

![HX Edit installer 2](https://github.com/user-attachments/assets/e1ab00cb-fecd-4d83-97b2-d163ab7a8754)

[RS_ASIO-log.txt](https://github.com/user-attachments/files/16328058/RS_ASIO-log.txt)

**Comment by ConnorGriffin** [comment]
I experienced the same issue, it seems the Line6 HX Stomp driver installer does not work properly, and version 2.x doesn't even ship with a 32 bit driver at all. 

I was able to get this working by installing version 1.97 of the HxStomp drivers, then following [mdias' instructions](https://github.com/mdias/rs_asio/issues/455#issuecomment-2241159725) for locating the driver DLL path, and updating the path to: `"C:\Program Files (x86)\Line6\Tools\Driver2 Archive\HxStomp\L6HXStompAsio_OnInterposer.dll"`
