### ISSUE TITLE
Two real tone cables detected

### ISSUE THREAD

**Issue by roeiburstein** [mdias/rs_asio#456]
I'm playing Rocksmith on Mac OS using a Focusrite Scarlette 2i2 3rd gen and I get the error message `Two real tone cables have been detected. We dont know which cable you are using. Disconnect one of your Rocksmith Real Tone Cables.`. When I go to the input settings I see 2 and sometimes more real tone cables. The game works for about 2 minutes and then the message pops up and blocks gameplay. I'm using the recommended RS_ASIO.ini and Rocksmith.ini files. All help would be greatly appreciated!

**Comment by roeiburstein** [comment]
A few threads of people with the same problem. All of them are very old with no help:
https://www.reddit.com/r/rocksmith/comments/eo5e8i/detecting_2_realtone_cables_with_asio/
https://www.reddit.com/r/rocksmith/comments/4o108k/nocablelauncher_w_scarlett_2i2_two_rocksmith/
https://steamcommunity.com/app/221680/discussions/0/558746089318020918/?l=russian

**Comment by mdias** [comment]
The threads you linked are all very old, and only the first one is about RS ASIO.

RS ASIO no longer displays that message, and is not available on MacOS.

**Comment by roeiburstein** [comment]
I'm playing rocksmith on Mac OS on steam. Are you saying the files in this repo are for windows only? The two cables message I get is in the game (with and without the files). The game registers my guitar and I can play a few songs before seeing the error

**Comment by mdias** [comment]
Correct, RS ASIO is for windows only.
