### ISSUE TITLE
Behringer UMC22 no driver only ASIO4all

### ISSUE THREAD

**Issue by talier00t** [mdias/rs_asio#461]
there is no drivers coming with this audio interface. it only works with ASIO4all and ASIO4all doesn't work. it shows up as ASIO4all v2 but   whenever i set up drivers at rs asio.ini as ASIO4all v2 it just doesnt work. no audio in game, it doesnt detect microphones and stuff. it just doesnt work.

**Comment by mdias** [comment]
ASIO4All is known to have problems with RS ASIO.

However, please post your `RS_ASIO-log.txt` and `RS_ASIO.ini` files so I can look at whats happening.

**Comment by talier00t** [comment]
here is log `0.000 [INFO]   - Wrapper DLL loaded (v0.7.1)
0.000 [INFO]  PatchOriginalCode
0.084 [INFO]  image crc32: 0xd1b38fcb
0.689 [INFO]  Patching CoCreateInstance
0.689 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.689 [INFO]  Patching call at 00C02DBD
0.689 [INFO]  Patching call at 00E75278
0.689 [INFO]  Patching PortAudio MarshalStreamComPointers
0.689 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.689 [INFO]  Patching call at 00E7483F
0.689 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.689 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.689 [INFO]  Patching call at 00E748F4
0.689 [INFO]  Patching Two Guitar Tones Connected Message Box (num locations: 1)
0.689 [INFO]  Patching bytes at 007C0C5F
0.689 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.693 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.693 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.693 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.
0.695 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.
0.697 [INFO]  AsioHelpers::FindDrivers
0.697 [INFO]    Ableton Push
0.698 [INFO]    ASIO4ALL v2
0.698 [INFO]    FL Studio ASIO
0.698 [INFO]    X-AIR ASIO Driver
0.698 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO4ALL v2
0.698 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\ASIO4ALL v2\asio4all.dll
1.200 [INFO]    info: asio4all detected
1.200 [INFO]    ASIO input channels info:
1.200 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: DroidCam Audio 1
1.200 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: DroidCam Audio 2
1.200 [INFO]    ASIO output channels info:
1.200 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 1
1.200 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 2
1.200 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
1.202 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 19 render devices, 0 capture devices
1.202 [INFO]    hr: S_OK
1.202 [INFO]    *ppEndpoint: 0250F170
1.202 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
1.202 [INFO]    hr: 80070490
1.202 [INFO]    *ppEndpoint: 00000000
1.202 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
1.202 [INFO]    hr: S_OK
1.202 [INFO]    *ppDevices: 0C0534D8
1.202 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.202 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
1.202 [INFO]    *cProps: 2
1.202 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.202 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
1.202 [INFO]    *pDataFlow: eRender
1.202 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
1.202 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
1.202 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
1.202 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.203 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperDevicePropertyStore::GetCount
1.203 [INFO]    *cProps: 60
1.204 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.204 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperEndpoint::GetDataFlow
1.204 [INFO]    *pDataFlow: eRender
1.204 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
1.204 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
1.205 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.205 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperDevicePropertyStore::GetCount
1.205 [INFO]    *cProps: 59
1.206 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.206 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperEndpoint::GetDataFlow
1.206 [INFO]    *pDataFlow: eRender
1.206 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
1.207 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
1.208 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.208 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperDevicePropertyStore::GetCount
1.208 [INFO]    *cProps: 65
1.223 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.224 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperEndpoint::GetDataFlow
1.224 [INFO]    *pDataFlow: eRender
1.224 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
1.224 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
1.238 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
1.238 [ERROR]    unsupported sample rate: 48000
1.238 [INFO]    requested format is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
1.238 [ERROR]    unsupported sample rate: 48000
1.238 [INFO]    requested format is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
1.238 [ERROR]    unsupported sample rate: 48000
1.238 [INFO]    requested format is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
1.238 [ERROR]    unsupported sample rate: 48000
1.238 [INFO]    requested format is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
1.238 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.238 [ERROR]    shared mode is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.238 [ERROR]    shared mode is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.238 [ERROR]    shared mode is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.238 [ERROR]    shared mode is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
1.238 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.238 [ERROR]    shared mode is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.238 [ERROR]    shared mode is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.238 [ERROR]    shared mode is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Shared
1.238 [ERROR]    shared mode is not supported
1.238 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
1.238 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
1.239 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\ASIO4ALL v2\asio4all.dll
1.337 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
1.337 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
1.337 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
1.337 [INFO]  AsioHelpers::FindDrivers
1.337 [INFO]    Ableton Push
1.338 [INFO]    ASIO4ALL v2
1.338 [INFO]    FL Studio ASIO
1.338 [INFO]    X-AIR ASIO Driver
1.338 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO4ALL v2
1.338 [INFO]  Creating AsioSharedHost - dll: C:\Program Files (x86)\ASIO4ALL v2\asio4all.dll
1.762 [INFO]    info: asio4all detected
1.762 [INFO]    ASIO input channels info:
1.762 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: DroidCam Audio 1
1.762 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: DroidCam Audio 2
1.763 [INFO]    ASIO output channels info:
1.763 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 1
1.763 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 2
1.763 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
1.766 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 13 render devices, 0 capture devices
1.766 [INFO]    hr: S_OK
1.766 [INFO]    *ppEndpoint: 0C1BED40
1.766 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
1.766 [INFO]    hr: 80070490
1.767 [INFO]    *ppEndpoint: 00000000
1.767 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
1.767 [INFO]    hr: S_OK
1.767 [INFO]    *ppDevices: 0C053358
1.767 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.767 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.767 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
1.767 [INFO]    *pDataFlow: eRender
1.767 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.767 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.767 [INFO]  {0.0.0.00000000}.{588039ac-7c95-4b2c-a3a8-4d428b05e08f} DebugWrapperEndpoint::GetDataFlow
1.767 [INFO]    *pDataFlow: eRender
1.767 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.767 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.767 [INFO]  {0.0.0.00000000}.{802a53e1-30fc-43eb-8d04-7770889a22e0} DebugWrapperEndpoint::GetDataFlow
1.767 [INFO]    *pDataFlow: eRender
1.767 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
1.767 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
1.767 [INFO]  {0.0.0.00000000}.{d07fdaec-a473-4cda-a8fc-e16122b18553} DebugWrapperEndpoint::GetDataFlow
1.767 [INFO]    *pDataFlow: eRender
1.776 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
330.468 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
330.469 [INFO]  Destroying AsioSharedHost - dll: C:\Program Files (x86)\ASIO4ALL v2\asio4all.dll
332.853 [INFO]   - Wrapper DLL unloaded` 

And here is ini
`for "EnableWasapiOutputs" you can use -1 to have a message prompting
to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
true if RS ASIO detects the usage of Asio4All.
the same applies for all inputs.
[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=`

**Comment by talier00t** [comment]
[message.txt](https://github.com/user-attachments/files/16984255/message.txt)
here is the log as txt if you want

**Comment by mdias** [comment]
Your ASIO4ALL drivers are configured to use the "DroidCam Audio" device, not your Behringer interface.
See in log:
```
1.200 [INFO]    ASIO input channels info:
1.200 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: DroidCam Audio 1
1.200 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: DroidCam Audio 2
1.200 [INFO]    ASIO output channels info:
1.200 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 1
1.200 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 2
```

Since using ASIO4ALL circumvents the advantages of ASIO, using RS ASIO in this case isn't really the best; I'd recommend you try the [Direct Connect](https://www.youtube.com/watch?v=H6nAB5ogfeU) method instead (and remove RS ASIO)

If you choose to stick with trying RS ASIO, please do this:

- Run the game (don't worry that audio is not working at this point)
- Put the game in window mode so you can see your desktop
- Now that you can see your desktop, your ASIO4ALL control panel icon should be in your tray bar next to your windows clock; open that control panel
- Ensure you enable ->ONLY<- your Behringer interface's outputs and inputs; nothing else
- Close the game
- Make sure your audio interface outputs and inputs in windows are configured to use 48000hz
- Run the game again

If it still doesn't work, please post the new log.

**Comment by talier00t** [comment]
now i can choose it as real tone cable but still no audio in game, 
![image](https://github.com/user-attachments/assets/88d769a4-f611-43b9-9c09-2e22db6f3047)

here is the .ini file
`[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=`
and here is the log
[RS_ASIO-log.txt](https://github.com/user-attachments/files/17005719/RS_ASIO-log.txt)

**Comment by talier00t** [comment]
still no audio, i can choose it as microphone and set it as realtone cable. but still no audio in game + it doesnt get guitars sound. so both input and output not working. 
here is the log
[RS_ASIO-log.txt](https://github.com/user-attachments/files/17005752/RS_ASIO-log.txt)

and here is the .ini in case.
`[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO4ALL v2
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=`

**Comment by mdias** [comment]
Log is showing:
```
2.178 [INFO]    ASIO input channels info:
2.178 [INFO]      0 - active: 0, channel: 0, group: 3, isInput: 1, type: ASIOSTInt32LSB, name: USB Audio CODEC  1
2.178 [INFO]      1 - active: 0, channel: 1, group: 3, isInput: 1, type: ASIOSTInt32LSB, name: USB Audio CODEC  2
2.178 [INFO]    ASIO output channels info:
2.178 [INFO]      0 - active: 0, channel: 0, group: 3, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 1
2.178 [INFO]      1 - active: 0, channel: 1, group: 3, isInput: 0, type: ASIOSTInt32LSB, name: Not Connected 2
```

Notice that it appears you have no outputs configured in ASIO4ALL: "Not Connected"

However I can see that RS ASIO is streaming audio to/from ASIO4ALL, albeit with a big buffer size (512 samples).
