### ISSUE TITLE
dll files don't seem to be in github repository?

### ISSUE THREAD

**Issue by cathalsmyth** [mdias/rs_asio#463]
As the title says, I do not see any dll files in the repo. Nor when I download. is there some build step that I am missing? I can find and configure the ini file no problem.

**Comment by mdias** [comment]
Have you read the [readme](https://github.com/mdias/rs_asio/blob/master/README.md)?

**Comment by cathalsmyth** [comment]
Yes. That is why I posted the issue.. By reading the readme, I was aware of
the filenames that I could not find.

**Comment by mdias** [comment]
Right after the filenames it links to where you should download it:
> Copy the contents (`avrt.dll`, `RS_ASIO.dll`, `RS_ASIO.ini`) of [latest release](https://github.com/mdias/rs_asio/releases/latest) (zip archive release-xxx.zip) to the game folder.

If you follow that link you'll see the latest current release (`release-0.7.1.zip` as of today) that will contain the files.

**Comment by cathalsmyth** [comment]
Yep that's my bad. I assumed it was the zip of the code repo. Thank you!

**Comment by mdias** [comment]
No problem 👍
