### ISSUE TITLE
Focusrite Scarlett solo gen 4, no guitar input in Rocksmith

### ISSUE THREAD

**Issue by PausBen** [mdias/rs_asio#465]
It doesn't work, but it doesn't seem to be the problem of not having the 32-bit driver.

windows audio and mic settings (already tried changing these but didn't do anything.)
![image](https://github.com/user-attachments/assets/55b013fb-a25c-489d-8c46-7e54687b766e)
![image](https://github.com/user-attachments/assets/ea99e41f-ad18-4a86-9c1a-416028b2531b)

windows version: 

Edition	Windows 11 Home
Version	24H2
Installed on	‎15/‎10/‎2024
OS build	26100.2314
Experience	Windows Feature Experience Pack 1000.26100.32.0

RS_ASIO.ini:

# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=192

[Asio.Output]
Driver=Focusrite USB ASIO
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
;Driver=Focusrite USB ASIO
;Channel=1
;EnableSoftwareEndpointVolumeControl=1
;EnableSoftwareMasterVolumeControl=1
;SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

Also tried this one before didn't work either: 

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
;Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

RS_ASIO-log.txt:

0.000 [INFO]   - Wrapper DLL loaded (v0.7.2)
0.000 [INFO]  PatchOriginalCode
0.030 [INFO]  image crc32: 0xd1b38fcb
0.145 [INFO]  Patching CoCreateInstance
0.145 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.145 [INFO]  Patching call at 00C02DBD
0.145 [INFO]  Patching call at 00E75278
0.145 [INFO]  Patching PortAudio MarshalStreamComPointers
0.145 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.145 [INFO]  Patching call at 00E7483F
0.145 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.145 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.145 [INFO]  Patching call at 00E748F4
0.145 [INFO]  Patching Two Guitar Tones Connected Message Box (starting menu) (num locations: 1)
0.145 [INFO]  Patching bytes at 007C0C66
0.145 [INFO]  Patching Two Guitar Tones Connected Message Box (main menu) (num locations: 1)
0.145 [INFO]  Patching bytes at 007C0CDA
0.145 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.145 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.145 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.145 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.
0.146 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.
0.146 [INFO]  AsioHelpers::FindDrivers
0.146 [INFO]    Focusrite Thunderbolt ASIO
0.146 [INFO]    Focusrite USB ASIO
0.146 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.146 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusrite\drivers\focusriteusbasio32.dll
0.149 [INFO]    ASIO input channels info:
0.149 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
0.149 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
0.149 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Loopback 1
0.149 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Loopback 2
0.149 [INFO]    ASIO output channels info:
0.149 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
0.149 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
0.149 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.149 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: Focusrite USB ASIO
0.149 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.149 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.149 [INFO]    hr: S_OK
0.149 [INFO]    *ppEndpoint: 0F6EBA48
0.149 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.149 [INFO]    hr: S_OK
0.149 [INFO]    *ppEndpoint: 0F6EBCE8
0.149 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.149 [INFO]    hr: S_OK
0.149 [INFO]    *ppDevices: 0EC70DD8
0.149 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.149 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.149 [INFO]    *cProps: 2
0.149 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.149 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.149 [INFO]    *pDataFlow: eRender
0.149 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.149 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.149 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.149 [INFO]  {ASIO IN 1} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.149 [INFO]  {ASIO IN 1} DebugWrapperDevicePropertyStore::GetCount
0.149 [INFO]    *cProps: 5
0.149 [INFO]  {ASIO IN 1} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.149 [INFO]  {ASIO IN 1} DebugWrapperEndpoint::GetDataFlow
0.149 [INFO]    *pDataFlow: eCapture
0.149 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.149 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.149 [INFO]  {ASIO IN 1} RSAsioAudioClient::~RSAsioAudioClient
0.317 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.317 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.317 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.317 [INFO]    requested format is not supported
0.317 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.317 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.317 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.317 [INFO]    requested format is not supported
0.317 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.317 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.317 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.317 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
0.317 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
0.317 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 4ms (192 frames)
0.317 [INFO]  AsioSharedHost::Setup - startCount: 0
0.317 [INFO]    post output ready: 0
0.317 [INFO]    ASIOBufferSize - min: 16 max: 1024 preferred: 192 granularity: 16
0.317 [INFO]    Creating ASIO buffers (2 out, 4 in)...
0.318 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
0.318 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 2 value: 0 | returning: 1
0.318 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 3 | returning: 0
0.318 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 5 | returning: 0
0.318 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 4 | returning: 0
0.318 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 6 | returning: 0
0.318 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 15 | returning: 0
0.318 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.318 [INFO]    *pNumBufferFrames: 192
0.318 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.318 [INFO]    latency: 10ms
0.318 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.318 [INFO]    returning render client
0.318 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.319 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.319 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.319 [INFO]  {ASIO Out} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.319 [INFO]  {ASIO Out} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.319 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
0.319 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.319 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.319 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.319 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.319 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.319 [INFO]  AsioSharedHost::Start - enter startCount: 0
0.319 [INFO]    Starting ASIO stream...
0.688 [INFO]  AsioSharedHost::Start - leave startCount: 1
0.695 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.695 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.695 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.695 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.699 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.699 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.699 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.699 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.703 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
2.579 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
2.579 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
2.579 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
2.579 [INFO]    requested format is not supported
2.579 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
2.579 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
2.579 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
2.579 [INFO]    requested format is not supported
2.579 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
2.579 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
2.579 [INFO]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
2.579 [INFO]    requested format is not supported
2.579 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
2.579 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
2.579 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
2.579 [INFO]  {ASIO IN 1} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
2.579 [INFO]  {ASIO IN 1} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
2.579 [INFO]  {ASIO IN 1} RSAsioAudioClient::Initialize - actual buffer duration: 4ms (192 frames)
2.579 [INFO]  AsioSharedHost::Setup - startCount: 1
2.579 [INFO]  {ASIO IN 1} DebugWrapperDevice::Activate - Activate iid: IID_IAudioEndpointVolume dwClsCtx: 1
2.579 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
2.579 [INFO]    *pNumBufferFrames: 192
2.579 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
2.579 [INFO]    latency: 8ms
2.579 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioCaptureClient
2.579 [INFO]    returning capture client
2.579 [INFO]  Patched_PortAudio_MarshalStreamComPointers
2.580 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
2.580 [INFO]  {ASIO IN 1} DebugWrapperAudioClient3::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
2.580 [INFO]  {ASIO IN 1} DebugWrapperAudioClient2<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
2.580 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::QueryInterface riid: {F2D67F48-1977-4991-A3FC-A093835A7DC2}
2.580 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
2.580 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Start
2.580 [INFO]  AsioSharedHost::Start - enter startCount: 1
2.580 [INFO]  AsioSharedHost::Start - leave startCount: 2
2.580 [INFO]  {ASIO IN 1} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.17
2.583 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
2.583 [INFO]  {ASIO IN 1} RSAsioAudioClient::SwapBuffers
2.583 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 192
2.587 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
2.587 [INFO]  {ASIO IN 1} RSAsioAudioClient::SwapBuffers
2.587 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 192
2.591 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::GetBuffer
2.591 [INFO]  {ASIO IN 1} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 192
42.766 [INFO]  {ASIO IN 1} DebugWrapperAudioClient<struct IAudioClient3>::Stop
42.766 [INFO]  AsioSharedHost::Stop - enter startCount: 2
42.766 [INFO]  AsioSharedHost::Stop - leave startCount: 1
42.766 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
42.767 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
42.767 [INFO]  AsioSharedHost::Stop - enter startCount: 1
42.767 [INFO]  AsioSharedHost::Stop - stopping ASIO stream
42.768 [INFO]  AsioSharedHost::Stop - leave startCount: 0
42.768 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
44.372 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
The log appears to be showing that ASIO is streaming audio fine.

What do you mean by "it doesn't work"? Do you get any error message?
In case you mean that you hear nothing, where do you have your speakers connected?

**Comment by PausBen** [comment]
> The log appears to be showing that ASIO is streaming audio fine.
> 
> What do you mean by "it doesn't work"? Do you get any error message? In case you mean that you hear nothing, where do you have your speakers connected?

I can hear the game audio but no guitar. when I get to the tuning part it also doesn't recognize me playing a string. Guitar is plugged into the focusrite and my headphones in the headphone output of the focusrite. There are no error messages.

**Comment by mdias** [comment]
Do you have the game configured to use RTC input?

**Comment by PausBen** [comment]
> Do you have the game configured to use RTC input?

yes, tried switching it to the other option and back to see if that changes anything but nothing.

**Comment by PausBen** [comment]
It works now! made changes to the rs_asio.ini and made some changes in the settings of the focusrite control 2 app as you can read in the ini file.

So I don't really see any issues anymore with the 4th gen focusrite products. the solo at least has no problems so far with these settings.

rs_asio.ini

[Config]
EnableWasapi=0
EnableAsio=1

[Asio]
BufferSizeMode=custom
CustomBufferSize=48

[Asio.Output]
Driver=Focusrite USB ASIO
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

; In Foscurite Control 2 preferences, check "Combine input 1 and input 2" and "Send direct monitor mix"
[Asio.Input.1]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Comment by mdias** [comment]
Great! Thank you for telling us how you fixed it :)

Enjoy.

**Comment by derekklass** [comment]
Thanks man. Just got the Solo 4th gen, couldn't get anything to work, and this was it.
