### ISSUE TITLE
RS_ASIO.dll removed on startup

### ISSUE THREAD

**Issue by SomeGuycCalledBlake** [mdias/rs_asio#468]
Hi, As the title suggests, I follow the instructions listed (Drag and drop extracted zip, configuring the RS_asio.ini and rocksmith.ini) but on startup I get "Failed to load RS_ASIO.dll" and opening my Rocksmith folder shows the file isn't there anymore. I've attached screenshots below, please tell me if you need more. Thank You!

![Before Startup](https://github.com/user-attachments/assets/68ecdd0c-0169-4d97-b72c-187f32177be0)
![During Startup](https://github.com/user-attachments/assets/8893cf51-b39f-442d-abb5-1b2c23fea9b8)
![After Startup](https://github.com/user-attachments/assets/3e8ef215-a956-466f-83b3-0d58db99bc2e)
![RS_ASIO](https://github.com/user-attachments/assets/2d932279-1c6f-4522-bc9d-8ac19adcb5e2)
![Rocksmith ini](https://github.com/user-attachments/assets/b05ed85b-ca7e-4aaa-b71c-f4248218e492)

**Comment by SomeGuycCalledBlake** [comment]
THANK YOU! It was that scoundrel, John Mcafee up to his dastardly tricks again. I thought I deleted it when I switched antiviruses but no.

**Comment by mdias** [comment]
Glad it worked, enjoy!
