### ISSUE TITLE
''no audio output device is detected'' when using rs asio

### ISSUE THREAD

**Issue by rootz4** [mdias/rs_asio#469]
when i load the rs asio in the game's directory, it gives this error. i use Focusrite Scarlett Solo (gen3) with the old 32 bit ASIO driver to make it possible to run (since the game only reads the 32 bit asio's only). I tried changing the audio buffers from 24 to 16 bit, it set to 48000hz too because i use it that way already. but i cant make it able to work.

my rs asio things:

> 0.000 [INFO]   - Wrapper DLL loaded (v0.7.2)
0.000 [INFO]  PatchOriginalCode
0.026 [INFO]  image crc32: 0xd1b38fcb
0.119 [INFO]  Patching CoCreateInstance
0.119 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.119 [INFO]  Patching call at 00C02DBD
0.120 [INFO]  Patching call at 00E75278
0.120 [INFO]  Patching PortAudio MarshalStreamComPointers
0.120 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.120 [INFO]  Patching call at 00E7483F
0.120 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.120 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.120 [INFO]  Patching call at 00E748F4
0.120 [INFO]  Patching Two Guitar Tones Connected Message Box (starting menu) (num locations: 1)
0.120 [INFO]  Patching bytes at 007C0C66
0.120 [INFO]  Patching Two Guitar Tones Connected Message Box (main menu) (num locations: 1)
0.120 [INFO]  Patching bytes at 007C0CDA
0.120 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.120 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.120 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.120 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.
0.120 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.
0.120 [INFO]  AsioHelpers::FindDrivers
0.121 [INFO]    Focusrite Thunderbolt ASIO
0.121 [INFO]    Focusrite USB ASIO
0.121 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.121 [INFO]    hr: 80070490
0.121 [INFO]    *ppEndpoint: 00000000
0.121 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.121 [INFO]    hr: 80070490
0.121 [INFO]    *ppEndpoint: 00000000
0.121 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.121 [INFO]    hr: S_OK
0.121 [INFO]    *ppDevices: 172CE750
3.568 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
3.568 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
3.568 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
3.568 [INFO]  AsioHelpers::FindDrivers
3.568 [INFO]    Focusrite Thunderbolt ASIO
3.568 [INFO]    Focusrite USB ASIO
3.568 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
3.568 [INFO]    hr: 80070490
3.568 [INFO]    *ppEndpoint: 00000000
3.568 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
3.568 [INFO]    hr: 80070490
3.568 [INFO]    *ppEndpoint: 00000000
3.568 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
3.568 [INFO]    hr: S_OK
3.568 [INFO]    *ppDevices: 09085268
3.573 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
5.116 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
5.259 [INFO]   - Wrapper DLL unloaded

> for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize= 96

 if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
 when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
 true if RS ASIO detects the usage of Asio4All.
 the same applies for all inputs.
[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=0

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

> [Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=16
ForceDefaultPlaybackDevice=1
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=1
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1

**Comment by mdias** [comment]
For some reason it looks like your RS_ASIO.ini couldn't be read properly, or at least doesn't match what you've put here.
Can you please attach the actual file here so I can take a look? (just drag and drop to into your comment text box)
