### ISSUE TITLE
'It sounds like your cable is unplugged. Connect a Rocksmith Real Tone Cable' when using rs asio

### ISSUE THREAD

**Issue by h-rafo** [mdias/rs_asio#470]
Unable to load driver. Everything used to be fine, I haven't changed any setting except update to Windows 11 24H2. Not sure if it could be related

`0.376 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices`
`0.376 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.`
`0.377 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.`
`0.379 [INFO]  AsioHelpers::FindDrivers`
`0.379 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: ASIO POD Go`
`0.379 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.`
`0.382 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 22 render devices, 0 capture devices`

> [Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1
[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=
[Asio.Output]
Driver=
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
[Asio.Input.0]
Driver=
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
[Asio.Input.1]
Driver=ASIO POD Go
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

**Comment by mdias** [comment]
There are no asio drivers found in your system.
Please try re-installing the drivers.

**Comment by mdias** [comment]
You need the 32 bit driver.
The game is a 32-bit application unfortunately, so it's only able to load 32-bit modules.

If your interface doesn't provide 32-bit drivers, you can get around that with a "middle-man" application like Voicemeeter which is able to pose as a 32 bit ASIO driver and route the audio to/from another 64-bit driver. This works and has no noticeable impact in audio but is more annoying to use as you have to have Voicemeeter opened in order for it to stream the audio.

**Comment by h-rafo** [comment]
Pretty sure it does provide 32-bit ASIO drivers because it used to work until I updated to Windows 11 24H2.
