### ISSUE TITLE
0.069 [ERROR]  Unknown game version

### ISSUE THREAD

**Issue by lum3n7** [mdias/rs_asio#471]
I am using steam version of Rocksmith2014 remastered and rs_asio v0.72. When I launch the game a log file is created with the following contents:

```
0.000 [INFO]   - Wrapper DLL loaded (v0.7.2)
0.000 [INFO]  PatchOriginalCode
0.069 [INFO]  image crc32: 0x6ea6d1ba
0.069 [ERROR]  Unknown game version
49.719 [INFO]   - Wrapper DLL unloaded
```

I am unable to track down the cause of this error. I have tried older versions of rs_asio with no luck. Has anyone had a similar problem?

**Comment by empix** [comment]
Same.
Something has changed in this "new version" on steam

**Comment by lum3n7** [comment]
Ah I see, bad time to buy rocksmith I guess

**Comment by Igor3699** [comment]
Same here :(

**Comment by ffio1** [comment]
New L&P build of Rocksmith 2014 is out. @mdias, this will require some changed pointers.

Basically it is as such - Previous owners keep the old pointers (they're on the old executable). New owners have a new build, where you'll have to find the new offsets.

If I get RSMods back up and running, I'll try to take a look to see what offsets you need for this if you don't get to it before me.

**Comment by alexgo84** [comment]
Same. I'm inclined to refund the game if I don't find a workaround.

**Comment by Vadyy** [comment]
I was so excited to try this :/
Hopefully the dev can deliver.

Or if someone knows of a way to downgrade the game's version.

**Comment by empix** [comment]
@ffio1 is there any content I can read/watch about finding these offsets? even if its something difficult to learn in a short period of time, Im curious to understand how it works.

**Comment by enaielei** [comment]
up.

**Comment by Slimey1337** [comment]
Been trying to make it work for hours, thankfully i checked issues otherwise i'd have been up all night. Something with the new version. I hope it will be fixed soon.

**Comment by gustavommcv** [comment]
UP

**Comment by Codegn** [comment]
up

**Comment by umenorin** [comment]
up

**Comment by Brady2002** [comment]
Same issue here

**Comment by mdias** [comment]
Thank you for letting me know of this new build, I just got access to it.

Unfortunately there seems to be some sort of new memory protection going on and memory patching isn't working at the moment.
I haven't spent too much time on this yet, so I have no idea if this will be easy to circumvent or not.

**Comment by mdias** [comment]
@ffio1 if you manage to find a way around the memory patching (`VirtualProtect` calls are failing), please let me know as I'm not sure about how much time I'll be able to invest into it at this time.

**Comment by ffio1** [comment]
@mdias Will do!

You actually just helped me with an issue. Trying to figure out why a pointer that was valid kept getting marked as invalid when we'd verify it's integrity... Forgot that VirtualProtect can cause issues so I'll take a look at it on our end and let you know.

**Comment by Vadyy** [comment]
That sounds like trouble. Could anyone meanwhile find a way for us to downgrade our Steam version?

**Comment by Elerphore** [comment]
Same.

**Comment by ffio1** [comment]
@mdias We were able to use the Nt-level version of VirtualProtect, NtProtectVirtualMemory, via a syscall.

Reference: https://www.unknowncheats.me/forum/general-programming-and-reversing/561747-syscall-x86-x64.html

We're still trying to figure out the proper way to address it, but I think we're down the right track. From the reference, you'd make a new version and have a `mov eax, 50h` instead of what they do in the asm function `NtQuerySystemInformation`. 0x50 is the syscall number for NtProtectVirtualMemory (you can double check on your end as well, just open ntdll in your tool of choice, and look at the disassembly and see what bytes get pushed into EAX before the syscall).

This is what Lovro is doing for some mods, and it's also looking promising for RSMods.
https://github.com/Lovrom8/RSCDLCEnabler-TooManyCoresFix/commit/01881dcff8ab48e47eca033021d1af345ad1f70c

**Comment by saif-ellafi** [comment]
@ffio1 - genius, thanks for trying. Will be following this one!

**Comment by martinvlk** [comment]
up
I also bought the Steam version yesterday, got as far as having a working VBASIOTest32.exe - so great if you could make a functional build for this version...

**Comment by mdias** [comment]
The `NtProtectVirtualMemory` call was the first and only thing I tried, but it returns `STATUS_ACCESS_DENIED` too.
But I did this with `GetProcAddress(Ntdll, "NtProtectVirtualMemory");`, not with a custom implementation of `NtProtectVirtualMemory`.

One thing it's easy to notice is that any calls to `NtProtectVirtualMemory` or `VirtualProtect` appear to take more than 1 second to return, which is strange.. I'm assuming the game is somehow hooking into these, or maybe they relocate all of the process' memory pages to something that is always protected. I'm not sure, and I'm not too familiar with these kinds shenanigans either tbh.
I'm concerned that if it comes down to needing some sort of driver/service with elevated privileges to be able to patch the memory, the effort may not be worth the can of worms.

**Comment by martinvlk** [comment]
I know nothing about these things, so this may be a very long shot, but could it be anything to do with AppArmor configuration?

**Comment by ffio1** [comment]
Yeah the game hooks both the VirtualProtect and the NT level. But they don't hook the syscall. Once you move over to the syscall, you should also see the VirtualProtect times to down. I was seeing times of like 2-6 seconds per call, after moving to the syscall they were immediate as it's just a few bytes of asm before it interrupts the process to call it.

**Comment by Alberto-Xie** [comment]
Up

**Comment by loopspin225** [comment]
This looks like it has worked for me after downloading the cdlcenabler from custom forge.
https://ignition4.customsforge.com/tools/cdlcenabler

Install the enabler first
then install the RSMods installer
copy the rs asio files to the directory
launch game
update ini

you may be able to skip the rs mods part but thats the process I took to get it working.

**Comment by HomelessPig** [comment]
@loopspin225 yea this actually worked for me

**Comment by jonasbros** [comment]
@loopspin225 this worked for me too, using Focusrite solo gen 4. thank you!

**Comment by SnailTrailed** [comment]
> @loopspin225 this worked for me too, using Focusrite solo gen 4. thank you!
> 
> edit: i skipped RSMods part

Did you get Rocksmith after the Dec 19th release 2024?

**Comment by jonasbros** [comment]
> > @loopspin225 this worked for me too, using Focusrite solo gen 4. thank you!
> > edit: i skipped RSMods part
> > @jonasbros
> > Did you get Rocksmith after the Dec 19th release 2024?

yepyep i did

**Comment by SnailTrailed** [comment]
worked for me! @loopspin225 @mdias

**Comment by enaielei** [comment]
> [loopspin225](/loopspin225)

Tested and working for Creative Live! Audio A3.

**Comment by Owaan** [comment]
Can confirm the workaround of installing the cdlcenabler application before following the RS Asio installation steps worked a charm

**Comment by walterfr** [comment]
Works for me. Thanks a lot.

**Comment by RaphaelDdS** [comment]
Working! 
Thanks a lot!

**Comment by Igor3699** [comment]
> This looks like it has worked for me after downloading the cdlcenabler from custom forge. https://ignition4.customsforge.com/tools/cdlcenabler
> 
> Install the enabler first then install the RSMods installer copy the rs asio files to the directory launch game update ini
> 
> you may be able to skip the rs mods part but thats the process I took to get it working.

works for me, ty

**Comment by karfder** [comment]
> This looks like it has worked for me after downloading the cdlcenabler from custom forge. https://ignition4.customsforge.com/tools/cdlcenabler
> 
> Install the enabler first then install the RSMods installer copy the rs asio files to the directory launch game update ini
> 
> you may be able to skip the rs mods part but thats the process I took to get it working.

Thanks  a lot！It  works！

**Comment by mdias** [comment]
Sorry it's taking some time guys. I've been busy with other things.

I have good news though; I was able to try the syscall suggested by @ffio1 and it works well.
I should be able to get a new RS ASIO release for this build soon.

**Comment by D3XX3R** [comment]
> This looks like it has worked for me after downloading the cdlcenabler from custom forge. [ignition4.customsforge.com/tools/cdlcenabler](https://ignition4.customsforge.com/tools/cdlcenabler)
> 
> Install the enabler first then install the RSMods installer copy the rs asio files to the directory launch game update ini
> 
> you may be able to skip the rs mods part but thats the process I took to get it working.

With that I can finally start the game without it crashing.
But I'm still having issues with rs_asio.
This is what it sounds like. (might be loud)
[2024-12-24 17-51-03(1).webm](https://github.com/user-attachments/assets/f7448e97-794d-47c3-80a4-4807d84cd9f3)

**Comment by loopspin225** [comment]
> > This looks like it has worked for me after downloading the cdlcenabler from custom forge. [ignition4.customsforge.com/tools/cdlcenabler](https://ignition4.customsforge.com/tools/cdlcenabler)
> > Install the enabler first then install the RSMods installer copy the rs asio files to the directory launch game update ini
> > you may be able to skip the rs mods part but thats the process I took to get it working.
> 
> With that I can finally start the game without it crashing. But I'm still having issues with rs_asio. This is what it sounds like. (might be loud) [2024-12-24 17-51-03(1).webm](https://github.com/user-attachments/assets/f7448e97-794d-47c3-80a4-4807d84cd9f3)

I would check your settings in the ini or rs mods and make sure the buffer and MHz are set to 48000 and 48mhz, 96mhz or 128mhz and play with those until you get less interference.

If you want to use your headset from your pc for output, you will need to unselect all output options and use wasapi output for it to split input and output.

**Comment by D3XX3R** [comment]
> > > This looks like it has worked for me after downloading the cdlcenabler from custom forge. [ignition4.customsforge.com/tools/cdlcenabler](https://ignition4.customsforge.com/tools/cdlcenabler)
> > > Install the enabler first then install the RSMods installer copy the rs asio files to the directory launch game update ini
> > > you may be able to skip the rs mods part but thats the process I took to get it working.
> > 
> > 
> > With that I can finally start the game without it crashing. But I'm still having issues with rs_asio. This is what it sounds like. (might be loud) [2024-12-24 17-51-03(1).webm](https://github.com/user-attachments/assets/f7448e97-794d-47c3-80a4-4807d84cd9f3)
> 
> I would check your settings in the ini or rs mods and make sure the buffer and MHz are set to 48000 and 48mhz, 96mhz or 128mhz and play with those until you get less interference.
> 
> If you want to use your headset from your pc for output, you will need to unselect all output options and use wasapi output for it to split input and output.

Huh I didn't touch the asio settings since they've worked before, but found out my audio device settings reset so my USB and ASIO buffer size changed. Now with lower buffer size it works perfectly.

**Comment by mdias** [comment]
[New release created](https://github.com/mdias/rs_asio/releases/tag/v0.7.3).

Please report back if working fine for you.

**Comment by snakecase** [comment]
> [New release created](https://github.com/mdias/rs_asio/releases/tag/v0.7.3).
> 
> Please report back if working fine for you.

Just tested **release-0.7.3** on Rocksmith® 2014 Edition REMASTERED LEARN & PLAY **without** CDLC Enabler: works as expected! 🥳
Thank you!

**Comment by mdias** [comment]
@snakecase thank you for confirming 👍

**Comment by Ricardo744** [comment]
I haven't tested the new version with my UMC202HD interface yet, but I want to thank you for your work! @mdias

**Comment by D3XX3R** [comment]
Can confirm this is working without any issues with the latest release.
Thank you for the quick fix!

**Comment by michaelparkadze** [comment]
> [New release created](https://github.com/mdias/rs_asio/releases/tag/v0.7.3).
> 
> Please report back if working fine for you.

It seems that the game recognizes the audio interface as a real tone cable, but for some reason I am still not getting past the "make a sound" as it seems to not be getting the input.

I checked in the control panel -> sound, and it seems that when playing the guitar i get input, and also made sure to adjust my scarlett solo (3rd gen) to a 48k sample rate with 128 buffer size.

Will continue trying, if anyone has an idea - will be much appreciated!

**Comment by Codegn** [comment]
> [New release created](https://github.com/mdias/rs_asio/releases/tag/v0.7.3).
> 
> Please report back if working fine for you.

It's working with M-Audio Air 192|4 thank you very much!

**Comment by tomalaber** [comment]
Working like charm with Behringer U-Phoria UM2. Thank you very much @mdias and @ffio1 for your work. You are legends xd.

**Comment by martinvlk** [comment]
After applying the 0.7.3 version the app crashes on startup with:
`0024:err:seh:NtRaiseException Unhandled exception code c0000409 flags 1 addr 0x797b820f`

**Comment by mdias** [comment]
@martinvlk please attach the .mdmp file that is generated on the game folder when it crashes and also let us know what OS and CPU you have.

**Comment by martinvlk** [comment]
I haven't found any *.mdmp file anywhere in the ~/.steam/steam directrory. Can I instruct steam in any way to generate it?

Computer Information:
Manufacturer: LENOVO
Model: 20FL000DMC
Form Factor: Laptop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
CPU Family: 0x6
CPU Model: 0x4e
CPU Stepping: 0x3
CPU Type: 0x0
Speed: 3100 MHz
4 logical processors
2 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
BMI1: Supported
BMI2: Supported
F16C: Supported
FMA: Supported
Operating System Version:
Ubuntu 24.04.1 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 6.8.0-50-lowlatency
X Server Vendor: The X.Org Foundation
X Server Release: 12101011
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20241024.105847
Client Information:
Version: 1733265492
Browser GPU Acceleration Status: Disabled
Browser Canvas: Unavailable
Browser Canvas out-of-process rasterization: Disabled
Browser Direct Rendering Display Compositor: Disabled
Browser Compositing: Disabled
Browser Multiple Raster Threads: Enabled
Browser OpenGL: Disabled
Browser Rasterization: Disabled
Browser Raw Draw: Disabled
Browser Skia Graphite: Disabled
Browser Video Decode: Disabled
Browser Video Encode: Disabled
Browser Vulkan: Disabled
Browser WebGL: Unavailable
Browser WebGL2: Unavailable
Browser WebGPU: Disabled
Browser WebNN: Disabled
Video Card:
Driver: NVIDIA Corporation Quadro M500M/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 550.120
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x8086
DeviceID: 0x1916
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 13.54" x 7.64" (15.51" diag), 34.4cm x 19.4cm (39.4cm diag)
Primary VRAM: 2048 MB
Sound card:
Audio device: Realtek ALC293
Memory:
RAM: 31952 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: cs_CZ.UTF-8
Total Hard Disk Space Available: 933665 MB
Largest Free Hard Disk Block: 354151 MB
Storage:
Number of SSDs: 1
SSD sizes: 1000G
Number of HDDs: 0
Number of removable drives: 0

**Comment by enaielei** [comment]
> I haven't found any *.mdmp file anywhere in the ~/.steam/steam directrory. Can I instruct steam in any way to generate it?

Try to check this [link](https://docs.fileformat.com/system/mdmp/#:~:text=Windows%20keeps%20a%20list%20of,listed%20in%20the%20steps%20below).

**Comment by mdias** [comment]
@martinvlk that looks like a linux path.

RS ASIO 0.7.3 is not compatible with linux. Please see [this post](https://github.com/mdias/rs_asio/issues/483#issuecomment-2564196342).

**Comment by mdias** [comment]
As of now linux is also supported on 0.7.3d release.
Closing this issue.
