### ISSUE TITLE
New version rock smith 2014 steam

### ISSUE THREAD

**Issue by Ricardo744** [mdias/rs_asio#477]
A few weeks ago the Rock Smith game was re-released on Steam with this new version I have not been able to use my umc202hd interface, is there a way to be able to use it? The logs in the log file do not detect anything.  

the error is

0.000 [INFO]   - Wrapper DLL loaded (v0.7.2)
0.000 [INFO]  PatchOriginalCode
0.077 [INFO]  image crc32: 0x6ea6d1ba
0.078 [ERROR]  Unknown game version
147.218 [INFO]   - Wrapper DLL unloaded

**Comment by neftalito** [comment]
The fix is in work #471

**Comment by Ricardo744** [comment]
> The fix is in work #471
Could you tell me how to fix it?
