### ISSUE TITLE
crashing on startup for new Rocksmith 2014 release

### ISSUE THREAD

**Issue by bachittle** [mdias/rs_asio#480]
I've been keeping a close eye on https://github.com/mdias/rs_asio/issues/471 to see if rs_asio will work with the new version of Rocksmith 2014. It seems to get past the unknown game version and print that the drivers are being loaded for my focusrite scarlett 2i2 2nd gen. I followed the README and applied the specific settings found here: https://github.com/mdias/rs_asio/issues/126 . Even tried setting EnableRefCountHack=1 . Seems to just start and immediately crash. 

The logs aren't very helpful either unfortunately. Just shows that the objects are created and immediately destroyed. 
```
0.000 [INFO]   - Wrapper DLL loaded (v0.7.3)
0.000 [INFO]  PatchOriginalCode
0.057 [INFO]  image crc32: 0x6ea6d1ba
0.215 [INFO]  Patching CoCreateInstance
0.215 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 1
0.215 [INFO]  Patching call at 00AD42A8
0.215 [INFO]  Patching PortAudio MarshalStreamComPointers
0.215 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.215 [INFO]  Patching call at 00AD385F
0.215 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.215 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.215 [INFO]  Patching call at 00AD1DE5
0.215 [INFO]  Patching Two Guitar Tones Connected Message Box (starting menu) (num locations: 0)
0.215 [INFO]  Patching Two Guitar Tones Connected Message Box (main menu) (num locations: 0)
0.216 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.222 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.222 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.222 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Not found.
0.223 [INFO]  GetWineAsioInfo - Looking for "wineasio.dll"...  Not found.
0.224 [INFO]  AsioHelpers::FindDrivers
0.224 [INFO]    ASIO4ALL v2
0.224 [INFO]    FL Studio ASIO
0.224 [INFO]    Focusrite Thunderbolt ASIO
0.224 [INFO]    Focusrite USB ASIO
0.224 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.225 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusrite\drivers\focusriteusbasio32.dll
0.230 [INFO]    ASIO input channels info:
0.230 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
0.230 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
0.230 [INFO]    ASIO output channels info:
0.230 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
0.230 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
0.230 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.230 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Focusrite USB ASIO
0.230 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.230 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices
0.230 [INFO]    hr: S_OK
0.230 [INFO]    *ppEndpoint: 1B51F4B8
0.230 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.230 [INFO]    hr: S_OK
0.230 [INFO]    *ppEndpoint: 1B51F518
0.230 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.230 [INFO]    hr: S_OK
0.230 [INFO]    *ppDevices: 0D7EC308
0.230 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.230 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.230 [INFO]    *cProps: 2
0.230 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.230 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.230 [INFO]    *pDataFlow: eRender
0.230 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.230 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.230 [INFO]  {ASIO Out} RSAsioAudioClient::~RSAsioAudioClient
0.230 [INFO]  {ASIO IN 0} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.230 [INFO]  {ASIO IN 0} DebugWrapperDevicePropertyStore::GetCount
0.230 [INFO]    *cProps: 5
0.230 [INFO]  {ASIO IN 0} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.230 [INFO]  {ASIO IN 0} DebugWrapperEndpoint::GetDataFlow
0.230 [INFO]    *pDataFlow: eCapture
0.230 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.230 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.230 [INFO]  {ASIO IN 0} RSAsioAudioClient::~RSAsioAudioClient

```

any help here would be appreciated!

I also tried re-installing my drivers like what was mentioned here: https://github.com/mdias/rs_asio/issues/425

here is my Rocksmith.ini and RS_ASIO.ini:
```
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=1
ForceDefaultPlaybackDevice=1
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=0
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1
```

```
# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=48

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=Focusrite USB ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```

**Comment by mdias** [comment]
When the game crashes it should generate a file with the `.mdmp` extension in the game folder.
Do you mind attaching one of those here? It might contain some information that could help with the crash.

Also can you please specify what's your CPU and OS?

**Comment by n-lazy** [comment]
The same thing is happening to me. The farthest I get to is the calibration portion. Running windows 11 with an amd ryzen 7700x

Here are the .mdmp files:
[Rocksmith Crashes.zip](https://github.com/user-attachments/files/18244588/Rocksmith.Crashes.zip)

**Comment by mdias** [comment]
@n-lazy your crash seems to happen on a "medal_hook32" function which appears to be related to a software called "Medal" or "MedalTV".
This seems to be some sort of software to capture gameplay video and is having trouble changing some game memory probably due to its recently added protections in this new build.

Can you confirm that you have this software installed? Perhaps uninstalling/disabling it could help.

**Comment by bachittle** [comment]
[rocksmith2014_396721_crash_2024_12_24T22_25_23C0.zip](https://github.com/user-attachments/files/18254796/rocksmith2014_396721_crash_2024_12_24T22_25_23C0.zip)

here is a crash file for reference. but i have been doing some digging, and the hint you gave helped me resolve my issue. 

this is just because I had a really weird audio driver setup on my pc. I installed a program called VB-CABLE, which is a tool that adds extra audio input and output drivers that can re-route audio to other sources, and it seems like Rocksmith didn't like this. But for some reason it does work with the real-tone cable, but only in this way: you have the real-tone cable unplugged, start Rocksmith, then plug it back in. If RS_ASIO had a feature that mimicked this, it could work. I thought the ref count hack would have worked, but that might be for something else. 

Anyways, I got it to work on my end, so we can close this issue. But in the future, it may be worth adding another "hack" parameter that could make it work, similar to how I got it to work with the real tone cable.

**Comment by mdias** [comment]
Thank you for reporting back.

The hack you mention is actually not a hack but just missing functionality in RS_ASIO. Implementing this hotplug support is a fair bit of work for very little gain. Usually there is no issue with having all the appropriate input/output devices connected at game launch, but I guess you hit some edge case somewhere.

Anyway, glad to know you managed to make it work.

**Comment by bachittle** [comment]
Curious to know what was causing the crash, how do you read the MDMP files? Do you have a special program or do you just reverse engineer the binary with Linux commands or like a hex dumper?

**Comment by mdias** [comment]
You can open the mdmp files with Microsoft Visual Studio or WinDbg and then look at the callstack to look for hints as what could cause be the cause of the crash.
You usually have to know what you're doing to gather any useful information from that though.

**Comment by bachittle** [comment]
Oh yea I've done some Visual Studio debugging for C++ before. There is a lot to learn there though 😅 .  I mostly use vscode and cmake for my programming nowadays but use the debugging tools in Visual Studio when I need to go deep, and for release builds and debugging DLLs and stuff like that.
