### ISSUE TITLE
No output device detected (UMC22 + USB audio output)

### ISSUE THREAD

**Issue by 666radke** [mdias/rs_asio#481]
Hi guys,

I hope you're having wonderful winter holidays.

I've tried fixing this issue myself and scrolled through many similar issues here, but unfortunately with no success. I'm getting guitar input in the game, but not any output, no sounds whatsoever. It gives me the warning "no output device detected".

I'm using Behringer UMC22 and my output device is Logitech Pro X 2 Lightspeed (connected wirelessly via the Lightspeed USB dongle).

Here's my RS_ASIO.ini (based on the issue linked in the main text for UMC22):
https://hastebin.com/share/qexiyudasa.makefile

And here's the log:
https://hastebin.com/share/exumihaxam.yaml

Thanks in advance for your help.

**Comment by 666radke** [comment]
Update: I got it working. This 5-year old Reddit post helped me.

https://www.reddit.com/r/rocksmith/comments/hdh7ja/fix_for_no_audio_output_with_logitech_headsets/

I wonder how that affects my sound quality though - am I using a generic driver instead of the Logitech one now?
Well, anyways, I got it working.

@mdias, massive thanks for the work you put in this project. I hope good karma comes to you in your life a lot. <3

**Comment by mdias** [comment]
Glad to see you got it working.

It might make no difference to audio quality, as I suppose signal gets to the dongle in digital form anyway, but if the "original" driver did some DSP or applied other settings, you might not get that.
Although I guess if you can't hear a difference, then it's probably fine :)

Anyway, hope you're also enjoying some good holidays, and have fun 👍
