### ISSUE TITLE
Learn and Play crashes on launch on Linux

### ISSUE THREAD

**Issue by cooldoggy** [mdias/rs_asio#483]
Hi, not sure if anyone's going to be able to help here, but the game crashes with RS_ASIO on my machine. The game starts, but crashes about 2 seconds in. I am running Arch Linux x64 with kernel 6.12.4-arch1-1. The game does not show an error message when launching, it just exits. There is no crash dump generated in the install directory. This is the output of rs_asio-log.txt:

0.000 [INFO]   - Wrapper DLL loaded (v0.7.3)
0.000 [INFO]  PatchOriginalCode
0.062 [INFO]  image crc32: 0x6ea6d1ba
0.234 [INFO]  Patching CoCreateInstance
0.234 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 1
0.234 [INFO]  Patching call at 00E742A8

**Comment by ZazikWorld** [comment]
You should use the previous release 0.7.2. Last one is broken. I've got the same error on my fedora 41 machine.

**Comment by mdias** [comment]
RS ASIO 0.7.3 changed the way it patches memory to work around some new protections the game has.
It now uses direct syscalls instead of using the normal API calls, and I guess this is what's causing the issue.

Unfortunately with the version of the game you're using, the 0.7.2 version won't work. Not sure if this is on Wine or something else.

**Comment by pawelj84** [comment]
Launching the game with Proton Experimental and RS_ASIO 0.7.3 in command line produces following log before crash (last three lines):

```
Attempting to load original DLL from: C:\windows\system32\avrt.dll
Load OK; fetching procedure addresses...
0024:err:seh:NtRaiseException Unhandled exception code c0000409 flags 1 addr 0x797b820f
```
My RS_ASIO log is the same  as reported by @cooldoggy.

**Comment by AngelBePro** [comment]
I have the same log and same exception code as @pawelj84. The entire time I thought I didn't set up my config right, going to try using a older version of the game.

**Comment by AngelBePro** [comment]
> I have the same log and same exception code as @pawelj84. The entire time I thought I didn't set up my config right, going to try using a older version of the game.

I tried using the previous_version beta, but no difference whatsoever.

**Comment by santasemilla** [comment]
Came here as RS_ASIO was my last stop after checking everything was installed and configured as supposed. I'm Running RockSmith 2014 with the latest update under KUbuntu 24.04 (pipewire, using Proton 8) and the game is freezing right at start. I'm having exact rs_asio-log as @cooldoggy . I hope there would be an update to be able to run under Linux/wine.

Cheers and thanks for the time and work to the developers!

**Comment by mdias** [comment]
It is my understanding that Wine does not translate direct syscalls into linux equivalents, it only translate normal API calls.
Due to some sort of new memory protection in the game, RS ASIO 0.7.3 is now using syscalls instead of normal API calls to patch the memory of game, which makes it misbehave/crash in linux.

I don't have any estimate on when this will be fixed, or if this is fixable at all. If you're not using the Learn & Play edition of the game, please use RS ASIO 0.7.2 instead.

**Comment by mdias** [comment]
I have a tentative fix for linux but I can't test it myself at the moment. Please replace your `RS_ASIO.dll` file with this one: [RS_ASIO-0.7.3b.zip](https://github.com/user-attachments/files/18268117/RS_ASIO-0.7.3b.zip)
Please post the resulting log whether it succeeds or fails.

**Comment by santasemilla** [comment]
Hi @mdias, I just tested 0.7.3b and I still get the same in RS-ASIO.log. 

0.000 [INFO]   - Wrapper DLL loaded (v0.7.3a)
0.001 [INFO]  ntdll.dll loaded. ZwProtectVirtualMemory: 12CCBEA0
0.001 [INFO]  PatchOriginalCode
0.028 [INFO]  image crc32: 0xd1b38fcb
0.148 [INFO]  Patching CoCreateInstance
0.148 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.148 [INFO]  Patching call at 00C02DBD

Additionally, executing RockSmith in command line states:

fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Setting breakpad minidump AppID = 221680
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198022995154 [API loaded no]
ERROR: ld.so: object 'libalsapid.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
info:  Game: Rocksmith2014.exe
info:  DXVK: v2.3-21-g1b31aa5dbca0749
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x6fa8fb20
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  Enabled instance extensions:
info:    VK_EXT_surface_maintenance1
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping CPU adapter: llvmpipe (LLVM 17.0.6, 256 bits)
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce RTX 3060 Laptop GPU:
info:    Driver : NVIDIA 550.120.0
info:    Memory Heap[0]: 
info:      Size: 6144 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[2]: Property Flags = 0x1
info:      Memory Type[5]: Property Flags = 0x7
info:    Memory Heap[1]: 
info:      Size: 23588 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x6
info:      Memory Type[4]: Property Flags = 0xe
info:  Process set as DPI aware
info:  Device properties:
info:    Device : NVIDIA GeForce RTX 3060 Laptop GPU
info:    Driver : NVIDIA 550.120.0
info:  Enabled device extensions:
info:    VK_EXT_attachment_feedback_loop_layout
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_bias_control
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state3
info:    VK_EXT_fragment_shader_interlock
info:    VK_EXT_graphics_pipeline_library
info:    VK_EXT_memory_priority
info:    VK_EXT_non_seamless_cube_map
info:    VK_EXT_robustness2
info:    VK_EXT_shader_module_identifier
info:    VK_EXT_swapchain_maintenance1
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_external_memory_win32
info:    VK_KHR_external_semaphore_win32
info:    VK_KHR_maintenance5
info:    VK_KHR_pipeline_library
info:    VK_KHR_present_id
info:    VK_KHR_present_wait
info:    VK_KHR_swapchain
info:    VK_KHR_win32_keyed_mutex
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    wideLines                              : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 1
info:    shaderResourceResidency                : 0
info:    shaderResourceMinLod                   : 0
info:    sparseBinding                          : 0
info:    sparseResidencyBuffer                  : 0
info:    sparseResidencyImage2D                 : 0
info:    sparseResidencyImage3D                 : 0
info:    sparseResidency2Samples                : 0
info:    sparseResidency4Samples                : 0
info:    sparseResidency8Samples                : 0
info:    sparseResidency16Samples               : 0
info:    sparseResidencyAliased                 : 0
info:  Vulkan 1.1
info:    shaderDrawParameters                   : 0
info:  Vulkan 1.2
info:    samplerMirrorClampToEdge               : 1
info:    drawIndirectCount                      : 1
info:    samplerFilterMinmax                    : 0
info:    hostQueryReset                         : 1
info:    timelineSemaphore                      : 1
info:    bufferDeviceAddress                    : 0
info:    shaderOutputViewportIndex              : 1
info:    shaderOutputLayer                      : 1
info:    vulkanMemoryModel                      : 1
info:  Vulkan 1.3
info:    robustImageAccess                      : 0
info:    pipelineCreationCacheControl           : 1
info:    shaderDemoteToHelperInvocation         : 1
info:    shaderZeroInitializeWorkgroupMemory    : 0
info:    synchronization2                       : 1
info:    dynamicRendering                       : 1
info:  VK_AMD_shader_fragment_mask
info:    extension supported                    : 0
info:  VK_EXT_attachment_feedback_loop_layout
info:    attachmentFeedbackLoopLayout           : 1
info:  VK_EXT_conservative_rasterization
info:    extension supported                    : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_depth_bias_control
info:    depthBiasControl                       : 1
info:    leastRepresentableValueForceUnormRepresentation : 1
info:    floatRepresentation                    : 0
info:    depthBiasExact                         : 1
info:  VK_EXT_extended_dynamic_state3
info:    extDynamicState3AlphaToCoverageEnable  : 1
info:    extDynamicState3DepthClipEnable        : 1
info:    extDynamicState3RasterizationSamples   : 1
info:    extDynamicState3SampleMask             : 1
info:    extDynamicState3LineRasterizationMode  : 1
info:  VK_EXT_fragment_shader_interlock
info:    fragmentShaderSampleInterlock          : 0
info:    fragmentShaderPixelInterlock           : 0
info:  VK_EXT_full_screen_exclusive
info:    extension supported                    : 0
info:  VK_EXT_graphics_pipeline_library
info:    graphicsPipelineLibrary                : 1
info:  VK_EXT_line_rasterization
info:    rectangularLines                       : 1
info:    smoothLines                            : 1
info:  VK_EXT_memory_budget
info:    extension supported                    : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_module_identifier
info:    shaderModuleIdentifier                 : 1
info:  VK_EXT_shader_stencil_export
info:    extension supported                    : 0
info:  VK_EXT_swapchain_colorspace
info:    extension supported                    : 0
info:  VK_EXT_swapchain_maintenance1
info:    swapchainMaintenance1                  : 1
info:  VK_EXT_hdr_metadata
info:    extension supported                    : 0
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_external_memory_win32
info:    extension supported                    : 1
info:  VK_KHR_external_semaphore_win32
info:    extension supported                    : 1
info:  VK_KHR_maintenance5
info:    maintenance5                           : 1
info:  VK_KHR_present_id
info:    presentId                              : 1
info:  VK_KHR_present_wait
info:    presentWait                            : 1
info:  VK_NVX_binary_import
info:    extension supported                    : 0
info:  VK_NVX_image_view_handle
info:    extension supported                    : 0
info:  VK_KHR_win32_keyed_mutex
info:    extension supported                    : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:    Sparse   : 0
Fossilize INFO: Overriding serialization path: "/home/luk/.local/share/Steam/steamapps/shadercache/221680/fozpipelinesv6/steamapprun_pipeline_cache".
warn:  DXVK: No state cache file found
info:  DXVK: Graphics pipeline libraries supported
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              2560
info:      - Height:             1440
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
info:      - Swap effect:        1
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR (dynamic: yes)
info:    Buffer size:  2560x1427
info:    Image count:  3
info:    Exclusive FS: 0
info:  DXVK: Using 16 compiler threads
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR (dynamic: yes)
info:    Buffer size:  2560x1440
info:    Image count:  3
info:    Exclusive FS: 0
Fossilize WARN: Pipeline library handle 0xffffffffc913db18 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc9162de8 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc9162de8 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc9162de8 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc9162de8 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc91ada48 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc91ada48 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc91ada48 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc91ada48 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc91ada48 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffc91ada48 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).
Fossilize WARN: Pipeline library handle 0xffffffffde504298 is not registered.
It has either not been recorded, or it failed to be recorded earlier (which is expected if application uses an extension that is not recognized by Fossilize).

And finally, I see a new pop up window when executing Rocksmith that I haven't seen in previous versions of RS-ASIO. (see attached image as I cannot copy-paste the text. Is this normal? 

![image](https://github.com/user-attachments/assets/952deab1-87f2-4264-9559-ea9998f6c230)


Thanks a lot for your work and help!

**Comment by ZazikWorld** [comment]
I got the same error running rocksmith on windows. Maybe it’s not a WINE problem? Although I’m using an old 1607 windows build

**Comment by mdias** [comment]
Thank you for the report. It looks like I'll have to get a proper linux setup to test this more thoroughly locally...

**Comment by cooldoggy** [comment]
Definitely a different error, that's progress! I ended up going with direct connect, but I ended up testing the .dll you sent and I got this error.

0.000 [INFO]   - Wrapper DLL loaded (v0.7.3a)
0.000 [INFO]  Loading ntdll.dll to memory
0.002 [INFO]  Loaded ntdll.dll to memory: 947 kB
0.004 [INFO]  ntdll.dll loaded. ZwProtectVirtualMemory: 77DCC260
0.004 [INFO]  PatchOriginalCode
0.037 [INFO]  image crc32: 0xd1b38fcb
0.179 [INFO]  Patching CoCreateInstance
0.179 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 2
0.179 [INFO]  Patching call at 00C02DBD

**Comment by perlindgren** [comment]
I just bought the Play and learn Rocksmith2014. I run Manjaro, with a Komplete 6 interface. Got Rocksmith+ working since before, but want to try the 2014 version.

I installed wineasio dll:s and so:s in Proton Experimental, and registered the asio drivers successfully in, the `compdata/221680/pfx`. I launch the game through steam, with compatibility setting to `Proton Experimental`.

With the v073 RS_ASIO.dll, arvt.dll I get exactly the some crash as the original post:
I tried with the patch, it also crashes, with `RS-ASIO-log.txt`:

```
0.000 [INFO]   - Wrapper DLL loaded (v0.7.3a)
0.000 [INFO]  Loading ntdll.dll to memory
0.001 [INFO]  Loaded ntdll.dll to memory: 947 kB
0.002 [INFO]  ntdll.dll loaded. ZwProtectVirtualMemory: 77E0C260
0.002 [INFO]  PatchOriginalCode
0.056 [INFO]  image crc32: 0x6ea6d1ba
0.200 [INFO]  Patching CoCreateInstance
0.200 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 1
0.200 [INFO]  Patching call at 00E742A8
```
My settings are as follows, `RS_ASIO.ini`

```
# for "EnableWasapiOutputs" you can use -1 to have a message prompting
# to use either WASAPI or ASIO for output every time you boot the game
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
# available buffer size modes:
#    driver - respect buffer size setting set in the driver
#    host   - use a buffer size as close as possible as that requested by the host application
#    custom - use the buffer size specified in CustomBufferSize field
# used to be 
# BufferSizeMode=driver
BufferSizeMode=custom
CustomBufferSize=128

# if your game hangs or crashes on exit, try setting "EnableRefCountHack" to true.
# when blank or invalid, the value of "EnableRefCountHack" will be interpreted as
# true if RS ASIO detects the usage of Asio4All.
# the same applies for all inputs.
[Asio.Output]
Driver=WineASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.0]
Driver=WineASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.1]
Driver=WineASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=

[Asio.Input.Mic]
Driver=WineASIO
Channel=2
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
EnableRefCountHack=
```
And `Rocksmith.ini`
```
[Audio]
EnableMicrophone=0
ExclusiveMode=0
LatencyBuffer=4
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=1
MonoToStereoChannel=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=0
ScreenHeight=0
Fullscreen=1
VisualQuality=1
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=1
EnableShadows=1
EnableHighResScope=1
EnableDepthOfField=1
EnablePerPixelLighting=1
MsaaSamples=4
DisableBrowser=0
[Net]
UseProxy=1
[Global]
Version=1
```
Not sure if those setting "should be ok", or if there are some things that should be changed.

/Per

**Comment by AngelBePro** [comment]
> Definitely a different error, that's progress! I ended up going with direct connect, but I ended up testing the .dll you sent and I got this error.
> 
> 0.000 [INFO] - Wrapper DLL loaded (v0.7.3a) 0.000 [INFO] Loading ntdll.dll to memory 0.002 [INFO] Loaded ntdll.dll to memory: 947 kB 0.004 [INFO] ntdll.dll loaded. ZwProtectVirtualMemory: 77DCC260 0.004 [INFO] PatchOriginalCode 0.037 [INFO] image crc32: 0xd1b38fcb 0.179 [INFO] Patching CoCreateInstance 0.179 [INFO] Patch_CallAbsoluteIndirectAddress - num locations: 2 0.179 [INFO] Patching call at 00C02DBD

That's nice to hear. Thanks for reporting the progress. Rocksmith 2014 is my only hope for Rocksmith on Linux as Rocksmith+ just crashes on start. And thanks to mdias for putting in effort for the Linux users.

**Comment by mdias** [comment]
I have a new build which seems to be loading fine on a temporary linux setup I have.
Please test it and report back with log: [RS_ASIO-0.7.3c.zip](https://github.com/user-attachments/files/18276472/RS_ASIO-0.7.3c.zip)

**Comment by martinvlk** [comment]
Hi, thanks for this.
I have tried with this version and the game indeed loads, but then crashes later after I select the profile.
See attached logs.

**Comment by mdias** [comment]
@martinvlk great to hear! I have identified the issue and I'll post here a new build later today.

**Comment by martinvlk** [comment]
Damn it., IT WORKS!!!! :-D

**Comment by perlindgren** [comment]
With the 0.7.3d it does not crash for me, but it reports, `no audio device found`, in a window.

![image](https://github.com/user-attachments/assets/f27feeca-5935-425f-89e8-df2ae4a9a218)

And consecutively
![image](https://github.com/user-attachments/assets/bd759a92-4954-48b7-85ec-debd63e81b68)

The  `RS_ASIO-log.txt`:
```
0.000 [INFO]   - Wrapper DLL loaded (v0.7.3d)
0.000 [INFO]  PatchOriginalCode
0.053 [INFO]  image crc32: 0x6ea6d1ba
0.053 [INFO]  Generating function to patch memory
0.053 [INFO]  Loading ntdll.dll to memory
0.054 [INFO]  Loaded ntdll.dll to memory: 918 kB
0.245 [INFO]  Patching CoCreateInstance
0.245 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 1
0.245 [INFO]  Patching call at 00E742A8
0.245 [INFO]  Patching PortAudio MarshalStreamComPointers
0.245 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.245 [INFO]  Patching call at 00E7385F
0.246 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.246 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.246 [INFO]  Patching call at 00E71DE5
0.246 [INFO]  Patching Two Guitar Tones Connected Message Box (starting menu) (num locations: 1)
0.246 [INFO]  Patching bytes at 007C1A36
0.246 [INFO]  Patching Two Guitar Tones Connected Message Box (main menu) (num locations: 1)
0.246 [INFO]  Patching bytes at 007C1AAA
0.246 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.246 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.246 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.246 [INFO]  GetWineAsioInfo - Looking for "wineasio32.dll"...  Loaded and found at "C:\windows\system32\wineasio32.dll".
0.247 [INFO]    name: wineasio-rsasio
0.247 [INFO]  AsioHelpers::FindDrivers
0.247 [INFO]    wineasio-rsasio
0.247 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: wineasio-rsasio
0.247 [INFO]  Creating AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
6.290 [ERROR]  ASIO Error: WineASIO does not return error messages

6.290 [INFO]  Destroying AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
6.290 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
6.290 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: wineasio-rsasio
6.291 [INFO]  Creating AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
12.332 [ERROR]  ASIO Error: WineASIO does not return error messages

12.332 [INFO]  Destroying AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
12.333 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
12.333 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: wineasio-rsasio
12.333 [INFO]  Creating AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
18.376 [ERROR]  ASIO Error: WineASIO does not return error messages

18.376 [INFO]  Destroying AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
18.376 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
18.376 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
18.376 [INFO]    hr: 80070490
18.376 [INFO]    *ppEndpoint: 00000000
18.376 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
18.376 [INFO]    hr: 80070490
18.376 [INFO]    *ppEndpoint: 00000000
18.376 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
18.376 [INFO]    hr: S_OK
18.376 [INFO]    *ppDevices: 04103528
23.102 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
23.102 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
23.102 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
23.102 [INFO]  AsioHelpers::FindDrivers
23.102 [INFO]    wineasio-rsasio
23.102 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: wineasio-rsasio
23.102 [INFO]  Creating AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
29.144 [ERROR]  ASIO Error: WineASIO does not return error messages

29.144 [INFO]  Destroying AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
29.144 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
29.144 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: wineasio-rsasio
29.145 [INFO]  Creating AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
29.150 [ERROR]  ASIO Error: WineASIO does not return error messages

29.150 [INFO]  Destroying AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
29.150 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
29.150 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[1] requesting ASIO driver: wineasio-rsasio
29.150 [INFO]  Creating AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
29.155 [ERROR]  ASIO Error: WineASIO does not return error messages

29.155 [INFO]  Destroying AsioSharedHost - dll: C:\windows\system32\wineasio32.dll
29.155 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
29.155 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
29.155 [INFO]    hr: 80070490
29.155 [INFO]    *ppEndpoint: 00000000
29.155 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
29.155 [INFO]    hr: 80070490
29.155 [INFO]    *ppEndpoint: 00000000
29.155 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
29.155 [INFO]    hr: S_OK
29.155 [INFO]    *ppDevices: 04118010
29.156 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback

```
So it seems that the patch was successful but that it does not recognize the `WineASIO` driver for some reason.

My system setup is Manjaro (arch based). I've compiled the latest (wine 8> compat) wineasio from source, and it works well with RS+. 

As @martinvlk  made it work using `Proton 9 Hotfix`, I set the steam launcher to use that. I've copied the `wineasio32.dll/winasio32.dll.so` to the `Proton 9 Hotfix`, but did not run the regsvr (as the `wineasio` should be auto detected.

Not sure what else to try (I tried a `Proton 8` as well but it behaves exactly the same.

Any ideas, what I might be missing?

Thanks for all the great work making this possible!!!

**Comment by mdias** [comment]
@perlindgren your problem now is something outside of the scope of this task.

I recommend you follow [this guide](https://github.com/theNizo/linux_rocksmith/tree/main).
You might just be missing the `LD_PRELOAD=/usr/lib32/libjack.so` or something else entirely.

**Comment by bonzaihb** [comment]
Hi,

FYI the 0.7.3d also works for me: Mint 21.3 with Pulseaudio/Jack combo installed. Steam using Proton Experimental, Realtone Cable via Jack (profile disabled in Pulseaudio/Pavucontrol).
I still got some crackling here and there, maybe I can fix it via disabling theWin32UltraLowLatencyMode in Rocksmith.ini.
Next step: get it running on my HTPC box (Mint 22 with pipewire), so I can jam from the couch. ^^

Thanks a lot for your hard work mdias and have a happy new year, now I can finally pick up learning guitar again! :+1:

**Comment by martinvlk** [comment]
Just to provide full info, I am on Kubuntu 24.04 using Proton Hotfix, Steinberg UR22c audio interface. Working like a charm, with reasonable latency and occasional xruns.. 

Many thanks, this is awesome work!

**Comment by mdias** [comment]
Thank you everyone for confirming and helping with the fix.
A [new release is out now](https://github.com/mdias/rs_asio/releases/tag/v0.7.3d), and this issue can be closed.

**Comment by cooldoggy** [comment]
Wow! Thanks for the fix, I didn't even know if this was fixable!
