### ISSUE TITLE
ESI Maya44 eX works perfectly

### ISSUE THREAD

**Issue by aenimaex** [mdias/rs_asio#486]
Hello, i have seen that there were problems with the Interface ESI Maya44 eX in the past.
I've tried a few things and got it to work like a charm. :)
Even after closing and reopening the game you can play without restarting your pc, as the interface will be recognized again without problems.

Just use the actual rs_asio release and copy/paste the settings from this text document into the RS_ASIO.ini file.

[settings.txt](https://github.com/user-attachments/files/18273952/settings.txt)

Greetings,

aenimaex

**Comment by aenimaex** [comment]
Driver Settings in the ESI Maya44 eX ASIO Control Panel (C:\Windows\System32\MAYA44eXPan.exe):
Latency: 256
Samplerate: 48000 Hz

You should use Input 3 for Guitar., because it is the Hi-Z Input.
Click in the ESI Maya44 eX ASIO Control Panel at the Guitar Button for Channel 3/4 and set Volume to -10.0 dB

**Comment by mdias** [comment]
Thank you for the report. 👍 
This interface was reported before as working too on #134
