### ISSUE TITLE
avrt.dll, RS_ASIO.dll, RS_ASIO.ini are crushing the game

### ISSUE THREAD

**Issue by adrian92tur** [mdias/rs_asio#50]
Hello. 

As in title. 

Without those files, game is running smoothly. Everytime when I copy them and run the game only rocksmith title screen is showing and then game is closing without any error showed.
RS_ASIO-log.txt is not generating.

All microphones, and any additional devices are turned off.

Now I use Windows 10 Home 64. Same problem occured on Windows 7 Home 64. 

I am using Behringer umc 22 interface. Asio4all 2.14 (adjusted) and Behringer 2.8.40 Drivers are installed.

Need an advice what should I do know.
Thanks in advance.

**Comment by mdias** [comment]
Can you post the contents of your RS_ASIO.ini?

I suspect some other software might be influencing the loading of rs_asio since it doesn't even generate the log file...

**Comment by janabimustafa** [comment]
I had to download the C++ redistributables from here: https://aka.ms/vs/16/release/VC_redist.x64.exe
and here: https://aka.ms/vs/16/release/VC_redist.x86.exe

Then did a restart for it to work on a new system

**Comment by mdias** [comment]
@janabimustafa  Thank you for this information.
