### ISSUE TITLE
No audio, no log file generated and crash

### ISSUE THREAD

**Issue by Adam22200** [mdias/rs_asio#53]
Dear Mdias,

I am using the UR22 from Steinberg, Yamaha Steinberg USB driver and my game is the Rocksmith 2014 remastered on STEAM. Upon launch of the game, there is no audio, no generation of the log file and when I change windows from fx Rocksmith to Chrome, Rocksmith crashes. Must be mentioned that upon deletion of AVRT.dll there is no longer a crash when changing windows (but things still don't work).

I tried for 1 week straight and maybe at least 6 hours concomitantly, trying different ways with RS asio and reading through your guide extensively.

I hope you can help me.

BR

**Comment by mdias** [comment]
You probably have some other software influencing the load of rs asio.

I have no way of knowing what you should do in this case as I don't know what software that could be, but a clean windows install will probably solve it, though I'm aware this is not a good solution to suggest. Sorry.

**Comment by mdias** [comment]
Installing [this](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) (both the [x86](https://aka.ms/vs/16/release/vc_redist.x86.exe) and [x64](https://aka.ms/vs/16/release/vc_redist.x64.exe) versions) may help you.
Feel free to re-open this issue if that's not the case.
