### ISSUE TITLE
Is it normal that I can't use the Real Tone Cable while using RS_ASIO?

### ISSUE THREAD

**Issue by Adzetko** [mdias/rs_asio#55]
I don't know if this is a normal thing, but for some reasons I can't use my Asus DGX mic inputs (Windows 10 related issue as far as I know), and while RS_ASIO is enabled, I can't make my Real Tone Cable to be detected by the game. (tried plugging it before launching Rocksmith 2014, and also after).

Except this, the output is perfect on my Asus Xonar DGX (with the UNi drivers)!

So, I don't know if it is a normal behaviour from this patch, but as it is not written anywhere (as far as I can see) that's why I'm bothering you.

**Comment by mdias** [comment]
It is normal behavior on the default settings.

The game uses WASAPI to interface with Real Tone Cable, so you should be good to go with just setting `EnableWasapi=1`. This should expose all your other sound interfaces to the game again, as well as the ASIO ones you configure.

**Comment by Adzetko** [comment]
Thanks for your answer! Now I managed to make it work as you said. Maybe add this to the readme? Because there's not really any mention of this anywhere else, and I think I'm not the only Real Tone Cable player who wants to use RS_ASIO that didn't know what means `EnableWasapi`. Thanks again, this is a blast!
