### ISSUE TITLE
Select channel asio output

### ISSUE THREAD

**Issue by restrada8** [mdias/rs_asio#62]
Hello!

First of all thanks for this program, it's awesome.

I've been searching and can't find a way to change the output channel asio, is it possible?
I have a Komplete Audio 6 MK2 and I would like to select S/PDIF output.
if it helps, in the log you can see the available channel.

> 0.000 [INFO]   - Wrapper DLL loaded (v0.4.2)
0.000 [INFO]  PatchOriginalCode
0.000 [INFO]  Patching CoCreateInstance
0.162 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.162 [INFO]  Patching call at 01C5AA85
0.162 [INFO]  Patching call at 01F03B6E
0.162 [INFO]  Patching call at 01F5C681
0.162 [INFO]  Patching call at 01FAEF75
0.162 [INFO]  Patching call at 01FAF40D
0.162 [INFO]  Patching PortAudio MarshalStreamComPointers
0.304 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.304 [INFO]  Patching call at 01F03059
0.304 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.438 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.438 [INFO]  Patching call at 01F0310E
0.440 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.440 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.440 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.440 [INFO]  AsioHelpers::FindDrivers
0.440 [INFO]    ASIO4ALL v2
0.441 [INFO]    Komplete Audio ASIO Driver
0.441 [INFO]    Voicemeeter Virtual ASIO
0.441 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Komplete Audio ASIO Driver
0.441 [INFO]  Creating AsioSharedHost - dll: c:\program files\native instruments\komplete audio driver\w10_x64\nativeinstrumentsusbaudioasio.dll
0.479 [INFO]    ASIO input channels info:
0.479 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
0.479 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
0.479 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 3
0.479 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 4
0.479 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: S/PDIF Input5
0.479 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: S/PDIF Input6
0.479 [INFO]    ASIO output channels info:
0.479 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
0.479 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
0.479 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 3
0.479 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 4
0.479 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: S/PDIF Output5
0.479 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: S/PDIF Output6
0.479 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.479 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: Komplete Audio ASIO Driver
0.479 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.479 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 1 render devices, 1 capture devices

**Comment by mdias** [comment]
Not implemented yet.
This should be easy enough to implement though. I'll keep a note for next release :)

**Comment by mdias** [comment]
New version 0.5.0 now supports this with the `BaseChannel` option. Check the included RS_ASIO.ini and you'll figure it out :)

**Comment by restrada8** [comment]
Nice work, thank you!!
