### ISSUE TITLE
I couldn't manage to make it work

### ISSUE THREAD

**Issue by 395v** [mdias/rs_asio#64]
Hello. I am trying make it work with onboard sound device with asio4all v2 driver.
Log is here:

> 0.000 [INFO]   - Wrapper DLL loaded (v0.4.2)
> 0.000 [INFO]  PatchOriginalCode
> 0.000 [INFO]  Patching CoCreateInstance
> 0.047 [INFO]  Patch_CallAbsoluteAddress - num locations: 0
> 0.048 [INFO]  Patching PortAudio MarshalStreamComPointers
> 0.093 [INFO]  Patch_CallRelativeAddress - num locations: 0
> 0.094 [INFO]  Patching PortAudio UnmarshalStreamComPointers
> 0.139 [INFO]  Patch_CallRelativeAddress - num locations: 0
> 98.156 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
You're not using a compatible version of Rocksmith.
Read the first sentence of the [readme file](https://github.com/mdias/rs_asio/blob/master/README.md).
