### ISSUE TITLE
Game freeze on exit

### ISSUE THREAD

**Issue by kravask** [mdias/rs_asio#67]
After exit getting the white screen and can't switch or end task etc using 0.5 release.
Had the same issue when used 0.3

**Comment by mdias** [comment]
Can you provide a little more information?
RS_ASIO-log.txt, RS_ASIO.ini, which interface?

**Comment by kravask** [comment]
Sorry, didn't mentioned it.
interface Yamaha THR II 30 (worked since 0.2)
RS_ASIO.ini
[Config]
EnableWasapi=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=128

[Asio.Output]
Driver=ASIO4ALL v2
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO4ALL v2
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100



[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4663898/RS_ASIO-log.txt)

**Comment by mdias** [comment]
Thank you for the heads up on this.
I just made the 0.5.1 release that should fix this; please re-open the issue if for some reason it's still not fixed for you
