### ISSUE TITLE
Guitar rig session i/o

### ISSUE THREAD

**Issue by dimancorel** [mdias/rs_asio#69]
Hello! I Tried to launch rs_asio with a lot of sample settings,but i have a cracks and slow chew sounds.
Can anybody can help me?))
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4680334/RS_ASIO-log.txt)

**Comment by mdias** [comment]
You have a lot of underruns there. It could be the case that your asio drivers suffer from the same issue as the focusrite ones where unless a specific buffer size is used, timing issues occur.

In any case as a first step you can try increasing your buffer size from 128 to 256.

A quick search shows that your interface's [drivers may not be well supported in windows 10](https://support.native-instruments.com/hc/en-us/community/posts/207771109-Guitar-Rig-Session-I-O-on-Windows-10).

**Comment by dimancorel** [comment]
[Rocksmith.txt](https://github.com/mdias/rs_asio/files/4719430/Rocksmith.txt)
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4719432/RS_ASIO-log.txt)
I think, i found a problem,and solve it. I change USB Buffer setting for 1ms, and it played well.
(buffer size 128). @mdias Please see logs, and say,that we not have critical underruns))

**Comment by mdias** [comment]
The log looks good, thought it seems that your first log was also already using 128 sample buffer size.
But what matters is that it's working now :)

**Comment by dimancorel** [comment]
@mdias Thank you, i think, we can include my card in support list. Soon, i try to reduce sample buffer size, and see, how it works :)
