### ISSUE TITLE
Missing requirements in the description

### ISSUE THREAD

**Issue by rs123user** [mdias/rs_asio#76]
Hello, you did great work with this patch.
However I spent lots of time trying to make this work. I have focusrite 2i2 3rd gen, updated and licensed windows, game in steam. And it was crashing all the time without any error log.
So solution is just install vc_redist -_-
Add this information to description please.

**Comment by mdias** [comment]
Hello!
Thank you for the heads up, this problem was reported before and some things were changed in order for this to not be needed.
I will investigate this when able to find the issue and fix it.

**Comment by mdias** [comment]
Hopefuly this is fixed on 0.5.2
