### ISSUE TITLE
Output Focusrite 6i6 and Input with Cable not recognizing

### ISSUE THREAD

**Issue by Corno1** [mdias/rs_asio#78]
Hello,
I got a problem with the Input sound of the RS Cable while Outputing through my Focusrite 6i6 works fine. I get absolutely no sound from my guitar but get the sound from the "intro" screen. There seemes no Error in the Log to me so idk what exactly the problem is. I set it up to use WASAPI for the Output only. The Patch worked until i patched from 0.4.2 to 0.5.1.

Heres my .ini and .log file:

[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Focusrite USB ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=

[Asio.Input.1]
Driver=

Log:

0.000 [INFO]   - Wrapper DLL loaded (v0.5.0)
0.000 [INFO]  PatchOriginalCode
0.455 [INFO]  Patching CoCreateInstance
0.456 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.456 [INFO]  Patching call at 01C5AA85
0.456 [INFO]  Patching call at 01F03B6E
0.456 [INFO]  Patching call at 01F5C681
0.456 [INFO]  Patching call at 01FAEF75
0.456 [INFO]  Patching call at 01FAF40D
0.456 [INFO]  Patching PortAudio MarshalStreamComPointers
0.456 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.456 [INFO]  Patching call at 01F03059
0.456 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.456 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.456 [INFO]  Patching call at 01F0310E
0.458 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.458 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.458 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.458 [INFO]  AsioHelpers::FindDrivers
0.459 [INFO]    Focusrite Thunderbolt ASIO
0.459 [INFO]    Focusrite USB ASIO
0.459 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: Focusrite USB ASIO
0.459 [INFO]  Creating AsioSharedHost - dll: c:\program files\focusriteusb\focusriteusbasio32.dll
0.469 [INFO]    ASIO input channels info:
0.469 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 1
0.469 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 2
0.469 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 3
0.469 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: Input 4
0.469 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: SPDIF 1
0.469 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 1, type: ASIOSTInt32LSB, name: SPDIF 2
0.469 [INFO]    ASIO output channels info:
0.469 [INFO]      0 - active: 0, channel: 0, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 1
0.469 [INFO]      1 - active: 0, channel: 1, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 2
0.469 [INFO]      2 - active: 0, channel: 2, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 3
0.469 [INFO]      3 - active: 0, channel: 3, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 4
0.469 [INFO]      4 - active: 0, channel: 4, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 5
0.469 [INFO]      5 - active: 0, channel: 5, group: 0, isInput: 0, type: ASIOSTInt32LSB, name: Output 6
0.469 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - OK
0.477 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 67 render devices, 0 capture devices
0.477 [INFO]    hr: S_OK
0.477 [INFO]    *ppEndpoint: 117206B8
0.477 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.477 [INFO]    hr: 80070490
0.477 [INFO]    *ppEndpoint: 00000000
0.477 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.479 [INFO]    hr: S_OK
0.479 [INFO]    *ppDevices: 17F22140
0.479 [INFO]  {ASIO Out} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.479 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetCount
0.479 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.479 [INFO]  {ASIO Out} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.479 [INFO]  {ASIO Out} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.479 [INFO]  {ASIO Out} DebugWrapperEndpoint::GetDataFlow
0.479 [INFO]    *pDataFlow: eRender
0.479 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.479 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.479 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.481 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetCount
0.481 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.481 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.482 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.482 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.482 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
0.482 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 5
0.483 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 6
0.483 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 7
0.483 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 8
0.483 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 9
0.484 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 10
0.484 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 11
0.484 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 12
0.485 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 13
0.485 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 14
0.485 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 15
0.485 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 16
0.486 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 17
0.486 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 18
0.486 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 19
0.487 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 20
0.487 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 21
0.487 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 22
0.487 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 23
0.488 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 24
0.488 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 25
0.488 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 26
0.488 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 27
0.489 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 28
0.489 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 29
0.489 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 30
0.490 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 31
0.490 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 32
0.490 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 33
0.490 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 34
0.491 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 35
0.491 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 36
0.491 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 37
0.491 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 38
0.492 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 39
0.492 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 40
0.492 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 41
0.492 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 42
0.493 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 43
0.493 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 44
0.493 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 45
0.494 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 46
0.494 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 47
0.494 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 48
0.495 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 49
0.495 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 50
0.495 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 51
0.495 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 52
0.496 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 53
0.496 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 54
0.496 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 55
0.496 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 56
0.497 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 57
0.497 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 58
0.497 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevicePropertyStore::GetAt - iProp: 59
0.498 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.498 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperEndpoint::GetDataFlow
0.498 [INFO]    *pDataFlow: eRender
0.498 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.499 [INFO]  {0.0.0.00000000}.{8e575af8-b355-4342-9a64-607544d7a3ea} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.500 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevice::OpenPropertyStore - stgmAccess: 0
0.500 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevicePropertyStore::GetCount
0.501 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevicePropertyStore::GetAt - iProp: 0
0.501 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevicePropertyStore::GetAt - iProp: 1
0.501 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevicePropertyStore::GetAt - iProp: 2
0.501 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevicePropertyStore::GetAt - iProp: 3
0.502 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevicePropertyStore::GetAt - iProp: 4
0.502 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevice::QueryInterface - riid: IID_IMMEndpoint
0.502 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperEndpoint::GetDataFlow
0.502 [INFO]    *pDataFlow: eRender
0.502 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 1
0.502 [INFO]  {0.0.0.00000000}.{941bd23f-80c3-416b-b323-c26898106e71} DebugWrapperAudioClient<struct IAudioClient3>::GetDevicePeriod
0.518 [INFO]  {ASIO Out} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
0.518 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.518 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.518 [ERROR]    failed to initialize asio driver with requested format
0.518 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.518 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.518 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
0.518 [ERROR]    failed to initialize asio driver with requested format
0.518 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
0.518 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
0.518 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Initialize - ShareMode: Exclusive Flags: 40000 bufferDuration: 3ms periodicity: 3ms
0.518 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - host requested buffer duration: 3ms (144 frames)
0.518 [INFO]  {ASIO Out} WAVEFORMATEX
  wFormatTag: fffe
  nChannels: 2
  nSamplesPerSec: 48000
  nAvgBytesPerSec: 384000
  nBlockAlign: 8
  wBitsPerSample: 32
  cbSize: 22
  ext.SubFormat: KSDATAFORMAT_SUBTYPE_PCM
  ext.Samples: 24
  ext.dwChannelMask: 3
0.518 [INFO]  {ASIO Out} RSAsioAudioClient::Initialize - actual buffer duration: 4ms (192 frames)
0.518 [INFO]  AsioSharedHost::Setup - startCount: 0
0.518 [INFO]    post output ready: 1
0.518 [INFO]    ASIOBufferSize - min: 8 max: 1024 preferred: 192 granularity: 16
0.518 [INFO]    Creating ASIO buffers (6 out, 6 in)...
0.518 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 7 value: 0 | returning: 0
0.518 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 2 value: 0 | returning: 1
0.518 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 3 | returning: 0
0.518 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 5 | returning: 0
0.518 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 4 | returning: 0
0.518 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 6 | returning: 0
0.518 [INFO]  AsioSharedHost::AsioCalback_asioMessage - selector: 1 value: 15 | returning: 0
0.518 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetBufferSize
0.518 [INFO]    *pNumBufferFrames: 192
0.518 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetStreamLatency
0.518 [INFO]    latency: 8ms
0.518 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::GetService - riid: IID_IAudioRenderClient
0.518 [INFO]    returning render client
0.519 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
0.521 [INFO]  Patched_PortAudio_MarshalStreamComPointers
0.521 [INFO]  Patched_PortAudio_UnmarshalStreamComPointers
0.521 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::SetEventHandle
0.521 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.521 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.521 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.521 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Start
0.521 [INFO]  AsioSharedHost::Start - startCount: 0
0.521 [INFO]    Starting ASIO stream...
0.538 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 1
0.538 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.538 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.538 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.542 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 2
0.542 [INFO]  {ASIO Out} DebugWrapperRenderClient::GetBuffer NumFramesRequested: 192
0.542 [INFO]  {ASIO Out} DebugWrapperRenderClient::ReleaseBuffer NumFramesWritten: 192
0.542 [INFO]  {ASIO Out} RSAsioAudioClient::SwapBuffers
0.546 [INFO]  Focusrite USB ASIO - AsioSharedHost::AsioCalback_bufferSwitch - buffer switch 3 (not logging upcoming switches)
58.879 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
58.880 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
58.880 [INFO]  AsioSharedHost::Stop - startCount: 1
58.880 [INFO]  AsioSharedHost::Stop  stopping ASIO stream
58.883 [INFO]  Destroying AsioSharedHost - dll: c:\program files\focusriteusb\focusriteusbasio32.dll
60.210 [INFO]   - Wrapper DLL unloaded

**Comment by mdias** [comment]
You config is bad.
You don't need to be using `EnableWasapiOutputs=1` if you're going to output to the Focusrite, and you have no driver selected for the input, which is why you have no input.

Look [here for a sample config](https://github.com/mdias/rs_asio/tree/master/docs/focusrite_solo) and change the input channel according to the input you use.

**Comment by Corno1** [comment]
I tried the sample config but it didn't work for me. I don't really get when to set Wasapi to 1. So this was my old .ini file that worked.

[Config]
EnableWasapi=1
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Focusrite USB ASIO
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=

[Asio.Input.1]
Driver=

I want to output through my focusrite but still using the rocksmith cable as the input so i guess either the input or output wasapi should be 1 ? 

Thx for your help :)

**Comment by mdias** [comment]
Ah damn, I missed the part where you said you wanted to use the RealTone Cable.
In that case set `EnableWasapiOutputs=0` and `EnableWasapiInputs=1`.

**Comment by Corno1** [comment]
Okay I got it, I had to leave the rest of the parameters and just delete the driver. 
Thank you for your help !
