### ISSUE TITLE
Not working on my end

### ISSUE THREAD

**Issue by Z3KE02** [mdias/rs_asio#82]
I unpacked everything from the most recent download into the Steam directory (fresh install)
I launch the game, there's no input device detected, there's no log file generated as well

I use ASIO4ALL V2
My guitar's volume knob is on max

my interface (which is probably the problem) is an iRig UA, which isn't much of an interface. on Windows It acts as a Playback & Recording device, and without the fix, when I launch the game, the game detects my built-in soundcard, but not the iRig's
I've tried different ports, and even the old no cable fix, but the game just won't detect it
one more thing, in ASIO4ALL's GUI, it detects it, and it runs fine with softwares like Amplitube and BIAS FX

**Comment by mdias** [comment]
If you're not getting a log file the problem is not your interface.

Can you post a screenshot of the files in the game's folder next to the game executable?

**Comment by Z3KE02** [comment]
![image](https://user-images.githubusercontent.com/67641849/86164156-fcea2000-bb19-11ea-8fc3-b8a14d8ddc70.png)
there you go

**Comment by mdias** [comment]
You downloaded the repository instead of the (only 3) files required.

Follow the download link on the [front-page readme](https://github.com/mdias/rs_asio/blob/master/README.md) with the text "[latest release](https://github.com/mdias/rs_asio/releases/latest)".

**Comment by Z3KE02** [comment]
yea I figured I was doing something wrong, thanks
