### ISSUE TITLE
Confirm working with SoundCraft  Notepad-12FX

### ISSUE THREAD

**Issue by RomE-HK** [mdias/rs_asio#86]
Friend of mine gave me SoundCraft Notepad-12FX for few days, to test it with Rocksmith 2014. And it works like a charm!
@mdias, thank you for your work!

## Config files

**RS_ASIO.ini**

[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=Soundcraft USB Audio ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Soundcraft USB Audio ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

**Rocksmith.ini**

[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=1
ForceDefaultPlaybackDevice=1
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=1
Win32UltraLowLatencyMode=1

**Comment by RomE-HK** [comment]
Can't wait for multiplayer mode =)

**Comment by mdias** [comment]
Nice! Thanks for the report, will add it to the list soon 👍 


> Can't wait for multiplayer mode =)

If you mean multiplayer support in RS_ASIO it's there already, just use also the `Asio.Input.1` :)

**Comment by RomE-HK** [comment]
> If you mean multiplayer support in RS_ASIO it's there already, just use also the `Asio.Input.1` :)

Great news! Thank you! 👍

**Comment by bluesmcgroove** [comment]
I can confirm this is also working with the Notepad-8FX. Wasn't exactly surprised as they use the same USB ASIO driver, but good for anyone else who might be wondering!

**Comment by mdias** [comment]
Thank you. Also added to the lst 👍

**Comment by D3XX3R** [comment]
RS ASIO is also working for the UI24R from Soundcraft. It was complicated to find the right channel, but overall this works.

**Comment by mdias** [comment]
Added, thank you.
