### ISSUE TITLE
Focusrite Scarlett Solo Issues

### ISSUE THREAD

**Issue by vebberim** [mdias/rs_asio#88]
I'm using a Focusrite Scarlett Solo rig for RS ASIO. I tried letting the options run blank, and I also set them up with the known/best settings as listed, with no response from the game. There is no ASIO found, and the game gives me a warning at startup that "no audio output is detected."

What else can I do to set this up?

**Comment by mdias** [comment]
The initial configuration are stated in the [readme file](https://github.com/mdias/rs_asio/blob/master/README.md), and it also has links with [instructions for Scarlett Solo](https://github.com/mdias/rs_asio/blob/master/docs/focusrite_solo/README.md) devices.
