### ISSUE TITLE
No sound help :(

### ISSUE THREAD

**Issue by Knocfath** [mdias/rs_asio#89]
So i think im doing the unthinkable im trying to surely get uncussesfuly running a clarett focusrite which might be explained because my drivers prob are 64 bit and they arent connected via usb exactly i tried with 2 versions with no audio also im planning now to re route with with asio4all and voicemeeter or wold asio4all work with a adapter for my 1/4 jack to 3.5? wold it even be need the asio? i just feel it can make it faster? could i do a hybrid and just use the focusrite for input maybee rerouted and the asio4all for the output? ty in advance version 0.3.1

```
Edit:Deteled for the sake of scrolling

**Comment by mdias** [comment]
Hello

The log file looks right, and depending on how you config file looks, you should be getting audio on the interface's output 1 and 2.
Perhaps you were expecting the audio on some other output?

**Comment by Knocfath** [comment]
Before anything Mr.Mdias let me tell you that I love you, thanks for your work for humanity
Hello and now to your reply, wait wha? The output that im using is the one included in the Audio interface, the only time I heared sound was when I installed wrongly the source package of rs asio(no dll and skipping) after that Ive only got it using asio4all, I've had no input or output (never had my guittar sound being detected) with the thunderbolt driver but if what you are telling me is correct then it means that rs asio could be compatible with thunderbolt :00 lemme search my configs

**Comment by mdias** [comment]
> but if what you are telling me is correct then it means that rs asio could be compatible with thunderbolt

Correct. RS_ASIO doesn't have any limitation regarding this, it communicates only with the ASIO driver itself, and whether your interface is USB, Thunderbolt or anything else does not concern RS_ASIO, it's a detail of the ASIO driver implementation.

You should have your interface connected to your PC just the same as with any other application that uses ASIO. If you hear audio there, it should work with RS_ASIO too.

Try this config:

```
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
BufferSizeMode=driver

[Asio.Output]
Driver=Focusrite Thunderbolt ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite Thunderbolt ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

If this doesn't output sound on your first two outputs of your interface, let's check if it works by using the normal sound path for rocksmith audio output with this config:

```
[Config]
EnableWasapiOutputs=1
EnableWasapiInputs=0
EnableAsio=1

[Asio]
BufferSizeMode=driver

[Asio.Output]
;Driver=Focusrite Thunderbolt ASIO
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Focusrite Thunderbolt ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by Knocfath** [comment]
Done! the first try had no sound and the second issued a no sound detected from Rocksmith...i'm all for testing if you are willing but i don't feel confortable abusing your time Mr.Mdias so you tellme i was thinking of searching a usb interface since it seems those are more secure..but..i just can wonder that all it wold be left wold be to check  khz and buffers..maybe at windows sound settings

**Comment by mdias** [comment]
> all it wold be left wold be to check khz and buffers..maybe at windows sound settings

In theory this should make no difference when using ASIO. The whole purpose of ASIO is to bypass all of the windows sound system, so if on your ASIO control panel you have 48000hz it should be enough for this.

> my interface only has 1 audio output

This is strange. The logs say it should have 4 outputs. Can you give me the full model name of your Focusrite just for curiosity?


Let's go back to the 1st config then.
So right now you're outputting to the first 2 outputs of your device (because BaseChannel=0 on the output) so it's possible that you have your speakers connected to the other 2 outputs (you can test by changing BaseChannel=2 on the output) or maybe your ASIO control panel has some sort of audio routing that I'm unaware of.

It's also possible that you're refering to the headphone output as being the single one? If so, you might need to change what that output is monitoring. I believe clarett devices show volume meters on their control panel. If that's the case, try running the game in windowed mode (which will also allow you to terminate it more easily if it crashes) while having the control panel window visible so you can see volume meters.

**Comment by Knocfath** [comment]
Here claret 2pre https://www.amazon.com.mx/Focusrite-Clarett-Pre-USB-10/dp/B0794PMMNB/ref=mp_s_a_1_1?dchild=1&keywords=focusrite+2pre&qid=1593963851&sr=8-1 Damn probably my inexperience is showing yeah I believe it has more outputs at the back but yeah I was talking about the headphone output I only have connected the headphone output and another headphones via usb to my PC but you might be onto something with the output routing, I have do software Wich is the asio that can only change buffer and htz and the focusrite control , I'll check if I can see a routing in the software and try connecting my headphones to any of the 4 outputs, I just never had a issue using the headphones one but it does make sense , I've always runned it in windows mode for testing but just focusing another program is enough to make it crash unless it's asio4all

**Comment by Knocfath** [comment]
Base channel 3 did nothing, im trying again with 0 with the added display
![Untitled1](https://user-images.githubusercontent.com/39888301/86536956-38d20c00-beb1-11ea-83fb-e9fca9804407.jpg)

**Comment by mdias** [comment]
The game window must be in focus for this to work. When the window is not in focus, the game sounds are muted :)

**Comment by mdias** [comment]
Also, according to #42 the Clarett 4Pre works, and I would guess it uses pretty much the same drivers as yours, so hopefuly it's just some setting you have to change.
#42 mentions changing `LatencyBuffer=1` in Rocksmith.ini, so maybe it's that?

**Comment by Knocfath** [comment]
> The game window must be in focus for this to work. When the window is not in focus, the game sounds are muted :)
> Set the game to windowed mode with a lower resolution so you can still look at the clarett control panel while having the game in focus.
> 
> Also, if you want to try base channel, it should be 2, not 3. Remember it starts counting at zero.
Totally right, tested and no output still ill change the latency now

**Comment by deadcombo** [comment]
I'm also not getting any audio output on `0.5.2`, on my MAYA22USB. If I launch it straight from `Rocksmith2014.exe` it even gives me the "No audio output detected" pop-up.

´´´ini
[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=1
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
[Renderer.Win32]
ShowGamepadUI=0
ScreenWidth=1280
ScreenHeight=720
Fullscreen=2
VisualQuality=3
RenderingWidth=0
RenderingHeight=0
EnablePostEffects=0
EnableShadows=0
EnableHighResScope=0
EnableDepthOfField=0
EnablePerPixelLighting=1
MsaaSamples=0
DisableBrowser=1
[Net]
UseProxy=1
´´´

´´´ini
[Config]
EnableWasapiOutputs=0
EnableWasapiInputs=0
EnableAsio=1

[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize=

[Asio.Output]
Driver=ASIO 2.0 - ESI MAYA22USB
BaseChannel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=ASIO 2.0 - ESI MAYA22USB
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
´´´

´´´txt
0.000 [INFO]   - Wrapper DLL loaded (v0.5.2)
0.000 [INFO]  PatchOriginalCode
0.459 [INFO]  Patching CoCreateInstance
0.459 [INFO]  Patch_CallAbsoluteAddress - num locations: 5
0.459 [INFO]  Patching call at 01C5AA85
0.459 [INFO]  Patching call at 01F03B6E
0.459 [INFO]  Patching call at 01F5C681
0.459 [INFO]  Patching call at 01FAEF75
0.459 [INFO]  Patching call at 01FAF40D
0.459 [INFO]  Patching PortAudio MarshalStreamComPointers
0.459 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.459 [INFO]  Patching call at 01F03059
0.459 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.459 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.459 [INFO]  Patching call at 01F0310E
0.461 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.467 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.467 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.467 [INFO]  AsioHelpers::FindDrivers
0.468 [INFO]    ASIO 2.0 - ESI MAYA22USB
0.468 [INFO]    Fender Universal ASIO
0.468 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO 2.0 - ESI MAYA22USB
0.468 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\system32\MAYA22USBasio32.dll
0.470 [ERROR]  ASIO Error: ESI MAYA22USB ASIO DRIVERASIO Open Fails
0.470 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\system32\MAYA22USBasio32.dll
0.471 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.471 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO 2.0 - ESI MAYA22USB
0.471 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\system32\MAYA22USBasio32.dll
0.473 [ERROR]  ASIO Error: ESI MAYA22USB ASIO DRIVERASIO Open Fails
0.473 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\system32\MAYA22USBasio32.dll
0.473 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.473 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
0.473 [INFO]    hr: 80070490
0.473 [INFO]    *ppEndpoint: 00000000
0.473 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
0.473 [INFO]    hr: 80070490
0.473 [INFO]    *ppEndpoint: 00000000
0.474 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
0.474 [INFO]    hr: S_OK
0.474 [INFO]    *ppDevices: 0A0D23B0
2.929 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
2.929 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
2.929 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
2.929 [INFO]  AsioHelpers::FindDrivers
2.929 [INFO]    ASIO 2.0 - ESI MAYA22USB
2.929 [INFO]    Fender Universal ASIO
2.929 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: ASIO 2.0 - ESI MAYA22USB
2.929 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\system32\MAYA22USBasio32.dll
2.932 [ERROR]  ASIO Error: ESI MAYA22USB ASIO DRIVERASIO Open Fails
2.932 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\system32\MAYA22USBasio32.dll
2.932 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
2.932 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: ASIO 2.0 - ESI MAYA22USB
2.932 [INFO]  Creating AsioSharedHost - dll: C:\WINDOWS\system32\MAYA22USBasio32.dll
2.934 [ERROR]  ASIO Error: ESI MAYA22USB ASIO DRIVERASIO Open Fails
2.934 [INFO]  Destroying AsioSharedHost - dll: C:\WINDOWS\system32\MAYA22USBasio32.dll
2.935 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
2.935 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
2.935 [INFO]    hr: 80070490
2.935 [INFO]    *ppEndpoint: 00000000
2.935 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eCapture - role: eMultimedia
2.935 [INFO]    hr: 80070490
2.935 [INFO]    *ppEndpoint: 00000000
2.935 [INFO]  DebugDeviceEnum::EnumAudioEndpoints - dataFlow: eAll - dwStateMask: 1
2.935 [INFO]    hr: S_OK
2.935 [INFO]    *ppDevices: 0A0D2290
2.941 [INFO]  DebugDeviceEnum::RegisterEndpointNotificationCallback
5.895 [INFO]  DebugDeviceEnum::UnregisterEndpointNotificationCallback
6.154 [INFO]   - Wrapper DLL unloaded
´´´

**Comment by mdias** [comment]
@Knocfath no problem, sorry I can't help further. Without the hardware it's difficult to make sure everything else works fine :/

@deadcombo does it work with any previous version? If so, do you know which version made it stop working?

**Comment by Knocfath** [comment]
It hurts to see one man do what a developer team probably intentionally didn't do, I'll be buying the cable since there are no cheap interfaces where I live atm and asking for a refund and using a torrent version #fuckubisoft good day

**Comment by deadcombo** [comment]
It  was working fine until yesterday, I can't remember which version I had, but it was recent enough.

I have regressed through each version individually. All of them the same. 

I think this is a result of a Windows update. I was playing and the audio cut out (it was normal, it happened after 2 or 3 hours). I restarted my PC to get everything working again and I started getting some weird behavior, most noticeably Windows was loading 44100Hz I think, all audio was getting slowed down. I noticed it by playing a YouTube video in Firefox, and by playing audio through TIDAL.

I can't say for sure it was a sample rate mismatch, but it sounded like it. My interface offers virtual I/O in channels 3-4, disabling these made sure Windows picked the correct channel, and playback got back to normal.

I have also reinstalled my interface's drivers, just to be sure.

I don't have ASIO at all in Reaper either. This is definitely a Windows bug. mdias can you give me a hand? Got any ASIO debugging tips?

**Comment by Knocfath** [comment]
It's probably windows, one update fucked up my Thunderbolt and had to reinstall drivers along with the firmware I recommend you to at least download asio link to see if your asio drivers are defected as that's what introduced me better to the mombo jombo of the software as my interface has always worked and without a problem without any daw, when I installed it allowed me to see the asio flow of my drivers and if you are willing use it for one of its outputs, but the last 2 trys my asio driver output wasn't being detected by the app even when focusrite control and any daw had input from them, and actually Rocksmith detected my interface from the mic option which I couldn't get to do the last 2 tries and I had to give up for now as my interface is burning hot, like seriously I have 6 hours in Rocksmith of pure testing just buy a mac next time ._.

**Comment by mdias** [comment]
@deadcombo the only tips I have are:

- Make sure you're using the latest drivers for your interface
- Try another USB port
- Try rebooting the computer when trying different stuff (yeah... it sounds weird, but it can solve some issues with drivers getting "locked")
- Make sure your interface is set to use 48000hz on windows sound settings.
