### ISSUE TITLE
Roland VS-100 Audio Interface

### ISSUE THREAD

**Issue by roark735** [mdias/rs_asio#91]
I have older Roland VS-100 audio interface that I've been using with RS_ASIO with success. I have an error in the log file related to the ASIO sample type ASIOSTInt32LSB, which I don't recall a setting on the device I can change. This device works great in the game, I have the buffer at 96, but it seems to hang when exiting, just a black screen. However, if I turn off the interface, the game exits as normal. My guess is the driver is not releasing when it should but I thought I'd ask if there was something else to try. My .ini and log file are included. Thank you for all of your work on this project!

[RS_ASIO.ini.txt](https://github.com/mdias/rs_asio/files/4881671/RS_ASIO.ini.txt)

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4881672/RS_ASIO-log.txt)

**Comment by mdias** [comment]
Disregard the error about ASIOSTInt32LSB; it's actually the game asking for floating point sample format when your device only supports ASIOSTInt32LSB, and therefore we're returning an error to it. It seems to try that twice before trying to ask for ASIOSTInt32LSB format that your interface supports.

Regarding the hang, this is kind of a known issue and it's "on the back of my mind" to fix, as it happens in a small number of drivers including ASIO4ALL. I'm currently unsure if it's bad handling on the side of the game or on the side of RS_ASIO itself.
When I'm able to pick up development again this is one of the things I want to fix, although I can't make any promises.

Also, thank you for the report about Roland VS-100 working well with the exception of this annoyance when exiting.

**Comment by roark735** [comment]
Thank you for the quick response and the explanation for the error. And it's a minor inconvenience to turn off the device when I’m finished playing. Should I put some documentation in the doc folder with the caveat about the hang on exit? Thanks again!

**Comment by mdias** [comment]
Sorry for the late reply.
There's no need for adding it for now. I'm linking the report to this issue for now, and I should reorganize this list to better expose the caveats of interfaces that need them.

Thank you 👍
