### ISSUE TITLE
Problems with logs and inis

### ISSUE THREAD

**Issue by jacobepic** [mdias/rs_asio#94]
trying to use rs_asio as a no cable mod for non asio gear, I am under the impression it should be possible, but I am not seeing a driver name to put into the RS_ASIO ini file, are you able to help 
[clues.zip](https://github.com/mdias/rs_asio/files/4905688/clues.zip)

**Comment by mdias** [comment]
I'm not sure I understand what you're trying to do.
You're disabling ASIO in the settings and just enabling wasapi; this is effectively the same as running without RS_ASIO at all.

If you don't have ASIO capable gear, you should use the NoCablePatch instead.

**Comment by zagatozee** [comment]
That would be my error than, I was under the impression that RS_ASIO also would work on non-asio gear as a (much improved) "No Cable" mod, since it can do all the same things on WDM gear, just with the added bonus of also handling ASIO.

I shouldn't be suggesting non-asio users use this instead of the older "no cable" options then?

**Comment by mdias** [comment]
> I shouldn't be suggesting non-asio users use this instead of the older "no cable" options then?

Correct.

All the audio devices the game detects through "EnableWasapiOuputs" and "EnableWasapiInputs" are "pure" devices in the sense that their functionality doesn't go through RS_ASIO logic at all. For example, only the real RealTone Cable will be detected as a valid cable there (plus devices configured as asio inputs).

It wouldn't be impossible to make all inputs detected as valid cables, but then there's no way to select a single input for it etc. Basically for that case, the NoCablePatch is the best solution.
