### ISSUE TITLE
CAN CONFIRM WORKING FLAWLESSLY ON MOTU ULTRALITE MK-4 (ESS Sabre 32)

### ISSUE THREAD

**Issue by coffeemate1911** [mdias/rs_asio#95]

**Comment by mdias** [comment]
Thank you for the feedback :)

**Comment by Haxign** [comment]
How did you get it to work? It throws up the "No audio device is detected" error every time I try to start up Rocksmith. I've tried literally everything and it just won't go away.

**Comment by coffeemate1911** [comment]
I followed the instructions that were written, and my default communication device is motu afterall, which version of mk4 are you using.  There are 2, 1 is apparently with akm the one i use clearly labels ess sabre on the packaging

**Comment by mdias** [comment]
@Haxign you should post the contents of your `RS_ASIO.ini`, `RS_ASIO-log.txt` and `Rocksmith.ini` files to help us help you.
